### ISSUE TITLE
Website doesn't show

### ISSUE THREAD

**Issue by LeWuDISE** [cmdr2/stable-diffusion-ui#1]
I've had some troubles executing server.sh in WSL, it said something about no permission even with sudo, but with some chmod magic I got that working eventually. After executing it, docker showed that it is using port 5000 instead of 8000 like shown in the Tutorial. 

When opening localhost:5000 in a browser, all the site contains is 

`{"docs_url":"/docs","openapi_url":"/openapi.json"}`

**Comment by cmdr2** [comment]
Hi, docker will start Stable Diffusion at 5000, but the UI (that you'll interact with) will start at port 8000. You should use http://localhost:8000 to access the UI interface. That will talk to the docker instance behind-the-scenes.

`./server.sh` will start both servers. Are you able to see the UI at http://localhost:8000 ? Thanks

**Comment by cmdr2** [comment]
The message you're getting when you hit port 5000 is good news. That means Stable Diffusion was installed successfully and your docker container started up correctly.

Just try http://localhost:8000 in your browser, to access the UI. If that doesn't work, please let me know.

**Comment by kkaspar** [comment]
Hello,

I have a similar problem, it all starts, but in the end when I use localhost:8000 I end up in a webpage titled "AppDetectService Service" with the message
"You have created a service.

To test this service, you will need to create a client and use it to call the service. You can do this using the svcutil.exe tool from the command line with the following syntax:"

**Comment by cmdr2** [comment]
Hi @kkaspar You can override the port used. Please change `docker-compose.yml` inside the project directory, and update the line `8000:8000` to `1337:8000` (or where 1337 is whichever port number you want).

After doing this, please restart your server, by running `docker-compose down` and then `docker-compose up &`. If it doesn't take effect immediately, please try restarting once more.

Hope that helps!

**Comment by cmdr2** [comment]
I've added a note in the troubleshooting for the port number. Closing this issue for now, please re-open if the problem isn't fixed for you! Thanks

**Comment by LeWuDISE** [comment]
Sorry for not responding. We had a pretty bad thunderstorm, resulting in a power surge and outage, and I had to rebuild my entire Homelab.. When connecting to localhost:8000, all I get is a refused connection.

**Comment by cmdr2** [comment]
@LeWuDISE Okay, can you please try my suggestion above to start this at a different port?

Also, when can you please paste the output shown in your terminal when you run `docker-compose up &`? Maybe there's an error in starting up.

Finally, can you please confirm you're running the latest version of this project? It's changing quite rapidly. Thanks, and sorry for the trouble!

**Comment by LeWuDISE** [comment]
The Issue seems to be fixed on the new version (1.1). Thanks for your help, I didn't notice there was a new version! :D

**Comment by LeWuDISE** [comment]
Whoops.. Clicked two times..
