### ISSUE TITLE
[Suggestion] Queue stacks

### ISSUE THREAD

**Issue by ChrisAcrobat** [cmdr2/stable-diffusion-ui#10]
Instead of replacing the result image with the new, shift the old image to the left and put the new image to the right and add a display settings button below or on each image.
If an image was used as a source, but that image and resulting images on a new row (or column).

First row (or column) is images without a source image, the preceding rows (or columns) uses the source image as header and resulting images as children.

Possibly also allow push future image-settings to the stack that will be fetched once the current it is ready. Workaround right now is to have multiple browser tabs.

**Comment by cmdr2** [comment]
Hi @ChrisAcrobat , I'm looking at implementing this feature soon, and I started a discussion on this in the new Discord server for this project: https://discord.com/invite/u9yhsFmEkB . Would love to see you there, if you're interested! :)

**Comment by cmdr2** [comment]
Done
