### ISSUE TITLE
ImportError: cannot import name 'Mapping' from 'collections' 

### ISSUE THREAD

**Issue by gazhay** [cmdr2/stable-diffusion-ui#100]
Does not install or function on linux with the error

````ImportError: cannot import name 'Mapping' from 'collections' ````

**Comment by gazhay** [comment]
First run generated this error

````scripts/on_env_start.sh: line 26: unexpected EOF while looking for matching `''
scripts/on_env_start.sh: line 37: syntax error: unexpected end of file
````

but running again we get the module error

**Comment by cmdr2** [comment]
Thanks for your patience with this, I noticed that you managed to fix this: https://discord.com/channels/1014774730907209781/1014774732018683927/1017108183526944829
