### ISSUE TITLE
Error activating conda for Easy Diffusion

### ISSUE THREAD

**Issue by Weaklyispro** [cmdr2/stable-diffusion-ui#1006]
Im having issues with activiation conda for easy diffusion pls help

**Comment by Weaklyispro** [comment]
Install dir: D:\stable-diffusion-ui\
C:\Program Files\Git\cmd\git.exe
git version 2.39.2.windows.1
INFO: Could not find files for the given pattern(s).
'conda' is not recognized as an internal or external command,
operable program or batch file.

"Easy Diffusion - v2"

"Easy Diffusion's git repository was already installed. Updating from main.."
HEAD is now at 4e35580 Update README.md
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
493 File(s) copied
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
A subdirectory or file tmp already exists.
'conda' is not recognized as an internal or external command,
operable program or batch file.

"Error activating conda for Easy Diffusion. Sorry about that, please try to:"
"  1. Run this installer again."
"  2. If that doesn't fix it, please try the common troubleshooting steps at https://github.com/cmdr2/stable-diffusion-ui/wiki/Troubleshooting"
"  3. If those steps don't help, please copy *all* the error messages in this window, and ask the community at https://discord.com/invite/u9yhsFmEkB"
"  4. If that doesn't solve the problem, please file an issue at https://github.com/cmdr2/stable-diffusion-ui/issues"
"Thanks!"

Press any key to continue . . .
Press any key to continue . . .
Press any key to continue . . .
Full log

**Comment by cmdr2** [comment]
Can you please try the latest installer? https://github.com/cmdr2/stable-diffusion-ui/releases/download/v2.5.24/Easy-Diffusion-Windows.exe

That avoids the error that you're facing. Please feel free to reopen if this doesn't solve your problem, thanks!

**Comment by davidke460** [comment]
Error activating conda for Easy Diffusion. Sorry about that, please try to:
