### ISSUE TITLE
Removing the first image from a batch job in progress removes the entire section, preventing other results from showing up

### ISSUE THREAD

**Issue by Salvatos** [cmdr2/stable-diffusion-ui#1011]
**Describe the bug**
When running multiple image generations at once, if you click the X on the first result to remove it, the entire section gets removed from the page. The job continues and the other images it generates aren’t accessible.

**To Reproduce**
1. Generate multiple images at once (e.g. 3 total, 1 in parallel).
2. When the first image is ready (and not the others), hover it and click X to remove it.

**Expected behavior**
Only the image should be deleted; the section should remain in place.

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.1
 - Browser: Firefox 110.0.1
 - Version: 2.25.24

**Comment by JeLuF** [comment]
This has been fixed with PR #1009 
If you're using the beta version, a restart of the program should apply this change to your system. If you're using the main version, it should become activated in the next few days.
