### ISSUE TITLE
USB devices randomly disconnect and reconnect

### ISSUE THREAD

**Issue by Jones-UI** [cmdr2/stable-diffusion-ui#1028]
Several of my USB devices are randomly disconnecting and reconnecting while running EasyDiffusion.
Keyboard, Wacom Tablet, etc

I don't experience this issue with AUTOMATIC1111, but I much prefer the EasyDiffusion UI.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro  22H2
 - Browser: Firefox 111.0
 - Version: v2.5.24

**Additional context**
This behavior only started on Friday, 2023-03-17.
Was not happening the day before.

**Comment by cmdr2** [comment]
Hi @Jones-UI I'm sorry but we do not touch USB devices at all. Our source code is open for review, and the changes since Mar 17 can be reviewed as well. Can you please check if some other software was installed, or if it's a driver issue?
