### ISSUE TITLE
Please add a short description on how to remove/uninstall it

### ISSUE THREAD

**Issue by dkipp** [cmdr2/stable-diffusion-ui#103]
I was unable to find a description on how to remove or uninstall everything if I want to.
Please guide me and others who install this out of curiosity

**Comment by cmdr2** [comment]
Hi @dkipp You can just delete the 'stable-diffusion-ui' folder. But yes, this should be mentioned in the docs. Thanks

**Comment by dkipp** [comment]
how awesome is that.

does this also meen it is posible to copy the 'stable-diffusion-ui' folder to a nother windows based PC and it will work there too?
Or do we need to excecute the install script again to adapt to posible hardware differentces.

**Comment by cmdr2** [comment]
Hi @dkipp It'll have to be installed again :) the binary formats and the file links are different. Infact the folder can't be moved once installed, similar to how you can't move an installed program from `C:\Program Files` and expect it to run. :)

**Comment by cmdr2** [comment]
Added steps for uninstallation on https://github.com/cmdr2/stable-diffusion-ui#installation
