### ISSUE TITLE
easy server port change

### ISSUE THREAD

**Issue by andrearicci** [cmdr2/stable-diffusion-ui#1030]
**Is your feature request related to a problem? Please describe.**
I run a company pc with limited access (no administrator) win 10
I get the error:
ERROR:    [Errno 10048] error while attempting to bind on address ('0.0.0.0', 9000)....

and
C:\EasyDiffusion\scripts>netstat -na | find "9000"
  TCP    0.0.0.0:9000           0.0.0.0:0              LISTENING
  TCP    127.0.0.1:9000         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:49265        127.0.0.1:9000         TIME_WAIT
  TCP    127.0.0.1:49277        127.0.0.1:9000         TIME_WAIT
  TCP    127.0.0.1:49287        127.0.0.1:9000         TIME_WAIT
  TCP    127.0.0.1:49312        127.0.0.1:9000         TIME_WAIT

**Describe the solution you'd like**
an easy way to change the port number to serach for a free one

**Describe alternatives you've considered**
I googled to search for a solution, I couldn't find a config or bat file with the port number. I donnow how to set the server's port.

**Additional context**
maybe we can set the port in the _Start Stable Diffusion UI.cmd_

Thank you

**Comment by JeLuF** [comment]
You can set the port from the `Settings` tab in the web interface, or via the config file, as described in the documentation:
https://github.com/cmdr2/stable-diffusion-ui/wiki/Config-settings#network-ports

**Comment by andrearicci** [comment]
thank you!
