### ISSUE TITLE
RuntimeError: CUDA out of memory. 

### ISSUE THREAD

**Issue by msahin** [cmdr2/stable-diffusion-ui#104]
`RuntimeError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 4.00 GiB total capacity; 3.35 GiB already allocated; 0 bytes free; 3.41 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`
i get this error everytime

**Comment by cmdr2** [comment]
Hi @msahin I've added a few common reasons for this error at https://github.com/cmdr2/stable-diffusion-ui/blob/main/Troubleshooting.md#runtimeerror-cuda-out-of-memory

Please try those out, they usually fix the problem for most of the Out of Memory queries we get on #support on the discord server. If that doesn't fix it, please drop by the Discord server (https://discord.com/invite/u9yhsFmEkB), or reopen this issue. Thanks!
