### ISSUE TITLE
Add a setting to specify the source disk for allocating memory at startup.

### ISSUE THREAD

**Issue by uteal** [cmdr2/stable-diffusion-ui#1047]
The program reserves about 10 GB of space on the C drive at startup. If there is not enough space, an error occurs. I would like to be able to tell the app to allocate space on the D drive instead.

**Comment by cmdr2** [comment]
Hi, sorry but that's a setting in the Operating System, not something our program can control. This might help: https://www.ibm.com/docs/en/opw/8.2.0?topic=tuning-optional-increasing-paging-file-size-windows-computers
