### ISSUE TITLE
Parallel processing results in different images from same seed, causing incorrect upscale

### ISSUE THREAD

**Issue by lucasmarcelli** [cmdr2/stable-diffusion-ui#1056]
**Describe the bug**
When parallel processing, the images will be different from non-parallel despite having the same seed. If you then press the "upscale" button on one that was parallel, the resulting upscaled image is incorrect because the upscale task does not run with that option set..

**To Reproduce**
1. Enter a prompt and choose a seed
2. Generate 2 images, make sure 1 is entered for `(in parallel)`
3. Using the same seed, generate 2 images but make sure 2 is entered for `(in parallel)`. This is the only changed setting.
4. Observe that the result is different
5. Click upscale on one of the parallel processed images
6. Observe that the result is actually the upscaled image from the non parallel result

See example images below.

**Expected behavior**
Either:
- Processing in parallel should not generate different images from non-parallel
- Upscaling a parallel processed image should result in the same image being upscaled, not the non-parallel version

The choice is really up to the maintainers. 

**Screenshots**
Starting seed: `9252644`
Prompt: `a guy riding a horse on a busy street`

Run not in parallel:
![a_guy_riding_a_horse_on_a_busy_street_Seed-9252645_Steps-50_Guidance-17 5](https://user-images.githubusercontent.com/1221253/227603958-729a80a9-36a8-448d-8ec7-e8ef4fcfd4d6.jpeg)
![a_guy_riding_a_horse_on_a_busy_street_Seed-9252644_Steps-50_Guidance-17 5](https://user-images.githubusercontent.com/1221253/227603977-07b0b774-4b36-4fc5-8407-89189f1b31ed.jpeg)

Run in parallel, same seed and settings:
![a_guy_riding_a_horse_on_a_busy_street_Seed-9252645_Steps-50_Guidance-17 5 (1)](https://user-images.githubusercontent.com/1221253/227604072-30732f04-484a-4913-8a45-7bbf5d5a7c23.jpeg)
![a_guy_riding_a_horse_on_a_busy_street_Seed-9252644_Steps-50_Guidance-17 5 (1)](https://user-images.githubusercontent.com/1221253/227604057-07341448-041a-48e7-8b5a-97f0eda56595.jpeg)

Screenshot:
<img width="833" alt="Screen Shot 2023-03-24 at 2 01 35 PM" src="https://user-images.githubusercontent.com/1221253/227606021-04526bb1-926b-47c3-b991-f19c63f21ea5.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 2.5.x

**Additional context**
- If you upscale the batched process, the images are generated "correctly"

**Comment by JeLuF** [comment]
This is actually documented behaviour of ancestral samplers:
https://github.com/cmdr2/stable-diffusion-ui/wiki/How-to-Use#samplers

If you plan to use upscaling, avoid to generate images in parallel.
