### ISSUE TITLE
add Kandinsky 2.0 - the first multilingual text2image model

### ISSUE THREAD

**Issue by 0-NiK-0** [cmdr2/stable-diffusion-ui#1066]
Ability to write Prompt in more than 100 languages.

Kandinsky 2.0
https://github.com/ai-forever/Kandinsky-2.0
https://huggingface.co/sberbank-ai/Kandinsky_2.0

Model architecture:
It is a latent diffusion model with two multilingual text encoders:

mCLIP-XLMR 560M parameters
mT5-encoder-small 146M parameters
These encoders and multilingual training datasets unveil the real multilingual text-to-image generation experience!

Kandinsky 2.0 was trained on a large 1B multilingual set, including samples that we used to train Kandinsky.

In terms of diffusion architecture Kandinsky 2.0 implements UNet with 1.2B parameters.

<img width="1428" alt="NatallE" src="https://user-images.githubusercontent.com/126181396/227801399-24d04f77-8f02-4068-939b-43d12b4e82f9.png">

**Comment by 0-NiK-0** [comment]
Kandinsky 2.1 inherits best practicies from Dall-E 2 and Latent diffucion, while introducing some new ideas.

As text and image encoder it uses CLIP model and diffusion image prior (mapping) between latent spaces of CLIP modalities. This approach increases the visual performance of the model and unveils new horizons in blending images and text-guided image manipulation.

For diffusion mapping of latent spaces we use transformer with num_layers=20, num_heads=32 and hidden_size=2048.

Other architecture parts:

Text encoder (XLM-Roberta-Large-Vit-L-14) - 560M
Diffusion Image Prior — 1B
CLIP image encoder (ViT-L/14) - 427M
Latent Diffusion U-Net - 1.22B
MoVQ encoder/decoder - 67M
Kandinsky 2.1 was trained on a large-scale image-text dataset LAION HighRes and fine-tuned on our internal datasets.

<img width="730" alt="kandinsky21" src="https://user-images.githubusercontent.com/126181396/228552493-b498c415-936d-4c24-8ea9-adc2f60dd2ab.png">

**Comment by ke1ne** [comment]
1. This guy looks like a spammer who is pushing the same message into all Stable Diffusion related discussion.
2. "Kandinsky" model team is a russian bank. The Russia is waing a genocidal war in Ukraine, killing, raping and torturing Ukrainian people. The International Criminal Court issued an arrest warrant for Russian President Putin for forced deporting Ukrainian children to Russia. It's ridiculus and not ethical to support russian products!

**Comment by ke1ne** [comment]
> ke1ne, GitHub is not the place for your political and nationalist propaganda.

It's a really serious accusal from empty "just created" profile.

**Comment by 0-NiK-0** [comment]
Kandinsky 2.1 
Demo
https://fusionbrain.ai/
https://t.me/kandinsky21_bot
https://rudalle.ru/kandinsky2
https://huggingface.co/spaces/ai-forever/Kandinsky2.1
Info
https://habr.com/ru/companies/sberbank/articles/725282/
https://www.reddit.com/r/StableDiffusion/comments/12bf5k2/kandinsky_21_beats_stable_diffusion_and_allows/

**Comment by cmdr2** [comment]
Thanks, but our project is an installer and UI around Stable Diffusion (and diffusers). If diffusers adds support for this, this can be looked into. No plans to do this right now.
