### ISSUE TITLE
Cannot start Easy Diffusion Beta with "Test Diffusers" enabled on my GTX1050.

### ISSUE THREAD

**Issue by smf69** [cmdr2/stable-diffusion-ui#1068]
**Describe the bug**
```
18:21:42.552 ERROR cuda:0 Error while loading stable-diffusion model:                                model_manager.py:46
D:\EasyDiffusion\models\stable-diffusion\sd-v1-4.ckpt
18:21:42.552 ERROR cuda:0 Error: CUDA out of memory. Tried to allocate 86.00 MiB (GPU 0; 3.00 GiB    model_manager.py:47
total capacity; 2.54 GiB already allocated; 0 bytes free; 2.61 GiB reserved in total by PyTorch) If
reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See
documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
18:21:42.561 ERROR cuda:0 Consider removing the model from the model folder.                         model_manager.py:48
```

**To Reproduce**
1. Launch Easy Diffusion from the start menu.
2. Wait until error appears in console.

**Expected behavior**
Easy Diffusion to start normally and just run slowly.

**Screenshots**
*n/a*

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2 (OS Build 22621.1413)
 - Browser: Google Chrome
 - Version: v2.5.28 (beta)

**Additional context**
- GPU memory usage *is* set to "Low".
- Haven't had this issue in the past.
- I tried resetting the image settings, but even the default `sd-1.4` model is failing to initially load.
- Cannot generate any images as "the stable diffusion model is not loaded".
- I am aware I do not have that much VRAM available, but I have been running Easy Diffusion on this machine since it was just called Stable Diffusion UI, so I am assuming this is just specific to the Test Diffusers option in the Beta.
- AFAIK there is nothing else on my system using the GPU (all of my daily apps are set to use the integrated graphics), so Easy Diffusion should have almost the full 3.0GB of VRAM my board's Nvidia GTX 1050 has available to it.

**Comment by ria00891** [comment]
I'm also experiencing this with my gtx 1650 super..maybe beta isn't optimized yet??

**Comment by smf69** [comment]
That seems to be the case. I wouldn't be surprised as it takes time to get AI models running smoothly (or at all) on more limited hardware. Unfortunately, I do not have access to better performing hardware (except for my institutions compute cluster, but no individual can get enough resources for SD without a specific research reason).

**Comment by smf69** [comment]
I figured as such. Best of luck with the optimizations! I can't wait to see how it turns out.

I might take a look at the code myself to see if there's anything I could do to help the project if possible, but my skills related to the generative AI subject are limited.

**Comment by smf69** [comment]
Looks like the last beta build dramatically improved test diffuser VRAM usage, I'll close this issue now. Good work, dev(s)!

**Comment by cmdr2** [comment]
Thanks @smf69 ! Glad it's working better now for you!
