### ISSUE TITLE
Image auto-saving doesn't obey the image quality parameter and there might be double quality conversion

### ISSUE THREAD

**Issue by ufuksarp** [cmdr2/stable-diffusion-ui#1080]
With some online JPEG quality checker I tested the JPEG quality of auto-saved images. All of them is at 75 quality, despite Image Quality being set to 95.

However the image quality still changes depending on the slider in the UI. This points to some double image creation shenanigans in the code, as in **converting** an image with a certain quality (set in UI) to another quality.

But if you manually click the "Download image" button, it works as it should, saving the image at the desired quality.

Also another slider should be added next to the Auto-Save switch in the Settings tab to change the auto-save quality.

**Comment by JeLuF** [comment]
Do you have metadata embedding enabled for auto-saved images?

**Comment by ufuksarp** [comment]
> Do you have metadata embedding enabled for auto-saved images?

Yes, set for "Embed".
