### ISSUE TITLE
Download image button doesn't save metadata

### ISSUE THREAD

**Issue by ufuksarp** [cmdr2/stable-diffusion-ui#1081]
Download image button doesn't save metadata. For auto-saved images it works as it should.

**Comment by JeLuF** [comment]
Which download image button did you use? The one in the image's overlay menu, or the one at the top of the page?

**Comment by ufuksarp** [comment]
> Which download image button did you use? The one in the image's overlay menu, or the one at the top of the page?

First one, singular download button.

**Comment by JeLuF** [comment]
The button does exactly what its label says. To download the metadata, use the "JSON" button next to it.
![image](https://user-images.githubusercontent.com/5852422/228585459-e2bec25e-cf00-42f1-af9c-c916f3412fce.png)

If your request is about embedded metadata in downloaded images, this is covered in #966.

**Comment by ufuksarp** [comment]
About metadata of auto-saved images, they are working fine. I think metadata should be embedded when you click the "Download Image" button on a singular image. I mean there is a reason I pick "embed" for auto-saved images' metadata, not JSON. 😅 Maybe add an option in the settings page for automatically downloading or embedding of metadata on manual downloads?

**Comment by ollobrains** [comment]
extra option sounds good

**Comment by cmdr2** [comment]
Tracking this in https://github.com/cmdr2/stable-diffusion-ui/issues/467
