### ISSUE TITLE
Error: Unexpected Read Error:

### ISSUE THREAD

**Issue by elijas-m** [cmdr2/stable-diffusion-ui#1084]
Seed: 2442442, Sampler: euler_a, Inference Steps: 25, Guidance Scale: 7.5, Model: sd-v1-4
Error: Unable to load weights from pytorch checkpoint file for 'C:\EasyDiffusion\profile/.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snapshots\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff\pytorch_model.bin' at 'C:\EasyDiffusion\profile/.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snapshots\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff\pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

Seed: 5842043, Sampler: euler_a, Inference Steps: 25, Guidance Scale: 7.5, Model: sd-v1-4
Error: Unexpected Read Error:
Error:undefined
EventInfo: {
    "reader": {}
}

Error: The model for Stable Diffusion has not been loaded yet! If you've tried to load it, please check the logs above this message for errors (while loading the model).

Seed: 3001678, Sampler: euler_a, Inference Steps: 25, Guidance Scale: 7.5, Model: v1-5-pruned-emaonly, VAE: vae-ft-mse-840000-ema-pruned
Error: Unexpected Read Error:
Error:undefined
EventInfo: {
    "reader": {}
}

Error: The model for Stable Diffusion has not been loaded yet! If you've tried to load it, please check the logs above this message for errors (while loading the model).

Seed: 7266969, Sampler: euler_a, Inference Steps: 25, Guidance Scale: 7.5, Model: v1-5-pruned-emaonly
Error: Unable to load weights from pytorch checkpoint file for 'C:\EasyDiffusion\profile/.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snapshots\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff\pytorch_model.bin' at 'C:\EasyDiffusion\profile/.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snapshots\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff\pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

**Comment by elijas-m** [comment]
Help! Please correct the error.

**Comment by JeLuF** [comment]
```
Error: Unable to load weights from pytorch checkpoint file for 'C:\EasyDiffusion\profile\.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snapshots\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff\pytorch_model.bin'
```
The `pytorch_model.bin` file is broken. Please remove it and restart EasyDiffusion.

**Comment by elijas-m** [comment]
can I use this with Lora models?

**Comment by elijas-m** [comment]
can I work locally without using the internet?

**Comment by JeLuF** [comment]
> requests.exceptions.ProxyError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries
exceeded with url: /openai/clip-vit-large-patch14/resolve/main/vocab.json (Caused by
ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be
HTTP.

Did you specify `http://` or `https://` for the proxy server address? According to the error message, you should change it from `https` to `http`.

**Comment by elijas-m** [comment]
I don't manage proxy server

**Comment by JeLuF** [comment]
According to the error message, there's a proxy configuration in place. Please run the `Developer Console.cmd` from EasyDiffusions installation directory and run the commands:
```
set | findstr /i proxy
python -m pip config list
```
Do these commands return any proxy settings?

**Comment by elijas-m** [comment]
> Do these commands return any proxy settings?

No

**Comment by JeLuF** [comment]
The HTTPS proxy setting is wrong. It must be: `'https': 'http://192.168.1.52:8080/',` (note the missing `s` in the URL).

**Comment by elijas-m** [comment]
proxy server settings are set in windows 11, I can't write letters there, only numbers

**Comment by elijas-m** [comment]
> the missing `s` in the URL
 `s` is missing only in the `http` protocol, everything is correct

**Comment by cmdr2** [comment]
You can try downloading this file manually from: https://huggingface.co/openai/clip-vit-large-patch14/resolve/main/pytorch_model.bin

And save it in `C:\EasyDiffusion\profile\.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snapshots\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff\`
