### ISSUE TITLE
multi GPU bug? 

### ISSUE THREAD

**Issue by 852569069** [cmdr2/stable-diffusion-ui#1086]
I have 10 3080 GPU.
but the page stuck like that:
![image](https://user-images.githubusercontent.com/30398478/228682713-07340eef-462a-49db-a623-0957e336f22b.png)

and the cmd windows shows like this:
![image](https://user-images.githubusercontent.com/30398478/228682850-fe985082-c85d-4047-b905-0166bad55749.png)

**Comment by 852569069** [comment]
why so many rom require?
![image](https://user-images.githubusercontent.com/30398478/228776205-33bda4da-6ba9-4789-bfde-50e1c89392c3.png)
 this is my gpu
 
![image](https://user-images.githubusercontent.com/30398478/228776285-f028743a-4bbb-458d-8b7a-057457794400.png)

**Comment by W1Real** [comment]
I have two Tesla T4 14GB, and 13GB ram. And I can attest that the system crashes due to running out of RAM. 

I did download easy diffusion specially for that, but it sadly didn't work.

**Comment by JeLuF** [comment]
@W1Real Add more swap space. It's only needed to load the model. It will not affect the generation speed.

Please make sure that your swap space uses the disk, but not zram or similar techniques.

**Comment by 852569069** [comment]
I add the ram to 128g, it's working now
