### ISSUE TITLE
new pytorch update could be affecting easy diffusion UI

### ISSUE THREAD

**Issue by ollobrains** [cmdr2/stable-diffusion-ui#1091]
been having random problems today and with xfomers this could be responsible https://www.reddit.com/r/StableDiffusion/comments/1262c7u/if_you_use_xformers_an_update_dropped_yesterday/

**Comment by ollobrains** [comment]
seems to be affecting automatic1111 and stable diffusion WebUI users amoung others.  Might need a tweak based on this

**Comment by JeLuF** [comment]
EasyDiffusion isn't using xformers.
