### ISSUE TITLE
Test Diffusers is not in the settings

### ISSUE THREAD

**Issue by iegoshin** [cmdr2/stable-diffusion-ui#1099]
**Describe the bug**
After restarting the server I noticed the LORA pull-down list, so I started downloading models.
There was no refresh icon next to the pull-down list, so I restarted server.
After that I cannot see the LORA pull-down list.
I checked "What's new" tab and found that there should be "Test Diffusers" in the settings, but it is not there - neither in Main, nor in Beta channel.

**To Reproduce**
Add LORA models into ~/models/lora/

**Expected behavior**
See LORA pull-down list.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by JeLuF** [comment]
You need to activate beta, click on save, restart the server, go to the settings, activate Test diffusers, restart again.

If the Test Diffusers option does not appear after the first restart, a second restart might help.

**Comment by iegoshin** [comment]
Ah, that worked, thank you JeLuF! :)
