### ISSUE TITLE
Lack of uninstall information

### ISSUE THREAD

**Issue by wxyEquation** [cmdr2/stable-diffusion-ui#111]
Currently there is no good way to keep tracking dependencies installed by the one click installer.

I assume most of the dependency are inside the conda enviroment, so if I need to free some space for other uses in the future I can just delete the enviroment and everything under C:\stable-diffusion-ui

Is this true?

**Comment by cmdr2** [comment]
Thanks, I've added the uninstall info. Yes you can delete the folder, should be enough. https://github.com/cmdr2/stable-diffusion-ui/blob/main/README.md#installation
