### ISSUE TITLE
@set FORCE_FULL_PRECISION=T

### ISSUE THREAD

**Issue by Kenneth-Rosenstroem** [cmdr2/stable-diffusion-ui#1113]
@JeLuF  - Writing the "@set FORCE_FULL_PRECISION=T" in config.bat, described here: https://github.com/cmdr2/stable-diffusion-ui/issues/922 gives me this result:

Exception in thread cuda:0:
Traceback (most recent call last):
  File "E:\EasyDiffusion\installer_files\env\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "E:\EasyDiffusion\installer_files\env\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\EasyDiffusion\ui\easydiffusion\task_manager.py", line 348, in thread_render
    gc(renderer.context)
  File "E:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\utils\memory_utils.py", line 17, in gc
    torch.cuda.empty_cache()
  File "E:\EasyDiffusion\installer_files\env\lib\site-packages\torch\cuda\memory.py", line 125, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

Any hints as to what I should do. Got green, black and noise images depending on the chosen resolution. Tried to follow the troubleshooter guide, but nothing worked here. https://imagetwist.com/j33gq1ns6a6p/A_cat_on_a_grass_field_FYLQQCR0.jpeg

Running on Nvidia GTX 780 Ti win 11

Everything installed as it should.

**Comment by RenaKunisaki** [comment]
That link led me to a bunch of porn.

**Comment by Kenneth-Rosenstroem** [comment]
It's just 1 picture link, just uploaded it and linked it. Sorry about that, it's just a small 512 x 512 with noise.

**Comment by Kenneth-Rosenstroem** [comment]
OK, let me try this again. 

Cuda: https://ibb.co/M9Vbrz5
Easdy Diffusion: https://ibb.co/KFL1BP6
Browser: https://ibb.co/bW2bDm7
Settings: https://ibb.co/V2MqfZv

I hope it works this time. Thanks.

**Comment by JeLuF** [comment]
Why do you want to enable Full Precision?

Can you please share the full log? That excerpt isn't very helpful. On Windows 10, you can use these 6 clicks to copy the text:
![image](https://user-images.githubusercontent.com/5852422/229556787-c70b53fd-e7b3-4ebe-acd1-546dcb94036e.png)

Can you please check whether your GPU is listed in the `System Info` section on the `Settings` tab?
![image](https://user-images.githubusercontent.com/5852422/229560049-3260a9e2-d18d-4f51-9ff2-0768955f1c8a.png)


PS: You can paste images directly into github.

**Comment by ollobrains** [comment]
> Why do you want to enable Full Precision?
> 
> Can you please share the full log? That excerpt isn't very helpful. On Windows 10, you can use these 6 clicks to copy the text: ![image](https://user-images.githubusercontent.com/5852422/229556787-c70b53fd-e7b3-4ebe-acd1-546dcb94036e.png)
> 
> Can you please check whether your GPU is listed in the `System Info` section on the `Settings` tab? ![image](https://user-images.githubusercontent.com/5852422/229560049-3260a9e2-d18d-4f51-9ff2-0768955f1c8a.png)
> 
> PS: You can paste images directly into github.

slight quality improvement over half precision, but its very small at the end of the day

**Comment by JeLuF** [comment]
@ollobrains 
> slight quality improvement over half precision, but its very small at the end of the day

A/B tests have shown that people can not tell which image has been made with half or full precision. They differ slightly, but in general one isn't better than the other.
