### ISSUE TITLE
UI wont start and gives Opera Error

### ISSUE THREAD

**Issue by GrimTheDragonLord** [cmdr2/stable-diffusion-ui#1114]
**Describe the bug**
UI won't start and gives me an error for Opera GX

**To Reproduce**
1. Have Opera GX
2. Install Easy Diffusion
3. Try to open Easy Diffusion and get error

**Expected behavior**
The UI opens im guessing.

For anyone wondering I have an old prebuilt PC that is currently running on a Ryzen 3 2200G with 32GB of ram, Windows 10 x64, and 1 TB of storage. No GPU besides my Radeon x1600 pro but that wont work in my pc for some reason.

![image](https://user-images.githubusercontent.com/101131318/229553307-c5c96bcc-fe10-40be-9058-bfa1d081d594.png)

**Comment by JeLuF** [comment]
Re-run the opera GX installer. It will fix the Opera installation. After doing this once, both Opera and EasyDiffusion can be used together.

**Comment by GrimTheDragonLord** [comment]
> Re-run the opera GX installer. It will fix the Opera installation. After doing this once, both Opera and EasyDiffusion can be used together.

It worked! Thank you!
