### ISSUE TITLE
ImportError: cannot import name 'SAFE_WEIGHTS_NAME' from 'transformers.utils'

### ISSUE THREAD

**Issue by wyy3535** [cmdr2/stable-diffusion-ui#1122]
ImportError: cannot import name 'SAFE_WEIGHTS_NAME' from 'transformers.utils'
(C:\EasyDiffusion\installer_files\env\lib\site-packages\transformers\utils\__init__.py)
Press any key to continue . . .
[错误文档.txt](https://github.com/cmdr2/stable-diffusion-ui/files/11157817/default.txt)

**Comment by pranjalyadav451** [comment]
I am having the same problem

**Comment by JeLuF** [comment]
Does this happen on a fresh installation, or when upgrading an existing version?

Please start `Developer Console.cmd` in the EasyDiffusion directory and in there, run the command:
```
python -m pip show diffusers transformers
```

**Comment by neoOpus** [comment]
Name: diffusers
Version: 0.14.0
Summary: Diffusers
Home-page: https://github.com/huggingface/diffusers
Author: The HuggingFace team
Author-email: patrick@huggingface.co
License: Apache
Location: c:\easydiffusion\installer_files\env\lib\site-packages
Requires: filelock, huggingface-hub, importlib-metadata, numpy, Pillow, regex, requests
Required-by: compel, sdkit
---
Name: transformers
Version: 4.26.1
Summary: State-of-the-art Machine Learning for JAX, PyTorch and TensorFlow
Home-page: https://github.com/huggingface/transformers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
Author-email: transformers@huggingface.co
License: Apache
Location: c:\easydiffusion\installer_files\env\lib\site-packages
Requires: filelock, huggingface-hub, numpy, packaging, pyyaml, regex, requests, tokenizers, tqdm
Required-by: compel, stable-diffusion-sdkit

**Comment by YesThisIsMe007** [comment]
And what now?

**Comment by JeLuF** [comment]
Those versions look fine, but we failed so far to reproduce the issue.

Do you have other python installations on your system, that might have diffusers or transformers installed?

**Comment by YesThisIsMe007** [comment]
I uninstalled Python, deleted all left files and folder + ran CCleaner registry scan. Also deleted the whole Easy Diffusion folder and after that ran installing again. It helped.

**Comment by neoOpus** [comment]
> [**@JeLuF**](https://github.com/JeLuF) commented on [Apr 15, 2023, 2:04 PM EDT](https://github.com/cmdr2/stable-diffusion-ui/issues/1122#issuecomment-1509916759):
> 
> > Those versions look fine, but we failed so far to reproduce the issue.
> > 
> > Do you have other python installations on your system, that might have diffusers or transformers installed?
> > 
> > _Originally posted by @JeLuF in https://github.com/cmdr2/stable-diffusion-ui/issues/1122#issuecomment-1509916759_

Yes I have Python 3.11 Installed... I will try to see how to find a solution.
