### ISSUE TITLE
Use CPU more?

### ISSUE THREAD

**Issue by HubKing** [cmdr2/stable-diffusion-ui#1126]
**Is your feature request related to a problem? Please describe.**
My AMD GPU is not supported, so I have to use CPU. The problem is that the overall CPU usage seems to be around 50%. It took me about 4 minutes to render the default sample. Doesn't that mean, that if it used 100% CPU, it would be done in 2 minutes? Why is the CPU usage low?

**Describe the solution you'd like**
Use 100% CPU.

**Describe alternatives you've considered**
Nothing.

**Additional context**
Ryzen 3600, 32GB RAM, Linux 6.2.9
![image](https://user-images.githubusercontent.com/10900489/230419572-f718f564-c073-4d97-bfd0-77a13d0116b1.png)

**Comment by JeLuF** [comment]
PyTorch is doing a lot of computations while processing the Stable Diffusion algorithm. Some of them it can do in parallel tasks, but often it can only continue if all tasks have been completed.

Imagine you want to add all prime numbers between 0 and 20. An algorithm could look like this:
```
In parallel do for i = 2 to 20:
    If is_prime(i):
        list_of_primes.append(i)
Print "The sum of all primes smaller than 20 is:", compute_sum_in_parallel(list_of_primes)
```
The computation of the sum can only start after all prime number tests have been completed.
Testing whether 19 is prime takes longer than testing it for 2.
If you have 18 cores, you will notice that some are more busy than others, even though you've reached the maximum level of parallelism. I think something similar happens with PyTorch.

Do you have the AMD ROCm Linux drivers installed? Have a look at PR #1078 which will add AMD support on Linux.

**Comment by HubKing** [comment]
1. So, it is normal that about 50% CPU is used during the entire generation?
2. Does AMD GPU currently work? That is, is an RX 6609XT supposed to be usable with the current version? I have installed some sort of runtime version of it, because Blender can use HIP for rendering on my PC.

**Comment by DianaNites** [comment]
@HubKing a 6600XT is RDNA 2 so I believe it should work with my PR, but you will probably need to add `export HSA_OVERRIDE_GFX_VERSION=10.3.0` to `scripts/user_config.sh`.

I believe the runtime is the only thing you need, so you should be good there

**Comment by HubKing** [comment]
> you will need to apply my PR somehow

I installed it using Arch AUR package. The app is placed under `/opt/stable-diffusion-ui`. So, it probably is not using GIT, and the commands you wrote seem to inclde some sort of GIT commands. If I ran the commands in `/opt/stable-diffusion-ui/sd-ui-files`, does it work? 

Or do I have to install it by cloning the GIT repository?

**Comment by DianaNites** [comment]
@HubKing I use Arch too, it is using git, `/opt/stable-diffusion-ui/sd-ui-files` is the right folder.

**Comment by HubKing** [comment]
It said that it is switched to amd-gpu-patch, and I have also created user_config.sh, but it still shows only the CPU. It seems that I have `rocm-him-runtime` 5.4.3.-2 and its dependencies (rocm-core, roocm-cmake, rocm-device-libs, rocm-language-runtime, rocm-llvm, rocminfo) installed. Are there ROCm packages that I need to install?

**Comment by DianaNites** [comment]
@HubKing Try installing `hip-runtime-amd` or see if the [Arch Wiki GPGPU page](https://wiki.archlinux.org/title/GPGPU#ROCm) helps

**Comment by HubKing** [comment]
> Try installing `hip-runtime-amd`

That thing was also already installed. I just searched installed packages with `rocm`, so it did not show up.


`user_config.sh` did not exist, so I created a new one as you wrote. 

![image](https://user-images.githubusercontent.com/10900489/230758614-0d3d0028-63ae-44be-9185-91d7db50c668.png)


The output

```
  Name:                    gfx1032                            
  Uuid:                    GPU-XX                             
  Marketing Name:          AMD Radeon RX 6600 XT              
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
--
      Name:                    amdgcn-amd-amdhsa--gfx1032         
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE   
```

**Comment by DianaNites** [comment]
@HubKing You forgot to add `export update_branch="amd-gpu-patch"`

**Comment by HubKing** [comment]
If I run `stable-diffusion-ui-server` with my account, I get some sort of file permission denied errors and then it stays still for a long time at `AMD GPU detected`, and then it printed the error "OSError: ERROR: No active render devices! Please verify the "render_devices" value in config.json" and exited.  If I run it with `sudo`, then it starts but shows only CPU.

The full output is: [stable output.txt](https://github.com/cmdr2/stable-diffusion-ui/files/11185005/stable.output.txt)

Also, the content of config.json:

```
cat config.json 
{"render_devices": "auto", "update_branch": "main", "ui": {"open_browser_on_start": true}, "net": {"listen_port": 9000, "listen_to_network": true}, "model": {"stable-diffusion": ""}, "vram_usage_level": "high"}
```

**Comment by DianaNites** [comment]
When it's staying still for a long time, it's installing the ROCm version of torch and etc that it needs and shouldnt be interrupted. I don't now why it gives permission errors, sorry. It looks like it's working at the start, it detects the GPU and logs it as "cudo:0"(it does that even on AMD/ROCm), but I dont know why it fails after that

Are you on the latest kernel? Whats your system like, is that the only GPU in it?

**Comment by HubKing** [comment]
To be honest, at first try, I thought it was stuck and ctrl+c'd it. On the second try, I left it alone, and the log I attached was from that uninterrupted run. Maybe, I need to delete everything and start from scratch again?

By "kernel", if you mean Linux kernel, I update the system daily, so the version was 6.2.9 or 6.2.10, everything is up to date.

That AMD GPU is the only GPU. The CPU is a Ryzen, so it doesn't have an integrated GPU.

**Comment by DianaNites** [comment]
@HubKing Try deleting `installer_files/env` and re-running `start.sh`

**Comment by HubKing** [comment]
> @HubKing Try deleting `installer_files/env` and re-running `start.sh`

I deleted the AUR package, and manually deleted the /opt/stable... directory. And then, I downloaded the latest version from this GIT site, extracted it under my home directory, installed it, and then applied your patch. This time, it worked. When I first tried the default astronaut, it seemed stuck, and after a long time, the progress bar started to move and done. It was done over 2 minutes. I tried it again, and this time, it took 6 seconds. Is it normal that it takes that amount of time at first try?

**Comment by HubKing** [comment]
It works, but there is a weird problem. When the process is alive (not generating images, but just idling after completing generation), I cannot suspend the computer. If I try to suspend it, the monitor gets turned off but the PC's HDD lamp keeps blinking and then after a few seconds the monitor gets turned back on aromatically. I tried it several times, and it was the same. I terminated the process with Ctrl+C, then I could suspend the PC.  This had not happened when using the original version with CPU rendering only.

**Comment by DianaNites** [comment]
@HubKing I dont know why the first time is slow, but glad to hear its working! Was it because it was loading the model from disk to your GPUs VRAM? That can take some time, and will depend on the speed of your drive, models are a few gigabytes that has to be read, but after its done that model will stay in VRAM ready to use, unless you switch to another model.

Re suspend, think of it like trying to suspend with a game running. Idk about you, but I don't expect that to work very well usually. It's keeping the GPU busy and model in VRAM so it can be fast, and that might be preventing suspend. It could also be lacking AMD driver support. I would just close it before suspending.

You could also try troubleshooting and reporting the failure to upstream AMD [here](https://gitlab.freedesktop.org/drm/amd/-/blob/master/scripts/amd_s2idle.py), and also see [here](https://gitlab.freedesktop.org/drm/amd/-/blob/master/.gitlab/issue_templates/s2idle_BUG_TEMPLATE.md)

**Comment by HubKing** [comment]
The initial delay did not happen from the next start of the server (not the next generation, but I quit the server and restarted it), so I don't know, maybe it was compiling something for the first time? Now it constantly takes about 6 seconds per one generation. That's quite fast, but the generated images don't look so good compared to online image generators. Maybe I need to download bigger data files? I am willing to spend more time than 6 seconds, if I could get better-looking results.

You have said that you use a Radeon card, too. The suspend problem happens on your computer, too?

**Comment by DianaNites** [comment]
@HubKing I don't know, I don't try to suspend when its running.

For difference in looks with online generators, they might be using different models or settings than you. Now that you have the GPU working and can generate images way faster than CPU, you're free to experiment with all kinds of models and settings and find a look you like., so I recommend doing so. Getting an image to look really good can be difficult sometimes, depending on the model.

**Comment by HubKing** [comment]
Am i supposed to apply your command when I start the app in a new terminal? Because, it seems that if I don't, it automatically goes back to the original which only allows CPU.

```
Easy Diffusion

Easy Diffusion's git repository was already installed. Updating from main..
HEAD is now at 7bc8341 Add back -q
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
```
> With all that said, since the GPU works now, is this issue still relevant?

For me, no, because I won't use CPU. But there could be other users who do not have a supported GPU (e.g., integrated or maybe Intel Arc?), and maybe they would want better CPU usage. I had this thought, which may or may not be true, but isn't the app miscalculating the CPU's capability? At the bottom, it says that the CPU has 6 cores. That is true, but the CPU has 6 cores and 12 threads. Perhaps, this app doesn't detect that it has 12 threads and thinks that it only has 6 cores and 6 threads, so it runs only 6 thread and that is why the CPU usage is constantly around 50%?

![image](https://user-images.githubusercontent.com/10900489/230806955-c910601a-4048-4de5-8806-11eb97ca8ca5.png)

**Comment by DianaNites** [comment]
@HubKing  Is `export update_branch="amd-gpu-patch"` in `user_config.sh`?

re: CPU cores and threads, thats not how it works. Hardware threads don't "really" exist, they're a hardware trick that can improve performance, but I don't think it does in cases like this that are actually heavily using the CPU

each of your 6 cores runs 2 threads each, and each core can only do so much work.

The CPU is always going to be slow. Thats *why* the GPU is used for machine learning, because CPUs aren't fast enough, period. There probably isnt much of anything they can do to make it faster.

**Comment by HubKing** [comment]
If I do Blender rendering in CPU mode, the usage graph shows that the CPU usage is 100%.
![image](https://user-images.githubusercontent.com/10900489/230808039-278260d0-5a95-499b-a065-76602863b831.png)

This is not the case for this A.I. tasks and due to the nature of A.I., it cannot use more  threads than the number of physical cores? If so, I will close this issue, because there is no room for improvements.

**Comment by DianaNites** [comment]
I don't know, i'm not an expert, maybe I was wrong and a lot better can be done here?
