### ISSUE TITLE
Easy Diffusion forgets what it was supposed to do with certain prompts when tasked with upscaling

### ISSUE THREAD

**Issue by Ryder17z** [cmdr2/stable-diffusion-ui#1134]
**Describe the bug**
Some very specific prompts will cause the upscaling to create a brand new image
It keeps happening every time with certain prompts and never with most prompts.

**To Reproduce**
1. run the prompt "furry dog black red"
2. upscale one or multiple
3. observe new image(s) looking very different from the source

**Expected behavior**
To chug along and upscale normally.

**Screenshots**
[image](https://user-images.githubusercontent.com/2000703/230661650-ae00831c-af8e-4d0b-93bc-622cdf88a984.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser: Firefox 108.0.1
 - Version: 22.00

**Additional context**
Before "easy diffusion" was a thing, this never occurred.

I don't believe this is vram problem as the "balanced" option is used.
By default i tend to generate 16 images, 4 in parallel, up to 768x768 and then  perhaps upscale it.

System specs: Ryzen 3800x, 64GB RAM. GTX1080

**Comment by JeLuF** [comment]
"Euler Ancestral" produces different images depending on the number of parallel images. If you "upscale", it will run a new job without parallelism. This is a [documented behaviour](https://github.com/cmdr2/stable-diffusion-ui/wiki/How-to-Use#samplers) of the "Ancestral" samplers.

**Comment by Ryder17z** [comment]
It is highly inconsistent. That's the issue.

**Comment by JeLuF** [comment]
In this case I'd recommend not to use the "in parallel" feature.

**Comment by cmdr2** [comment]
Sorry, it's a limitation of the way the ancestral sampler has been written. Fixing the ancestral sampler is beyond the scope of our project, we're just a UI and installer for Stable Diffusion.

**Comment by Ryder17z** [comment]
> Sorry, it's a limitation of the way the ancestral sampler has been written. Fixing the ancestral sampler is beyond the scope of our project, we're just a UI and installer for Stable Diffusion.

Aha. thanks for clarification.

**Comment by RenaKunisaki** [comment]
I think I'm experiencing a similar bug. If I click Upscale quickly on three images, often the first one won't actually be done. If I upscale some images while others are generating, often it will hang entirely.
