### ISSUE TITLE
Could not fetch URL https://pypi.org/simple/torch/

### ISSUE THREAD

**Issue by ange841** [cmdr2/stable-diffusion-ui#1147]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser:
 - Version:

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by JeLuF** [comment]
Duplicate of #1148
