### ISSUE TITLE
Easy Diffusion insist on loading older SD-V1-4.ckpt

### ISSUE THREAD

**Issue by tkocou** [cmdr2/stable-diffusion-ui#1156]
**Describe the bug**
Latest model is not available after the start.sh file is ran

**To Reproduce**
1) Enable BETA mode and save the config
2) Shutdown the server and delete the sd-v1-4.ckpt file
3) restart the SD server
4) the start.sh file re-dowloads the sd-v1-4.ckpt file

**Expected behavior**
With the configuration being in BETA mode, the latest version of model should be downloaded and made available

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.1
 - Browser: Brave
 - Version: 1.50.114

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**
I read about the latest version in the announcement channel on discord and wanted to give it a try.

![Screenshot 2023-04-13 22:58:19](https://user-images.githubusercontent.com/44550192/231930723-d30aada3-c9de-49b7-ba10-7cdcbe5c65fe.png)

**Comment by ollobrains** [comment]
yeah most users prefer 1.4 or 1.5.  much more flexibility, very least it should be 1.5 (u can always load it from huggingface with the latest checkpoint)

**Comment by JeLuF** [comment]
> Latest model is not available after the start.sh file is ran

The installer only installs 1.4, even though the software supports newer versions. You have to download the models you want to use yourself. With 1.4, there was only one model file. For 2.1, there's about 10 different files and we decided to leave the decision which model file to use to the user.

- https://huggingface.co/stabilityai/stable-diffusion-2-1-base
- https://huggingface.co/stabilityai/stable-diffusion-2-1

**Comment by tkocou** [comment]
Thank you for the enlightenment. I was not aware of the variations for SD 2.1. So, does Easy Diffusion need to be in BETA mode to use the SD 2.1 checkpoints? I prefer a "stable" version over the cutting edge version.

**Comment by ollobrains** [comment]
transferring that part to the main branch is a good idea

**Comment by JeLuF** [comment]
With the latest changes introduced in the main version, you now can delete the 1.4 model, as long as there is any other model in the `models/stable-diffusion` directory. Only if there are no other models, 1.4 will be downloaded again.
