### ISSUE TITLE
easy diffusion on AMD

### ISSUE THREAD

**Issue by LightbringeRIX** [cmdr2/stable-diffusion-ui#1157]
Hello dear friends! I started using Easy diffusion not so long ago, I think this is the best build to start mastering working with neural networks of this type. Many thanks to the developers for this wonderful work. However, there are disadvantages. Most of the problems that arise are considered in the framework of more popular assemblies. I have studied in detail the possibility of running the program on GPU with AMD, but I can't apply it to this build. Please tell me what I can do to make the program work with my GPU? Thank you in advance.

**Comment by cmdr2** [comment]
Tracking this in https://github.com/cmdr2/stable-diffusion-ui/issues/115

Current status: AMD now works out-of-the-box on Linux, but not yet on Windows
