### ISSUE TITLE
Embeddings not loading

### ISSUE THREAD

**Issue by ahroyce** [cmdr2/stable-diffusion-ui#1164]
**Describe the bug**  I added several embeddings to the embeddings folder in Stable Diffusion then restarted the .bat file but noted this...
Textual inversion embeddings loaded(5): bad-artist-anime, bad-artist, bad-hands-5, bad_prompt, bad_prompt_version2
Textual inversion embeddings skipped(7): anthro, CGI_Animation-185, CGI_Animation-245, CGI_Animation, midjourney, VikingPunk, vray-render
The embeddings that I just added show that they loaded but there was a second line reading embeddings that were skipped.  I am not sure why they were skipped?

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 112.0.5615.86 (Official Build) (64-bit)

**Comment by JeLuF** [comment]
EasyDiffusion doesn't support embeddings, so you're probably using a different software.

**Comment by ahroyce** [comment]
OK now I am confused...it loaded 5 embeddings but skipped 7.  Am I missing something?  What is EasyDiffusion?
