### ISSUE TITLE
LoRA Strength slider missing

### ISSUE THREAD

**Issue by warmos9** [cmdr2/stable-diffusion-ui#1165]
The LoRA Strength slider stopped showing up in the UI. I'm 100% sure I've been using it with my model. Not only it stopped showing up, but it does not use any LoRA models right now. In the console log there is no obvious reason, why it does happen and I am unable to give you exact steps for reproduction. The last time, it was working, was maybe before when I added some more LoRA models, but deletion of the models didn't make it show up again. I'm not sure, if that is the cause of the problem.
Can you tell me exactly when the slider hides? What are the conditions? Maybe I have some misconfiguration or something else.
Also it would be great to at least make any message to show up, why it was hidden in the UI.
I'm runnin Arch Linux, fully updated today, i've tried to restart etc.

i5-10400F, RTX4070 Ti 12G VRAM, 96G DDR4

**Comment by shenija** [comment]
setting -> Beta channel (turn on) -> Test Diffusers (turn on)

**Comment by warmos9** [comment]
Thank you, that helped. I swear I have seen the option without using beta channel. Also it looked a little bit different. The LoRA was triggered using words and not by selecting model from dropdown menu.
