### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement sdkit==1.0.70 (from versions: none)

### ISSUE THREAD

**Issue by LarryBug** [cmdr2/stable-diffusion-ui#1169]
**Describe the bug**
When I run "Start Stable Diffusion UI.cmd", still has two issues.

Following are ERROR logs:
ERROR: Could not find a version that satisfies the requirement sdkit==1.0.70 (from versions: none)
ERROR: No matching distribution found for sdkit==1.0.70
"Error updating sdkit"
sdkit version: 1.0.35

ERROR: Could not find a version that satisfies the requirement stable-diffusion-sdkit==2.1.4 (from versions: none)
ERROR: No matching distribution found for stable-diffusion-sdkit==2.1.4
"Error updating stable-diffusion-sdkit"
stable-diffusion version: 2.1.1

**Screenshots**
![1](https://user-images.githubusercontent.com/4980453/232488239-7134ea4e-9137-4158-ad35-43684ca3e7c4.png)

**Additional context**
Someone tell me Easy Diffusion python version must be pyton3.10.6, but I checked the EasyDiffusion's python version is 3.8,5 (D:\EasyDiffusion\installer_files\mamba\pkgs\python-3.8.5-h60c2a47_9_cpython\), Should I install the new python ? Thanks.

Notes:
And I have closed my all firewalls...
my pip version is 23.0.1
I have try to pip install sdkit==1.0.70 &&  stable-diffusion-sdkit==2.1.4, still has same above Screenshots issues.

**Comment by JeLuF** [comment]
Version 3.8.5 is the correct version for EasyDiffusion.

The error messages say that the installer can't connect to your proxy server. Please check your system's proxy settings.
To check which settings the installer uses, you can run the `Developer Console.cmd` tool and run the following in there:
```
python -c "import urllib.request; print(urllib.request.getproxies())"
```

**Comment by LarryBug** [comment]
thank you , Chinese network so shit....Today is work well.
