### ISSUE TITLE
No compatible GPU found.

### ISSUE THREAD

**Issue by Cyberbutt** [cmdr2/stable-diffusion-ui#1177]
I have GTX 1080 TI and windows 7. But no compatible GPU found. I can't switch "Use CPU (not GPU)" button.

**Comment by shenija** [comment]
An RTX graphics card is required

**Comment by Cyberbutt** [comment]
> > An RTX graphics card is required
> 
> Is that new requirenments I was using GTX for about one year before but from recently update I see the same problem: my GTX no can't be found

You probably need to update the Nvidia driver to a newer version. Anything newer than October 2022 should work. Older Nvidia drivers aren't supported.

Please note that Windows 7 is not supported any more. Please update your operating system.

([JeLuF](https://github.com/JeLuF) commented
