### ISSUE TITLE
not working (ubuntu 20.04.6)

### ISSUE THREAD

**Issue by M-C-2** [cmdr2/stable-diffusion-ui#1178]
Easy Diffusion

Easy Diffusion's git repository was already installed. Updating from main..
HEAD ist jetzt bei 11517b0 Merge pull request #1168 from cmdr2/beta
Bereits auf 'main'
Ihr Branch ist auf demselben Stand wie 'origin/main'.
Bereits aktuell.
torch and torchvision have already been installed.
sdkit is already installed.
sdkit version: 1.0.70
stable-diffusion version: 2.1.4
rich has already been installed.
Packages necessary for Easy Diffusion were already installed

The model file present at models/stable-diffusion/sd-v1-4.ckpt is invalid. It is only 0 bytes in size. Re-downloading..Downloading data files (weights) for Stable Diffusion..
/home/.../Software/easy-diffusion/scripts/on_sd_start.sh: Zeile 176: curl: Befehl nicht gefunden

EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

ERROR: The downloaded model file was invalid! Bytes downloaded: 0

Error downloading Stable Diffusion UI. Sorry about that, please try to:
 1. Run this installer again.
 2. If that doesn't fix it, please try the common troubleshooting steps at https://github.com/cmdr2/stable-diffusion-ui/wiki/Troubleshooting
 3. If those steps don't help, please copy *all* the error messages in this window, and ask the community at https://discord.com/invite/u9yhsFmEkB
 4. If that doesn't solve the problem, please file an issue at https://github.com/cmdr2/stable-diffusion-ui/issues

Thanks!

Press any key to continue

**Comment by HPPinata** [comment]
You need to
```
sudo apt update && sudo apt install -y curl
```
curl is a program to download files from the internet and usually preinstalled on many linux systems.
That's why the script assumes it should be there.

Alternatively you could download the model yourself (maybe ``wget`` is installed) and move it to the correct location
see the [custom model](https://github.com/cmdr2/stable-diffusion-ui/wiki/Custom-Models) section.

**Comment by M-C-2** [comment]
That's it, thanks.
