### ISSUE TITLE
Error installing on Windows

### ISSUE THREAD

**Issue by sfabriece** [cmdr2/stable-diffusion-ui#118]
I'm getting a weird error when installing on windows.

Stable diffusion is on the following path as recommended:

`C:\stable-diffusion-ui>`

![image](https://user-images.githubusercontent.com/3108592/189238918-7874a9dd-5bfb-43d9-b263-ab420f59d8fb.png)

**Comment by RocketPop** [comment]
You need to have xcopy in your path. Put c:\windows\system32 near the front of your PATH environment variable. My windows 10 install also needed this.

**Comment by cmdr2** [comment]
Thanks @RocketPop . @sfabriece Did the earlier suggestion help fix the problem? https://www.computerhope.com/issues/ch000549.htm

**Comment by sfabriece** [comment]
It seems like I already had xcopy in my path but it did not solve the problem @cmdr2

**Comment by cmdr2** [comment]
Okay, can you please remove the `conda_sd_ui_deps_installed` line from `scripts\install_status.txt` and re-run the installer? Thanks

**Comment by chrisdreid** [comment]
Try installing and running the server as Admin. For stability, I run the browser in my regular user account and not Admin.

**Comment by sfabriece** [comment]
I just re-installing and I get a different error @cmdr2 :

![image](https://user-images.githubusercontent.com/3108592/190211333-53c41da9-facf-4b21-bf8f-d33e83c54919.png)

**Comment by sfabriece** [comment]
> Try installing and running the server as Admin. For stability, I run the browser in my regular user account and not Admin.

what do you mean by server @chrisdreid

**Comment by chrisdreid** [comment]
Sorry for the confusion @sfabriece when one launches the command prompt that does the install and launch, it also boots up and runs a server listening on the localhost port 9000. I run the command prompt as admin and it works. Once it opens the browser window with localhost:9000 I close that browser window and open a browser that does not have elevated privileges (I am using chrome) and open a tab for localhost:9000 there. Hopefully that is more clear.

**Comment by chrisdreid** [comment]
> what do you mean by server @chrisdreid

Sorry for the confusion @sfabriece when one launches the command prompt that does the install and launch, it also boots up and runs a server listening on the localhost port 9000. I run the command prompt as admin and it works. Once it opens the browser window with localhost:9000 I close that browser window and open a browser that does not have elevated privileges (I am using chrome) and open a tab for localhost:9000 there. Hopefully that is more clear.

**Comment by sfabriece** [comment]
still getting the same error in elevated cmd unfortunately @chrisdreid

**Comment by HPPinata** [comment]
This does not occur any more and should be closed.
