### ISSUE TITLE
Upload Dialog broken

### ISSUE THREAD

**Issue by MitteMedia** [cmdr2/stable-diffusion-ui#1181]
When using the 'Download All' Button it was always creating a .zip file that includes all created images.

Now it downloads the single images with the file extension: .undefined

In Firefox it keeps downloading (in my case .png's) the pictures one by one but does also not create a .zip file.

Checked with: Windows, Chromebook and Mac and Chrome newest Version

**Comment by JeLuF** [comment]
Are you using the main or beta version?
Does this dialog get shown?
![image](https://user-images.githubusercontent.com/5852422/233499368-d8bda719-b9e1-4434-8444-9b63d901d2ef.png)

If yes - is the first option "Download as a ZIP file" enabled?

**Comment by MitteMedia** [comment]
Hello JeLuF,
nice to meet you.
Yes this (Your Screenshot) is what I expect.
I tested both Beta and Standard. I created a little .gif file to show you what happens.
![Animation](https://user-images.githubusercontent.com/29146310/233573473-c81f6a7a-2e61-47d7-9125-f68de4bd0473.gif)

**Comment by cmdr2** [comment]
Hi @MitteMedia I'm not sure why, but you're using a pretty old version of Easy Diffusion. Your screenshot is showing v2.5.22, whereas the latest version is v2.5.33.

Have you disabled updates or edited the script files? If so, can you please update to the current version?

Thanks

**Comment by cmdr2** [comment]
The button to download as a zip was added in v2.5.25, which is newer than what you have.

**Comment by cmdr2** [comment]
The program auto-updates, so if you haven't edited any script files, just closing the program and running `Start Stable Diffusion UI.cmd` again will get you the latest updates.
