### ISSUE TITLE
New python error when attempting to generate an image

### ISSUE THREAD

**Issue by tkocou** [cmdr2/stable-diffusion-ui#1185]
**Describe the bug**
Error: 'utf-8' codec can't decode byte 0x9c in position 2: invalid start byte  (Python error)

**To Reproduce**
1. start easy diffusion server
2. click on "Make Image"

**Expected behavior**
A generation of an image from the default prompt

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.1
 - Browser: Brave Browser
 - Version: 1.50.112

**Additional context**
Just started happening. I restored a backup made a few days ago when easy diffusion was working. This restoration rolled back any Linux updates. Still getting the error.

**Comment by cmdr2** [comment]
Hi, can you please try with a different model? I think the model that you're using is corrupted. Can you please try with the sd-v1-4 model? Thanks

**Comment by tkocou** [comment]
It is the SD1.4 model which is throwing the error. Also, I tries a different browser, same error. I did try a different model and it worked for a while. However, when I switched to the default SD1.4 model, the error started. Afterwards, switching to other models continues to throw the same error

**Comment by cmdr2** [comment]
Can you please share the full logs from the command line, after starting the program? Thanks

**Comment by tkocou** [comment]
[server.log](https://github.com/cmdr2/stable-diffusion-ui/files/11295406/server.log)

**Comment by tkocou** [comment]
One other thing to note, I had enabled the BETA in the settings and then disabled the BETA. Where can I insure that the BETA mode is truly turned off?

**Comment by tkocou** [comment]
I was on BETA and disabled it in the settings. I restarted the server. Still the same error

**Comment by cmdr2** [comment]
Just checking - did you replace your username with `*` in the logs, or is it indeed a star symbol? No issues if you removed it from the logs, just checking

**Comment by tkocou** [comment]
I removed the user name and replaced it with the star

**Comment by tkocou** [comment]
I compared the huggingface  sha256 checksum to the local sd-v1-4.ckpt file checksum. The model is free of corruption.

**Comment by JeLuF** [comment]
It fails within the functions
```
tokenizer = CLIPTokenizer.from_pretrained("openai/clip-vit-large-patch14")
....
self.encoder = json.load(vocab_handle)
```
This points into the direction of the JSON files in the `.cache/huggingface/hub/models--openai--clip-vit-large-patch14/snapshots/8d052a0f05efbaefbc9e8786ba291cfdf93e5bff` folder. I think it's in `$HOME` on Linux.

On my system, they have these sizes:
![image](https://user-images.githubusercontent.com/5852422/233687919-8054bbff-b00b-4d5e-a615-b4dbe5cecb4e.png)

To refresh them, it should be sufficient to delete them and to restart EasyDiffusion.

**Comment by tkocou** [comment]
I deleted those files and then started the server (it was down while deleting). The files were recreated as you said, however, the error still exists as posted.

**Comment by tkocou** [comment]
I will purge all references to easy-diffusion and re-install from scratch. Hopefully that will fix this problem.

**Comment by tkocou** [comment]
I will close this issue. Totally purging the easy-diffusion from Linux and re-installing easy-diffusion fixed the issue. The crying shame is that there is no way to figure out what part of easy-diffusion was corrupted. The fix:

Step 1) delete the _**easy-diffusion**_ directory and all of its sub-directories.
Step 2) delete the _**~/.cache/huggingface**_ directory and all of its sub-directories
Step 3) unpack the _**easy-diffusion-linux.zip**_ file at a convenient location
Step 4) _**cd easy-diffusion**_
Step 5) invoke the installation procedure _**./start.sh**_

**Comment by tkocou** [comment]
Figured out the root cause of the corruption: easy-diffusion server does not play well with the shutdown sequence for Linux. When you reboot / shutdown Linux while the easy-diffusion server is running, the Linux file system gets corrupted. So, the solution is to make sure the easy-diffusion server is shutdown before you reboot / shutdown Linux.

**Comment by cmdr2** [comment]
That's interesting, thanks for sharing @tkocou !
