### ISSUE TITLE
Mac M1 Pro use GPU not working

### ISSUE THREAD

**Issue by guangmingzizai** [cmdr2/stable-diffusion-ui#1187]
**Describe the bug**
On Mac M1 Pro, the result is noisy point if use GPU, it is normal if use CPU.

**Comment by cmdr2** [comment]
Hi @guangmingzizai I've pushed a fix, can you please restart Easy Diffusion and try again? Thanks

**Comment by guangmingzizai** [comment]
@cmdr2 I can't get it to work, and it needs to install `torch`(v1.13.1) every time, resulting in a very slow startup.

**Comment by cmdr2** [comment]
@guangmingzizai It won't install torch every time. It just needs to install torch 1.13.1 the first time.

**Comment by cmdr2** [comment]
Did it finish installing torch 1.13.1?

**Comment by guangmingzizai** [comment]
It is working now, thanks.

**Comment by cmdr2** [comment]
Thanks, glad it's working. Sorry for the trouble!
