### ISSUE TITLE
Bug: Install script failing on Windows 10 - zip file error.

### ISSUE THREAD

**Issue by KridOCaign** [cmdr2/stable-diffusion-ui#119]
[SDUIError.txt](https://github.com/cmdr2/stable-diffusion-ui/files/9531174/SDUIError.txt)

**Comment by cmdr2** [comment]
Hi @KridOCaign - Did we talk about this on Discord as well?

Have you tried re-installing it? Like unzipping it again and running the installer?

Looking at the logs that you sent, the dependencies for Stable Diffusion failed to download. One approach is to re-run that step. You can delete the `stable-diffusion` folder and remove the `sd_git_cloned` and `conda_sd_env_created` lines from `scripts\install_status.txt` and re-run the installer.

**Comment by KridOCaign** [comment]
Yes.
I deleted everything from stable-diffusion-UI folder and re-extracted it. There was no change.
I repeated the process on different drive roots, and had no change - fresh extractions, nothing is being moved.
A redownload of the zip did not change anything.

**Comment by KridOCaign** [comment]
Solution:
Delete %localappdata%/pip
Proceed with normal reinstall instructions.

**Comment by BadassBetty** [comment]
Hey guys my install seems to be taking a long time on installing pip dependencies, so far around 45 mins, is this normal?

**Comment by HPPinata** [comment]
Installation works by now (Downloads just take some time) this should be closed.
