### ISSUE TITLE
Error: The model for Stable Diffusion has not been loaded yet!

### ISSUE THREAD

**Issue by LarryBug** [cmdr2/stable-diffusion-ui#1192]
**Describe the bug**
I have copy the new model file to the models\stable-diffusion, and I can selected this new model,
But when I "Make Image", still say : 

Error: Unexpected Read Error:
Error:undefined
EventInfo: {
    "reader": {}
}

Error: The model for Stable Diffusion has not been loaded yet! If you've tried to load it, please check the logs above this message for errors (while loading the model).

**Screenshots**
![11](https://user-images.githubusercontent.com/4980453/233792504-e2a60afc-cc6d-47d0-87db-3f459f47eb48.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version: 11.0.5563.65（正式版本） （64 位）

**Additional context**
I have checked the [custom models notes](https://github.com/cmdr2/stable-diffusion-ui/wiki/Custom-Models) 
and one[ same issue](https://github.com/cmdr2/stable-diffusion-ui/issues/882) still cannot solve this issue.
Someone can help me , thanks.

-----------------------------------
Logs:
Install dir: D:\EasyDiffusion\
D:\EasyDiffusion\installer_files\env\Library\bin\git.exe
git version 2.40.0.windows.1
D:\EasyDiffusion\installer_files\env\Library\bin\conda.bat
D:\EasyDiffusion\installer_files\env\Scripts\conda.exe
conda 22.11.1

"Easy Diffusion - v2"

"Easy Diffusion's git repository was already installed. Updating from main.."
HEAD is now at 6b07525 Merge pull request #1190 from cmdr2/beta
Already on 'main'
Your branch is up to date with 'origin/main'.
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 7 (delta 2), reused 3 (delta 2), pack-reused 0
Unpacking objects: 100% (7/7), 5.70 KiB | 3.00 KiB/s, done.
From https://github.com/cmdr2/stable-diffusion-ui
   6b07525..ce95072  main       -> origin/main
   4ef1022..1f4e4d8  beta       -> origin/beta
Updating 6b07525..ce95072
Fast-forward
复制了 498 个文件
已复制         1 个文件。
已复制         1 个文件。
已复制         1 个文件。
已复制         1 个文件。
已复制         1 个文件。
已复制         1 个文件。
已复制         1 个文件。
已复制         1 个文件。
子目录或文件 tmp 已经存在。
torch: 1.13.1+cu116
torchvision: 0.14.1+cu116
sdkit: 1.0.80
stable-diffusion-sdkit: 2.1.4
rich: 12.6.0
uvicorn: 0.19.0
fastapi: 0.85.1
No module 'xformers'. Proceeding without it.
stable-diffusion model(s) found.
gfpgan model(s) found.
realesrgan model(s) found.
vae model(s) found.

"Easy Diffusion installation complete! Starting the server!"

PYTHONPATH=D:\EasyDiffusion\installer_files\env\lib\site-packages
D:\EasyDiffusion\installer_files\env\python.exe
Python 3.8.5
No module 'xformers'. Proceeding without it.
22:55:45.415 INFO MainThread started in D:\EasyDiffusion\stable-diffusion                                   server.py:2122:55:45.420 INFO MainThread started at 04/22/23 22:55:45                                                   server.py:2222:55:45.425 INFO MainThread Scanning all model folders for models...                               model_manager.py:24922:55:45.554 INFO MainThread Scanned 4 models. Nothing infected                                     model_manager.py:25822:55:45.658 INFO MainThread Start new Rendering Thread on device: cuda:0                            task_manager.py:46022:55:46.563 INFO cuda:0 Setting cuda:0 as active, with precision: half                            device_manager.py:15122:55:46.565 INFO cuda:0 loading stable-diffusion model from                                              __init__.py:24D:\EasyDiffusion\models\stable-diffusion\sd-v1-4.ckpt to device: cuda:0
22:55:48.147 INFO AnyIO worker thread Scanning all model folders for models...                      model_manager.py:24922:55:57.056 INFO cuda:0 using config:                                                                    __init__.py:75D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\models_db\configs\v1-inference.yaml
22:55:57.074 INFO cuda:0 using attn_precision: fp16                                                       __init__.py:81LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
22:56:14.785 INFO cuda:0 VRAM Optimizations: {'SET_ATTENTION_STEP_TO_16', 'KEEP_FS_AND_CS_IN_CPU'}   optimizations.py:2622:56:15.989 INFO cuda:0 Global seed set to 42                                                                seed.py:65Sampling:   0%|                                                                                  | 0/1 [00:00<?, ?it/s]22:56:20.564 INFO cuda:0 seeds used = [42]                                                            sampler_main.py:64
Data shape for PLMS sampling is (1, 4, 8, 8)
Running PLMS Sampling with 1 timesteps
PLMS Sampler: 100%|██████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.00s/it]
Sampling: 100%|██████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.44s/it]
22:56:23.212 INFO cuda:0 loaded stable-diffusion model from                                               __init__.py:28D:\EasyDiffusion\models\stable-diffusion\sd-v1-4.ckpt to device: cuda:0
22:56:23.216 INFO cuda:0 loading vae model from                                                           __init__.py:24D:\EasyDiffusion\models\vae\vae-ft-mse-840000-ema-pruned.ckpt to device: cuda:0
22:56:24.185 INFO cuda:0 loaded vae model from                                                            __init__.py:28D:\EasyDiffusion\models\vae\vae-ft-mse-840000-ema-pruned.ckpt to device: cuda:0
22:56:24.192 INFO cuda:0 Session 1682175347951 starting task 2357870185872 on GeForce RTX 2060       task_manager.py:31222:56:24.367 INFO cuda:0 unloaded stable-diffusion model from device: cuda:0                              __init__.py:5222:56:24.368 INFO cuda:0 loading stable-diffusion model from                                              __init__.py:24D:\EasyDiffusion\models\stable-diffusion\GuoFeng3.3.safetensors to device: cuda:0
22:56:33.106 INFO cuda:0 using config:                                                                    __init__.py:75D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\models_db\configs\v1-inference.yaml
22:56:33.125 INFO cuda:0 using attn_precision: fp16                                                       __init__.py:81LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
22:56:45.137 ERROR cuda:0 Traceback (most recent call last):                                         task_manager.py:349  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line
415, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\torch\serialization.py", line 789, in
load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\torch\serialization.py", line 1131,
in _load
    result = unpickler.load()
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\torch\serialization.py", line 1101,
in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\torch\serialization.py", line 1079,
in load_tensor
    storage = zip_file.get_storage_from_record(name, numel,
torch.UntypedStorage).storage().untyped()
RuntimeError:  data. DefaultCPUAllocator: not enough memory: you tried to allocate 12582912 bytes.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line
419, in load_state_dict
    if f.read(7) == "version":
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 64: illegal multibyte sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\EasyDiffusion\ui\easydiffusion\task_manager.py", line 336, in thread_render
    model_manager.reload_models_if_necessary(renderer.context, task.task_data)
  File "D:\EasyDiffusion\ui\easydiffusion\model_manager.py", line 124, in reload_models_if_necessary
    action_fn(context, model_type, scan_model=False)  # we've scanned them already
  File
"D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_loader\__init__.py", line
26, in load_model
    context.models = models.load_model(context, **kwargs)
  File
"D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_loader\stable_diffusion\_
_init__.py", line 84, in load_model
    model = instantiate_from_config(config.model)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\ldm\util.py", line 79, in
instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\ldm\models\diffusion\ddpm.py", line
563, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\ldm\models\diffusion\ddpm.py", line
630, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\ldm\util.py", line 79, in
instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\ldm\modules\encoders\modules.py",
line 100, in __init__
    self.transformer = CLIPTextModel.from_pretrained(version)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line
2301, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line
431, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for
'D:\EasyDiffusion\profile/.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snapshots\8d
052a0f05efbaefbc9e8786ba291cfdf93e5bff\pytorch_model.bin' at
'D:\EasyDiffusion\profile/.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snapshots\8d
052a0f05efbaefbc9e8786ba291cfdf93e5bff\pytorch_model.bin'. If you tried to load a PyTorch model from
a TF 2.0 checkpoint, please set from_tf=True.

22:56:45.671 INFO cuda:0 Session 1682175347951 task 2357870185872 failed!                            task_manager.py:35822:57:01.909 INFO AnyIO worker thread Scanning all model folders for models...                      model_manager.py:24922:57:50.110 INFO cuda:0 Session 1682175347951 starting task 2357870103712 on GeForce RTX 2060       task_manager.py:31222:57:50.115 INFO cuda:0 request: {'guidance_scale': 1.8,                                                 renderer.py:64 'height': 512,
 'hypernetwork_strength': 0,
 'lora_alpha': 0,
 'negative_prompt': '',
 'num_inference_steps': 25,
 'num_outputs': 1,
 'preserve_init_image_color_profile': False,
 'prompt': 'best quality, masterpiece, highres, 1 girl,blush',
 'sampler_name': 'dpmpp_2m',
 'seed': 0,
 'width': 512}
22:57:50.127 INFO cuda:0 task data: {'block_nsfw': False,                                                 renderer.py:65 'metadata_output_format': 'none',
 'output_format': 'jpeg',
 'output_lossless': False,
 'output_quality': 63,
 'request_id': 2357870103712,
 'save_to_disk_path': None,
 'session_id': '1682175347951',
 'show_only_filtered_image': False,
 'stream_image_progress': False,
 'stream_image_progress_interval': 5,
 'upscale_amount': 4,
 'use_face_correction': None,
 'use_hypernetwork_model': None,
 'use_lora_model': None,
 'use_stable_diffusion_model': 'D:\\EasyDiffusion\\models\\stable-diffusion\\GuoFeng3.3.safetensors',
 'use_upscale': None,
 'use_vae_model': 'D:\\EasyDiffusion\\models\\vae\\vae-ft-mse-840000-ema-pruned.ckpt',
 'vram_usage_level': 'balanced'}
22:57:50.146 INFO cuda:0 Global seed set to 0                                                                 seed.py:6522:57:50.150 ERROR cuda:0 Traceback (most recent call last):                                         task_manager.py:349  File "D:\EasyDiffusion\ui\easydiffusion\task_manager.py", line 339, in thread_render
    task.response = renderer.make_images(
  File "D:\EasyDiffusion\ui\easydiffusion\renderer.py", line 51, in make_images
    images, seeds = make_images_internal(req, task_data, data_queue, task_temp_images,
step_callback)
  File "D:\EasyDiffusion\ui\easydiffusion\renderer.py", line 71, in make_images_internal
    images, user_stopped = generate_images_internal(
  File "D:\EasyDiffusion\ui\easydiffusion\renderer.py", line 118, in generate_images_internal
    images = generate_images(context, callback=callback, **req.dict())
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\generate\image_generator.py",
line 54, in generate_images
    raise RuntimeError(
RuntimeError: The model for Stable Diffusion has not been loaded yet! If you've tried to load it,
please check the logs above this message for errors (while loading the model).

22:57:50.261 INFO cuda:0 Session 1682175347951 task 2357870103712 failed!                            task_manager.py:35822:59:48.517 INFO AnyIO worker thread Scanning all model folders for models...                      model_manager.py:24922:59:55.403 INFO AnyIO worker thread Scanning all model folders for models...                      model_manager.py:24923:00:04.272 INFO cuda:0 Session 1682175595303 starting task 2357995340608 on GeForce RTX 2060       task_manager.py:31223:00:04.355 INFO cuda:0 unloaded vae model from device: cuda:0                                           __init__.py:5223:00:04.355 INFO cuda:0 request: {'guidance_scale': 1.8,                                                 renderer.py:64 'height': 512,
 'hypernetwork_strength': 0,
 'lora_alpha': 0,
 'negative_prompt': '',
 'num_inference_steps': 25,
 'num_outputs': 1,
 'preserve_init_image_color_profile': False,
 'prompt': 'a photograph of an astronaut riding a horse',
 'sampler_name': 'dpmpp_2m',
 'seed': 0,
 'width': 512}
23:00:04.372 INFO cuda:0 task data: {'block_nsfw': False,                                                 renderer.py:65 'metadata_output_format': 'none',
 'output_format': 'jpeg',
 'output_lossless': False,
 'output_quality': 63,
 'request_id': 2357995340608,
 'save_to_disk_path': None,
 'session_id': '1682175595303',
 'show_only_filtered_image': False,
 'stream_image_progress': False,
 'stream_image_progress_interval': 5,
 'upscale_amount': 4,
 'use_face_correction': None,
 'use_hypernetwork_model': None,
 'use_lora_model': None,
 'use_stable_diffusion_model': 'D:\\EasyDiffusion\\models\\stable-diffusion\\GuoFeng3.3.safetensors',
 'use_upscale': None,
 'use_vae_model': None,
 'vram_usage_level': 'balanced'}
23:00:04.372 INFO cuda:0 Global seed set to 0                                                                 seed.py:6523:00:04.372 ERROR cuda:0 Traceback (most recent call last):                                         task_manager.py:349  File "D:\EasyDiffusion\ui\easydiffusion\task_manager.py", line 339, in thread_render
    task.response = renderer.make_images(
  File "D:\EasyDiffusion\ui\easydiffusion\renderer.py", line 51, in make_images
    images, seeds = make_images_internal(req, task_data, data_queue, task_temp_images,
step_callback)
  File "D:\EasyDiffusion\ui\easydiffusion\renderer.py", line 71, in make_images_internal
    images, user_stopped = generate_images_internal(
  File "D:\EasyDiffusion\ui\easydiffusion\renderer.py", line 118, in generate_images_internal
    images = generate_images(context, callback=callback, **req.dict())
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\generate\image_generator.py",
line 54, in generate_images
    raise RuntimeError(
RuntimeError: The model for Stable Diffusion has not been loaded yet! If you've tried to load it,
please check the logs above this message for errors (while loading the model).

23:00:04.455 INFO cuda:0 Session 1682175595303 task 2357995340608 failed!                            task_manager.py:358

**Comment by cmdr2** [comment]
> RuntimeError: data. DefaultCPUAllocator: not enough memory

Your PC is running out of system RAM. Please add some more virtual memory - https://www.ibm.com/docs/en/opw/8.2.0?topic=tuning-optional-increasing-paging-file-size-windows-computers

Thanks

Please feel free to reopen if this continues being a problem
