### ISSUE TITLE
still having error after increasing my RAM from 5GB to 8GB

### ISSUE THREAD

**Issue by jimqartworks** [cmdr2/stable-diffusion-ui#120]
<img width="864" alt="Screen Shot 2022-09-08 at 6 37 53 PM" src="https://user-images.githubusercontent.com/112999421/189256308-a3b476c7-5ca2-4f97-8848-a6824b3025b4.png">
<img width="871" alt="Screen Shot 2022-09-08 at 7 03 46 PM" src="https://user-images.githubusercontent.com/112999421/189256845-dfeb81cb-3da7-4a17-8dea-201c330f24eb.png">

**Comment by cmdr2** [comment]
Already talking in https://github.com/cmdr2/stable-diffusion-ui/issues/102
