### ISSUE TITLE
какие минимальные системные требования

### ISSUE THREAD

**Issue by igoskakigos** [cmdr2/stable-diffusion-ui#1202]
Доброго времени суток.В описании написано требуеться видеокарта на 4 Гб и оперативной памяти 8+,так же в описание сказано,что если видеокарта меньше,то просто дольше думает.
Имею сис.требования такие: AMD Penom II x 4  995 (3.2 Ghz) Оперативная память 8 Gb  видеокарта Radeon 6800  1Gb
при первом запуске,выдало ошибку СPU,сделал подкачку и все заработало.
Но на обработку одной стандартной фотографии заняло около 4 часов...В этот момент компьютером пользоваться вообще не возможно было,даже курсор мышки через раз откликался.
Какие минимальные системные требования,для более-менее корректной работы в программе?
Заранее спасибо)

**Comment by rafipiccolo** [comment]
i'm sorry to say this, but if you go english like everyone else you may have an answer

**Comment by igoskakigos** [comment]
> Доброго времени суток.
> Имею сис.требования такие: AMD Penom II x 4 995 (3.2 Ghz) Оперативная память 8 Gb видеокарта Radeon 6800 1Gb
> при первом отказе,выдало ошибку СПУ,сделал подкачку и все заработало.
> Но на обработке одной стандартной фотографии заняло около 4 часов... В этом моменте компьютером вообще не было возможности, даже курсор мышки через раз откликался.
> Какие минимальные системные требования, для более-менее корректной работы в программе?
> Заранее спасибо)

**Comment by igoskakigos** [comment]
Good day.
I have the following system requirements: AMD Penom II x 4 995 (3.2 Ghz) RAM 8 Gb graphics card Radeon 6800 1Gb
at the first failure, it gave an error to the SPU, did a swap and it all worked.
But it took about 4 hours to process one standard photo... At that moment, the computer did not have the opportunity at all, even the mouse cursor responded every other time.
What are the minimum system requirements for more or less correct work in the program?
Thank you in advance)
