### ISSUE TITLE
Please, provide an alternative way to donate on ko-fi.com

### ISSUE THREAD

**Issue by llagerlof** [cmdr2/stable-diffusion-ui#121]
Can you add Stripe to [ko-fi.com](https://ko-fi.com/cmdr2_stablediffusion_ui) ?

I don't have paypal (I can't create an account there, long story).

**Comment by cmdr2** [comment]
Sorry, unfortunately Stripe doesn't allow individuals in my country. Would've loved to add it. Thanks for your offer though :)
