### ISSUE TITLE
Error: CUDA out of memory. Tried to allocate 2.00 GiB

### ISSUE THREAD

**Issue by LarryBug** [cmdr2/stable-diffusion-ui#1210]
**Describe the bug**
get this error when I make image size with size 2048*1024.

**Screenshots**
![无标题](https://user-images.githubusercontent.com/4980453/234614921-08d30ca5-3485-4d7c-9a04-df740975a724.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version: 112
 - GTX2060

**Additional context**
I have try to set more virtual memory still have this error.
What is the solution to generating such a large size image, even if it is slower.

**logs:**
22:33:08.806 INFO cuda:0 Session 1682519084128 starting task 1561665508784 on GeForce RTX 2060       task_manager.py:312
22:33:08.806 INFO cuda:0 request: {'guidance_scale': 20.9,                                                renderer.py:64
 'height': 1024,
 'hypernetwork_strength': 0,
 'lora_alpha': 0,
 'negative_prompt': '',
 'num_inference_steps': 27,
 'num_outputs': 1,
 'preserve_init_image_color_profile': False,
 'prompt': 'wallpaper, A volcano that is erupting',
 'sampler_name': 'dpmpp_2m',
 'seed': 0,
 'width': 2048}
22:33:08.824 INFO cuda:0 task data: {'block_nsfw': False,                                                 renderer.py:65
 'metadata_output_format': 'none',
 'output_format': 'jpeg',
 'output_lossless': False,
 'output_quality': 80,
 'request_id': 1561665508784,
 'save_to_disk_path': None,
 'session_id': '1682519084128',
 'show_only_filtered_image': False,
 'stream_image_progress': False,
 'stream_image_progress_interval': 5,
 'upscale_amount': 4,
 'use_face_correction': None,
 'use_hypernetwork_model': None,
 'use_lora_model': None,
 'use_stable_diffusion_model': 'D:\\EasyDiffusion\\models\\stable-diffusion\\sd-v1-4.ckpt',
 'use_upscale': None,
 'use_vae_model': None,
 'vram_usage_level': 'balanced'}
22:33:08.840 INFO cuda:0 Global seed set to 0                                                                 seed.py:65
Sampling:   0%|                                                                                  | 0/1 [00:00<?, ?it/s]22:33:09.040 INFO cuda:0 seeds used = [0]                                                             sampler_main.py:64
  0%|                                                                                           | 0/27 [00:00<?, ?it/s]
Sampling:   0%|                                                                                  | 0/1 [00:00<?, ?it/s]
22:33:09.556 ERROR cuda:0 Traceback (most recent call last):                                         task_manager.py:349
  File "D:\EasyDiffusion\ui\easydiffusion\task_manager.py", line 339, in thread_render
    task.response = renderer.make_images(
  File "D:\EasyDiffusion\ui\easydiffusion\renderer.py", line 51, in make_images
    images, seeds = make_images_internal(req, task_data, data_queue, task_temp_images,
step_callback)
  File "D:\EasyDiffusion\ui\easydiffusion\renderer.py", line 71, in make_images_internal
    images, user_stopped = generate_images_internal(
  File "D:\EasyDiffusion\ui\easydiffusion\renderer.py", line 118, in generate_images_internal
    images = generate_images(context, callback=callback, **req.dict())
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\generate\image_generator.py",
line 104, in generate_images
    images += generate_fn(common_sampler_params.copy(), **req_args)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\generate\image_generator.py",
line 119, in txt2img
    samples = make_samples(**params)
  File
"D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\generate\sampler\sampler_main.py",
line 55, in make_samples
    return sampler_module.sample(
  File
"D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\generate\sampler\k_samplers.py", line
68, in sample
    return sample_fn(**params)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\torch\autograd\grad_mode.py", line
27, in decorate_context
    return func(*args, **kwargs)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\k_diffusion\sampling.py", line 594,
in sample_dpmpp_2m
    denoised = model(x, sigmas * s_in, **extra_args)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line
1194, in _call_impl
    return forward_call(*input, **kwargs)
  File
"D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\generate\sampler\k_samplers.py", line
81, in forward
    uncond, cond = self.inner_model(x_in, sigma_in, cond=cond_in).chunk(2)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line
1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\k_diffusion\external.py", line 112,
in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\k_diffusion\external.py", line 138,
in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\ldm\models\diffusion\ddpm.py", line
858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line
1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\ldm\models\diffusion\ddpm.py", line
1329, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line
1194, in _call_impl
    return forward_call(*input, **kwargs)
  File
"D:\EasyDiffusion\installer_files\env\lib\site-packages\ldm\modules\diffusionmodules\openaimodel.py"
, line 776, in forward
    h = module(h, emb, context)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line
1194, in _call_impl
    return forward_call(*input, **kwargs)
  File
"D:\EasyDiffusion\installer_files\env\lib\site-packages\ldm\modules\diffusionmodules\openaimodel.py"
, line 84, in forward
    x = layer(x, context)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line
1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\ldm\modules\attention.py", line 334,
in forward
    x = block(x, context=context)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line
1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\ldm\modules\attention.py", line 269,
in forward
    return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
  File
"D:\EasyDiffusion\installer_files\env\lib\site-packages\ldm\modules\diffusionmodules\util.py", line
114, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
  File
"D:\EasyDiffusion\installer_files\env\lib\site-packages\ldm\modules\diffusionmodules\util.py", line
129, in forward
    output_tensors = ctx.run_function(*ctx.input_tensors)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\ldm\modules\attention.py", line 272,
in _forward
    x = self.attn1(self.norm1(x), context=context if self.disable_self_attn else None) + x
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line
1194, in _call_impl
    return forward_call(*input, **kwargs)
  File
"D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_loader\stable_diffusion\o
ptimizations.py", line 196, in forward
    s1 = einsum("b i d, b j d -> b i j", q[:, i:end], k)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\torch\functional.py", line 378, in
einsum
    return _VF.einsum(equation, operands)  # type: ignore
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 GiB (GPU 0; 6.00 GiB total
capacity; 2.21 GiB already allocated; 1.91 GiB free; 2.23 GiB reserved in total by PyTorch) If
reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See
documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

22:33:09.707 INFO cuda:0 Session 1682519084128 task 1561665508784 failed!

**Comment by JeLuF** [comment]
"CUDA out of memory" means that your graphics card is out of memory. Paging space is not being used for your graphics card, but for your system memory.

Your GPU has 6GB of VRAM. A neural network for an image with 2048*1024 nodes would require about 20GB of VRAM. 

You could generate the image on the CPU instead of the GPU. Since the CPU doesn't support half precision, and needs to store the model and some other data structures, I'd guess you'd need about 48-64 GB of RAM to compute such an image.

**Comment by LarryBug** [comment]
What is the way to modify the configuration file without requiring so many hardware resources, even if the speed is slightly slower, it can be accepted？

Most people do not have very high hardware resources currently  :(

**Comment by JeLuF** [comment]
The original requirements of Stable Diffusion are much higher. If I remember correctly, they needed 10-12GB GPUs as minimum. Easy Diffusion contains a lot of optimizations to make it work on smaller GPUs at all. 

One way to use less memory is to go to the settings tab and set the GPU memory profile to "low" instead of "balanced". This will still not be enough to create 2MPixel images, though.

You can generate images at smaller dimensions and then use the upscalers in the rendering section to create larger images.

**Comment by LarryBug** [comment]
ok, tks guys. Have a nice day :)
