### ISSUE TITLE
xformers - available to install? 

### ISSUE THREAD

**Issue by bixarre** [cmdr2/stable-diffusion-ui#1214]
sorry if this is asked ad nauseum;

i read in a posting from january xformers would be added in SD version 2.x.xx+, i am currently on 2.5.33. 

is it available in the beta channel? 

thanks

**Comment by cmdr2** [comment]
Hi @bixarre I've just added the instructions to a wiki. Please try it out, and let us know whether it works or doesn't :)

https://github.com/cmdr2/stable-diffusion-ui/wiki/xFormers

You don't need to enable beta for this.

Thanks
