### ISSUE TITLE
The downloaded model reports an error 

### ISSUE THREAD

**Issue by mingyu0519** [cmdr2/stable-diffusion-ui#1218]
**Describe the bug**
Error: Unexpected Read Error:
Error:undefined
EventInfo: {
    "reader": {}
}

Error: The model file doesn't contain a model's checkpoint. Instead, it seems to be a LORA file.

00:00:51.764 INFO mps loading stable-diffusion model from                                                           __init__.py:24
/Users/Downloads/easy-diffusion/models/stable-diffusion/blindbox_V1Mix.safetensors to device: mps                      
00:00:51.920 ERROR mps Traceback (most recent call last):                                                      task_manager.py:349
  File "/Users/Downloads/easy-diffusion/ui/easydiffusion/task_manager.py", line 336, in                                
thread_render                                                                                                                     
    model_manager.reload_models_if_necessary(renderer.context, task.task_data)                                                    
  File "/Users/Downloads/easy-diffusion/ui/easydiffusion/model_manager.py", line 124, in                               
reload_models_if_necessary                                                                                                        
    action_fn(context, model_type, scan_model=False)  # we've scanned them already                                                
  File                                                                                                                            
"/Users/Downloads/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/models/model                    
_loader/__init__.py", line 26, in load_model                                                                                      
    context.models = models.load_model(context, **kwargs)                                                                         
  File                                                                                                                            
"/Users/Downloads/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/models/model                    
_loader/stable_diffusion/__init__.py", line 58, in load_model                                                                     
    raise Exception("The model file doesn't contain a model's checkpoint. Instead, it seems to be a LORA                          
file.")                                                                                                                           
Exception: The model file doesn't contain a model's checkpoint. Instead, it seems to be a LORA file.

**Comment by mingyu0519** [comment]
Found the cause of the problem

**Comment by tajaddini** [comment]
can you please share your workaround? I'm getting the same error

**Comment by ricpumanes** [comment]
I tried merging the LORA file, and it fixed the issue. Not sure if @mingyu0519 did the same thing.
