### ISSUE TITLE
Hidden features?

### ISSUE THREAD

**Issue by ikumi90s** [cmdr2/stable-diffusion-ui#122]
So I was playing with it today and I suddenly discovered that there's a new feature being added in my menu and it was fixing the face issue and also Real-ESRGAN upscale, how did this pop out from my menu? I didn't do anything but after I closed the system and reopen it, those 2 features were gone and back to normal, are these hidden? is there any way I can re-enable it?

**Comment by cmdr2** [comment]
Hi the program auto-updates. The new features were released, but rolled back temporarily. They will be released later today. Thanks
