### ISSUE TITLE
Make it work from a docker container

### ISSUE THREAD

**Issue by Bennoo** [cmdr2/stable-diffusion-ui#1222]
**Is your feature request related to a problem? Please describe.**
When installing everything in a linux container, this seems not possible to map the port (9000) to the host

**Describe the solution you'd like**
I think this is possibly due to the fact that the server is using 127.0.0.1

**Describe alternatives you've considered**
A way to start using 0.0.0.0 can possibly make it possible to map the port to the host
**Additional context**
It should be great to make this available from a container, easy to run locally but also to make it available as a service

**Comment by JeLuF** [comment]
To change the bind IP, you need to edit the listen port in `scripts/config.json`. The `config.sh` option just got retired a few moments ago, I need to update the documentation in the wiki later today.

**Comment by Inglebard** [comment]
Hi,
Here is my example image: https://github.com/Inglebard/dockerfiles/blob/stable-diffusion-ui/Dockerfile

It seems to work in docker without issue.

**Comment by alanpeng** [comment]
> Hi, Here is my example image: https://github.com/Inglebard/dockerfiles/blob/stable-diffusion-ui/Dockerfile
> 
> It seems to work in docker without issue.

How to enable Nvida GPU card in this container?

**Comment by Inglebard** [comment]
On your host install "nvidia-container-runtime". The installation depends of your OS.

Then launch the container with something like this `docker run -t -i --rm --gpus all -v /dev/shm:/dev/shm -p 9000:9000 inglebard/stable-diffusion-ui`

It seems to work but I am not able to test it because my GPU is too old but detected : 
```
/opt/easy-diffusion/installer_files/env/lib/python3.8/site-packages/torch/cuda/__init__.py:152: UserWarning: 
Found GPU0 NVIDIA GeForce GTX 650 which is of cuda capability 3.0.
PyTorch no longer supports this GPU because it is too old.
The minimum cuda capability supported by this library is 3.7.
```

**Comment by alanpeng** [comment]
> > Hi, Here is my example image: https://github.com/Inglebard/dockerfiles/blob/stable-diffusion-ui/Dockerfile
> > It seems to work in docker without issue.
> 
> How to enable Nvida GPU card in this container?

I change the base image with nvidia cuda support:
FROM nvidia/cuda:11.6.2-base-ubuntu20.04

**Comment by alanpeng** [comment]
> On your host install "nvidia-container-runtime". The installation depends of your OS.
> 
> Then launch the container with something like this `docker run -t -i --rm --gpus all -v /dev/shm:/dev/shm -p 9000:9000 inglebard/stable-diffusion-ui`
> 
> It seems to work but I am not able to test it because my GPU is too old but detected :
> 
> ```
> /opt/easy-diffusion/installer_files/env/lib/python3.8/site-packages/torch/cuda/__init__.py:152: UserWarning: 
> Found GPU0 NVIDIA GeForce GTX 650 which is of cuda capability 3.0.
> PyTorch no longer supports this GPU because it is too old.
> The minimum cuda capability supported by this library is 3.7.
> ```

I tried both nvidia-docker run command and docker run --runtime=nvidia. It did not help.

**Comment by alanpeng** [comment]
> --gpus all

Sorry, I forgot to add --gpus all.

It works! Thank you very much.

**Comment by alanpeng** [comment]
If we use nvidia/cuda:11.6.2-base-ubuntu20.04 as the base image, no need to add --gpus all. It will enable all GPUs by default.

But if we only want to use some graphics cards instead of all, then we need to use the parameter. For example:
docker run --gpus '"device=0,2"' -v /dev/shm:/dev/shm  ....

**Comment by Bennoo** [comment]
Thanks a lot for the help!
From my side I got the following error when trying to build the Docker Image

ModuleNotFoundError: No module named 'sdkit'

Do you know Why I got this?

**Comment by Inglebard** [comment]
Maybe related to : https://github.com/cmdr2/stable-diffusion-ui/issues/1221

**Comment by Bennoo** [comment]
Okay got it. I don't know why by GCC was not installed.
I only add it in the apt-install

`RUN apt-get update && apt-get install -y \
	ca-certificates \
	curl \
	python3 \
	unzip \
    gcc python3-dev \
	libgl1 \
	libglib2.0-0 \
	bzip2 \
	--no-install-recommends \
	&& rm -rf /var/lib/apt/lists/*`

This is working now.. 
Many thanks I close the issue
