### ISSUE TITLE
default prompt appears even if the web page is still open during engine restart

### ISSUE THREAD

**Issue by laurentopia** [cmdr2/stable-diffusion-ui#1239]
so in the scenario where you've been working for a while and need to reset, suddenly your prompt is gone

**Comment by laurentopia** [comment]
looks like a bug because all other settings are kept

**Comment by ex479** [comment]
By default, the settings are set not to save a "positive" prompt. Does it not persist even if you override this setting?

**Comment by JeLuF** [comment]
When you restart the engine, a new tab gets opened in your browser, but the old tab does still exist and doesn't get changed.
You can disable the browser start in the settings tab.

**Comment by laurentopia** [comment]
Roger that, and I see there is a sub option to keep the prompt so I'll try that.
Thanks for the awesome interface.
