### ISSUE TITLE
Windows 10 error.

### ISSUE THREAD

**Issue by DarkAlchy** [cmdr2/stable-diffusion-ui#124]
HEAD is now at d154155 Merge pull request #122 from ryudrigo/main
"Packages necessary for Stable Diffusion were already installed"
"Packages necessary for Stable Diffusion UI were already installed"
"Data files (weights) necessary for Stable Diffusion were already downloaded"

"Stable Diffusion is ready!"

started in  E:\stable-diffusion-ui\stable-diffusion
←[32mINFO←[0m:     Started server process [←[36m3044←[0m]
←[32mINFO←[0m:     Waiting for application startup.
←[32mINFO←[0m:     Application startup complete.
←[32mINFO←[0m:     Uvicorn running on ←[1mhttp://0.0.0.0:9000←[0m (Press CTRL+C to quit)
Traceback (most recent call last):
  File "E:\stable-diffusion-ui\ui\server.py", line 63, in ping
    from sd_internal import runtime
  File "E:\stable-diffusion-ui\ui\sd_internal\runtime.py", line 15, in <module>
    from ldm.util import instantiate_from_config
ModuleNotFoundError: No module named 'ldm'

Did I do something wrong?

**Comment by cmdr2** [comment]
Hi @DarkAlchy Sorry about that, it looks like it hasn't installed correctly. Can you please try re-installing it? Thanks

Please let me know if that doesn't fix it.

**Comment by DarkAlchy** [comment]
I will try this one more time but I did notice

Cloning into 'sd-ui-files'...
remote: Enumerating objects: 1346, done.
remote: Counting objects: 100% (48/48), done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 1346 (delta 23), reused 29 (delta 12), pack-reused 1298 eceiving objects:  98% (1320/1346)
Receiving objects: 100% (1346/1346), 2.25 MiB | 5.80 MiB/s, done.
Resolving deltas: 100% (802/802), done.
sd-ui-files\ui\index.html
sd-ui-files\ui\modifiers.json
sd-ui-files\ui\server.py
sd-ui-files\ui\media\ding.mp3
sd-ui-files\ui\media\kofi.png
sd-ui-files\ui\sd_internal\runtime.py
sd-ui-files\ui\sd_internal\__init__.py
7 File(s) copied
sd-ui-files\scripts\on_env_start.bat
sd-ui-files\scripts\on_env_start.sh
sd-ui-files\scripts\on_sd_start.bat
sd-ui-files\scripts\on_sd_start.sh
sd-ui-files\scripts\post_activate.bat
sd-ui-files\scripts\post_activate.sh
sd-ui-files\scripts\Start Stable Diffusion UI.cmd
sd-ui-files\scripts\start.sh
sd-ui-files\scripts\win_enable_long_filepaths.ps1
9 File(s) copied

(installer) E:\stable-diffusion-ui>t to install at the current location, please press any key to continue." & echo.
't' is not recognized as an internal or external command,
operable program or batch file.

(installer) E:\stable-diffusion-ui>pause
Press any key to continue . . .

**Comment by DarkAlchy** [comment]
Loaded this time.

Thanks.

**Comment by cmdr2** [comment]
@DarkAlchy I think I know why that `(installer) E:\stable-diffusion-ui>t to install at the current location, please press any key to continue." & echo.` message showed up. I'll fix it, thanks!
