### ISSUE TITLE
[Linux] Specify another location for the "Models" folder?

### ISSUE THREAD

**Issue by Davetheraveuk** [cmdr2/stable-diffusion-ui#1241]
Hello, my OS is Arch Linux. I have only a limited amount of space on my boot/OS drive but do have a 10TB external HDD. The 'models' folder is very large, how do I specify another storage device (or place) for the model folder? Thank you.

**Comment by JeLuF** [comment]
You can use symlinks to point to other folders or individual files. The command to create symlinks in Linux is `ln`
