### ISSUE TITLE
When using the openjourney model all I get is static after processing.

### ISSUE THREAD

**Issue by personanomada** [cmdr2/stable-diffusion-ui#1245]
Thank you for this awesome tool!

I have added the openjourney model from huggingface (https://huggingface.co/prompthero/openjourney) and when using this model I end up with a screen that I'll describe as rainbow snow storm.

1. Download openjourney model
2. Add it to Easy Diffusion
3. Run the default prompt and include mdjrny-v4 style in the prompt

I'd expect to see an image reflecting the prompt.

![image](https://user-images.githubusercontent.com/1664981/236195143-bce3c96e-8ba1-4c71-a878-85d604ab06e9.png)

 - OS: MacOS
 - Browser: Chrome
 - Version: 13.3.1

This happens every single time, no exceptions. The regular model works fine.

**Comment by Bennoo** [comment]
Hello There, 
I tried with latest ckpt model of openjourney and it is working for me
I used the following settings:
![image](https://user-images.githubusercontent.com/2066836/236398772-e3e3bf29-d7d0-4569-a18e-c3bd49d1093e.png)

And got the result:
![image](https://user-images.githubusercontent.com/2066836/236399166-66b43fc8-66d2-4e57-8375-3e4e77e82e4b.png)

Could you share your settings? Maybe this is an issue with the sampler?

**Comment by personanomada** [comment]
@Bennoo you were right mate! It was the sampler. Thank you for the thoughtful reply!
![image](https://user-images.githubusercontent.com/1664981/236444565-dc4abaa5-af3d-4b1b-a7df-40988b62bf8a.png)
