### ISSUE TITLE
After all programs run, then I just get a rolling slash /

### ISSUE THREAD

**Issue by 2655251820** [cmdr2/stable-diffusion-ui#125]
![屏幕截图 2022-09-09 162914](https://user-images.githubusercontent.com/38093850/189307127-8c962a3b-a370-40a2-9f35-1a2f6d8bf10a.png)
Oh this I waited for a long time and got nothing

**Comment by cmdr2** [comment]
Please try the latest installer from https://github.com/cmdr2/stable-diffusion-ui#installation . 

Also, if you're running behind a VPN or Proxy, they might be blocking access to the download servers. In that case we can't really do much about it, sorry.
