### ISSUE TITLE
ModuleNotFoundError: No module named 'websockets.datastructures'

### ISSUE THREAD

**Issue by gogo199432** [cmdr2/stable-diffusion-ui#126]
I'm getting the error above. It is a completely virgin install, I have just decompressed the folder into my root C:\ drive and run the installer.

![kép](https://user-images.githubusercontent.com/9107561/189378323-cfdbc22e-25f4-47af-94f4-e976b315eb24.png)

**Comment by cmdr2** [comment]
Hi, please try this suggestion from @gazhay who got past that websockets error:

"Ok so I hacked uvicorn (/home/gaz/Projects/StableDiffusion/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py)

commented out line 9 and 12
Added "Headers = {}
HTTPResponse = Any"

and then ran ./start.sh and it has opened the webui and is downloading again"

**Comment by tamal777** [comment]
I'm getting this "noModelFound Error"

started in D:\stable-diffusion-ui\stable-diffusion
←[32mINFO←[0m: Started server process [←[36m3452←[0m]
←[32mINFO←[0m: Waiting for application startup.
←[32mINFO←[0m: Application startup complete.
←[32mINFO←[0m: Uvicorn running on ←[1mhttp://0.0.0.0:9000←[0m (Press CTRL+C to quit)
←[32mINFO←[0m: 127.0.0.1:51222 - "←[1mGET / HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m: 127.0.0.1:51222 - "←[1mGET /output_dir HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m: 127.0.0.1:51222 - "←[1mGET /app_config HTTP/1.1←[0m" ←[32m200 OK←[0m
Traceback (most recent call last):
File "D:\stable-diffusion-ui\ui\server.py", line 70, in ping
from sd_internal import runtime
File "D:\stable-diffusion-ui\ui\sd_internal\runtime.py", line 15, in
from ldm.util import instantiate_from_config
ModuleNotFoundError: No module named 'ldm'

**Comment by cmdr2** [comment]
@tamal777 I replied to you on the other issue: https://github.com/cmdr2/stable-diffusion-ui/blob/main/Troubleshooting.md#no-ldm-found-or-antlr4-or-any-other-missing-module-or-clobbererror-this-transaction-has-incompatible-packages-due-to-a-shared-path
