### ISSUE TITLE
Autoupdate doesn't work.

### ISSUE THREAD

**Issue by JohnClaw** [cmdr2/stable-diffusion-ui#1263]
My EasyDiffusion's version is 2.5.22 (beta) and for some reason ED can't autoupdate. Here is the full log from the console window:

Install dir: C:\EasyDiffusion\
"Packages to install: git"

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

conda-forge/noarch                                  12.2MB @   4.8MB/s  3.6s
conda-forge/win-64                                  20.2MB @   2.8MB/s  9.5s
critical libmamba ������ ������� �� ����� ������������� � �������� ������������� ������� ��������.
INFO: Could not find files for the given pattern(s).
'git' is not recognized as an internal or external command,
operable program or batch file.
C:\EasyDiffusion\installer_files\env\Library\bin\conda.bat
C:\EasyDiffusion\installer_files\env\Scripts\conda.exe
conda 22.11.1

"Easy Diffusion - v2"

"Easy Diffusion's git repository was already installed. Updating from beta.."
'git' is not recognized as an internal or external command,
operable program or batch file.
'git' is not recognized as an internal or external command,
operable program or batch file.
'git' is not recognized as an internal or external command,
operable program or batch file.
493 File(s) copied
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
A subdirectory or file tmp already exists.

Hotfixed broken JSON file from OpenAI
"torch and torchvision have already been installed."
"sdkit is already installed."
sdkit version: 1.0.43
stable-diffusion version: 2.1.3
"rich has already been installed."
"Packages necessary for Easy Diffusion were already installed"
"Data files (weights) necessary for Stable Diffusion were already downloaded. Using the HuggingFace 4 GB Model."
"Data files (weights) necessary for GFPGAN (Face Correction) were already downloaded"
"Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus were already downloaded"
"Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus_anime were already downloaded"
"Data files (weights) necessary for the default VAE (sd-vae-ft-mse-original) were already downloaded"

"Easy Diffusion installation complete! Starting the server!"

PYTHONPATH=C:\EasyDiffusion\installer_files\env\lib\site-packages
C:\EasyDiffusion\installer_files\env\python.exe
Python 3.8.5
No module 'xformers'. Proceeding without it.
01:53:48.809 INFO MainThread started in C:\EasyDiffusion\stable-diffusion                                   server.py:19
01:53:48.820 INFO MainThread started at 05/11/23 01:53:48                                                   server.py:20
01:53:49.151 INFO MainThread Scanned 3 models. Nothing infected                                     model_manager.py:248
01:53:49.157 WARNING MainThread WARNING: Could not find a compatible GPU. Using the CPU, but this   device_manager.py:55
will be very slow!
01:53:49.160 INFO MainThread Start new Rendering Thread on device: cpu                               task_manager.py:454
01:53:50.719 INFO cpu forcing full precision for device: cpu                                              __init__.py:52
01:53:50.723 INFO cpu loading stable-diffusion model from                                                 __init__.py:23
C:\EasyDiffusion\models\stable-diffusion\sd-v1-4.ckpt to device: cpu
01:53:56.843 INFO cpu using config:                                                                       __init__.py:57
C:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\models_db\configs\v1-inference.yaml
01:53:56.889 INFO cpu using attn_precision: fp32                                                          __init__.py:63
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
01:54:13.435 INFO cpu No VRAM optimizations being applied                                            optimizations.py:21
01:54:14.119 INFO cpu loaded stable-diffusion model from                                                  __init__.py:27
C:\EasyDiffusion\models\stable-diffusion\sd-v1-4.ckpt to device: cpu

**Comment by cmdr2** [comment]
Hi @JohnClaw , sorry about that. Can you please try these steps:

1. Double-click `Developer Console.cmd` inside `C:\EasyDiffusion`
2. Type this and press enter: `conda install -y --prefix C:\EasyDiffusion\installer_files\env -c conda-forge git`

Assuming it installed git successfully, please try running `git --version` in the Developer Console.

If that returns a valid version (instead of a "not found" error), please run Easy Diffusion again.

Please let me know if that doesn't work. Thanks!

**Comment by JohnClaw** [comment]
It worked. Now ED's version is up to date. Thanks.

**Comment by cmdr2** [comment]
Great, glad it worked!
