### ISSUE TITLE
502 Bad Gateway?

### ISSUE THREAD

**Issue by stillmar** [cmdr2/stable-diffusion-ui#1266]
**Describe the bug**

I installed Stable Diffusion on cloudmos of Akash Network. 

https://github.com/88plug/awesome-akash/tree/master/stable-diffusion-ui

After the installation was completed, I opened the host URL provided on the LEASES tab but received a 502 Bad Gateway error message.

I tried specifying the port after the URL, but it still didn't work.

http://xxxxxxxxxx.xxxx.xxx.com:9000

What could be the reason for this?

Can someone help me?

**Comment by cmdr2** [comment]
Please open an issue on the git repository you linked to. You need to ask the akash network, since they're the ones who setup the network. Thanks
