### ISSUE TITLE
[Suggestion] Generate images from a batch of prompts

### ISSUE THREAD

**Issue by frode** [cmdr2/stable-diffusion-ui#128]
Context: sometimes you want to queue up a batch of generations to work while you are out doing other stuff, or you might be lucky and have a spare machine to work for you.

Enter multiple prompts and the amount of generations per prompt. 
As a start, all the prompts could use the same set of settings.

**Comment by Adil3tr** [comment]
Seconded, this would be a huge feature, when I find a good prompt I want to try lots of tweaked version of it like different artists.

**Comment by stefnotch** [comment]
Related issues: https://github.com/cmdr2/stable-diffusion-ui/issues/199 and https://github.com/cmdr2/stable-diffusion-ui/issues/135

**Comment by cmdr2** [comment]
I've just added support for prompt queue to the main UI, please try it out and let me know if there are any problems! Thanks

Closing this in favor of https://github.com/cmdr2/stable-diffusion-ui/issues/135
