### ISSUE TITLE
Remove warning when reusing settings

### ISSUE THREAD

**Issue by ManInDark** [cmdr2/stable-diffusion-ui#1290]
**Describe the bug**
The warning "Small image sizes can cause bad image quality" does not get removed if you change the settings by "Use these settings" of an earlier image generation.
It only disappears after changing the width or height manually to another value.

**To Reproduce**
1. Enqueue an image (or more) with high enough width and height for the warning not to appear
2. Change the height and width to a setting that causes the warning to appear (for example 256x256)
3. Click on "Use these settings" of the image(s) enqueued in 1
5. See that the warning did not disappear

**Expected behavior**
The warning should disappear.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows, CPU mode
 - Browser: Brave (Chromium)
 - Version: Beta Channel, likely this commit: 29ec34169c13403ebf7780a38e8143f6ea071fe9

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by ManInDark** [comment]
The `Enqueue Next n Images` isn't updated too, so when first typing in 2 it is `Enqueue Next 2 Images` but that doesn't get updated if you reuse settings from another one which had for example 3 Images generated.

**Comment by JeLuF** [comment]
Hi @ManInDark , 

Thanks for reporting this issue. The patch has been merged into the beta version and can be tested there.
