### ISSUE TITLE
[Suggestion] Use latest stable-diffusion

### ISSUE THREAD

**Issue by ChrisAcrobat** [cmdr2/stable-diffusion-ui#13]
docker-compose.yml is currently configured to download version 3080f37ef327, which is no longer the latest version.
https://github.com/cmdr2/stable-diffusion-ui/blob/f526b2df9465ef51fac87b09b9193a16e9c476d7/docker-compose.yml#L8

**Comment by cmdr2** [comment]
Thanks, updated: https://github.com/cmdr2/stable-diffusion-ui/commit/661eff90fc5d405640ec774e9ed3bcc8b9f3aa5e

**Comment by ChrisAcrobat** [comment]
@cmdr2: Any reason for not shortening it to `image: 'r8.im/stability-ai/stable-diffusion'`, so it default to latest?
If there is a reason, please do tell! I'm quite new to Docker, so I might have something to learn. 🙂

**Comment by cmdr2** [comment]
Hi, yeah I'd prefer to test a new release once before pushing it to all the users. Otherwise there's a chance that the API could change and I only discover it through user bug reports.
