### ISSUE TITLE
ImportError: Module use of python39.dll conflicts with this version of Python. -- Win10

### ISSUE THREAD

**Issue by SYSTEMST91** [cmdr2/stable-diffusion-ui#130]
I got this message, but I only have one (latest) version of Python.
![Error](https://user-images.githubusercontent.com/112665714/189398303-9ca629c9-36a7-47ad-a1e1-5ad3c3ce3e5b.jpg)

![py](https://user-images.githubusercontent.com/112665714/189398380-c1b7c309-4fe6-43f4-8614-f84f7c97df8e.jpg)

Re-installing the program didn't help.
Thanks in advance for help.

**Comment by cmdr2** [comment]
If this is still an issue, please try the latest installer from https://github.com/cmdr2/stable-diffusion-ui#installer

A lot of installation bugs have been fixed since this issue. Thanks!
