### ISSUE TITLE
(user interface) Tighten image editor dialog controls to reduce mouse travel distance

### ISSUE THREAD

**Issue by fdwr** [cmdr2/stable-diffusion-ui#1307]
**Is your feature request related to a problem? Please describe.**
On my 4k monitor, I gladly maximize the window to see as many generated images in the history as will fit, but when in-painting, I find myself constantly hauling the mouse cursor halfway across the screen between the color picker and the brush or any time selecting a new color, which becomes tiring. 🥱

![image](https://github.com/cmdr2/stable-diffusion-ui/assets/1809166/339cbd3e-d897-49cf-8809-056cf006f096)

**Describe the solution you'd like**
Consider tightening the controls relative to the image size rather than maximizing the dialog to the browser tab size. All that empty gray space adds no value anyway 🔎⚪.

![image](https://github.com/cmdr2/stable-diffusion-ui/assets/1809166/0817791b-3e4b-41e0-a2d9-1c99f4a3144b)

**Describe alternatives you've considered**
I could restore the browser window (unmaximize) and then maximize it again each time I enter/exit the dialog, but it would be nice to not even need to. 😎 I can also hack these CSS values locally, but then the next update would replace them 😟. If you ever happen to touching up that area anyway, these appear to be the pertinent values:

```
.editor-controls-center {
    ...
    flex: 0;
    ...
}

.image-editor-popup > div {
    ...
    max-width: fit-content;
    ...
}
```

It's a nice little image editor (with a better default palette selection than Windows Paint). Cheers, commander SS.

**Comment by cmdr2** [comment]
Hi @fdwr Sorry for the delay, thanks for the code change. I've added that (and tweaked the UI a bit to center the image editor horizontally).

It's been pushed to the latest beta. Please let me know if it works as expected! Thanks!

**Comment by cmdr2** [comment]
Hi @fdwr Thanks! Beta can be enabled by toggling the "Beta channel" setting in the Settings tab, and restarting ED.
