### ISSUE TITLE
how to implements kerasCV to boost SD in SDui?

### ISSUE THREAD

**Issue by CaneRandagio1983** [cmdr2/stable-diffusion-ui#1308]
I don't have a decent video card on my notebook to run Stable Diffusion well, it uses CPU and it's not very fast.

I came to know that with Stable DIffusion it is possible to implement kerasCV, to speed up the calculation process of creating images.
Is it possible to implement keras in Stable Diffusion ui?
If it is not yet possible, do you plan to implement this feature soon?

https://keras.io/guides/keras_cv/generate_images_with_stable_diffusion/

**Comment by JeLuF** [comment]
The paper is more than half a year old. It uses high end GPUs for its benchmarks. Do you have any current performance figures, comparing it with today's diffusers version?

**Comment by CaneRandagio1983** [comment]
Forgive me, I hadn't noticed the date of publication of the document.
But maybe it is still current? in the sense that it is possible to integrate it in SD?!

I don't have any more information about it, maybe we could find it on the official keras website.

**Comment by cmdr2** [comment]
Hi @CaneRandagio1983 Thanks for the suggestion. If you're interested in implementing it (after testing the performance and quality of images), please feel free to submit a PR!

Closing this for now. Thanks!
