### ISSUE TITLE
It was working but suddenly config.json error

### ISSUE THREAD

**Issue by tamal777** [cmdr2/stable-diffusion-ui#131]
File "D:\stable-diffusion-ui\ui\server.py", line 144, in getAppConfig
    with open(config_json_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\stable-diffusion-ui\\ui\\..\\scripts\\config.json'

**Comment by casc1701** [comment]
Same error here.

**Comment by KridOCaign** [comment]
`started in  S:\stable-diffusion-ui\stable-diffusion
←[32mINFO←[0m:     Started server process [←[36m18956←[0m]
←[32mINFO←[0m:     Waiting for application startup.
←[32mINFO←[0m:     Application startup complete.
←[32mINFO←[0m:     Uvicorn running on ←[1mhttp://0.0.0.0:9000←[0m (Press CTRL+C to quit)
Loading model from sd-v1-4.ckpt
Global Step: 470000
UNet: Running in eps-prediction mode
CondStage: Running in eps-prediction mode
Traceback (most recent call last):
  File "S:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\transformers\configuration_utils.py", line 650, in _get_config_dict
    config_dict = cls._dict_from_json_file(resolved_config_file)
  File "S:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\transformers\configuration_utils.py", line 734, in _dict_from_json_file
    return json.loads(text)
  File "S:\stable-diffusion-ui\stable-diffusion\env\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "S:\stable-diffusion-ui\stable-diffusion\env\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "S:\stable-diffusion-ui\stable-diffusion\env\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 88 column 3 (char 2317)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "S:\stable-diffusion-ui\ui\server.py", line 71, in ping
    runtime.load_model(ckpt_to_use="sd-v1-4.ckpt")
  File "S:\stable-diffusion-ui\ui\sd_internal\runtime.py", line 91, in load_model
    modelCS = instantiate_from_config(config.modelCondStage)
  File "s:\stable-diffusion-ui\stable-diffusion\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "s:\stable-diffusion-ui\stable-diffusion\optimizedSD\ddpm.py", line 262, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "s:\stable-diffusion-ui\stable-diffusion\optimizedSD\ddpm.py", line 282, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "s:\stable-diffusion-ui\stable-diffusion\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "s:\stable-diffusion-ui\stable-diffusion\ldm\modules\encoders\modules.py", line 142, in __init__
    self.transformer = CLIPTextModel.from_pretrained(version)
  File "S:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\transformers\modeling_utils.py", line 1764, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "S:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\transformers\models\clip\configuration_clip.py", line 126, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "S:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\transformers\configuration_utils.py", line 553, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "S:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\transformers\configuration_utils.py", line 652, in _get_config_dict
    raise EnvironmentError(
OSError: It looks like the config file at 'C:\Users\Justin/.cache\huggingface\transformers\9c24e6cd9f499d02c4f21a033736dabd365962dc80fe3aeb57a8f85ea45a20a3.26fead7ea4f0f843f6eb4055dfd25693f1a71f3c6871b184042d4b126244e142' is not a valid JSON file.

INFO:     127.0.0.1:25316 - "GET /ping HTTP/1.1" 200 OK
INFO:     127.0.0.1:25311 - "GET / HTTP/1.1" 200 OK
Traceback (most recent call last):
  File "S:\stable-diffusion-ui\ui\server.py", line 144, in getAppConfig
    with open(config_json_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'S:\\stable-diffusion-ui\\ui\\..\\scripts\\config.json'

INFO:     127.0.0.1:25311 - "GET /app_config HTTP/1.1" 200 OK`

**Comment by tamal777** [comment]
> `started in S:\stable-diffusion-ui\stable-diffusion ←[32mINFO←[0m: Started server process [←[36m18956←[0m] ←[32mINFO←[0m: Waiting for application startup. ←[32mINFO←[0m: Application startup complete. ←[32mINFO←[0m: Uvicorn running on ←[1mhttp://0.0.0.0:9000←[0m (Press CTRL+C to quit) Loading model from sd-v1-4.ckpt Global Step: 470000 UNet: Running in eps-prediction mode CondStage: Running in eps-prediction mode Traceback (most recent call last): File "S:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\transformers\configuration_utils.py", line 650, in _get_config_dict config_dict = cls._dict_from_json_file(resolved_config_file) File "S:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\transformers\configuration_utils.py", line 734, in _dict_from_json_file return json.loads(text) File "S:\stable-diffusion-ui\stable-diffusion\env\lib\json__init__.py", line 357, in loads return _default_decoder.decode(s) File "S:\stable-diffusion-ui\stable-diffusion\env\lib\json\decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "S:\stable-diffusion-ui\stable-diffusion\env\lib\json\decoder.py", line 353, in raw_decode obj, end = self.scan_once(s, idx) json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 88 column 3 (char 2317)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "S:\stable-diffusion-ui\ui\server.py", line 71, in ping runtime.load_model(ckpt_to_use="sd-v1-4.ckpt") File "S:\stable-diffusion-ui\ui\sd_internal\runtime.py", line 91, in load_model modelCS = instantiate_from_config(config.modelCondStage) File "s:\stable-diffusion-ui\stable-diffusion\ldm\util.py", line 85, in instantiate_from_config return get_obj_from_str(config["target"])(**config.get("params", dict())) File "s:\stable-diffusion-ui\stable-diffusion\optimizedSD\ddpm.py", line 262, in **init** self.instantiate_cond_stage(cond_stage_config) File "s:\stable-diffusion-ui\stable-diffusion\optimizedSD\ddpm.py", line 282, in instantiate_cond_stage model = instantiate_from_config(config) File "s:\stable-diffusion-ui\stable-diffusion\ldm\util.py", line 85, in instantiate_from_config return get_obj_from_str(config["target"])(**config.get("params", dict())) File "s:\stable-diffusion-ui\stable-diffusion\ldm\modules\encoders\modules.py", line 142, in **init** self.transformer = CLIPTextModel.from_pretrained(version) File "S:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\transformers\modeling_utils.py", line 1764, in from_pretrained config, model_kwargs = cls.config_class.from_pretrained( File "S:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\transformers\models\clip\configuration_clip.py", line 126, in from_pretrained config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs) File "S:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\transformers\configuration_utils.py", line 553, in get_config_dict config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs) File "S:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\transformers\configuration_utils.py", line 652, in _get_config_dict raise EnvironmentError( OSError: It looks like the config file at 'C:\Users\USERNAME/.cache\huggingface\transformers\9c24e6cd9f499d02c4f21a033736dabd365962dc80fe3aeb57a8f85ea45a20a3.26fead7ea4f0f843f6eb4055dfd25693f1a71f3c6871b184042d4b126244e142' is not a valid JSON file.
> 
> INFO: 127.0.0.1:25316 - "GET /ping HTTP/1.1" 200 OK INFO: 127.0.0.1:25311 - "GET / HTTP/1.1" 200 OK Traceback (most recent call last): File "S:\stable-diffusion-ui\ui\server.py", line 144, in getAppConfig with open(config_json_path, 'r') as f: FileNotFoundError: [Errno 2] No such file or directory: 'S:\stable-diffusion-ui\ui\..\scripts\config.json'
> 
> INFO: 127.0.0.1:25311 - "GET /app_config HTTP/1.1" 200 OK`

same problem

**Comment by mkiscaden** [comment]
Looks like the file 9c24e6cd9f499d02c4f21a033736dabd365962dc80fe3aeb57a8f85ea45a20a3.26fead7ea4f0f843f6eb4055dfd25693f1a71f3c6871b184042d4b126244e142 is putting trailing commas at the end of and object block. Work around is to remove them. Example:

`"projection_dim": 768,
  },`

Just find all instances where you have a comma followed by the close brace, and thats an offender. There are just a few of them.

**Comment by tamal777** [comment]
> Looks like the file 9c24e6cd9f499d02c4f21a033736dabd365962dc80fe3aeb57a8f85ea45a20a3.26fead7ea4f0f843f6eb4055dfd25693f1a71f3c6871b184042d4b126244e142 is putting trailing commas at the end of and object block. Work around is to remove them. Example:
> 
> `"projection_dim": 768, },`
> 
> Just find all instances where you have a comma followed by the close brace, and thats an offender. There are just a few of them.

where is this file located?

**Comment by cmdr2** [comment]
Please restart your server, this issue has been fixed! Thanks

**Comment by tamal777** [comment]
> Please restart your server, this issue has been fixed! Thanks

I'm getting this error now 
started in  D:\stable-diffusion-ui\stable-diffusion
←[32mINFO←[0m:     Started server process [←[36m3452←[0m]
←[32mINFO←[0m:     Waiting for application startup.
←[32mINFO←[0m:     Application startup complete.
←[32mINFO←[0m:     Uvicorn running on ←[1mhttp://0.0.0.0:9000←[0m (Press CTRL+C to quit)
←[32mINFO←[0m:     127.0.0.1:51222 - "←[1mGET / HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m:     127.0.0.1:51222 - "←[1mGET /output_dir HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m:     127.0.0.1:51222 - "←[1mGET /app_config HTTP/1.1←[0m" ←[32m200 OK←[0m
Traceback (most recent call last):
  File "D:\stable-diffusion-ui\ui\server.py", line 70, in ping
    from sd_internal import runtime
  File "D:\stable-diffusion-ui\ui\sd_internal\runtime.py", line 15, in <module>
    from ldm.util import instantiate_from_config
ModuleNotFoundError: No module named 'ldm'

**Comment by cmdr2** [comment]
@tamal777 Please try this guide: https://github.com/cmdr2/stable-diffusion-ui/blob/main/Troubleshooting.md#no-ldm-found-or-antlr4-or-any-other-missing-module-or-clobbererror-this-transaction-has-incompatible-packages-due-to-a-shared-path
