### ISSUE TITLE
The "merge models" feature inverts A with B ratio, compared to what the UI claims

### ISSUE THREAD

**Issue by lucavice** [cmdr2/stable-diffusion-ui#1312]
**Describe the bug**
The "merge models" feature uses opposite ratio compared to what UI says and what the user would expect.

**To Reproduce**
Let's take two models:
![image](https://github.com/cmdr2/stable-diffusion-ui/assets/14258744/d3d03894-d235-4300-b0e1-cb185145e34d)
A: Hyper-realistic model
B: Art model, painting style

I then produce two merges:

1: Merge ratio 93%. I expect images to be almost realistic, as it should take 93% from model A. I call this new model "realistic"
![image](https://github.com/cmdr2/stable-diffusion-ui/assets/14258744/f8a75f12-06c5-44d7-8b8e-fe720913b2cc)

2: Merge ratio 7%. I expect images to be almost paintings, as it should take 93% from model B. I call this new model "artsy"
![image](https://github.com/cmdr2/stable-diffusion-ui/assets/14258744/d333853f-effd-4d50-877d-ad178221fd78)

**Expected behavior**
I expect merged model 1 "realistic" to be almost realistic, and merged model 2 "artsy" to be almost a painting.
What happens instead is the opposite, which makes me thing that the UI or the tooling code at some points inverts the ratio compared to what the UI claims.

![image](https://github.com/cmdr2/stable-diffusion-ui/assets/14258744/61fb6e4f-2d0c-4e0d-8951-c17a9ffa7e3f)

![image](https://github.com/cmdr2/stable-diffusion-ui/assets/14258744/7c85dea6-0c6c-486e-ac81-76a5f2ad1214)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome

**Comment by JeLuF** [comment]
You're right. Working on a fix.
