### ISSUE TITLE
Stable Diffusion Installation Errors

### ISSUE THREAD

**Issue by ianphilly** [cmdr2/stable-diffusion-ui#1319]
After I double clicked the 'Start Stable Diffusion UI' cmd file, it turned into warnings and errors as below:

torch: 1.13.1+cu116
torchvision: 0.14.1+cu116
> python -m pip install --upgrade sdkit==1.0.97 -q
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/sdkit/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/sdkit/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/sdkit/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/sdkit/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/sdkit/
ERROR: Could not find a version that satisfies the requirement sdkit==1.0.97 (from versions: none)
ERROR: No matching distribution found for sdkit==1.0.97
sdkit: 1.0.35
> python -m pip install --upgrade stable-diffusion-sdkit==2.1.4
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/stable-diffusion-sdkit/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/stable-diffusion-sdkit/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/stable-diffusion-sdkit/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/stable-diffusion-sdkit/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/stable-diffusion-sdkit/
ERROR: Could not find a version that satisfies the requirement stable-diffusion-sdkit==2.1.4 (from versions: none)
ERROR: No matching distribution found for stable-diffusion-sdkit==2.1.4
stable-diffusion-sdkit: 2.1.1
> python -m pip install --upgrade rich==12.6.0
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/rich/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/rich/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/rich/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/rich/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/rich/
ERROR: Could not find a version that satisfies the requirement rich==12.6.0 (from versions: none)
ERROR: No matching distribution found for rich==12.6.0
rich: 13.3.1
> python -m pip install --upgrade uvicorn==0.19.0
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/uvicorn/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/uvicorn/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/uvicorn/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/uvicorn/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/uvicorn/
ERROR: Could not find a version that satisfies the requirement uvicorn==0.19.0 (from versions: none)
ERROR: No matching distribution found for uvicorn==0.19.0
uvicorn: 0.20.0
> python -m pip install --upgrade fastapi==0.85.1
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/fastapi/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/fastapi/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/fastapi/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/fastapi/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/fastapi/
ERROR: Could not find a version that satisfies the requirement fastapi==0.85.1 (from versions: none)
ERROR: No matching distribution found for fastapi==0.85.1
fastapi: 0.92.0
No module 'xformers'. Proceeding without it.
![1](https://github.com/cmdr2/stable-diffusion-ui/assets/135112019/472dfc86-a028-4b84-baed-ae01d73a7e53)

How can I fix it? Many thanks!

**Comment by JeLuF** [comment]
```
Cannot connect to proxy
```
This error message indicates that you have a proxy configured that is not reachable.

Please start `D:\EasyDiffusion\Developer Console.cmd` and in there, run this command to inspect the current proxy configuration:
```
python -c "import urllib.request; print(urllib.request.getproxies())"
```

**Comment by cmdr2** [comment]
@ianphilly Please feel free to reopen if this is still an issue.
