### ISSUE TITLE
Multi GPU support?

### ISSUE THREAD

**Issue by aeon3** [cmdr2/stable-diffusion-ui#132]
Hey are you planning on adding multiple GPU support? I have 2 RTX and would love to either get more VRAM or use them in parallel for faster outputs!

**Comment by cmdr2** [comment]
Hi, this is available in the latest beta. Please try enabling beta (system settings, top-right corner). Please feel free to ask on our discord server (in the beta channel) if you face any problems: https://discord.com/invite/u9yhsFmEkB
