### ISSUE TITLE
easy diffusion + plugin photoshop

### ISSUE THREAD

**Issue by bloodninjaa** [cmdr2/stable-diffusion-ui#1331]
How to make friends easy diffusion with plugin for photoshop stable.art? Writes that the server is running, but the api is not available.

**Comment by 19Georgy59** [comment]
Same problem.  I rummaged through everything where I could not find an API.

**Comment by JeLuF** [comment]
Easy Diffusion does not support the API used by that photoshop plugin.

**Comment by 19Georgy59** [comment]
it is clear which plugin is suitable, can you tell me?

**Comment by cmdr2** [comment]
Hi, the first result on Google shows this - https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin

I haven't used it, but maybe it'll help.

Closing this issue, since Easy Diffusion doesn't have a photoshop plugin.
