### ISSUE TITLE
Button to switch dimensions

### ISSUE THREAD

**Issue by Salvatos** [cmdr2/stable-diffusion-ui#1332]
**Is your feature request related to a problem? Please describe.**
Hopefully this isn’t too niche, but I find myself using almost exclusively 512 x 768 and 768 x 512, and always feel like I need too many clicks to just flip the two dropdowns (especially when going from one image to another in img2img testing).

**Describe the solution you'd like**
I’d love to have a button that flips width and height to quickly switch between portrait and landscape formats.

**Comment by JeLuF** [comment]
Check out the "Switch Width & Height Settings" plugin at https://github.com/cmdr2/stable-diffusion-ui/wiki/UI-Plugins#general-ui-changes

**Comment by Salvatos** [comment]
Perfect, thank you! I didn’t realize there were UI plugins.
