### ISSUE TITLE
uvicorn hangs up and ed doesn't start anymore (Debian 12, Beta channel with Diffusers)

### ISSUE THREAD

**Issue by jdumke** [cmdr2/stable-diffusion-ui#1333]
Today while starting up easy diffusion uvicorn files a list of errors, which were absent former days.
Here is all I got on stderr:
Already on 'beta'
cp: cannot stat 'sd-ui-files/scripts/check_models.py': No such file or directory
cp: cannot stat 'sd-ui-files/scripts/check_models.py': No such file or directory
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/jds/test/easy-diffusion/installer_files/env/bin/uvicorn:8 in <module>  │
│                                                                              │
│   5 from uvicorn.main import main                                            │
│   6 if __name__ == '__main__':                                               │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])     │
│ ❱ 8 │   sys.exit(main())                                                     │
│   9                                                                          │
│                                                                              │
│ /home/jds/test/easy-diffusion/installer_files/env/lib/python3.8/site-package │
│ s/click/core.py:1130 in __call__                                             │
│                                                                              │
│   1127 │                                                                     │
│   1128 │   def __call__(self, *args: t.Any, **kwargs: t.Any) -> t.Any:       │
│   1129 │   │   """Alias for :meth:`main`."""                                 │
│ ❱ 1130 │   │   return self.main(*args, **kwargs)                             │
│   1131                                                                       │
│   1132                                                                       │
│   1133 class Command(BaseCommand):                                           │
│                                                                              │
│ /home/jds/test/easy-diffusion/installer_files/env/lib/python3.8/site-package │
│ s/click/core.py:1055 in main                                                 │
│                                                                              │
│   1052 │   │   try:                                                          │
│   1053 │   │   │   try:                                                      │
│   1054 │   │   │   │   with self.make_context(prog_name, args, **extra) as c │
│ ❱ 1055 │   │   │   │   │   rv = self.invoke(ctx)                             │
│   1056 │   │   │   │   │   if not standalone_mode:                           │
│   1057 │   │   │   │   │   │   return rv                                     │
│   1058 │   │   │   │   │   # it's not safe to `ctx.exit(rv)` here!           │
│                                                                              │
│ /home/jds/test/easy-diffusion/installer_files/env/lib/python3.8/site-package │
│ s/click/core.py:1404 in invoke                                               │
│                                                                              │
│   1401 │   │   │   echo(style(message, fg="red"), err=True)                  │
│   1402 │   │                                                                 │
│   1403 │   │   if self.callback is not None:                                 │
│ ❱ 1404 │   │   │   return ctx.invoke(self.callback, **ctx.params)            │
│   1405 │                                                                     │
│   1406 │   def shell_complete(self, ctx: Context, incomplete: str) -> t.List │
│   1407 │   │   """Return a list of completions for the incomplete value. Loo │
│                                                                              │
│ /home/jds/test/easy-diffusion/installer_files/env/lib/python3.8/site-package │
│ s/click/core.py:760 in invoke                                                │
│                                                                              │
│    757 │   │                                                                 │
│    758 │   │   with augment_usage_errors(__self):                            │
│    759 │   │   │   with ctx:                                                 │
│ ❱  760 │   │   │   │   return __callback(*args, **kwargs)                    │
│    761 │                                                                     │
│    762 │   def forward(                                                      │
│    763 │   │   __self, __cmd: "Command", *args: t.Any, **kwargs: t.Any  # no │
│                                                                              │
│ /home/jds/test/easy-diffusion/installer_files/env/lib/python3.8/site-package │
│ s/uvicorn/main.py:404 in main                                                │
│                                                                              │
│   401 │   h11_max_incomplete_event_size: int,                                │
│   402 │   factory: bool,                                                     │
│   403 ) -> None:                                                             │
│ ❱ 404 │   run(                                                               │
│   405 │   │   app,                                                           │
│   406 │   │   host=host,                                                     │
│   407 │   │   port=port,                                                     │
│                                                                              │
│ /home/jds/test/easy-diffusion/installer_files/env/lib/python3.8/site-package │
│ s/uvicorn/main.py:569 in run                                                 │
│                                                                              │
│   566 │   │   sock = config.bind_socket()                                    │
│   567 │   │   Multiprocess(config, target=server.run, sockets=[sock]).run()  │
│   568 │   else:                                                              │
│ ❱ 569 │   │   server.run()                                                   │
│   570 │   if config.uds:                                                     │
│   571 │   │   os.remove(config.uds)  # pragma: py-win32                      │
│   572                                                                        │
│                                                                              │
│ /home/jds/test/easy-diffusion/installer_files/env/lib/python3.8/site-package │
│ s/uvicorn/server.py:60 in run                                                │
│                                                                              │
│    57 │                                                                      │
│    58 │   def run(self, sockets: Optional[List[socket.socket]] = None) -> No │
│    59 │   │   self.config.setup_event_loop()                                 │
│ ❱  60 │   │   return asyncio.run(self.serve(sockets=sockets))                │
│    61 │                                                                      │
│    62 │   async def serve(self, sockets: Optional[List[socket.socket]] = Non │
│    63 │   │   process_id = os.getpid()                                       │
│                                                                              │
│ /home/jds/test/easy-diffusion/installer_files/env/lib/python3.8/asyncio/runn │
│ ers.py:43 in run                                                             │
│                                                                              │
│   40 │   try:                                                                │
│   41 │   │   events.set_event_loop(loop)                                     │
│   42 │   │   loop.set_debug(debug)                                           │
│ ❱ 43 │   │   return loop.run_until_complete(main)                            │
│   44 │   finally:                                                            │
│   45 │   │   try:                                                            │
│   46 │   │   │   _cancel_all_tasks(loop)                                     │
│                                                                              │
│ /home/jds/test/easy-diffusion/installer_files/env/lib/python3.8/asyncio/base │
│ _events.py:616 in run_until_complete                                         │
│                                                                              │
│    613 │   │   if not future.done():                                         │
│    614 │   │   │   raise RuntimeError('Event loop stopped before Future comp │
│    615 │   │                                                                 │
│ ❱  616 │   │   return future.result()                                        │
│    617 │                                                                     │
│    618 │   def stop(self):                                                   │
│    619 │   │   """Stop running the event loop.                               │
│                                                                              │
│ /home/jds/test/easy-diffusion/installer_files/env/lib/python3.8/site-package │
│ s/uvicorn/server.py:67 in serve                                              │
│                                                                              │
│    64 │   │                                                                  │
│    65 │   │   config = self.config                                           │
│    66 │   │   if not config.loaded:                                          │
│ ❱  67 │   │   │   config.load()                                              │
│    68 │   │                                                                  │
│    69 │   │   self.lifespan = config.lifespan_class(config)                  │
│    70                                                                        │
│                                                                              │
│ /home/jds/test/easy-diffusion/installer_files/env/lib/python3.8/site-package │
│ s/uvicorn/config.py:474 in load                                              │
│                                                                              │
│   471 │   │   self.lifespan_class = import_from_string(LIFESPAN[self.lifespa │
│   472 │   │                                                                  │
│   473 │   │   try:                                                           │
│ ❱ 474 │   │   │   self.loaded_app = import_from_string(self.app)             │
│   475 │   │   except ImportFromStringError as exc:                           │
│   476 │   │   │   logger.error("Error loading ASGI app. %s" % exc)           │
│   477 │   │   │   sys.exit(1)                                                │
│                                                                              │
│ /home/jds/test/easy-diffusion/installer_files/env/lib/python3.8/site-package │
│ s/uvicorn/importer.py:21 in import_from_string                               │
│                                                                              │
│   18 │   │   raise ImportFromStringError(message.format(import_str=import_st │
│   19 │                                                                       │
│   20 │   try:                                                                │
│ ❱ 21 │   │   module = importlib.import_module(module_str)                    │
│   22 │   except ImportError as exc:                                          │
│   23 │   │   if exc.name != module_str:                                      │
│   24 │   │   │   raise exc from None                                         │
│                                                                              │
│ /home/jds/test/easy-diffusion/installer_files/env/lib/python3.8/importlib/__ │
│ init__.py:127 in import_module                                               │
│                                                                              │
│   124 │   │   │   if character != '.':                                       │
│   125 │   │   │   │   break                                                  │
│   126 │   │   │   level += 1                                                 │
│ ❱ 127 │   return _bootstrap._gcd_import(name[level:], package, level)        │
│   128                                                                        │
│   129                                                                        │
│   130 _RELOADING = {}                                                        │
│ <frozen importlib._bootstrap>:1014 in _gcd_import                            │
│ <frozen importlib._bootstrap>:991 in _find_and_load                          │
│ <frozen importlib._bootstrap>:975 in _find_and_load_unlocked                 │
│ <frozen importlib._bootstrap>:671 in _load_unlocked                          │
│ <frozen importlib._bootstrap_external>:783 in exec_module                    │
│ <frozen importlib._bootstrap>:219 in _call_with_frames_removed               │
│                                                                              │
│ /home/jds/test/easy-diffusion/ui/main.py:1 in <module>                       │
│                                                                              │
│ ❱  1 from easydiffusion import model_manager, app, server                    │
│    2 from easydiffusion.server import server_api # required for uvicorn      │
│    3                                                                         │
│    4 # Init the app                                                          │
│                                                                              │
│ /home/jds/test/easy-diffusion/ui/easydiffusion/server.py:359 in <module>     │
│                                                                              │
│   356 │   │   else:                                                          │
│   357 │   │   │   return None                                                │
│   358                                                                        │
│ ❱ 359 cloudflare = CloudflareTunnel()                                        │
│   360                                                                        │
│   361 def start_cloudflare_tunnel_internal(req: dict):                       │
│   362    try:                                                                │
│                                                                              │
│ /home/jds/test/easy-diffusion/ui/easydiffusion/server.py:342 in __init__     │
│                                                                              │
│   339 │   def __init__(self):                                                │
│   340 │   │   config = app.getConfig()                                       │
│   341 │   │   self.Urls = None                                               │
│ ❱ 342 │   │   self.port = config["net"]["listen_port"]                       │
│   343 │                                                                      │
│   344 │   def start(self):                                                   │
│   345 │   │   self.Urls = try_cloudflare(self.port)                          │
╰──────────────────────────────────────────────────────────────────────────────╯
KeyError: 'listen_port'
Press any key to continue

It seems an update removed check_models.py.

Systemspecs:
OS: Debian 12 (Bookworm)
CPU/GPU: AMD Ryzen 5600G with Radeon Graphics
Systemram (VRAM) Total 32 GB with 8/16GB VRAM depending on purpose.

Greets.

**Comment by cmdr2** [comment]
Thanks, pushed a fix for this. Please reopen if this continues to be an issue!
