### ISSUE TITLE
Prompts queue

### ISSUE THREAD

**Issue by MrManny** [cmdr2/stable-diffusion-ui#135]
The ability to queue up additional / new prompts while SD is already processing could be of interest.
I envision it as such: if the user submits new prompt(s) while SD is still doing its magic, the prompt along with its settings could be put into a queue, and the browser will start those once the backend is idle. This will also kind of require the frontend to retain generated images in-between queues. #10 is loosely related in that regard. (And maybe #56)

I am mainly adding this issue to get additional input / ideas, and to gauge interest.

**Comment by Jay4242** [comment]
What I like is that the backend already responds in a similar way.
If I send a backgrounded curl request like https://gist.github.com/Jay4242/d139fc827028f0e0299cd8018accd070 then it idles until the backend responds.
I can check the 'queue' by reading my curl processes, https://gist.github.com/Jay4242/8d11d7f7ebba983519208d1dbaa63bb5
Although, I didn't test how long curl will idle like that, so not sure what the upper limit of the queue is.  The only downside is the webUI doesn't have any indication that this is going on.

**Comment by cmdr2** [comment]
I've just added support for prompt queue to the main UI, please try it out and let me know if there are any problems! Thanks

**Comment by MrLemur** [comment]
Thanks @cmdr2! Unfortunately it still crashes if it receives a request for a generation while it is currently doing a generation.
