### ISSUE TITLE
Already downloaded and extracted pip depends but it's stuck at "Installing pip dependecies"

### ISSUE THREAD

**Issue by Yasand123** [cmdr2/stable-diffusion-ui#137]
It's been like this for 2 hours. Doesn't seem to be doing anything. CPU usage is 0-1%. No internet traffic. Note that the dependencies have already been downloaded and extracted inside `env` directory which is currently 5.0 GiB in size.

I downloaded the tar.xz file, extracted it in home, ran start.sh.

Arch Linux 5.19.7.
NVIDIA GPU.
Internet connection ~7 Megabytes per second.

**Comment by expandingfrog** [comment]
I'm having this same issue but I'm on Windows 10. Been stuck on installing pip dependencies for at least an hour now. Any updates?

**Comment by Yasand123** [comment]
> I'm having this same issue but I'm on Windows 10. Been stuck on installing pip dependencies for at least an hour now. Any updates?

It just takes time. Be patient.
