### ISSUE TITLE
start_server() in ./server not working

### ISSUE THREAD

**Issue by zaqxs123456** [cmdr2/stable-diffusion-ui#14]
I am not familiar with shell script, but I think line 10 in server did not run. I can run `docker-compose up stability-ai stable-diffusion-ui` in console manually.

**Comment by cmdr2** [comment]
Thanks, what error did it print when you tried `./server`? Can you please paste the output?

**Comment by zaqxs123456** [comment]
Nothing, didn't print anything out, but the 8000 redirect page did show up, line 9 did run.

**Comment by cmdr2** [comment]
Are you using Windows? With WSL?

**Comment by zaqxs123456** [comment]
Linux, Ubuntu

**Comment by cmdr2** [comment]
Thanks, I'd really like to figure this out, and would like your help :)

Can you please modify the `server` file to this, and then run `./server restart`

I don't think functions would be an issue, but worth a shot. Thanks!

```
#!/bin/bash

CMD="$1"
if [ -z "$1" ]; then
  CMD="start"
fi

if [ "$CMD" == "start" ]; then
  docker-compose up -d stable-diffusion-old-port-redirect > /dev/null 2>&1 # old port 8000 server, show redirect notice

  docker-compose up stability-ai stable-diffusion-ui &
elif [ "$CMD" == "stop" ]; then
  stop_server
elif [ "$CMD" == "restart" ]; then
  docker-compose down
  
  docker-compose up -d stable-diffusion-old-port-redirect > /dev/null 2>&1 # old port 8000 server, show redirect notice

  docker-compose up stability-ai stable-diffusion-ui &
else
  echo "Unknown option: $1 (Expected start or stop)"
fi
```

**Comment by zaqxs123456** [comment]
Still not working, but I find that if I remove `2>&1` in line 9 and `&` in line 10 it will run properly. I googled that use the `&` will executes the command in the background, but it didn't execute at all, I waited for few minutes still can't connect to 9000, seems it didn't run in background.

**Comment by cmdr2** [comment]
Thanks. Does running even this fail to produce any output: `docker-compose up stability-ai stable-diffusion-ui &` (with the &)

**Comment by cmdr2** [comment]
How about this? I've removed the 2>&1 and &. Does `./server restart` work now, and produce the output?

```
#!/bin/bash

CMD="$1"
if [ -z "$1" ]; then
  CMD="start"
fi

start_server() {
  docker-compose up -d stable-diffusion-old-port-redirect # old port 8000 server, show redirect notice
  docker-compose up stability-ai stable-diffusion-ui
}

stop_server() {
  docker-compose down
}

if [ "$CMD" == "start" ]; then
  start_server
elif [ "$CMD" == "stop" ]; then
  stop_server
elif [ "$CMD" == "restart" ]; then
  stop_server
  start_server
else
  echo "Unknown option: $1 (Expected start or stop)"
fi
```

Thanks!

**Comment by zaqxs123456** [comment]
> Thanks. Does running even this fail to produce any output: `docker-compose up stability-ai stable-diffusion-ui &` (with the &)

Save the below as server and run ./server don't work:

```
#!/bin/bash

docker-compose up stability-ai stable-diffusion-ui &
```

but run `docker-compose up stability-ai stable-diffusion-ui &` in shell will work. And I can't Ctrl+C to stop it.



> How about this? I've removed the 2>&1 and &. Does `./server restart` work now, and produce the output?
> 
> ```
> #!/bin/bash
> 
> CMD="$1"
> if [ -z "$1" ]; then
>   CMD="start"
> fi
> 
> start_server() {
>   docker-compose up -d stable-diffusion-old-port-redirect # old port 8000 server, show redirect notice
>   docker-compose up stability-ai stable-diffusion-ui
> }
> 
> stop_server() {
>   docker-compose down
> }
> 
> if [ "$CMD" == "start" ]; then
>   start_server
> elif [ "$CMD" == "stop" ]; then
>   stop_server
> elif [ "$CMD" == "restart" ]; then
>   stop_server
>   start_server
> else
>   echo "Unknown option: $1 (Expected start or stop)"
> fi
> ```
> 
> Thanks!

This work, output like just run `docker-compose up -d stable-diffusion-old-port-redirect` and `docker-compose up stability-ai stable-diffusion-ui` in shell.

```
Creating sd-old-port-redirect ... done
Creating sd ... done
Creating sd-ui ... done
Attaching to sd, sd-ui
sd-ui                                 | INFO:     Will watch for changes in these directories: ['/app']
sd-ui                                 | INFO:     Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
sd-ui                                 | INFO:     Started reloader process [1] using StatReload
sd-ui                                 | INFO:     Started server process [8]
sd-ui                                 | INFO:     Waiting for application startup.
sd-ui                                 | INFO:     Application startup complete.
sd                                    | INFO:     Started server process [1]
sd                                    | INFO:     Waiting for application startup.
sd                                    | Loading pipeline...
sd                                    | INFO:     Application startup complete.
sd                                    | INFO:     Uvicorn running on http://0.0.0.0:5000 (Press CTRL+C to quit)
sd-ui                                 | INFO:     172.21.0.1:52260 - "GET / HTTP/1.1" 200 OK
sd-ui                                 | INFO:     172.21.0.1:52260 - "GET /favicon.ico HTTP/1.1" 404 Not Found
sd                                    | INFO:     172.21.0.4:40258 - "GET / HTTP/1.1" 200 OK
sd-ui                                 | INFO:     172.21.0.1:52262 - "GET /ping HTTP/1.1" 200 OK
sd                                    | INFO:     172.21.0.4:40260 - "GET / HTTP/1.1" 200 OK
sd-ui                                 | INFO:     172.21.0.1:52262 - "GET /ping HTTP/1.1" 200 OK
sd                                    | INFO:     172.21.0.4:40262 - "GET / HTTP/1.1" 200 OK
sd-ui                                 | INFO:     172.21.0.1:52262 - "GET /ping HTTP/1.1" 200 OK
sd                                    | INFO:     172.21.0.4:40264 - "GET / HTTP/1.1" 200 OK
sd-ui                                 | INFO:     172.21.0.1:52262 - "GET /ping HTTP/1.1" 200 OK
```
I wonder why it work differently between our machine...

**Comment by cmdr2** [comment]
Yeah, that's really strange :) In any case, I've updated the code with the version that worked for you (by removing the & and pipe redirection).

Thanks a lot for your help, I really appreciate it! :)

Closing this issue, please reopen if this issue doesn't get resolved for you in the new code.
