### ISSUE TITLE
Windows installation bug - Fails if TMP/TEMP env vars contain a space.

### ISSUE THREAD

**Issue by Tomnewsom** [cmdr2/stable-diffusion-ui#140]
This is a known Conda issue. It can be caused by a username containing a space, or if the user has moved the Temp forlder manually to a path containing a space.

https://stackoverflow.com/questions/60789886/error-failed-to-create-temp-directory-c-users-user-appdata-local-temp-conda

I couldn't install SDUI properly until I'd manually set TMP and TEMP to a new path with no spaces. 
I have no idea if SDUI can workaround this issue. An error message to this effect would have been enough for me.

**Comment by cmdr2** [comment]
Thank you for letting us know! I'll add that to the troubleshooting guide, and see if the installer can auto-detect this and warn users at the start.

**Comment by cmdr2** [comment]
Hopefully fixed in https://github.com/cmdr2/stable-diffusion-ui/commit/1024da601dd1f12dd89020cd12608683710dc19b
