### ISSUE TITLE
Compatibility with NVIDIA Quadro?

### ISSUE THREAD

**Issue by antonietamg** [cmdr2/stable-diffusion-ui#143]
Hello, when I run SD in the UI, the console sends me the message "No compatible GPU found. Using the CPU, but this will be very slow!". 

I have a NVIDIA Quadro K5100M with 8gb. This GPU is actually not compatible, or the app is not recognizing my NVIDIA Quadro?

Please, help.

**Comment by kazax-inc** [comment]
noramaly Nvidia card are compatible, your driver are up to date? and you have the CUDA toolkit installed? this is a possible cause of non detection.
you can check with the commande `nvidia-smi` to see driver version, CUDA version

**Comment by JeLuF** [comment]
Sorry for the late response: The K5100M is a rather old card which only supports CUDA level 3.0. The libraries Stable Diffusion is using require at least CUDA level 3.5.
