### ISSUE TITLE
Use sd-v1-4-full-ema.ckpt instead of sd-v1-4.ckpt

### ISSUE THREAD

**Issue by plaidpants** [cmdr2/stable-diffusion-ui#149]
Allow swapping out of the weights file.

**Comment by tamal777** [comment]
> Allow swapping out of the weights file.

difference between these two?

**Comment by evilgenius79** [comment]
> > Allow swapping out of the weights file.
> 
> difference between these two?

The fill is a larger dataset. 7gb I believe

**Comment by cmdr2** [comment]
Hi, I understand it is larger, but does it improve the image quality? Can you please share examples where it has improved the image quality? Thanks.

**Comment by plaidpants** [comment]
From here "https://www.reddit.com/r/StableDiffusion/comments/x5am4v/ema_model_vs_non_ema_differences/"
EMA (exponential moving average) is meant as a checkpoint for resuming training while the normal, smaller one is for inference.

But I've also seen in several places that the larger one will provide better results but I've not seen a direct comparison, probably because even with the same seed the two models provide wildly different results so a direct comparison is not possible.

**Comment by plaidpants** [comment]
comparison for posterity, not much difference but then again they are not the same, need to find something that results in 3 arms or six fingers and see if the larger model helps in that case.
Prompt "Realistic portrait of a beautiful woman from United States, highly detailed, symmetrical, intricate, by Serge Marshennikov, greg rutkowski"
Seed 6
Steps 80
Guidance 7.5

using sd-v1-4-full-ema.ckpt
![Realistic_portrait_of_a_beautiful_woman_from_United_States__highly_detailed__symmetrical__intricate__Seed-6_Steps-80_Guidance-75 1](https://user-images.githubusercontent.com/8979271/189684030-6a8ffebe-d8e2-4faa-9846-9eb2436d4086.png) 

using sd-v1-4.ckpt
![Realistic_portrait_of_a_beautiful_woman_from_United_States__highly_detailed__symmetrical__intricate__Seed-6_Steps-80_Guidance-75](https://user-images.githubusercontent.com/8979271/189684099-b6fc359e-d83f-4608-965c-3b5535f27cb1.png)
