### ISSUE TITLE
Display result images in two columns

### ISSUE THREAD

**Issue by lensdigital** [cmdr2/stable-diffusion-ui#150]
Is there any way to modify HTML code to fit 512x512 result images in 2 columns instead of one? Would be a major life improvement for me, I have rather large monitor...

**Comment by cmdr2** [comment]
Sure, sounds like a good idea!

**Comment by cmdr2** [comment]
If you're familiar with HTML, you can edit ui/index.html to do this. I'd suggest fixing the left column (containing the prompt and input data) to a fixed width (instead of 50%, like it is now), so that the rest of the space can go for the images.

**Comment by lensdigital** [comment]
It's been a while since I've done HTML coding, and it seems that index.html is using CSS codes. It's not pretty but I got it working by changing preview-prompt div to "col-free":
` <div id="preview">
            <div id="preview-prompt" "col-free">`
And div editor to "col-10":
` <div id="editor" class="col-10">`

**Comment by cmdr2** [comment]
Hi, the space has been widened a lot for images.
