### ISSUE TITLE
Some UI improvements (squids!)

### ISSUE THREAD

**Issue by Fish0s** [cmdr2/stable-diffusion-ui#151]
Hi, I made some improvements to the UI. Do you like it?
![res](https://user-images.githubusercontent.com/112019029/189577938-8d5b36c8-fdc7-419a-82a9-f8dde8f8c70f.png)

Also, list of supported resolution up to 1024 is:
![res](https://user-images.githubusercontent.com/112019029/189578090-31b08b1a-35f3-448d-871e-d0d4a8622fc4.png)
Stable diffusion supports all resolutions that are multiplies of 64. While it technically accepts resolutions under 256 it doesn't actually support them, it just outputs noise.

Also#2:
Supported random seeds are 0 to 4294967295. Not just 0 to 30000 as Stable Diffusion UI's current defaults.

Squids:
&#129425; (unicode character #129425)
Squid favicon:
link rel="icon" href="data:image/webp;base64,UklGRpYEAABXRUJQVlA4TIkEAAAvH8AHEB451/8fsnO3j21sF3TX1sy1bc7/rGPbTjpWqazKyQtIZ9u27d3570v4Bf+t9qR0LmJvFXNuWrvaLvbEPkcOAICFJPkq9rY13aGylaxtI5mzbbuybfv662y9bdNtbdtKREN0QZ1kVETu7iMvG9lSAAggwMi2bdu2bTRm27Zte3vbtplsW8k3AcDeLpkwg5SJSK8Q9llE6qQhGVC/bRKXMLlnkgwwCEScjii1b3bJotVmk6gkUARFDgghRJ6NcAXskg2rySzGlDsTsiyISGxG/npzYRbjqFo82Uas4hGrhTQTRClHbJPgSndADdYJcq0TsFtLVP7VH7JO0I0VIKTlmOqvTSKi1NCp4uL1cEiBXTL8+NxxKKD3txsDHMJQRRK8ONhCAYdwaGjlnF5LdirbSRLC5DhEQ7dxQqRkLON0knAFnCjwZONsqAwcF6GEMw0eLPzQczaJ1vz4VHCAQQz8+IjRYNAJ1vzBiEsk7NZrxj9g+XcMPkXRXJxgkADAjlJLT1j7F6t+odUo+uxj9ltwuxd+wsBjNOvBpCdY/x8VKxEqU4PnydYx5Ay8wCxDYJ4z9Tn6HaLLMrpuoPsWDAwSWg7g8Zg7zHwNf4E1vBCpTf70AYFJSp0maPoeYM47OKbiwA9NtVrw4nQX8PwFTi/7hpsHDhw4u2PkNeTZOHDgwDY+UuU1nhfHjabd4NvPQ2BdYhaDdf9QrxU6PkQKgUVB/TbwWnemvwhTwELYKXcmmvWA5/nWU3Bj4FOTLvA832kRt+N0XgI2wuZ33o7ToXodyCeEwXmyEalCjXpwt2O1EJGO4yEsizwLEmPXTp2IxH8d0YRI8Z0grB5PmklUnO5tjAYafYAQzx4+fHjr466U/9JMhnggyZAiy4Iu5dbx48eP3/rO/RWnKwF1Bghd4YrnQ8txHJdwXxso8gqwnShkaUgcaCjZOgG7n3HfCCG6h3582CSCAoqAhoSdaeTYOKTQc6a5RgFQwD8K+PbUk+2vRayr6R37f1u+MshPBvn21ZWO9I49hmGuerJ9fXqHAn7REBTwzJXOWYVDCgXHVNUUMO9M0+nJdu+KO9MHCsgQEtGS2ramcOj/030G2RWvN1WyEEbh3qeyqcjj95ixTRLvwfLsiifbS1e6QQoYo4AeGjJQRkMyThTSAGAcwahQyC8nj99jMKf3SXrH/iENVRTLg4iULSJ5v/Hlqc3oPJ7I4XWQx++xVCDok2cUzs7AIBEAcKKQogAZZZtncVvSsnvunM/msZHOoftVMPjrKc00JiKBMHuESSGMorlOGoaxS+fQvcvqvnL2Yha3pQLY5/K5LPIHvt/l9r1bMzgNcbl9bxMa0pFm2iXNRLzeXYB4vd2SDMiyXPJgsRQSoZPBaYjO5XMV5Qt4fcnte0eyExIRlNP7NAOI1dIsU+xXAoOcRpgcADDIhjgdpYqAMGeALG6LupCIcFZ5/Z+CQiJEAECe7UuczvU4HR1QGqejGKu1LaFsCWmAfAEvkddsNkdYdLzeKLBEWAeDlIAaGcRBlkWPjSKHMsLcWQAA" type="image/webp"

Squids are animals who output ink!

Also#3: 
I changed it to output WebP files instead of PNG files as they are objectively superior. But I guess that's also a matter of personal preference.

If you like it and you'd like me to list the code changes I made to the HTML file just say the word :)

**Comment by cmdr2** [comment]
My reply is way too late, but thanks :) The UI has changed quite a bit since then
