### ISSUE TITLE
CUDA error

### ISSUE THREAD

**Issue by TashaMarkina** [cmdr2/stable-diffusion-ui#154]
When I try to generate an image, I get the following error. Of the possible causes of this error, I found only the option that my video card is outdated, is that so? Are there options to get around this moment, or should we wait for an update of the official SD version with possible support for older video cards?

Error: CUDA error: no kernel image is available for execution on the device CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by cmdr2** [comment]
Hi @TashaMarkina Yes it looks like the GPU isn't supported, although your nvidia-smi command shows CUDA version 11.4. You could try enabling the `Use CPU` setting under `Advanced Settings` in the Stable Diffusion UI, and it'll use your CPU instead of GPU. Unfortunately that's all I can think of, other than making sure your driver is up to date.

Thanks!

**Comment by TashaMarkina** [comment]
> Hi @TashaMarkina Yes it looks like the GPU isn't supported, although your nvidia-smi command shows CUDA version 11.4. You could try enabling the `Use CPU` setting under `Advanced Settings` in the Stable Diffusion UI, and it'll use your CPU instead of GPU. Unfortunately that's all I can think of, other than making sure your driver is up to date.
> 
> 
> 
> Thanks!

Thank you! I'll try to figure it out and look for options. It's a pity that retro cars are much more valued than retro graphics cards that still work great.

**Comment by Sivanot** [comment]
Hi, I'm getting the exact same error now when I try to start a batch of images. I was able to run it once after resolving a continuous error about a lack of memory, but now regardless of any options i choose, the error the original poster provided gets spat out immediately.

My GPU is a GTX 1650 SUPER, and I recently updated my drivers. So I don't think my problem is coming from an outdated gpu, and running it on cpu only still doesn't work anyway. Any suggestions?

**Comment by TashaMarkina** [comment]
@cmdr2 The GPU failed to start even after reinstalling and removing the Anaconda libraries. The CPU is working, I'll stay on it for now. The result in terms of picture quality is very pleasing! Thank you very much!!!
![a_photograph_of_an_astronaut_riding_a_horse_Seed-8597592_Steps-50_Guidance-7 5](https://user-images.githubusercontent.com/111082944/190451698-213c041e-7a71-4e6f-a482-22048d1e86bd.png)
![Beautiful_hyperrealistic_hobbit_house_by_the_lake__200764cc](https://user-images.githubusercontent.com/111082944/190451742-6e1eade7-99c5-4db2-b4fb-0b11c9944578.png)
