### ISSUE TITLE
ImportError: DLL load failed while importing _ctypes: Paramètre incorrect

### ISSUE THREAD

**Issue by DiegoRRR** [cmdr2/stable-diffusion-ui#158]
Hello

I have an issue trying to install, it says a file doesn't exist :

> C:\stable-diffusion-ui>installer\Scripts\activate.bat
> Traceback (most recent call last):
>   File "C:\stable-diffusion-ui\installer\Scripts\conda-script.py", line 12, in <
> module>
>     sys.exit(main())
>   File "C:\stable-diffusion-ui\installer\lib\site-packages\conda\cli\main.py", l
> ine 118, in main
>     from ..exceptions import conda_exception_handler
>   File "C:\stable-diffusion-ui\installer\lib\site-packages\conda\exceptions.py",
>  line 19, in <module>
>     from .models.channel import Channel
>   File "C:\stable-diffusion-ui\installer\lib\site-packages\conda\models\channel.
> py", line 13, in <module>
>     from ..base.context import context, Context
>   File "C:\stable-diffusion-ui\installer\lib\site-packages\conda\base\context.py
> ", line 54, in <module>
>     from ..common._os.linux import linux_get_libc_version
>   File "C:\stable-diffusion-ui\installer\lib\site-packages\conda\common\_os\__in
> it__.py", line 12, in <module>
>     from .windows import get_free_space_on_windows as get_free_space
>   File "C:\stable-diffusion-ui\installer\lib\site-packages\conda\common\_os\wind
> ows.py", line 14, in <module>
>     from ctypes import (POINTER, Structure, WinError, byref, c_ulong, c_char_p,
> c_int, c_ulonglong,
>   File "C:\stable-diffusion-ui\installer\lib\ctypes\__init__.py", line 8, in <mo
> dule>
>     from _ctypes import Union, Structure, Array
> ImportError: DLL load failed while importing _ctypes: Paramètre incorrect.
> git version 2.34.1.windows.1
> 
> (installer) C:\stable-diffusion-ui\installer\etc\conda\activate.d>cd C:\stable-d
> iffusion-ui\installer\..\scripts
> 
> (installer) C:\stable-diffusion-ui\scripts>on_env_start.bat
> 
> "Stable Diffusion UI - v2"
> 
> "Stable Diffusion UI's git repository was already installed. Updating from main.
> ."
> HEAD is now at 97e2a17 Merge pull request #155 from cmdr2/beta
> Already on 'main'
> Your branch is up to date with 'origin/main'.
> Already up to date.
> sd-ui-files\ui\index.html
> sd-ui-files\ui\modifiers.json
> sd-ui-files\ui\server.py
> sd-ui-files\ui\hotfix\9c24e6cd9f499d02c4f21a033736dabd365962dc80fe3aeb57a8f85ea4
> 5a20a3.26fead7ea4f0f843f6eb4055dfd25693f1a71f3c6871b184042d4b126244e142
> sd-ui-files\ui\media\ding.mp3
> sd-ui-files\ui\media\kofi.png
> sd-ui-files\ui\sd_internal\runtime.py
> sd-ui-files\ui\sd_internal\__init__.py
> 8 fichier(s) copié(s)
>         1 fichier(s) copié(s).
>         1 fichier(s) copié(s).
>         1 fichier(s) copié(s).
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "C:\stable-diffusion-ui\installer\lib\shutil.py", line 256, in copyfile
>     with open(dst, 'wb') as fdst:
> FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Gros2\\.cach
> e\\huggingface\\transformers\\9c24e6cd9f499d02c4f21a033736dabd365962dc80fe3aeb57
> a8f85ea45a20a3.26fead7ea4f0f843f6eb4055dfd25693f1a71f3c6871b184042d4b126244e142'
> 
> 
> "Downloading Stable Diffusion.."
> 
> Cloning into 'stable-diffusion'...
> remote: Enumerating objects: 513, done.
> remote: Counting objects: 100% (3/3), done.
> remote: Compressing objects: 100% (3/3), done.
> remote: Total 513 (delta 0), reused 2 (delta 0), pack-reused 510R
> Receiving objects: 100% (513/513), 42.50 MiB | 68.00 KiB/s, done.
> Resolving deltas: 100% (231/231), done.
> Note: switching to 'd154155d4c0b43e13ec1f00eb72b7ff9d522fcf9'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by switching back to a branch.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -c with the switch command. Example:
> 
>   git switch -c <new-branch-name>
> 
> Or undo this operation with:
> 
>   git switch -
> 
> Turn off this advice by setting config variable advice.detachedHead to false
> 
> HEAD is now at d154155 Merge pull request #122 from ryudrigo/main
> 
> "Downloading packages necessary for Stable Diffusion.."
> 
> "***** This will take some time (depending on the speed of the Internet connecti
> on) and may appear to be stuck, but please be patient ***** .."
> 
> Le fichier spécifié est introuvable.
> Traceback (most recent call last):
>   File "C:\stable-diffusion-ui\installer\Scripts\conda-script.py", line 12, in <
> module>
>     sys.exit(main())
>   File "C:\stable-diffusion-ui\installer\lib\site-packages\conda\cli\main.py", l
> ine 118, in main
>     from ..exceptions import conda_exception_handler
>   File "C:\stable-diffusion-ui\installer\lib\site-packages\conda\exceptions.py",
>  line 19, in <module>
>     from .models.channel import Channel
>   File "C:\stable-diffusion-ui\installer\lib\site-packages\conda\models\channel.
> py", line 13, in <module>
>     from ..base.context import context, Context
>   File "C:\stable-diffusion-ui\installer\lib\site-packages\conda\base\context.py
> ", line 54, in <module>
>     from ..common._os.linux import linux_get_libc_version
>   File "C:\stable-diffusion-ui\installer\lib\site-packages\conda\common\_os\__in
> it__.py", line 12, in <module>
>     from .windows import get_free_space_on_windows as get_free_space
>   File "C:\stable-diffusion-ui\installer\lib\site-packages\conda\common\_os\wind
> ows.py", line 14, in <module>
>     from ctypes import (POINTER, Structure, WinError, byref, c_ulong, c_char_p,
> c_int, c_ulonglong,
>   File "C:\stable-diffusion-ui\installer\lib\ctypes\__init__.py", line 8, in <mo
> dule>
>     from _ctypes import Union, Structure, Array
> ImportError: DLL load failed while importing _ctypes: Paramètre incorrect.
> 
> "Error installing the packages necessary for Stable Diffusion. Sorry about that,
>  please try to:"
> "  1. Run this installer again."
> "  2. If that doesn't fix it, please try the common troubleshooting steps at htt
> ps://github.com/cmdr2/stable-diffusion-ui/blob/main/Troubleshooting.md"
> "  3. If those steps don't help, please copy *all* the error messages in this wi
> ndow, and ask the community at https://discord.com/invite/u9yhsFmEkB"
> "  4. If that doesn't solve the problem, please file an issue at https://github.
> com/cmdr2/stable-diffusion-ui/issues"
> "Thanks!"
> 

I tried running the installer again, same error happens.
I can't access discord for some reason.

**Comment by HPPinata** [comment]
Does this error still occur? If not this should be closed
