### ISSUE TITLE
Feature Request: "Tidier" batching

### ISSUE THREAD

**Issue by jcpickens0215** [cmdr2/stable-diffusion-ui#159]
This only applies if image saving is enabled. 
Whenever I batch a generation, I feel like creating a .txt file for each image is completely unnecessary. I like to generate many batches when testing out prompts, and many times the clutter is overwhelming. 

Per each batch, the application should: 
- Output the entire batch including metadata to a new subfolder inside the session folder
- Create each image with its seed as its name
- Output only one metadata .txt file for the entire batch

This would make generating many batches much nicer.

Maybe this could be a setting that is off by default?

**Comment by wmooring** [comment]
Agreed, the main drawback of this UI currently is a lack of customization in how it saves images by default.  I'd like to be able to change the filename format and eliminate the usage of subfolders and the settings text files.

Ideally, the images would be able to save on generation with filenames containing all the data needed to reconstruct them later, in a more compact format than the "Download" button gives currently (there's no need for the full words "Guidance", "Seed", etc, when you need to save room in the filename length for the longer prompts to fit)

That's something I was able to set up for the AUTOMATIC1111 GUI, either by changing the checkboxes in the "Advanced" tab or editing some of the settings files, which I haven't been able to find equivalents for in this.

**Comment by hunterfrerich** [comment]
To add, it would be nice if images were saved with alphanumerically ordered filenames. It appears they append a random hash or something to the end right now, so if you try and view it in a photo viewer, they will always be out of order.
  
I always code my stuff to have the timestamp in it, placed so that sort-by-filename will put everything in order created:  
  
```
import time
timestamp = time.strftime('%Y%m%d-%H%M%S')
```

**Comment by cmdr2** [comment]
Hi, you can use the "File format" plugin for this: https://github.com/ogmaresca/easydiffusion-plugins

Thanks
