### ISSUE TITLE
Does xformers work on AMD?

### ISSUE THREAD

**Issue by itsdeadguy** [cmdr2/stable-diffusion-ui#1603]
Following the wiki instructions to install xformers hosed my easydiffusion install because it stopped recognizing my gpu (AMD rx 6700xt) and would default back to my cpu.

At first i panicked and nearly reinstalled the program from scratch, but then i went into the developer console and tracked down the package versions and ran a couple of websearches.
So in the end i replaced `python -m pip install --upgrade torch==2.0.1+cu118 torchvision==0.15.2+cu118 xformers==0.0.21 --extra-index-url https://download.pytorch.org/whl/cu118` with `python -m pip install --upgrade torch==2.0.1+rocm5.4.2 torchvision==0.15.2+rocm5.4.2 xformers==0.0.21 --extra-index-url https://download.pytorch.org/whl/rocm5.4.2` and i was able to use my gpu again.

As i fired up easydiffusion, i saw this message pop up: 
```
03:16:35.755 WARNING cuda:0 WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:                          _cpp_lib.py:137
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.0.1+rocm5.4.2)
    Python  3.8.17 (you have 3.8.5)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details

```

So, my question(s) would be:

- what am i missing to get xformers to work?
- where would i add the `XFORMERS_MORE_DETAILS=1` envvar to see if anything else pops up?

Thank you for work on this program, it seems to be my only option since A1111 won't run on my linux distro...

P.S: consider ammending the instructions in the wiki for amd users?

**Comment by Retardium** [comment]
https://github.com/facebookresearch/xformers/issues/807
https://github.com/facebookresearch/xformers/issues/513
