### ISSUE TITLE
Error in UI: ERR_INVALID_HTTP_RESPONSE

### ISSUE THREAD

**Issue by asimard1** [cmdr2/stable-diffusion-ui#163]
In CMD it says Uvicorn is running on port 9000, yet I keep getting this error on the actual site.

![image](https://user-images.githubusercontent.com/58919185/189717947-dbc28a80-d94d-46e2-97ea-18aeb637f25c.png)

**Comment by mrbusysky** [comment]
> In CMD it says Uvicorn is running on port 9000, yet I keep getting this error on the actual site.
> 
> ![image](https://user-images.githubusercontent.com/58919185/189717947-dbc28a80-d94d-46e2-97ea-18aeb637f25c.png)

Did you close the terminal?
If so you can't close this.

**Comment by mrbusysky** [comment]
Seems to be a UI issue.

**Comment by asimard1** [comment]
It seems that firewall might be blocking the page, but my firewall for Python (the one in the right folder, I checked) is set to "allow" so there shouldn't be any problems. No problem either in command line, everything is ok. Very weird.

**Comment by asimard1** [comment]
This was solved by restarting computer.
