### ISSUE TITLE
Using GFPGAN seems to break compatibility with some photo organizers

### ISSUE THREAD

**Issue by Jay4242** [cmdr2/stable-diffusion-ui#167]
**Describe the bug**
Images generated without GFPGAN seem to get their .txt files imported with the images just fine into organizers like Photoprism as a sidecar file.
When GFPGAN is used '_GFPGANv1.3' was added to the text files and that seemed to have confused Photoprism.
**To Reproduce**
1. Go to the webUI and generate images with GFPGAN activated.
2. Click on 'Make image'
3. Wait an eternity if you're on CPU.  Export to Photoprism's import directory.
4. Import images into Photoprism and the .txt file is left behind.

**Expected behavior**
The .txt files would be named the same as the photos and imported.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Version: v2.05

**Comment by Jay4242** [comment]
With the latest version, using RealESRGAN_x4plus adds 'RealESRGAN_x4plus' to the photo, not the text file.  It would be nice if it was the same for both the image and the text file.

**Comment by cmdr2** [comment]
This has been fixed, we add "_filtered" to the image name instead of the exact filtername
