### ISSUE TITLE
[Feature Request] Add/Remove/Edit Custom Modifiers and Categories

### ISSUE THREAD

**Issue by StateOfStaheli** [cmdr2/stable-diffusion-ui#168]
### **Description:**
Suggestion: User will be able to add, remove, or edit modifiers and categories to their liking from the treed modifier lists.

### **Acceptance Criteria:**
As a user, 

- I will be able to click an "Add" or "+" button next to an existing modifier or category , a text field will appear, and I will be able to input text.  Clicking outside of the text field will save the text as a modifier.

- I will be able to click a "Remove" or "-" button next to an existing modifier or category to delete it.  Upon clicking the button, a confirmation prompt will appear and ask if I really want to delete the modifier. Clicking 'Yes' will save the change.  Clicking 'No' will revert to an unmodified state.

- I will be able to edit an existing modifier or category by clicking an "Edit" button next to the modifier text.  A text field will appear with the existing modifier text and allow you to edit it.  Upon clicking the outside of the text field, a confirmation prompt will appear and ask if I really want to change the modifier. Clicking 'Yes' will save the change. Clicking 'No' will revert to an unmodified state.

**Comment by cmdr2** [comment]
Custom modifiers have been released, please try them out in the latest version. You can run the program and it'll autoupdate to the latest version.

It doesn't support custom categories yet, and that can be added if there is enough user-demand. Thanks!
