### ISSUE TITLE
huggingface\\transformers

### ISSUE THREAD

**Issue by ajaybenii** [cmdr2/stable-diffusion-ui#170]
No such file or directory: 'C:\\Users\\SqyUser\\.cache\\huggingface\\transformers\\9c24e6cd9f499d02c4f21a033736dabd365962dc80fe3aeb57a8f85ea45a20a3.26fead7ea4f0f843f6eb4055dfd25693f1a71f3c6871b184042d4b126244e142'

**Comment by cmdr2** [comment]
Hi @ajaybenii Is the UI failing to start up? Please ignore that message otherwise.

Closing for now, please re-open if your interface is not working, or if it is failing to generate images. Thanks
