### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by ajaybenii** [cmdr2/stable-diffusion-ui#171]
No such file or directory: 'C:\\Users\\SqyUser\\.cache\\huggingface\\transformers\\9c24e6cd9f499d02c4f21a033736dabd365962dc80fe3aeb57a8f85ea45a20a3.26fead7ea4f0f843f6eb4055dfd25693f1a71f3c6871b184042d4b126244e142'

**Comment by cmdr2** [comment]
This error can be ignored. Also, this error has been fixed :)
