### ISSUE TITLE
V3 Propossal

### ISSUE THREAD

**Issue by mrbusysky** [cmdr2/stable-diffusion-ui#176]
- [ ] #172 
- [ ] #173 
- [x] #174 
- [ ] #175
- [ ] #177  

Full design file: https://www.figma.com/file/6cQGK9w2NP45bQTfQS8PUd/Untitled?node-id=189%3A2020

Feel free to leave any comments on things you think might be a nice add.

**Comment by MrManny** [comment]
Neat! I'll add my Christmas wish list :)

Nice to have:
- [ ] UI, image prompt matrix (cf. [this](https://gigazine.net/gsc_news/en/20220909-automatic1111-stable-diffusion-webui-prompt-matrix/) for an example)
- [ ] UI, looping mode: ability to automatically start a new batch until cancelled

**Comment by JWNoctis** [comment]
Maybe an integration or reimplementation of [Cross Attention Control](https://github.com/bloc97/CrossAttentionControl), in a way that doesn't break the bank regarding VRAM usage, or require accounts and access tokens.

This should enable much more accurate tuning of generated images, than what's basically stylistic inspiration right now.

Might also provides some interesting UI design challenge, the way prompt editing works with this one.

**Comment by tails101** [comment]
maybe inpain outpaint and tiling features?

**Comment by AlphaRayReal** [comment]
> maybe inpaint outpaint and tiling features? upscale only maybe?

upscale and inpainting are already build in - when you activate the "Beta"-Checkbox and restart the CMD

**Comment by Uszaty** [comment]
I would appreciate 

- [ ] a gui to train the model with the given inputs

- [ ] Skip button - allows you to skip the currently generated picture, but does not stop the entire generation process for a given input

**Comment by AlphaRayReal** [comment]
1.  Will not be possible. Check the net for solution to train. Needs a very powerful card with 8 oder 10GB minimum
2. Already asked for such button four days ago :)

**Comment by tails101** [comment]
maybe a way to select the seeding method if it isn't already in latest beta?

**Comment by maikelsz** [comment]
there is a project for out painting: https://github.com/lkwq007/stablediffusion-infinity
maybe it can be integrated here, somehow.

PS: right now this project here is the only one I manage to install and run (although in CPU, my GPU es AMD, but I´m trying to make it run following a tutorial for that). also I think is the best in respect to user interface and usability. thanks
