### ISSUE TITLE
Experimental Mac version development (was "Installation issue on mac")

### ISSUE THREAD

**Issue by louisguthmannStarkWare** [cmdr2/stable-diffusion-ui#18]
After changing the port from 5000 to 1337, I get this error
ERROR: for stability-ai  Cannot start service stability-ai: could not select device driver "" with capabilities: [[gpu]]

I don't know how to solve it.
Mac Pro 2021, M1 Pro

**Comment by sidyakinian** [comment]
@louisguthmannStarkWare CUDA can't run on M1 which seems to be a requirement here.

**Comment by cmdr2** [comment]
Hi,

At present Mac isn't a supported platform, and it looks like the error is where Stable Diffusion is trying to look for an NVIDIA gpu.

I'm working on an update that might be able to support Mac as well, I will let you know shortly.

Thanks

**Comment by Karric** [comment]
@cmdr2 is there a way to be notified when macM1 is supported?

**Comment by cmdr2** [comment]
Hi @Karric I will update this thread

**Comment by Karric** [comment]
@cmdr2 perfect. Is that a near future thing or further out?

**Comment by cmdr2** [comment]
@Karric I really am keen to get to it, hopefully in a few days. I've bookmarked the fork mentioned here (https://replicate.com/blog/run-stable-diffusion-on-m1-mac) and was planning to use that as the baseline.

**Comment by cmdr2** [comment]
Ah cool, good to know it worked. I will look at it. :)

**Comment by lonnylippold** [comment]
https://github.com/divamgupta/diffusionbee-stable-diffusion-ui
easiest way to run stable diffusion on mac in an app but not as feature rich as cmdr2 version yet
I love cmdr2 version on windows and linux hopefully mac version will get some attention soon :)

**Comment by changeling** [comment]
Any word on this, @cmdr2? No pressure intended, just checking. :)

**Comment by cmdr2** [comment]
Mac M1/M2 is now supported
