### ISSUE TITLE
Error while loading model

### ISSUE THREAD

**Issue by Bragunetzki** [cmdr2/stable-diffusion-ui#180]
After the installer is finished, the web UI opens up in a new browser tab and begins loading the model. However, after some time the loading fails and the console produces an error (log attached). I've tried the troubleshooting steps presented, reinstalling webui, and trying to install on a different disc.

[log.txt](https://github.com/cmdr2/stable-diffusion-ui/files/9557840/log.txt)

**Comment by cmdr2** [comment]
Hi, if this is still an issue, please try deleting the file at `C:\Users\Drago/.cache\huggingface\transformers\c506559a5367a918bab46c39c79af91ab88846b49c8abd9d09e699ae067505c6.6365d436cc844f2f2b4885629b559d8ff0938ac484c01a6796538b2665de96c7'`

And re-run the program. Please feel free to ask on our Discord server (https://discord.com/invite/u9yhsFmEkB) if this continues to be a problem. Thanks
