### ISSUE TITLE
Various weird issues during the Windows installation

### ISSUE THREAD

**Issue by Overv** [cmdr2/stable-diffusion-ui#182]
The installation on my Windows 10 Home PC ended up being successful, but I ran into various weird things during the installation.

I extracted the zip to `C:/stable-diffusion-ui` as recommended:

![image](https://user-images.githubusercontent.com/285063/190013512-60cbb0d6-36ab-4588-ad61-cdbe39767ec8.png)

And ran the `Start Stable Diffusion UI.cmd` script. It seems the script incorrectly thought I had installed it in a different location and something weird happened while the warning was being printed:

![image](https://user-images.githubusercontent.com/285063/190014211-75aedadd-1568-4551-8eed-f9d4fada345a.png)

After that I got the following errors:

![image](https://user-images.githubusercontent.com/285063/190014290-8ddef4ec-ee79-44ee-a4b8-d773e9cc112b.png)

And a "System cannot find the file specified" error:

![image](https://user-images.githubusercontent.com/285063/190014411-4b90711a-49a6-4395-963d-1781f0e6f682.png)

**Comment by cmdr2** [comment]
Hi, please reopen if this is still an issue, or ask on Discord first (https://discord.com/invite/u9yhsFmEkB) since the community there is a lot bigger and active. Thanks
