### ISSUE TITLE
Stop or Interrupt current batch?

### ISSUE THREAD

**Issue by hunterfrerich** [cmdr2/stable-diffusion-ui#184]
Sometimes when you make a large batch, you want to stop the batch and use different settings. Also, sometimes I set the resolution too high and there is a CUDA error for every single image produced, but it does not stop the batch, it just keeps going.

I don't see a way to stop the batch on the web ui. 

I also tried to stop the server by closing the running cmd prompt and then restarting from the bat file, but it just resumes and kept making the errored batch of images again.  

It would be nice to be able to stop the current batch from both the web UI and from the server.  Is that already possible somehow?

**Comment by cmdr2** [comment]
Hi, this has been added today, please try it out and let me know if there are any problems! :) Thanks

https://github.com/cmdr2/stable-diffusion-ui/pull/185
