### ISSUE TITLE
Fatal: empty string is not a valid pathspec.

### ISSUE THREAD

**Issue by ZeroCool22** [cmdr2/stable-diffusion-ui#187]
![Screenshot_7](https://user-images.githubusercontent.com/13344308/190099715-85044a06-e033-4d86-849f-f98da7affc9c.jpg)

I can just ignore this error or..?

**Comment by cmdr2** [comment]
Please re-run the program if this is still an issue. Otherwise this error is harmless, and can be ignored :)
