### ISSUE TITLE
windows 10 defender blocks successfull install

### ISSUE THREAD

**Issue by cartazio** [cmdr2/stable-diffusion-ui#192]
**Describe the bug**
I copied the contents of the zip directly into a local directory , tried to run the install  command, and windows defender blocks it (but what to unblock is never persisted) and thence installation is aborted and fails partly
 
![the_install_bug](https://user-images.githubusercontent.com/4290/190249727-7a6c0dbb-3f32-476e-986a-8d9bd7c8909c.jpg)

**Comment by AlphaRayReal** [comment]
1. that is not a Win UI bug.  It's administration stuff.
2. if the windows defender causes the bug with installation - like you find out -> deactivate it while installation....?!
3. start CMD file with right click -> run as administrator.  Should help without temporary deactivating the defender
