### ISSUE TITLE
Only ever creates half the images per batch in some settings

### ISSUE THREAD

**Issue by Benzidrine** [cmdr2/stable-diffusion-ui#193]
**Describe the bug**
If I set to True the option: [Upscale the image to 4x Resolution...] and I set to False [Show only the corrected/upscaled image] Then it will display only half of the images. This is a new behavior it used to work correctly. 

**To Reproduce**
1. Set to True the option: [Upscale the image to 4x Resolution...]
2. Set to False [Show only the corrected/upscaled image]
3. Set [Generate in parallel] to 2 or 4

**Expected behavior**
It should display all the generated images, at the moment you only get half. 

**Screenshots**
![image](https://user-images.githubusercontent.com/14697373/190297852-bc21f25c-37d2-448a-a95e-b387f3aade91.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: Firefox
 - Version: 104.0.2

**Comment by cmdr2** [comment]
Hi, the UI has changed a lot since this report, and a lot of bugs have been fixed. Please feel to reopen or ask on Discord (https://discord.com/invite/u9yhsFmEkB) if this is still an issue. Thanks
