### ISSUE TITLE
Documentation missing Requiement Information for Microsoft Build Tools

### ISSUE THREAD

**Issue by PanadeEdu** [cmdr2/stable-diffusion-ui#196]
**Is your feature request related to a problem? Please describe.**
When installing the GUI on Windows, the CMD Might prompt to install Microsoft Build Tools. 
This is not mentioned except in an Error Message.

**Describe the solution you'd like**
Add Documentation for the Requirement, or at least a Troubleshooting Part in the documentation. 
Please contain the information which package to install exactly. 

**Additional context**
![ui2](https://user-images.githubusercontent.com/9149097/190460641-d530f379-1678-43c9-b19a-ef50e61c6468.png)
![ui1](https://user-images.githubusercontent.com/9149097/190460652-c302ca90-8c4d-450f-9fcc-7ffafb7a23ee.png)

**Comment by jwax33** [comment]
SD-UI does not normally require any MS Build Tools.  This error was introduced when an upstream package source updated.  This issue has been resolved with the latest available build here for download.
