### ISSUE TITLE
Queing Up prompts to reduce the amount of micromanagement

### ISSUE THREAD

**Issue by Adil3tr** [cmdr2/stable-diffusion-ui#199]
**Is your feature request related to a problem? Please describe.**

I am having trouble really learning SD and getting into generation because it feels really tedious to generate images sometimes. I will look through prompt ideas, and then put one in and keep looking. Then I find dozens more ideas but I can't try them because it's still generating , leading to me having notepad items or browser tabs in the hundreds and just giving up and wiping the slate clean. 

I also have the issue of different prompts working best with different variables but for the reasons above it's very tedious to sit and wait for a generation to finish so I can tweak the variables and try again. 

**Describe the solution you'd like**

I want to be able to make a long list of the prompt with the guidance/prompt strength values and the dimensions (and how many), and then walk away so the AI makes them all one after another. That way I can come back to a folder of finished images and see which ones I like to iterate on.

**Describe alternatives you've considered**

This could be a text file, in the UI text box, anything really, as long as I can queue up dozens of prompts.

**Comment by AlphaRayReal** [comment]
This is normal - i'm using notepad for ideas too.

- set low resolution for testing + low steps (35..40).  Generation on my 3060 Ti takes only about 20 seconds for 768x512. Thats not much time...
- additional parameters like resolution and the other are not the sense of the prompt or SD
- if you want test several different prompts, so try GRisk GUI.  Promps can be separated bei ENTER (new line). So you can put here 100..200 different prompts at time if you want

**Comment by jarble** [comment]
I was also looking for a feature like this. Does the UI have an option to enter a series of prompts, instead of just one prompt?

**Comment by MrManny** [comment]
This seems to be live now and can probably be closed (although I am not sure if it's just in the `beta` branch or already made its way to `main`).

**Comment by cmdr2** [comment]
I've just added support for prompt queue to the main UI, please try it out and let me know if there are any problems! Thanks

Closing this in favor of https://github.com/cmdr2/stable-diffusion-ui/issues/135
