### ISSUE TITLE
Docker-compose is deprecated

### ISSUE THREAD

**Issue by daddy32** [cmdr2/stable-diffusion-ui#20]
Minor issue with installation instructions: `docker-compose` is (supposedly) deprecated in favor of `docker compose` ("v2"). 

On my system (ubuntu 22.04), `docker-compose` installed from official ppa is of insufficient version 1.25.4, while `docker compose` returns v2.6.0. This means that `docker-compose up&` doesn't work, while `docker compose up&` does.

**Comment by ChrisAcrobat** [comment]
The `docker-compose up` command is working fine on my system (Windows 11).
(Except the unrelated problems talked about in #16. just for clarity)

**Comment by oc013** [comment]
@daddy32 yes I am still trying to mentally transition, thanks for the reminder. I just uninstalled docker-compose to reinforce that :)

It works on both docker-compose 1.28+ and docker compose

Instructions should encourage using `docker compose`

**Comment by cmdr2** [comment]
There is interest in adding docker to v2, so that people who have docker (and an interest in running this inside docker) can still do it. But this particular issue is no longer applicable, since v2 (the current version) doesn't use docker. Closing, thanks!
