### ISSUE TITLE
windows installation failed

### ISSUE THREAD

**Issue by www963257827** [cmdr2/stable-diffusion-ui#200]
![image](https://user-images.githubusercontent.com/49772139/190557542-47b6bad6-7fb2-4625-8cc8-51acb17ea686.png)
I am a Chinese development enthusiast. My system is win10. After the proxy is turned on, such a problem occurs during the installation process. Can you solve it? thank you very much.

**Comment by tyronx** [comment]
I had the same issue, running the installer again, as advised did fix this one issue.

**Comment by www963257827** [comment]
I've also re-run many times and still have this problem, it's really frustrating

**Comment by NaserElziadna** [comment]
i have a pip error 
this happed after i accedintly shotdown the computer 

i am using win 10
![image](https://user-images.githubusercontent.com/24838963/190900482-282fe001-7bf6-4fbe-aaf4-d91508b62eb2.png)

should i reinstall it , and try from the begging

**Comment by NaserElziadna** [comment]
Reinstall everything worked for me.

**Comment by www963257827** [comment]
Still not work sadlly

**Comment by NaserElziadna** [comment]
Sadly, I can work only with the CPU option, which is lame

**Comment by cmdr2** [comment]
The original issue here is caused by a VPN/Proxy blocking access to the download servers. Unfortunate there isn't much our project can do about network blockages on your PC, sorry.
