### ISSUE TITLE
BUG: Image download filename pulls current data from UI, not data used to create it

### ISSUE THREAD

**Issue by jwax33** [cmdr2/stable-diffusion-ui#203]
If you have any image results up on the UI and make any changes to the something like Guidance or Steps, if you later download the image before making new results the filename prompt will contain the new Guidance score and not the one originally used to generate the image.  This means tweaking your prompt while reviewing result images will mess up your original prompt info in the filenames.

**Comment by caranicas** [comment]
@jwax33 this will be solved in the upcoming release

**Comment by geuis** [comment]
@jwax33 Will the resolution include all of the details in the file name? As it is now, I've lost the prompts for a few images because the details aren't stored with the image files.

**Comment by cmdr2** [comment]
Hi, this has been fixed as of a few version ago. Thanks!
