### ISSUE TITLE
Model is reloaded when using init_image

### ISSUE THREAD

**Issue by jryebread** [cmdr2/stable-diffusion-ui#205]
When making api requests to img2img and then txt2img, or vica versa, the model is reloaded, which introduces a large amount of latency to requests.

`Loading model from checkpoint` 

I couldn't figure out the code enough to fix this but it is being reloaded here https://github.com/cmdr2/stable-diffusion-ui/blob/main/ui/sd_internal/runtime.py#L218

This would be an awesome fix that would save a lot of time overall :)

**Comment by AlphaRayReal** [comment]
1.  this coul'd be a normal procedure of SD.  I don't think die UI makes this
2.  whats the problem waiting the 2..3 seconds?

**Comment by cmdr2** [comment]
Fixed
