### ISSUE TITLE
Interface for other programming language

### ISSUE THREAD

**Issue by eeyrw** [cmdr2/stable-diffusion-ui#206]
**Is your feature request related to a problem? Please describe.**
The whole bundle and GUI is great but sometimes I need a programmable interface for creation.

**Describe the solution you'd like**
Reuse the current web api.
**Describe alternatives you've considered**
Add interface in future.

**Comment by AlphaRayReal** [comment]
This makes no sense, because Web UI uses the Stable Diffusion API  -  it's only communicating with SD. Like every available desktop + web ui  ;)     So you have use the SD API directly by yourself.

**Comment by eeyrw** [comment]
You are right. I took a day to walk through source code of SD and found out not so difficult to call SD directly due to simple API provided by SD.
