### ISSUE TITLE
Ability to define other ckpt files

### ISSUE THREAD

**Issue by MrAshRhodes** [cmdr2/stable-diffusion-ui#208]
**Is your feature request related to a problem? Please describe.**
There-s other models that have been created that can be used with SD. When Ive added a file and renamed it to sd-v1-4.ckpt the launch says its not correct and redownloads. Ive used this model with another SD and it worked ok.

**Describe the solution you'd like**
The ability to select the file on start up/launch

**Comment by AlphaRayReal** [comment]
@MrAshRhodes 
I don't think this will be possible.  And why would you replace the version?  By what?

**Comment by jwax33** [comment]
This feature is on the roadmap.  Currently you can use 3 different models with SD-UI.  The 4gb and 7gb models available from Compvis on Hugging Face and the Waifu model available here: https://huggingface.co/hakurei/waifu-diffusion

You will still need to rename the model you want to use to sd-v1-4.ckpt.

**Comment by MrManny** [comment]
A version of this landed in `beta`. Here's the announcement on Discord:

>  v2.195 of the beta now supports loading a custom model file (ending with .ckpt) - Just place your custom model file (the file with .ckpt at the end) in the stable-diffusion folder, and rename it to custom-model.ckpt. And restart the program.
>
> The logs (in the commandline window) should show Loading model from custom-model.ckpt after you restart the program.
>
> This is supported in the beta, so please enable 'Beta Channel' in the System Settings (top right corner of the UI), and restart the program, if you want to try this.

**Comment by cmdr2** [comment]
You can now use custom models by placing your `.ckpt` files inside `models\stable-diffusion` (in the project folder). Then refresh your browser tab, and you'll see your model under the "Models" setting (Image Settings).
