### ISSUE TITLE
Getting some errors starting up the container

### ISSUE THREAD

**Issue by bar10dr** [cmdr2/stable-diffusion-ui#21]
Creating network "stable-diffusion-ui_default" with the default driver
Creating sd                   ... error
Creating sd-old-port-redirect ...

ERROR: for sd  Cannot start service stability-ai: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error Creating sd-old-port-redirect ... done

ERROR: for stability-ai  Cannot start service stability-ai: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: signal: segmentation fault, stdout: , stderr:: unknown
ERROR: Encountered errors while bringing up the project.

**Comment by cmdr2** [comment]
Hi @bar10dr , this could be due to a number of reasons.

Can you please try the steps at https://github.com/cmdr2/stable-diffusion-ui/wiki/Troubleshooting#runtimeerror-found-no-nvidia-driver-on-your-system

Also, what output does running `nvidia-smi` in your command line give you? Does it respond immediately, or does it take more than a few seconds to print the output to nvidia-smi?

Thanks

**Comment by cmdr2** [comment]
Also, does `docker run hello-world` start successfully for you?

**Comment by cmdr2** [comment]
@bar10dr - Incase you're still interesting, you can now try the v2 version instead. It does not require docker or WSL anymore. You can just download one file, and it'll install everything behind-the-scenes and start.

You can download it from https://drive.google.com/file/d/1cEuOcb9OaldXcc2XzEMqEdvAr_w-KJ_p/view?usp=sharing and then double-click Start Stable Diffusion UI.cmd to install and run.

Please let me know if there are any problems after running it.

PS: There's a new Discord server for support and development discussions: https://discord.com/invite/u9yhsFmEkB . Please join in for faster discussion and feedback on v2. Thanks!
