### ISSUE TITLE
windows 7

### ISSUE THREAD

**Issue by worldnomady** [cmdr2/stable-diffusion-ui#211]
Incredibly! Are you kidding guys? It does not run on Windows 7, but only on 10 and 11.
I registered specifically to ask why you do this to people ?? WHY ??

**Comment by egorpezdir** [comment]
switch to linux 🗿

**Comment by jwax33** [comment]
Most likely one of the dependencies it requires does not have a Windows 7 version.  That said, Win7 has been EOLed for almost 3 years now.  It shouldn't surprise you that new applications don't support it.

**Comment by tails101** [comment]
what graphic card are you using? since it need a 10 series nvidia gpu at least?
and yea i think most ai api it is using are working on win10 only.

**Comment by worldnomady** [comment]
I can explain my position. I am a digital artist. I don't work in the  industry (creating games, movies, publishing etc.) so I still have an old PC: i7-2600k + 16GB DDR3 + Nvidia GeForce GTX570, no SSD. And Windows 7 SP2. An old version of Photoshop and other programs. I'm not trending. I am pure art.
And you will be surprised, but many artists are just like me. 
At the other extreme, Jurabaev, Bucci, Rutkowski and other commercially oriented personalities.
This is their choice. They pay a lot for it, even if they don't understand it. And generally they make the world a worse place. God is their judge, as people say.
(Though we can remember Stephane Richard (aka Wootha) who was one of them but made an extraordinary decision and quit)
For me, Stable Diffusion could become an opportunity to experiment for understanding.
The web version of Stable Diffusion contains many limitations.
I would like, like many other artists in my situation, to try the standalone version.
I understand that it would be slow on my computer. But I'm in no hurry. It is much more important for me to see and understand.
It is extremely unpleasant to see that people like me are left behind, overboard. 
I will not here state the reasons why I consider this an obvious mistake by people who write code (as I call them). This is not their first mistake, and certainly not the last.
Peace & prosperity 2 all.

**Comment by MrManny** [comment]
> It does not run on Windows 7

To be fair, the end-of-life for Windows 7 was January 14, 2020. So two and a half years ago. The cyber security engineer in me would like to warn you not to be running Windows 7 on a networked device.

**Comment by JeLuF** [comment]
I don't see why you can't upgrade your Computer to Windows 10.

Supporting ancient versions of Windows is a significant effort, and people who write code only have a limited amount of time available. They can either spend this time to develop features for the 99% running a modern version of their OS, or they can spend the same amount of time to make things work on an ancient version of Windows that you could have upgraded for FREE.

It's extremely unpleasant to see that people like you demand support, without being ready to do their part as well. 

Please understand that coding is art. And these artists want to work on exciting problems. Not on problems that have been already solved by Microsoft in newer versions of Windows.
