### ISSUE TITLE
CondaError: Downloaded bytes did not match Content-Length

### ISSUE THREAD

**Issue by Alejos7ven** [cmdr2/stable-diffusion-ui#212]
While downloading on windows 10 I'm getting the following error:

> CondaError: Downloaded bytes did not match Content-Length
  url: https://conda.anaconda.org/pytorch/win-64/pytorch-1.11.0-py3.8_cuda11.3_cudnn8_0.tar.bz2
  target_path: C:\stable-diffusion-ui\installer\pkgs\pytorch-1.11.0-py3.8_cuda11.3_cudnn8_0.tar.bz2
  Content-Length: 1318400419
  downloaded bytes: 607480247

> "Error installing the packages necessary for Stable Diffusion. Sorry about that, please try to:"
"  1. Run this installer again."
"  2. If that doesn't fix it, please try the common troubleshooting steps at https://github.com/cmdr2/stable-diffusion-ui/blob/main/Troubleshooting.md"
"  3. If those steps don't help, please copy *all* the error messages in this window, and ask the community at https://discord.com/invite/u9yhsFmEkB"
"  4. If that doesn't solve the problem, please file an issue at https://github.com/cmdr2/stable-diffusion-ui/issues"
"Thanks!"

**Comment by jwax33** [comment]
Your computer did not finish downloading the complete pytorch package referenced.  It appears to have only downloaded about half of it.  This can happen if your connection drops or flakes out during the download.  Try re-running the installer to see if it will re-download the package.  If that doesn't work, delete your install directory and try installing from scratch.
