### ISSUE TITLE
[ENHANCEMENT] OpenCL or Vulkan for cross-vendor GPU support

### ISSUE THREAD

**Issue by NintendoManiac64** [cmdr2/stable-diffusion-ui#213]
**Is your feature request related to a problem? Please describe.**
I use an AMD Ryzen 4800U which has integrated Radeon graphics - a configuration becoming more and more common (heck, all desktop Ryzen 7000 CPUs will now have integrated graphics).

This being AMD integrated graphics means that it's quite a bit more capable than the Intel counterparts, and it's only becoming more and more powerful with each subsequent generation (the 4800U uses Vega; the 6000 and desktop 7000 series uses RDNA2, and the 4nm "Phoenix" mobile APU will use RDNA3 with iGPU performance in the ballpark of a discrete RX 470 or so).  These APUs are also becoming more and more popular with handheld PC gaming devices, some of which even, like the Steam Deck, even have iGPUs that are considerably more powerful than their standard laptop counterparts (the Steam Deck's 8-CU RDNA2 iGPU is around twice as powerful as my Ryzen 4800U's Vega 7 iGPU).

Also, I use Linux which similarly has a disproportionate amount users with AMD and/or Intel graphics for a variety of reasons.

**Describe the solution you'd like**
Support for OpenCL or Vulkan so that it can run on not just Nvidia GPUs but also AMD and Intel.

**Describe alternatives you've considered**
ROCm would not be a solution since it is [officially unsupported on my 4800U](https://github.com/RadeonOpenCompute/ROCm/issues/1378).  CPU-only is obviously sub-ideal due to the lack of performance, especially on laptops with disproportionally-powerful integrated graphics compared to their desktop CPU counterparts (see also: Ryzen 6000 and the upcoming "Phoenix" Zen4 APUs compared to desktop Ryzen 7000 Zen4 CPUs).

**Additional context**
[rusticl (OpenCL 3.0 implementation with image support)](https://www.phoronix.com/news/Mesa-22.3-Rusticl-Merged) just got merged into mesa and should be included for mesa 22.3; currently it only works with Intel graphics but there is much interest in getting it working on AMD graphics (the primary developer has indicated that this may be the next task to work on).

Vulkan has also previously been used for cross-vendor GPGPU compute tasks such as with [RIFE's neural network-based framerate interpolation](https://github.com/nihui/rife-ncnn-vulkan).

**Comment by tails101** [comment]
good idea but i think only stable diffusion creator can do that.
not the ui creator.

**Comment by LostInTheShell** [comment]
Somebody had stable diffusion run on AMD 1 month ago, do not know further advancements/applicability

https://www.reddit.com/r/StableDiffusion/comments/ww436j/howto_stable_diffusion_on_an_amd_gpu/

**Comment by NintendoManiac64** [comment]
> Somebody had stable diffusion run on AMD 1 month ago, do not know further advancements/applicability
> 
> https://www.reddit.com/r/StableDiffusion/comments/ww436j/howto_stable_diffusion_on_an_amd_gpu/

That's using ROCm (which is mentioned immediately in the first step) - an option that I said is unsupported on integrated Ryzen graphics.

**Comment by AlphaJuliettOmega** [comment]
One more note, there is an official ROCm Docker image somewhere, it'd be neat if this UI could spin that up and attempt to run in that environment.

(it intercepts/interprets torch.device('cuda') calls as ROCm and attempts to render as requested supposedly)

**Comment by NintendoManiac64** [comment]
> I thought about Vulkan for this too, then it's OS independent (hopefully)

Just to be clear, OpenCL is OS-independent as well since that's what SVP uses on both Windows and Linux.

**Comment by cmdr2** [comment]
Sorry, but this isn't something in the scope of our project. Rather it's something that the Stable Diffusion project needs to look at. Our project is a UI and installer around the Stable Diffusion code. Sorry :)
