### ISSUE TITLE
'generator' object has no attribute 'json'

### ISSUE THREAD

**Issue by MrManny** [cmdr2/stable-diffusion-ui#215]
**Describe the bug**
The beta branch currently returns an error when status updates are opted out of if a custom client (curl, axios, ...) is used:
```json
{"status_code": 500, "detail": "'generator' object has no attribute 'json'", "headers": null}
```

This is probably related to the status updates of the back-end.
This problem cannot be reproduced in the main branch as of yet. It is exclusive to the beta branch for now.

**To Reproduce**
1. Run the back-end on the beta branch (v2.12 at the time of this writing)
2. Dispatch the request below to the POST /image back-end route with a regular HTTP client.
3. Receive the error above.

```
POST /image HTTP/1.1
Accept: application/json
Content-Type: application/json
User-Agent: axios/0.27.2
Content-Length: 700701
Host: localhost:9000
Connection: close

{
  "prompt": "Landscape, Cel Shading",
  "num_outputs": 1,
  "num_inference_steps": 75,
  "guidance_scale": 7.5,
  "width": 512,
  "height": 512,
  "turbo": true,
  "use_cpu": false,
  "use_full_precision": false,
  "show_only_filtered_image": false,
  "seed": 42,
  "init_image": "data:image/png;base64,I removed this, thank me later",
  "prompt_strength": 0.8
}
```

**Comment by cmdr2** [comment]
This has been fixed in the newest beta. Closing for now, please re-open if this is continuing to be an issue. Thanks!

**Comment by cmdr2** [comment]
https://github.com/cmdr2/stable-diffusion-ui/commit/b934a6b6e97838ff213dd2cebd70202eb058617f
