### ISSUE TITLE
Where can documentation for "Memory Management" and "PYTORCH_CUDA_ALLOC_CONF" be found?

### ISSUE THREAD

**Issue by DTJ200** [cmdr2/stable-diffusion-ui#216]
**Describe the bug**
I am currently getting this error message:

Error: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 4.00 GiB total capacity; 3.40 GiB already allocated; 0 bytes free; 3.45 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

How do I find Memory Management documentation and PYTORCH_CUDA_ALLOC_CONF

**Comment by hunterfrerich** [comment]
I've noticed a big improvement while using Turbo mode in v2.13(beta) with 4GB vRAM. I ran into intermittent problems using v2.12(beta) with a 4GB card, but those problems seem to have gone away. You can now "crash" it on purpose all you want, and it recovers just like 2.0~2.11 did.  
  
I see there have been updates to both vRAM and the stop button spaming issue in beta:  
https://github.com/cmdr2/stable-diffusion-ui/commits/beta
  
Thanks for fixing this! I think it might be the same problem as above? They didn't list a version.  
v2.13 is now the best option for me out of all the other local stable forks, at least for PLMS.

**Comment by cmdr2** [comment]
Hi, you don't need to edit those fields yourself. The CUDA out of memory is explained at https://github.com/cmdr2/stable-diffusion-ui/wiki/Troubleshooting#runtimeerror-cuda-out-of-memory
