### ISSUE TITLE
Have UI control multiple instances

### ISSUE THREAD

**Issue by evilantishad0w** [cmdr2/stable-diffusion-ui#221]
**Is your feature request related to a problem? Please describe.**
My family has three gaming machines, one of which that has dual GPUs, and I'd like to be able to split rendering different frames across all those GPUs.

**Describe the solution you'd like**
Rather than tying the UI to a single s-d instance I'd like if it could submit separate frame requests to different local instances, and gather the results locally.

**Describe alternatives you've considered**
Frame requests would be sent via simple ssh or ansible; not sure how best to copy the frames to the controller.
We've been trying to get separate s-d instances running on both of the GPUs but haven't had success; might need to try a VM and shunt the bottom GPU to it.

**Additional context**
It'd be fun to be able to have multiple people submit to the render farm simultaneously, though that'd complicate things; perhaps have a simple first-come, first-served, and some way of flagging if an instance is busy?

**Comment by cmdr2** [comment]
This has been released in the latest beta. Please try by enabling beta (in system settings, top-right corner of the UI).

After enabling the beta, please edit `scripts\config.json` and add "render_devices": ["GPU:0","GPU:1"] to enable both your GPUs.

Please feel free to ask on our discord server (https://discord.com/invite/u9yhsFmEkB) if you have any issues. Thanks!

**Comment by cmdr2** [comment]
Splitting across multiple computers isn't in the plan right now, but if you'd like to contribute code changes for this, I'd certainly be happy to accept them! :)
