### ISSUE TITLE
Error: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by Kenno9000** [cmdr2/stable-diffusion-ui#226]
re:  Stable Diffusion UI v2.15 (beta) 
I'm very much enjoying this app for SD at home!  
This error appeared today (I think after a change was issued earlier today).  Available data follows.
Ken.

Endorsing this:

"Use full precision (for GPU-only. warning: this will consume more VRAM)"
 
Returns this Error 

"Error: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!"

Follows the CMD Screen:  
C:\stable-diffusion-ui>installer\Scripts\activate.bat
conda 4.14.0
git version 2.34.1.windows.1

(installer) C:\stable-diffusion-ui\installer\etc\conda\activate.d>cd C:\stable-diffusion-ui\installer\..\scripts

(installer) C:\stable-diffusion-ui\scripts>on_env_start.bat

"Stable Diffusion UI - v2"

"Stable Diffusion UI's git repository was already installed. Updating from beta.."
HEAD is now at c675caf Fix a missing ddim_steps error for the DDIM sampler
Already on 'beta'
Your branch is up to date with 'origin/beta'.
Already up to date.
sd-ui-files\ui\index.html
sd-ui-files\ui\modifiers.json
sd-ui-files\ui\server.py
sd-ui-files\ui\hotfix\9c24e6cd9f499d02c4f21a033736dabd365962dc80fe3aeb57a8f85ea45a20a3.26fead7ea4f0f843f6eb4055dfd25693f1a71f3c6871b184042d4b126244e142
sd-ui-files\ui\media\ding.mp3
sd-ui-files\ui\media\drawingboard.min.css
sd-ui-files\ui\media\drawingboard.min.js
sd-ui-files\ui\media\favicon-16x16.png
sd-ui-files\ui\media\favicon-32x32.png
sd-ui-files\ui\media\jquery-3.6.1.min.js
sd-ui-files\ui\media\kofi.png
sd-ui-files\ui\sd_internal\ddim_callback.patch
sd-ui-files\ui\sd_internal\runtime.py
sd-ui-files\ui\sd_internal\__init__.py
14 File(s) copied
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.

Hotfixed broken JSON file from OpenAI
"Stable Diffusion's git repository was already installed. Updating.."
HEAD is now at f6cfebf Merge pull request #188 from jn-jairo/patch-1
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

HEAD is now at f6cfebf Merge pull request #188 from jn-jairo/patch-1
"Packages necessary for Stable Diffusion were already installed"
"Packages necessary for GFPGAN (Face Correction) were already installed"
"Packages necessary for ESRGAN (Resolution Upscaling) were already installed"
"Packages necessary for Stable Diffusion UI were already installed"
"Data files (weights) necessary for Stable Diffusion were already downloaded"
"Data files (weights) necessary for GFPGAN (Face Correction) were already downloaded"
"Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus were already downloaded"
"Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus_anime were already downloaded"
Re:  
"Stable Diffusion is ready!"

PYTHONPATH=C:\stable-diffusion-ui\stable-diffusion;C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages
Python 3.8.5
started in  C:\stable-diffusion-ui\stable-diffusion
INFO:     Started server process [13896]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
INFO:     127.0.0.1:53550 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:53552 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:53552 - "GET /output_dir HTTP/1.1" 200 OK
INFO:     127.0.0.1:53552 - "GET /app_config HTTP/1.1" 200 OK
GPU detected:  NVIDIA GeForce RTX 3060
Loading model from sd-v1-4.ckpt
Global Step: 470000
UNet: Running in eps-prediction mode
CondStage: Running in eps-prediction mode
FirstStage: Running in eps-prediction mode
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
loaded  sd-v1-4 to cuda precision autocast
INFO:     127.0.0.1:53550 - "GET /output_dir HTTP/1.1" 200 OK
INFO:     127.0.0.1:53550 - "GET /app_config HTTP/1.1" 200 OK
INFO:     127.0.0.1:53550 - "POST /image HTTP/1.1" 200 OK

    session_id: 1663904956707
    prompt: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
    seed: 8871840
    num_inference_steps: 50
    sampler: plms
    guidance_scale: 7.5
    w: 512
    h: 512
    precision: autocast
    save_to_disk_path: None
    turbo: True
    use_cpu: False
    use_full_precision: False
    use_face_correction: None
    use_upscale: None
    show_only_filtered_image: True

    stream_progress_updates: True
    stream_image_progress: False
    device cuda

    Using precision: autocast
Global seed set to 8871840
Sampling:   0%|                                                                                  | 0/1 [00:00<?, ?it/s]seeds used =  [8871840]                                                                           | 0/1 [00:00<?, ?it/s]
Data shape for PLMS sampling is [1, 4, 64, 64]
Running PLMS Sampling with 50 timesteps
PLMS Sampler: 100%|████████████████████████████████████████████████████████████████████| 50/50 [00:18<00:00,  2.70it/s]
saving images
memory_final =  0.544256███████████████████████████████████████████████████████████████| 50/50 [00:18<00:00,  3.72it/s]
data: 100%|██████████████████████████████████████████████████████████████████████████████| 1/1 [00:24<00:00, 24.88s/it]
Sampling: 100%|██████████████████████████████████████████████████████████████████████████| 1/1 [00:24<00:00, 24.88s/it]
Task completed
INFO:     127.0.0.1:53550 - "POST /image HTTP/1.1" 200 OK
loaded  GFPGANv1.3 to cuda precision autocast
loaded  RealESRGAN_x4plus to cuda precision autocast

    session_id: 1663904956707
    prompt: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
    seed: 3550586
    num_inference_steps: 50
    sampler: lms
    guidance_scale: 7.5
    w: 512
    h: 512
    precision: autocast
    save_to_disk_path: None
    turbo: True
    use_cpu: False
    use_full_precision: False
    use_face_correction: GFPGANv1.3
    use_upscale: RealESRGAN_x4plus
    show_only_filtered_image: True

    stream_progress_updates: True
    stream_image_progress: False
    device cuda

    Using precision: autocast
Global seed set to 3550586
Sampling:   0%|                                                                                  | 0/1 [00:00<?, ?it/s]seeds used =  [3550586]                                                                           | 0/1 [00:00<?, ?it/s]
Running LMS Sampling with 50 timesteps
100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:15<00:00,  3.24it/s]
saving images
Applying filters..█████████████████████████████████████████████████████████████████████| 50/50 [00:15<00:00,  3.18it/s]
memory_final =  672.437248
data: 100%|██████████████████████████████████████████████████████████████████████████████| 1/1 [00:20<00:00, 20.48s/it]
Sampling: 100%|██████████████████████████████████████████████████████████████████████████| 1/1 [00:20<00:00, 20.48s/it]
Task completed
INFO:     127.0.0.1:53550 - "POST /image HTTP/1.1" 200 OK
Loading model from sd-v1-4.ckpt
Global Step: 470000
UNet: Running in eps-prediction mode
CondStage: Running in eps-prediction mode
FirstStage: Running in eps-prediction mode
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
loaded  sd-v1-4 to cuda precision full

    session_id: 1663904956707
    prompt: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
    seed: 9707550
    num_inference_steps: 50
    sampler: lms
    guidance_scale: 7.5
    w: 512
    h: 512
    precision: autocast
    save_to_disk_path: None
    turbo: True
    use_cpu: False
    use_full_precision: True
    use_face_correction: None
    use_upscale: None
    show_only_filtered_image: True

    stream_progress_updates: True
    stream_image_progress: False
    device cuda

    Using precision: full
Global seed set to 9707550
Sampling:   0%|                                                                                  | 0/1 [00:00<?, ?it/s]seeds used =  [9707550]                                                                           | 0/1 [00:00<?, ?it/s]
Running LMS Sampling with 50 timesteps
  0%|                                                                                           | 0/50 [00:00<?, ?it/s]
data:   0%|                                                                                      | 0/1 [00:02<?, ?it/s]
Sampling:   0%|                                                                                  | 0/1 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "C:\stable-diffusion-ui\ui\sd_internal\runtime.py", line 190, in mk_img
    yield from do_mk_img(req)
  File "C:\stable-diffusion-ui\ui\sd_internal\runtime.py", line 407, in do_mk_img
    yield from x_samples
  File "C:\stable-diffusion-ui\ui\sd_internal\runtime.py", line 540, in _txt2img
    yield from samples_ddim
  File "C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\torch\autograd\grad_mode.py", line 43, in generator_context
    response = gen.send(None)
  File "C:\stable-diffusion-ui\stable-diffusion\optimizedSD\ddpm.py", line 566, in sample
    yield from samples
  File "C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\torch\autograd\grad_mode.py", line 43, in generator_context
    response = gen.send(None)
  File "C:\stable-diffusion-ui\stable-diffusion\optimizedSD\ddpm.py", line 1063, in lms_sampling
    eps = self.apply_model(x_in * c_in, cvd.sigma_to_t(t_in), cond_in)
  File "C:\stable-diffusion-ui\stable-diffusion\optimizedSD\samplers.py", line 44, in sigma_to_t
    dists = torch.abs(sigma - self.sigmas[:, None])
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by cmdr2** [comment]
Hi, thanks for the report! This has been fixed in the latest update to beta, can you please restart your program?

Closing this, please reopen if the problem continues. Thanks
