### ISSUE TITLE
Hide the 50% transparent image overlay OR ability to edit index.html?

### ISSUE THREAD

**Issue by hunterfrerich** [cmdr2/stable-diffusion-ui#230]
This program is really nice, but I have a small UI nitpick.  
  
This 50% transparent UI overlayed on the images is very distracting to me. This repo is one of the best UIs because it actually shows the images at 1:1 scale. Gradio UIs don't support 1:1 images yet natively (lol). It would be better if we could view the rendered images without any modification or overlay, e.g:

```
Seed: ###

Use as Input  
  
Download
```

I used to be able to edit the index.html to remove it (set transparency to 0.0). When I use beta, I think it is overwritten every time I start. I also don't think this 50% overlay is necessary, even for new users, because it's obvious once you hover over the image. Maybe it could be changed to visible only on hover (`mouseenter`)? Or hidden with a setting option? Or just explain how I can edit the html again?  
  
![firefox_JY7cDfFmbS](https://user-images.githubusercontent.com/15109673/191995362-9e07e6ff-d704-4d5a-b328-4036823fa0c2.png)

index.html (just Ctrl+F "0.5", replace with "0.0")

```
    .imgItemInfo {
        opacity: 0.5;
```
  
```
        imgItem.addEventListener('mouseleave', function() {
            imgItemInfo.style.opacity = 0.5
```

PS, thanks for adding support for all the samplers, this is awesome.

**Comment by cmdr2** [comment]
Hi, I've pushed this update to the main branch. The labels will now show up only when the mouse is over the image, otherwise will be hidden.

Thanks!
