### ISSUE TITLE
Full Precision, gives more quality or..?

### ISSUE THREAD

**Issue by ZeroCool22** [cmdr2/stable-diffusion-ui#235]
Curious about it...

**Comment by red0888** [comment]
Full precision is most likely used for fixing the green picture error on Nvidia 1600 GPU's.

**Comment by ZeroCool22** [comment]
> Full precision is most likely used for fixing the green picture error on Nvidia 1600 GPU's.

Oh, ok thx. So i guess it will not do anything with my 1080 TI.
