### ISSUE TITLE
(Enhancement) Use multiple images as input

### ISSUE THREAD

**Issue by dnorth87** [cmdr2/stable-diffusion-ui#241]
I'd like to use multiple pictures as input.

**Comment by cmdr2** [comment]
Hi, I'm sorry but this app is just a wrapper over Stable Diffusion. To my knowledge, Stable Diffusion doesn't support multiple images as input for a single output image.

Closing because that is out of scope of this project (a UI on top of Stable Diffusion). Thanks!
