### ISSUE TITLE
Allow the user to change maximum VRAM usage for faster image generation

### ISSUE THREAD

**Issue by TheMikirog** [cmdr2/stable-diffusion-ui#246]
I'm generating a lot of images in a short amount of time with stable diffusion UI by using my 8 GB VRAM GPU to its fullest. The issue is this implementation seems to use at most 1 GB of VRAM. I tried every setting, like Turbo Mode, full precision or trying to generate multiple images in parallel. No matter what, the amount of seconds per iteration is ridiculously high. One image that could be done in Diffusers in 4 minutes takes 20-30 here. If it's important, I always load an initial image with each generation and I'm always generating 512x512 images.

I want to see the Turbo Mode checkmark changed into a slider of some kind in the advanced settings that allows me to choose how much VRAM the app is allowed to use and it will keep using more of it until it reaches the limit set by the user unless the hardware does not have enough VRAM. This should allow the app to go faster with image generation and spend like 4 seconds per iteration rather than 50.

If my machine allows for stable diffusion to work faster, the app shouldn't be the bottleneck.

**Comment by cmdr2** [comment]
Hi, the windows reporting is often incorrect. Please using a software like GPU-Z (https://www.techpowerup.com/gpuz/) to profile the GPU usage correctly.

It does use the full capability, depending on what the image needs. If the image dimensions are small, then it won't use the full GPU RAM.

Closing, because this app doesn't do anything on top of what Stable Diffusion already does. The source code is open for review.  It uses the basujindal fork of Stable Diffusion under the hood: https://github.com/basujindal/stable-diffusion

Thanks!

**Comment by TheMikirog** [comment]
I profiled my Radeon RX580 GPU with GPU-Z while I ran two image generators that were both working on the same prompt (floating islands in the sky), resolution (512x512), steps (50), guidance scale (7.5) and seed (1). I don't think the initial findings from the windows task manager were all that wrong.

- Generation #1, [repo](https://github.com/harishanand95/diffusers/tree/dml), [ONNX DML.txt](https://github.com/cmdr2/stable-diffusion-ui/files/9658255/ONNX.DML.txt)
- Generation #2, [repo](https://github.com/cmdr2/stable-diffusion-ui#installation), [Stable Diffusion UI.txt](https://github.com/cmdr2/stable-diffusion-ui/files/9658265/Stable.Diffusion.UI.txt)

Notice how generator #2 is pretty much only exclusively using my CPU instead of the generator #1 that managed to make an image in just one minute in comparison to almost half an hour of generator #2.

The code definitely goes way over my head in both repos, but I'm guessing making generator #2 work fast on AMD is outside the scope of this repo or the original it's based on. That kinda sucks, because I was interested in doing some image2image generation using a graphical interface, but generator #1 does not offer that. It would be great to have the speed, but also have the friendly user interface for image2image on AMD, but I don't think a project like that exists yet. A man can only hope.

I'm leaving this to those who might have similar issues. If you have, be on the lookout for more stable diffusion implementations, since there's still more to be done!

**Comment by cmdr2** [comment]
Oh wait, this was for an AMD GPU? That makes sense, because AMD GPUs aren't supported yet.

I'm working on adding support for AMD, and am about to start beta testing AMD support with some users. Would be happy to send that to you as well.

Thanks for the detailed info!
