### ISSUE TITLE
An error appears if the base folder is renamed

### ISSUE THREAD

**Issue by maikelsz** [cmdr2/stable-diffusion-ui#249]
just renaming the base folder causes this error, and SD won't boot:

PYTHONPATH=f:\stable-diffusion-ui-a\stable-diffusion;f:\stable-diffusion-ui-a\stable-diffusion\env\Lib\site-packages
Python 3.8.5
started in  f:\stable-diffusion-ui-a\stable-diffusion
←[32mINFO←[0m:     Started server process [←[36m10844←[0m]
←[32mINFO←[0m:     Waiting for application startup.
←[32mINFO←[0m:     Application startup complete.
←[32mINFO←[0m:     Uvicorn running on ←[1mhttp://0.0.0.0:9000←[0m (Press CTRL+C to quit)
Traceback (most recent call last):
  File "f:\stable-diffusion-ui-a\ui\server.py", line 85, in ping
    from sd_internal import runtime
  File "f:\stable-diffusion-ui-a\ui\sd_internal\runtime.py", line 20, in <module>
    from gfpgan import GFPGANer
ImportError: cannot import name 'GFPGANer' from 'gfpgan' (unknown location)

INFO:     127.0.0.1:50715 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:50715 - "GET /modifiers.json?v=2 HTTP/1.1" 200 OK
INFO:     127.0.0.1:50715 - "GET /output_dir HTTP/1.1" 200 OK
INFO:     127.0.0.1:50715 - "GET /app_config HTTP/1.1" 200 OK

**Comment by cmdr2** [comment]
Hi, this is a bug with conda, and it's not a supported behavior. As such, there's not much our project can do, because the underlying package manager (conda) doesn't work if the folder is moved after installation. Thanks

**Comment by maikelsz** [comment]
> 

I think I found a way. 
In the Users folder, there is a .conda folder. there is a file inside named "environments.txt" that have a list of the enviroments.
I will test change the folder name and uptade this file, and see if it works
