### ISSUE TITLE
Error when using docker-compose up &

### ISSUE THREAD

**Issue by novatauri** [cmdr2/stable-diffusion-ui#25]
I keep getting this error and I can't fix it.
**_[it's an iMac 27" intel]_**

///////////////////////

(base) imac27 ~ % cd /Users/imac27/Desktop/stable-diffusion-ui-main 
(base) imac27 stable-diffusion-ui-main % docker-compose up &
[1] 22725
(base) imac27 stable-diffusion-ui-main % WARNING: Found orphan containers (sd-old-port-redirect) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Starting sd ... error

ERROR: for sd  Cannot start service stability-ai: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown

ERROR: for stability-ai  Cannot start service stability-ai: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown
ERROR: Encountered errors while bringing up the project.

[1]  + exit 1     docker-compose up
(base) imac27 stable-diffusion-ui-main % --remove-orphan
zsh: command not found: --remove-orphan
(base) imac27 stable-diffusion-ui-main % 

////////////////////////

**Comment by cmdr2** [comment]
Hi,

At present Mac isn't a supported platform, and it looks like the error is where Stable Diffusion is trying to look for an NVIDIA gpu.

I'm working on an update that might be able to support Mac as well, I will let you know shortly.

Thanks

**Comment by novatauri** [comment]
Oh I see. Thank you! I'll hold thumbs, maybe it will be successful :-)


> Hi,
> 
> At present Mac isn't a supported platform, and it looks like the error is where Stable Diffusion is trying to look for an NVIDIA gpu.
> 
> I'm working on an update that might be able to support Mac as well, I will let you know shortly.
> 
> Thanks

**Comment by ra0x3** [comment]
Here from Hackernews. Also went through the installation, got this error, found this issue. @cmdr2 Might be worth putting at the top of the README that OSX is not a supported platform at the moment :)

**Comment by cmdr2** [comment]
Thanks, done that :) Closing this in favor of https://github.com/cmdr2/stable-diffusion-ui/issues/18
