### ISSUE TITLE
Option to disable popup window

### ISSUE THREAD

**Issue by ChrisAcrobat** [cmdr2/stable-diffusion-ui#251]
**Is your feature request related to a problem? Please describe.**
I have multiple browser-accounts logged in, and I don't want the windows to be opened with the incorrect account.

**Describe the solution you'd like**
An option (for instance in an Json-config file) where I can disable the popup on load.

**Describe alternatives you've considered**
Could be a setting in the web page, but then a user system has to be built, so shared network users can't change the setting.

**Additional context**
_Nope._

**Comment by draeath** [comment]
I'd appreciate this as well. It appears that, however it currently launches a browser, it does it in a way that does not use my default firefox profile.

I'd rather it not do this, even going so far as to just give me the URL and let me wear my big-boy pants and open it myself.

**Comment by JeLuF** [comment]
Do you mean this setting?
![image](https://user-images.githubusercontent.com/5852422/209337352-74f6424e-c948-4833-b370-ee8dda0faed6.png)

**Comment by ChrisAcrobat** [comment]
Yes. That option did not exist when I submitted this issue. I have been using it for months. 🙂👍

**Comment by JeLuF** [comment]
Oh sorry, I think I sorted the issues by "least recent" instead of "most recent" :-)

**Comment by ChrisAcrobat** [comment]
No worries! I should have closed this issue anyway. 🙂
