### ISSUE TITLE
improve the images.

### ISSUE THREAD

**Issue by breidyfunes** [cmdr2/stable-diffusion-ui#259]
I think there is a lot to do to improve the images.

HAPPY DOG AND CAT
![A HAPPY DOG AND CAT](https://user-images.githubusercontent.com/48229287/192826305-3fe57d52-e16a-46bb-ac1b-7a95aba8de89.png)

a dog flying with wings
![a dog flying with wings](https://user-images.githubusercontent.com/48229287/192826398-a6c3b0f6-03b8-4f60-b787-d6ce81cad6e9.png)

**Comment by Saiboogu** [comment]
These are the result of the model plus your prompts, not the UI here.

**Comment by cmdr2** [comment]
Closing, since it depends on what prompts you use.
