### ISSUE TITLE
My four suggestions

### ISSUE THREAD

**Issue by MidnightStuff** [cmdr2/stable-diffusion-ui#261]
1. A sleep param between batches, so the GPU doesn't get overloaded throughout the night. For instance, a pause of 5 or 10 minutes (you specify the minutes) between batches, to give your GPU rest from overheating. 
2. Download files to prompt folders for them, then include a txt file with the prompt, etc. into it; the file name can still include the seed. Then you can keep track of the prompts. The file names don't hold the full prompt text. It's easy to get lost in what seed and prompt did what. (Or embed the info in the EXIF data of the image. The title property could be the prompt, the caption could be the seed and sampling, etc.)
3. A download indicator. It would be nice if there were a download button that changed to downloaded, or a circle, green button to indicate that you downloaded the image already, or something. It's so easy to forget which ones you downloaded in a batch. 
4. Another option would be to do a batch download. It would be nice to just download the whole batch to the download folder or check boxes to batch download the checked. 
Take care, :)

**Comment by Jay4242** [comment]
For number 2, it already adds things to a text file if you have the 'Automatically save to' System Setting set to a directory.
It includes the prompt, width/height, seed, steps, guidance scale, prompt strength, whether or not face correction/upscaling was used, the sampler, and the negative prompt.

My only complaints are that it doesn't always name the text file the same as the image, https://github.com/cmdr2/stable-diffusion-ui/issues/167.  Also, it doesn't seem to save the original filename when doing img2img, which would be nice to follow chains of img2img.

**Comment by MidnightStuff** [comment]
Thanks. I didn't see that setting. I'm going to try using it. :)

**Comment by cmdr2** [comment]
Thanks for the suggestions! Unfortunately, we don't have the resources to work on this right now. If you're interested in contributing code to this, we'd be happy to accept any code contributions.

I agree these suggestions would be helpful, and I'll keep them in mind. But cannot promise being able to work on them soon :) Thanks!
