### ISSUE TITLE
Either a confirmation when hitting "Stop all" and/or a button to re-queue the image

### ISSUE THREAD

**Issue by ImLunaHey** [cmdr2/stable-diffusion-ui#263]
**Is your feature request related to a problem? Please describe.**
I keep accidentality hitting the "Stop all" instead of the "Enqueue Next Image".

**Describe the solution you'd like**
Either a confirmation when hitting "Stop all" and/or a button to re-queue the image.

**Comment by Jay4242** [comment]
There's the 'Clear All' button.  Maybe the 'Stop All' button should go next to that?  Maybe to the right under the 'Settings' menu so it's even further away from 'Make Image' and closer to the other 'Stops'?
