### ISSUE TITLE
Save current settings

### ISSUE THREAD

**Issue by ImLunaHey** [cmdr2/stable-diffusion-ui#264]
**Is your feature request related to a problem? Please describe.**
A way to keep the **current** settings saved. I just lost the really good negative prompts I had working last night as I forgot to write them down before powering down my pc.

**Describe the solution you'd like**
Either using local storage or on the server I'd like to see the **current** image settings(negative prompt, etc) saved.

I know the settings for each image is saved but this would prevent page refreshes, etc. from resetting the image settings.

**Comment by Jay4242** [comment]
If you use the System Setting 'Automatically save to' to save them to a directory, then it already does this on my system.
With every image it creates a text file with the following format,

`Prompt would be here
Width: 512
Height: 512
Seed: 19198661
Steps: 50
Guidance Scale: 7.5
Prompt Strength: 0.8
Use Face Correction: None
Use Upscaling: None
Sampler: plms
Negative Prompt: Negative prompt would go here`

**Comment by bhickenbottom** [comment]
I lost a ton of work to this as well, almost a full day's worth. The page crashed, as pages with a lot of images tend to do, and I quickly realized that these images are not stored anywhere. Everything in the UI: prompt, settings, and all the images should be on disk and persist through refreshes. The current design is unnecessarily risky.

**Comment by cmdr2** [comment]
Hi, this feature has been enabled. Your UI settings will continue to exist across browser restarts (including negative prompts). You can customize which fields are autosaved using System Settings (top right corner)
