### ISSUE TITLE
Download button gets file name from current image settings

### ISSUE THREAD

**Issue by tkalayci71** [cmdr2/stable-diffusion-ui#266]
**Describe the bug**
Download button gets file name from current image settings which may have been modified, and also when creating multiple images does not use the increased seed. The info is correct in saved txt files, but not downloaded file names. 

Thank you.

**Additional context**
v2.195

Unrelated suggestion: consider "Daniel F Gerhartz" to artist list?

**Comment by MorganLOCode** [comment]
Also noticed this. Most noticeable when several jobs are enqueued: the filename chosen comes from the prompt of the job most recently completed.

**Comment by dxnxz** [comment]
+1 confirm

**Comment by MikkyD23** [comment]
File names seem correct now

**Comment by tkalayci71** [comment]
thank you  i will test it tonight. btw i am new to github, i dont know if im supposed to mark the issue done or something. thanks cmdr2 for this wonderful software
