### ISSUE TITLE
Option to switch models

### ISSUE THREAD

**Issue by egorpezdir** [cmdr2/stable-diffusion-ui#270]
**Is your feature request related to a problem? Please describe.**
People use different models based on different requests.

**Describe the solution you'd like**
A dropdown menu to choose different models and add your own.

**Comment by VincentJonesVR** [comment]
This please. I can no longer use WD in because it checks the SD-v1-4 file and redownloads if it doesn't match. This is an issue.

**Comment by egorpezdir** [comment]
> This please. I can no longer use WD in because it checks the SD-v1-4 file and redownloads if it doesn't match. This is an issue.
> 
> Scratch that, missed the new required rename. This dropdown would still be a great addition.

Well yea they added the `custom-model.ckpt` thing but it's still very useless, because you can only have one custom model and the name is overwritten, so you don't actually know which model you are using.

**Comment by SkyeBlep** [comment]
+1  Would love a setting for easy model switch :)

In the meanwhile, with the tip above about `custom-model.ckpt`, I realized I could just do a symbolic link, ie: `ln -s real-custom-model-name.ckpt custom-model.ckpt`  That helps keep it a bit more organized if you want to use multiple custom models.  Not sure if windows has a similar feature, but might be a strategy if you're on linux and need a temp workaround.

**Comment by cmdr2** [comment]
Hi,

The project now supports custom models. Please place your custom `.ckpt` model files inside the `stable-diffusion-ui/models/stable-diffusion` folder, and restart the program.

The UI will now automatically show your model files in a dropdown (under Image Settings), so you can select which model to use.

Thanks
