### ISSUE TITLE
Can't collapse generated image without text prompt input

### ISSUE THREAD

**Issue by Carson365** [cmdr2/stable-diffusion-ui#276]
**Describe the bug**
When you generate images with no prompt, you can't click on it to collapse/expand (because the prompt is what's supposed to be clickable)

**To Reproduce**
1. Generate using an initial image and no prompt
2. Try to minimize or maximize the prompt/images
3. See error

**Expected behavior**
You should be able to click on the grey setting header or there should be a default filler header to click on (like "[NO PROMPT]")

**Screenshot**
![image](https://user-images.githubusercontent.com/59584865/193510804-25a0b586-605c-411d-9f5f-9823a7f29e9a.png)

**Comment by cmdr2** [comment]
Hi, this has been fixed, thanks.
