### ISSUE TITLE
Error: local variable 'samples' referenced before assignment

### ISSUE THREAD

**Issue by jtippi** [cmdr2/stable-diffusion-ui#277]
Thats the error I get when I try to create an image with Stable Diffusion UI v2 (beta). Anybody knows how to fix it? :)
I'm using Windows 10.

**Comment by cmdr2** [comment]
Hi, we need a bit more information :) Can you please tell me the exact version you're using? If it's just v2, I think you're running a very old version. It's current v2.2. Please download the latest zip from https://github.com/cmdr2/stable-diffusion-ui#installation and it'll auto-update itself in the future.

Please re-open if the issue continues after updating to the latest version, or ask on the Discord chat https://discord.gg/adCyghfkSv. Thanks

**Comment by profispojka** [comment]
Hi. I am trying to connect to api with my own Front end app and I am getting exactly this error.
