### ISSUE TITLE
Skip model download

### ISSUE THREAD

**Issue by NaughtDZ** [cmdr2/stable-diffusion-ui#280]
I have stable-diffusion ckpt file.Download through your cmd is too slow(about 10kb/s).
Usually i need proxy on browser and make down load faster....
Is it possible to skip checking if the model is loaded and then I load the model manually?

**Comment by cmdr2** [comment]
You can just place the `sd-v1-4.ckpt` file manually inside your `stable-diffusion` folder, and the installer will skip checking for it if it's the known model file.
