### ISSUE TITLE
Load prompt list from text file

### ISSUE THREAD

**Issue by tkalayci71** [cmdr2/stable-diffusion-ui#281]
This would be a very helpful automation and easy to implement I think. Add a button that loads a text file which contains prompts on each line, and create tasks for each prompt with current image settings. Thank you.

**Comment by Polraudio** [comment]
I second this. It takes a while for my computer to render so it would be cool to just jot my ideas for a prompt in a text file, upload it to my server and wait till morning for them to all get done.

**Comment by towcar** [comment]
Should be implemented now - https://github.com/cmdr2/stable-diffusion-ui/pull/297
