### ISSUE TITLE
No option to toggle NSFW

### ISSUE THREAD

**Issue by SadKanehri** [cmdr2/stable-diffusion-ui#283]
I don't see an option to toggle NSFW, as mentioned in the features for V2

**To Reproduce**
1. Download the latest version from release.
2. Execute start.sh
3. No option to toggle NSFW (in browser) after stable-diffusion is ready

**Screenshots**

![Screenshot_12](https://user-images.githubusercontent.com/115102377/194127522-29e33a2a-2c3d-443d-adee-a3446ed4318c.png)
![Screenshot_14](https://user-images.githubusercontent.com/115102377/194128806-eff4dac6-c7c6-4855-b7a7-3e7c71ad9105.png)

**Desktop (please complete the following information):**
 - OS: Linux (garuda)
 

**Additional context**
I can't create scary looking monsters.
![download (1)](https://user-images.githubusercontent.com/115102377/194127702-d45df94f-82b5-4d4a-a4a3-f39d39bb6641.png)
![download (2)](https://user-images.githubusercontent.com/115102377/194127717-afee851f-c179-4ee9-abf8-768e8e34d92f.png)
![download](https://user-images.githubusercontent.com/115102377/194127722-5a4e2cc4-4f43-465c-a189-982aeac63357.png)

Prompts (in no particular order to the images above)
Prompt1: monster with hooks instead of limbs. (((Hunchback))), ((skinny)), rotting.
Prompt2: monster with hooks instead of limbs. (((Hunchback))), ((skinny)), rotting, ((scary)), ((ugly)), ((Bald)), (big eyes), (((big head)))
Prompt3: A monster that has hooks for wrists, no legs, one hook for lower body

Other info: Sampler: ddim, Inference Steps: 50, Guidance Scale: 7.5, Fix Faces: GFPGANv1.3

**Comment by Tsaukpaetra** [comment]
(Not a dev) As far as I understand, the NSFW filter isn't working, so currently it does not filter NSFW at all and the toggle has been disabled/hidden in the code.
Maybe your words aren't grotesque enough? I've certainly generated some skin-based images. 😈

**Comment by slymeasy** [comment]
>I can't create scary looking monsters.

You need something to indicate an image style.
