### ISSUE TITLE
Error installing antlr4-python3-runtime for Stable Diffusion

### ISSUE THREAD

**Issue by Zaithe** [cmdr2/stable-diffusion-ui#286]
get this bug when trying to install: 
```
The following specifications were found to be incompatible with a past
explicit spec that is not an explicit spec in this operation (pip):

  - antlr4-python3-runtime=4.8 -> python[version='>=3.6'] -> pip
```

When installing the application on Linux Mint i get the above error. Attaching a full log.
[log.txt](https://github.com/cmdr2/stable-diffusion-ui/files/9720762/log.txt)

**To Reproduce**
1. run the installation instructions
2. error pops up
3. `Error installing antlr4-python3-runtime for Stable Diffusion.`
4. installer closes

**Expected behavior**
it should successfully install

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version: 5.2.7

**Comment by cmdr2** [comment]
Hi, I responded to you in Discord: https://discord.com/channels/1014774730907209781/1014774732018683927/1027463785956524032
