### ISSUE TITLE
AMD GPU Support

### ISSUE THREAD

**Issue by dutch2005** [cmdr2/stable-diffusion-ui#288]
**Is your feature request related to a problem? Please describe.**
AMD GPU support is present in Diffusion Stable if the correct parts/modules are loaded.

**Describe the solution you'd like**
Detection of the script to load a different section e.g. AMD support if an AMD GPU is detected.

**Describe alternatives you've considered**
[https://pythoninoffice.com/run-stable-diffusion-amd-gpu-on-windows/]

[(https://www.youtube.com/watch?v=Lk2syPsVMQM&)]

**Comment by cmdr2** [comment]
Closing in favor of https://github.com/cmdr2/stable-diffusion-ui/issues/115
