### ISSUE TITLE
DefaultCPUAllocator: not enough memory

### ISSUE THREAD

**Issue by gaizka23d** [cmdr2/stable-diffusion-ui#289]
When i start "Start Stable Diffusion UI", in a few seconds, it says me this error.

DefaultCPUAllocator: not enough memory

Extend: RuntimeError: [enforce fail at C:\cb\pytorch_1000000000000\work\c10\core\impl\alloc_cpu.cpp:81] data. DefaultCPUAllocator: not enough memory: you tried to allocate 151781376 bytes.

Can you tell me how to fix it?

**Comment by cmdr2** [comment]
Hi, I'm sorry but that looks like your PC doesn't have enough RAM to run this program.

It allocates over 15 GB of RAM initially, before shrinking back to about 6-7 GB. So it seems to have run out of RAM while allocating a chunk of memory. You can check that in the system resource monitor while the program is starting up.

There isn't much else we can do to fix it, sorry :)

**Comment by FOSSenjoyer6** [comment]
Increasing virtual memory on windows fixed this issue for me.
