### ISSUE TITLE
unable to load custom model for release 2.16  after latest auto update 

### ISSUE THREAD

**Issue by Blizzardfur-Maxxx** [cmdr2/stable-diffusion-ui#296]
**Describe the bug**
unable to load custom model release 2.16  after the latest auto update 

**To Reproduce**
1. put the model in custom models are rename it to "custom model"
2. Run SDUI to see that it only loads the default 

**Expected behavior**
the custom model loads

 - OS: Windows 11
 - Browser: Chrome Latest
 - Version: 2.16

**Comment by cmdr2** [comment]
**How to use a custom model:**
1. Paste the model file ending with `.ckpt` into the `stable-diffusion-ui\models\stable-diffusion` folder. See the attached image for an example
2. Restart the program (close the black-and-white command prompt window, and re-run the `Start Stable Diffusion UI.cmd` file)
3. Your custom model will be available under "Image Settings" (see attached image for an example).
4. Select your custom model in the UI, and click "Make Image" to generate an image using your custom model
5. That's it
![image](https://user-images.githubusercontent.com/844287/194694072-db45ed30-3aa6-4f83-88d7-5efd78ca4913.png)
![image](https://user-images.githubusercontent.com/844287/194694076-064840ec-813b-4771-889d-7dd575685f4a.png)
