### ISSUE TITLE
Sticky Interface pannel 

### ISSUE THREAD

**Issue by carlosalosno** [cmdr2/stable-diffusion-ui#304]
As image form text generation is a lot of try and error, woudl be nice the interface part, the left part where introduce prompt and settigns will be sticky whiel the right parte, the part with the results can scroll down till the end of the resulting promps, that way can reuse the settings easier

**Comment by JeLuF** [comment]
That would be difficult to implement. The left hand side is too high for this to work. With inpainting enabled, it's one and a half screens high for me. When I open the image modifiers, it gets even higher.

**Comment by cmdr2** [comment]
I'd suggest the "Scrolling Panes" UI plugin for this - https://raw.githubusercontent.com/patriceac/Easy-Diffusion-Plugins/main/plugin-manager.plugin.js (listed in https://github.com/cmdr2/stable-diffusion-ui/wiki/UI-Plugins)
