### ISSUE TITLE
Indeterministic output with a-samplers

### ISSUE THREAD

**Issue by MrManny** [cmdr2/stable-diffusion-ui#311]
**Describe the bug**
This is more of an unexpected case of indeterminism than a bug. It would be nice to document this somewhere.

In my usual workflow, I tend to generate a bunch of images in batches. The ones I like, I re-run again one by one with upscaling and sometimes a slightly increased inference step count. However, even if I leave the step count the same, I notice that SD outputs different images with certain samplers even if the same seed is used.

This behavior has been tested and observed with the following samplers:
* dpm2_a
* euler_a

This behavior is **not** seen with the following samplers:
* ddim
* dpm2
* euler
* heun
* plms

Summary: it seems that only `…_a` samplers show this behavior.

**To Reproduce**
1. Select `euler_a` or `dpm2_a` as a sampler
2. Run any prompt with more than one image per batch and a fixed seed (or take note of the seeds used)
3. Re-run the same prompt with the same settings, but only one image with the corresponding seed observed/set in (2)
4. Visually compare the output. It will be different with `…_a` samplers.

**Expected behavior**
It is documented which samplers yield deterministic results and which don't.
Possibly (albeit optionally) use a deterministic sampler as a default (e.g., `euler`).

**Screenshots**
Batch of 2, 2 images total, seed 123, euler_a, 512x512:
![image](https://user-images.githubusercontent.com/683528/194739903-31ec5ace-113c-4b1c-8f7d-3337d27327ae.png)

Re-running the same seeds one by one yields:
Seed 123:
![image](https://user-images.githubusercontent.com/683528/194739940-ce75f03e-2780-40e6-b36e-eda926aead80.png)

Seed 124:
![image](https://user-images.githubusercontent.com/683528/194739947-5f617e11-1159-4297-9758-050f17fa8af4.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H1
 - Browser: Brave
 - Version: SD UI v2.22 (beta)

**Comment by tkalayci71** [comment]
There is indeed a bug. I made a batch of 3 images, 3 in parallel, then I could not reproduce them individually with exact same parameters, but then I was able o reproduce them using the same batch mode again.

**Comment by cmdr2** [comment]
Has now been documented in https://github.com/cmdr2/stable-diffusion-ui/wiki/How-to-Use
