### ISSUE TITLE
Generate two prompts concurrently with two GPUs

### ISSUE THREAD

**Issue by edocod1** [cmdr2/stable-diffusion-ui#315]
**Is your feature request related to a problem? Please describe.**
I have two video cards on my server, and i'd like to use them both to generate one prompt each concurrently. Currently, the implementation does not support this, and generating two prompts concurrently will use the first video card found for the first, and cpu for the second.

**Describe the solution you'd like**
Being able to define a port and GPU to use on startup (so i can run the interface twice), or specify the device to use in the web interface.

**Describe alternatives you've considered**
Creating two VMs and doing gpu passthrough on both.

**Additional context**
I am actually using this frontend with a Telegram bot to generate prompts, so even an additional parameter to be able to pass to /image/ would be enough for me. There is no need to have a drop-down to pick the gpu even though it looks like that'd be trivial to add after the option is added to the API.

**Comment by edocod1** [comment]
I have a current workaround.

You can force SD to use a specific GPU by specifying the environment variable `CUDA_VISIBLE_DEVICES` and `CUDA_DEVICE_ORDER`. In my case, i created a minimal script which would also run sd-ui on port 9001. This way i can use ./start.sh to upgrade the script, and ./start-custom.sh to start it with my custom settings.

```
source installer/etc/profile.d/conda.sh 
cd stable-diffusion/
conda activate ./env
SD_PATH=`pwd`
export CUDA_DEVICE_ORDER=PCI_BUS_ID
export CUDA_VISIBLE_DEVICES=1
export PYTHONPATH="$SD_PATH;$SD_PATH/env/lib/python3.8/site-packages"
echo "PYTHONPATH=$PYTHONPATH"
cd ..
export SD_UI_PATH=`pwd`/ui
cd stable-diffusion
python --version
uvicorn server:app --app-dir "$SD_UI_PATH" --port 9001 --host 0.0.0.0
```

The value of "CUDA_VISIBLE_DEVICES" needs to be the position of the desired video card as shown in lspci (by pci_bus_id), counted from 0. In my case, my 2060 was the first (aka 0) and my 1660 was second (aka 1).
```
$ lspci | grep -i VGA
01:00.0 VGA compatible controller: NVIDIA Corporation Device 2504 (rev a1)
02:00.0 VGA compatible controller: NVIDIA Corporation TU116 [GeForce GTX 1660 Ti] (rev a1)
```

**Comment by cmdr2** [comment]
Hi, this has been released on beta, please try it out by enabling "beta" in system settings (top right corner of the UI).
