### ISSUE TITLE
Doesnt auto install dependencies

### ISSUE THREAD

**Issue by AlizerUncaged** [cmdr2/stable-diffusion-ui#316]
**Describe the bug**
Running `Start Stable Diffusion UI.cmd` in a fresh installation of windows 11 crashes with the error:
```
Traceback (most recent call last):
  File "D:\Stuff\stable-diffusion-ui\installer\Scripts\conda-script.py", line 11, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'
git version 2.34.1.windows.1
```

**To Reproduce**
1. Install windows 11 and drivers
2. Download this repo
3. Run `Start Stable Diffusion UI.cmd`

**Expected behavior**
Auto installation of dependencies...? i kinda expected it to do it automatically, nevertheless i was able to install the dependencies and made it work myself

**Screenshots**
![image](https://user-images.githubusercontent.com/86959368/194855317-5a7347ac-a03e-4fd5-98f0-4b2e339338d9.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: microsoft edge
 - Version: 106.0.1370.37

**Additional context**
not sure if this is intentional

**Comment by gabfv** [comment]
Have you tried to download the [release ](https://github.com/cmdr2/stable-diffusion-ui/releases) instead of the repo?
![image](https://user-images.githubusercontent.com/24780542/196630233-3286bb2c-f5e5-41a9-b0b9-1bd5eff0c8cb.png)

**Comment by cmdr2** [comment]
Hi, please install using https://github.com/cmdr2/stable-diffusion-ui#installation

It won't work if you download the repo directly. Thanks
