### ISSUE TITLE
Outpainting doesn't work

### ISSUE THREAD

**Issue by sygi** [cmdr2/stable-diffusion-ui#32]
I tried to generate an up-scaled image by placing a right piece of a pre-generated image on the left, hoping the model will fill the rest.

I used this image:
![image](https://i.ibb.co/TmmVvf3/half-mountain.png).

I tried putting mask with black on the left, on the right, and without the mask at all, but all of the options only generate colorful images in the left side of the image, keeping the right side fully black, like this:

![image](https://i.ibb.co/Tr7skjf/7e6925a9-d781-4457-8223-19925c7adecb.png)

**Comment by cmdr2** [comment]
Hi, can you please try inverting the color in your mask? Black to white, and vice-versa? Thanks

**Comment by cmdr2** [comment]
@sygi Sorry for the delay, I'll look into this. Thanks for reporting.

**Comment by sygi** [comment]
Looking a bit more into the issue, I learned that the correct word for what I was doing is "outpainting". The mask itself works correctly. I'm not sure if stable diffusion itself supports outpaiting, though.

**Comment by cmdr2** [comment]
Hi @sygi Yeah I heard OpenAI supports outpainting, but I'm not sure Stable Diffusion does.

PS: There's also a Discord server now for support and development discussion related to this project: https://discord.com/invite/u9yhsFmEkB . Would love to see you there, thanks!

**Comment by MrManny** [comment]
I've seen outpainting exist here: https://github.com/AUTOMATIC1111/stable-diffusion-webui-feature-showcase

Although I hadn't had the time to check how it was done.

**Comment by cmdr2** [comment]
Outpainting is now supported via a UI plugin - https://github.com/cmdr2/stable-diffusion-ui/wiki/UI-Plugins#post-processing-plugins

Will look at adding outpainting to the core too
