### ISSUE TITLE
Concurrent access to UI breaks the application as it tries to render on CPU

### ISSUE THREAD

**Issue by exander77** [cmdr2/stable-diffusion-ui#321]
**Describe the bug**
Concurrent access to UI breaks the application as it tries to render on CPU.

Causes these:
>Error: CUDA error: invalid argument CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
>Error: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat2 in method wrapper_mm)

Any following ends with this:
>Error: Input type (torch.cuda.HalfTensor) and weight type (torch.HalfTensor) should be the same

**To Reproduce**
Access Web UI concurrently and try to generate images on both.

**Expected behavior**
Queue requests and process them as sson as GPU is released.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04, Ubuntu 22.04
 - Browser: Any
 - Version: Any

**Comment by JeLuF** [comment]
The newest version has queueing support and should no longer break if you access it concurrently. Please have a look whether it works for you.
