### ISSUE TITLE
Collecting package metadata (repodata.json): failed

### ISSUE THREAD

**Issue by 1mochidango** [cmdr2/stable-diffusion-ui#323]
See git-pull(1) for details.

    git pull <remote> <branch>

HEAD is now at f6cfebf Merge pull request #188 from jn-jairo/patch-1

"Downloading packages necessary for Stable Diffusion.."

"***** This will take some time (depending on the speed of the Internet connection) and may appear to be stuck, but please be patient ***** .."

Collecting package metadata (repodata.json): failed

CondaSSLError: Encountered an SSL error. Most likely a certificate verification issue.

Exception: HTTPSConnectionPool(host='repo.anaconda.com', port=443): Max retries exceeded with url: /pkgs/main/win-64/repodata.json (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

"Error installing the packages necessary for Stable Diffusion. Sorry about that, please try to:"
"  1. Run this installer again."
"  2. If that doesn't fix it, please try the common troubleshooting steps at https://github.com/cmdr2/stable-diffusion-ui/blob/main/Troubleshooting.md"
"  3. If those steps don't help, please copy *all* the error messages in this window, and ask the community at https://discord.com/invite/u9yhsFmEkB"
"  4. If that doesn't solve the problem, please file an issue at https://github.com/cmdr2/stable-diffusion-ui/issues"
"Thanks!"

It's what I got after downloading everything, still unable to run the program...notsure what is with it

**Comment by JeLuF** [comment]
Are you running any anti-malware or VPN or Proxy software? Something is preventing the installer from accessing the Internet.

**Comment by cmdr2** [comment]
Closing this, please feel free to ask on our Discord server if this continues to be an issue. https://discord.com/invite/u9yhsFmEkB

Thanks
