### ISSUE TITLE
Can't install on new Macbook Pro

### ISSUE THREAD

**Issue by TaciteOFF** [cmdr2/stable-diffusion-ui#324]
Hello,

I tried to install it on my new MacBook Pro and got this output :

`################################################################
Launching launch.py...
################################################################
Python 3.9.6 (default, Aug  5 2022, 15:21:02) 
[Clang 14.0.0 (clang-1400.0.29.102)]
Commit hash: bb7baf6b9cb6b4b9fa09b6f07ef997db32fe6e58
Installing torch and torchvision
Traceback (most recent call last):
  File "/Users/tom/Downloads/stable-diffusion-webui-mac-arm64/launch.py", line 168, in <module>
    prepare_enviroment()
  File "/Users/tom/Downloads/stable-diffusion-webui-mac-arm64/launch.py", line 118, in prepare_enviroment
    run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch")
  File "/Users/tom/Downloads/stable-diffusion-webui-mac-arm64/launch.py", line 32, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install torch.
Command: "/Users/tom/Downloads/stable-diffusion-webui-mac-arm64/venv/bin/python3" -m pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113
Error code: 1
stdout: Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu113

stderr: ERROR: Could not find a version that satisfies the requirement torch==1.12.1+cu113 (from versions: 1.9.0, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1)
ERROR: No matching distribution found for torch==1.12.1+cu113
WARNING: You are using pip version 21.2.4; however, version 22.2.2 is available.
You should consider upgrading via the '/Users/tom/Downloads/stable-diffusion-webui-mac-arm64/venv/bin/python3 -m pip install --upgrade pip' command.`

**Comment by JeLuF** [comment]
Your trying to install https://github.com/AUTOMATIC1111/stable-diffusion-webui
That is a different project.
