### ISSUE TITLE
Infinite loading

### ISSUE THREAD

**Issue by Maxecoy** [cmdr2/stable-diffusion-ui#325]
![6MWH~Q$GWE TT05QHX2NH{T](https://user-images.githubusercontent.com/89200001/195695136-25f5f125-961c-444f-81ed-e44cfae00432.png)

**Comment by Maxecoy** [comment]
Even longer infinite loop

**Comment by cmdr2** [comment]
Hi @Maxecoy We released a new installer recently, so can you please try with that? https://github.com/cmdr2/stable-diffusion-ui#installation

Please feel to reopen or ask on Discord (https://discord.com/invite/u9yhsFmEkB) if this is still an issue, thanks!
