### ISSUE TITLE
Install script fails to install dependencies, and runs wrong python version.

### ISSUE THREAD

**Issue by sloganking** [cmdr2/stable-diffusion-ui#326]
**Describe the bug**
After running `./start.sh`. The script fails with many errors. 
- At first it complains about `uvicorn` not being installed. which I manually installed with `sudo pacman -S uvicorn`
- Then upon each run it complains about all of these pip dependancies not being installed.
    `fastapi`
    `omegaconf`
    `einops`
    `pytorch_lightning`
    `ldm`
    So I installed them manually with `pip install`.
- Finally it throws a python error which I believe is due to the script trying to run `python2` on a python script written for `python3`
![](https://i.imgur.com/kWIZH9x.png)

I gave up after this point and have not fixed it further.

It just seems like this `./start.sh` utterly failed to install dependencies properly, and then to run things properly as well.

**To Reproduce**
1. run `./start.sh` on arch Linux.
2. Be met with all the errors listed above.

**Expected behavior**
running `./start.sh` should install everything correctly and 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox
- Version: Away from comp. unsure right now but will post later.

**Comment by JeLuF** [comment]
Can you please check whether the PYTHONPATH environment variable is set?
What is the value of the PATH variable?

The errors you see are caused by different versions of python interfering with each other.

**Comment by cmdr2** [comment]
Hi @sloganking You don't need to install any of those packages manually. This project uses python3, not 2.

If you're still interested in running this project, please try the new installer that we released a few days ago: https://github.com/cmdr2/stable-diffusion-ui#installation

Please feel free to reopen if this continues to be an issue.

Thanks!

**Comment by sloganking** [comment]
The new installer seems to work on my manjaro machine (different from what I made this issue with). I will try on the other machine in a little bit.

**Comment by cmdr2** [comment]
@sloganking Great, thanks! :)

**Comment by sloganking** [comment]
The new installer works on my other machine. So it's fine to keep this issue closed. Cheers!
