### ISSUE TITLE
"Show a live preview of the image" not consistent on MS Edge

### ISSUE THREAD

**Issue by ruby-yacht** [cmdr2/stable-diffusion-ui#327]
**Describe the bug**
I was able to generate a preview once, but it has stopped. I have tried restarting the scripts but this does not work. This may be a problem with the edge browser, it seems to be functioning with Firefox

**To Reproduce**
1. Launch Stable Diffustion
2. Click on 'Make Image'
3. Allow image to generate
4. If your default browser is Edge, you likely did not see the preview

**Expected behavior**
Expected to see intermediate steps but they were not visible.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10.0.109041  (Windows 10 Enterprise)
 - Browser:Microsoft Edge
 - Version:106.0.1370.42

**Additional context**
So the problem is solved for me in that I have changed my default browser, but if you have not tested with Edge, it is worth looking at this as it is not behaving as one might expect. I was able to get an image once or twice but then it fails altogether.

**Comment by MorganLOCode** [comment]
Curious to know if the console window reports regular GET requests while the image is generating.

**Comment by cmdr2** [comment]
Hi, I'm not sure why it's not working on Edge for you. I just tried it on Edge and it seems to be working.

Do you have any plugins on Edge that might cause this issue? And if you right-click on the page, and click "Inspect" and open the "Console" tab, do you see any errors after you click "Make Image"?

Additionally, a lot of bug fixes and improvements have been released in the past 2 weeks, so please try again. Re-running the program will auto-update you to the latest version.

Thanks, please feel to reopen or ask on our Discord server (https://discord.com/invite/u9yhsFmEkB) if this continues to be an issue.
