### ISSUE TITLE
I have a problem with the installation

### ISSUE THREAD

**Issue by www963257827** [cmdr2/stable-diffusion-ui#328]
- Ran pip subprocess with arguments:
['G:\\diffusion\\stable-diffusion-ui\\stable-diffusion\\env\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'G:\\diffusion\\stable-diffusion-ui\\stable-diffusion\\condaenv.4io6kdmt.requirements.txt']
Pip subprocess outpu\
Obtaining taming-transformers from git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers (from -r G:\diffusion\stable-diffusion-ui\stable-diffusion\condaenv.4io6kdmt.requirements.txt (line 17))

Pip subprocess error:
ERROR: Command errored out with exit status 128: git rev-parse HEAD Check the logs for full command output.

failed

CondaEnvException: Pip failed

"Error installing the packages necessary for Stable Diffusion. Sorry about that, please try to:"
"  1. Run this installer again."
"  2. If that doesn't fix it, please try the common troubleshooting steps at https://github.com/cmdr2/stable-diffusion-ui/blob/main/Troubleshooting.md"
"  3. If those steps don't help, please copy *all* the error messages in this window, and ask the community at https://discord.com/invite/u9yhsFmEkB"
"  4. If that doesn't solve the problem, please file an issue at https://github.com/cmdr2/stable-diffusion-ui/issues"
"Thanks!"

**Comment by www963257827** [comment]
Please help me.

**Comment by JeLuF** [comment]
Can you please provide the text prior to that "Ran pip subprocess with arguments:" line? A page or two perhaps?

**Comment by cmdr2** [comment]
Hi @www963257827 Please try again with the latest installer at https://github.com/cmdr2/stable-diffusion-ui#installation

And if it continues to show an error, please paste the full error message, otherwise it'll be hard for us to understand the reason for the error. Thanks!
