### ISSUE TITLE
Error:Unable to load weights from pytorch

### ISSUE THREAD

**Issue by shadinx2** [cmdr2/stable-diffusion-ui#331]
**Describe the bug**
No idea, stable difussion just doesn't work giving the error shown below.

**To Reproduce**
1. When attempting to run stable diffusion.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/36567585/195894921-b7e2096f-73a9-4756-b237-ce1c00842909.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**

**Comment by JeLuF** [comment]
Can you please open a cmd window and run these commands:
*  `dir c:\stable-diffusion-ui\stable-diffusion\sd-v1-4.ckpt`
    The file size should be 4'265'380'512
* If the file size is correct, please run:
    `certutil -hashfile c:\stable-diffusion-ui\stable-diffusion\sd-v1-4.ckpt`
    The command will take half a minute to complete. The result should be:
    `SHA1 hash of sd-v1-4.ckpt:`
    `210783247af4f65a3d23d026490cc37a670964dd`

If any of these figures doesn't match, please delete `c:\stable-diffusion-ui\stable-diffusion\sd-v1-4.ckpt` and restart the installer.

**Comment by cmdr2** [comment]
Hi @shadinx2 If this is still an issue, please try deleting the file that your error message displays (at the bottom), and run the program again. It'll try to download it again. Thanks!
