### ISSUE TITLE
sd-ui ERROR: Error loading ASGI app. Could not import module "main".

### ISSUE THREAD

**Issue by dborie** [cmdr2/stable-diffusion-ui#34]
Hello,

Everything seem up and working but sd-ui that got an error while starting. I dont have any more logs sadly
![image](https://user-images.githubusercontent.com/49395531/187710192-73895123-d98d-4877-baf0-0450d801d612.png)
The API under http://127.0.0.1:5000/ work find btw

I did not find other issue about this :/ Do you need more information?

Thanks a lot

**Comment by dborie** [comment]
My bad, the docker was not running from the WSL2 env, running it properly as described in the doc fixed my issue :)

**Comment by cmdr2** [comment]
Thanks @dborie :)
