### ISSUE TITLE
Support string interpolation and looping to run many different prompts

### ISSUE THREAD

**Issue by GregHilston** [cmdr2/stable-diffusion-ui#35]
Imagine having the ability to write

> A {village | city | town | space station} in the background of an lush forest

And then following prompts would be used:

> A village in the background of an lush forest
> A city in the background of an lush forest
> A town in the background of an lush forest
> A space station  in the background of an lush forest

This would be incredibly powerful, especially with multiple spots, like:

> > A {village | city | town | space station} in the background of an lush forest and a  {monster | kitten} attacking

**Comment by JeLuF** [comment]
This has been implemented, with small differences in the syntax:
`A {village,city,town,space station} in the background of an lush forest`
