### ISSUE TITLE
Generating a "prompt matrix" from a regex

### ISSUE THREAD

**Issue by jarble** [cmdr2/stable-diffusion-ui#358]
Is there an option to generate a series of prompts from a regular expression?

I'd want to use a regex like `/(painting|photo) of a (cowboy|astronaut) riding a (horse|donkey)/` as the "prompt matrix," using [genex.js](https://github.com/alixaxel/genex.js) to generate every prompt that matches the regex.

**Comment by JeLuF** [comment]
Try this:
`{painting,photo} of a {cowboy,astronaut} riding a {horse,donkey}`

https://github.com/cmdr2/stable-diffusion-ui/wiki/Writing-prompts#testing-variations-of-prompts
