### ISSUE TITLE
ModuleNotFoundError: No module named 'torch'

### ISSUE THREAD

**Issue by westquote** [cmdr2/stable-diffusion-ui#36]
I installed and ran v2 on Windows using Start Stable Diffusion UI.cmd, and encountered an error running the server:

```
started in  C:\Users\myuser\stable-diffusion-ui\stable-diffusion-ui\stable-diffusion
←[32mINFO←[0m:     Started server process [←[36m12336←[0m]
←[32mINFO←[0m:     Waiting for application startup.
←[32mINFO←[0m:     Application startup complete.
←[32mINFO←[0m:     Uvicorn running on ←[1mhttp://127.0.0.1:9000←[0m (Press CTRL+C to quit)
←[32mINFO←[0m:     127.0.0.1:51205 - "←[1mGET / HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m:     127.0.0.1:51205 - "←[1mGET /modifiers.json HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m:     127.0.0.1:51205 - "←[1mGET /output_dir HTTP/1.1←[0m" ←[32m200 OK←[0m
Traceback (most recent call last):
  File "C:\Users\myuser\stable-diffusion-ui\stable-diffusion-ui\stable-diffusion\..\ui\server.py", line 63, in ping
    from sd_internal import runtime
  File "C:\Users\myuser\stable-diffusion-ui\stable-diffusion-ui\stable-diffusion\..\ui\sd_internal\runtime.py", line 2, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

←[32mINFO←[0m:     127.0.0.1:51205 - "←[1mGET /ping HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m:     127.0.0.1:51205 - "←[1mGET /ping HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m:     127.0.0.1:51205 - "←[1mGET /ping HTTP/1.1←[0m" ←[32m200 OK←[0m
```

Is anyone else getting this?

**Comment by joaogeada** [comment]
I got the same problem (using the v2 installer)

**Comment by joaogeada** [comment]
This may be the cause: During installation, this error appears early on:


"***** This will take some time (depending on the speed of the Internet connection) and may appear to be stuck, but please be patient ***** .."

Collecting package metadata (repodata.json): done
Solving environment: done
Preparing transaction: done
Verifying transaction: failed

CondaVerificationError: The package for pytorch located at C:\Users\Joao\Downloads\stable-diffusion-ui\stable-diffusion-ui\installer\pkgs\pytorch-1.11.0-py3.8_cuda11.3_cudnn8_0
appears to be corrupted. The path 'Lib/site-packages/caffe2/python/serialized_test/data/operator_test/learning_rate_adaption_op_test.test_learning_rate_adaption_op_normalization.zip'
specified in the package manifest cannot be found.

**Comment by cmdr2** [comment]
Thanks @joaogeada That looks like the problem. Looking into why that's happening.

**Comment by joaogeada** [comment]
Seems the problem resolves itself if I move the installation directory into C:\ before running the "Start Stable Diffusion UI" batch script. Could it be a path length limitation?

**Comment by cmdr2** [comment]
@joaogeada Ah interesting, so it works if the path length is shorter? Is it running now (does the green light come in the ui)? Thanks

**Comment by joaogeada** [comment]
Yes, everything runs correctly as far as I can tell. Web browser connects, I get images when I click the "Make Image" button.
Thank you for making this easy installer!

**Comment by cmdr2** [comment]
Thanks a lot @joaogeada . I really appreciate your help in figuring out why it was failing for you. I've suggested that solution to other users on Discord (https://discord.com/invite/u9yhsFmEkB), and I'm investigating the path length limitation meanwhile.

**Comment by cmdr2** [comment]
@westquote If you have the project running, can you please open the `C:\Users\myuser\stable-diffusion-ui\stable-diffusion-ui\scripts\on_env_start.bat` file in `notepad` and change line 5 to `@set new_install=T` (instead of F)

And then save and double-click the `Start Stable Diffusion UI.cmd` file inside C:\Users\myuser\stable-diffusion-ui\stable-diffusion-ui).

Please paste the output here. It'll try to fix your installation, and show any errors while fixing. Thanks!

**Comment by cmdr2** [comment]
Hi @westquote a new version is available at https://drive.google.com/file/d/1MY5gzsQHV_KREbYs3gw33QL4gGIlQRqj/view?usp=sharing

This version will receive automatic updates in the future. Please let me know if there are any problems. Thanks

**Comment by cmdr2** [comment]
The latest version of the installer checks and fixes a lot of the common errors. Please try it, and feel free to reopen if this is still a problem. Thanks!
