### ISSUE TITLE
How to improve the drawing speed?

### ISSUE THREAD

**Issue by ck032** [cmdr2/stable-diffusion-ui#370]
The drawing speed is slower than Pipeline,which is about 3000ms for 512X512,50 steps.Is there any way to improve the speed？

**Comment by ck032** [comment]
sampling speed now : 2.06it/s

**Comment by cmdr2** [comment]
Hi, sorry but that's not within the scope of this project. We're just a UI and installer for Stable Diffusion. This would be a question better suited for https://github.com/basujindal/stable-diffusion . Thanks!
