### ISSUE TITLE
Images from "Make Similar Images" should show thumbnail of original image in the queue

### ISSUE THREAD

**Issue by Trithilon** [cmdr2/stable-diffusion-ui#374]
My workflow involves generating a ton of images overnight and then shortlisting some of them for generating variations upon.
However, when you queue up all those operations, its easy to forget which original image they are deriving from.

My solution is to simply do three things:
1. Add a Tag of "Upscale" "Iterate" and "Variations" to the operation
2. Show thumbnail of original image in the Queue
3. Clicking thumbnail should show parameters and details of original image

### Here is what it could look like:
Notice thumbnail indicated by the yellow arrow cursor.
![Variations_Mockup](https://user-images.githubusercontent.com/7444189/197341621-2ded7faa-4075-4b2f-899e-9fa1dfc7c9b7.png)

Clicking the thumbnail can open a menu detailing the parameters used to generate the original image.
![Variations_Mockup_Details](https://user-images.githubusercontent.com/7444189/197341627-fe33ac88-e0f3-4719-a7cb-ddc54ef5f60c.png)

At the very least, it would be useful to merely attach the original image as the first variation (and give it a different border) in that batch.

This applies to even other per image operations such as Upscale, 25 Iterations and Fixfaces.

**Comment by JeLuF** [comment]
This has been implemented a while ago already:
![image](https://user-images.githubusercontent.com/5852422/236528330-a6098432-31b7-4897-bc8b-38b0942e5c42.png)
