### ISSUE TITLE
Live Preview less noisy version if possible

### ISSUE THREAD

**Issue by tkalayci71** [cmdr2/stable-diffusion-ui#381]
I found that there are two types of live previews as seen in this video:
(Lesson 9A 2022 - Stable Diffusion deep dive)
https://youtu.be/0_BBRNYInx8?t=1315

v2.3.3 shows the one on the left, but the  one on the right seems more useful, and I think another popular repo shows that one. 
Code can be found at the notebook link in the description of the video.

Thanks..

**Comment by cmdr2** [comment]
Hi @tkalayci71 The kind of noise on the left is in the euler and heun samplers, and the kind of image on the right is the plms sampler. So if you want to see live previews of the "right side" type, please select the plms sampler while doing the live preview.

Thanks

**Comment by tkalayci71** [comment]
I tried plms and yes it works...  However I think it's possible with other samplers (there's no plms option with img2img). My understanding is: you start with 100% noise, model predicts the noise, but the sampler subtracts only some of the predicted noise, just enough to reach, say, 90% noise. This 90% noise is the noisy preview version. But if you had subtracted all the predicted noise, you would get the blurry preview version. I may be wrong and it's not a big deal, thanks anyway!
