### ISSUE TITLE
After installing I get an error and then the program closes

### ISSUE THREAD

**Issue by SniffHeinkel** [cmdr2/stable-diffusion-ui#382]
I just finished installing it but now when I run it it says "Error downloading the data files (weights) For Stable Diffusion. Press any key to continue". Then when I hit a key it says "Press any key to continue" two more times, then it closes. Using Windows 8.1 64 bit.

**Comment by jss367** [comment]
I don't know specifically what caused this but the requirements do say Windows 10 or 11, so if it's possible for you to upgrade that may fix the problem.

**Comment by JeLuF** [comment]
Can you please show more of the text prior to the error message?

**Comment by cmdr2** [comment]
@SniffHeinkel  If you're on Windows 8, you'll have to download and setup curl manually. You can install Git for Windows like this post suggests: https://stackoverflow.com/a/16216825

Thanks
