### ISSUE TITLE
Where is the NSFW toggle?

### ISSUE THREAD

**Issue by ChrisAcrobat** [cmdr2/stable-diffusion-ui#384]
The README references a NSFW toggle.
https://github.com/cmdr2/stable-diffusion-ui/blob/eb2f1cbc9efbdd13b1c2be4305c2d102fb1d2bcc/README.md?plain=1#L44
My kids would like to play with this, but I can not currently let them because you never know when the model decides to export something funny.
That the filter will not be perfect and that my kids will still be under supervision is besides the point.

**Comment by JeLuF** [comment]
That statement is outdated, there currently is no switch.

**Comment by ChrisAcrobat** [comment]
Too bad. Is it a plan to get it back or update the documentation?

**Comment by JeLuF** [comment]
The NSFW toggle has been re-implemented:
![image](https://user-images.githubusercontent.com/5852422/236527711-f68d2b11-e5ab-4db0-8e07-fa2ca2613174.png)
