### ISSUE TITLE
Always Get Error NSFW content detected on the console

### ISSUE THREAD

**Issue by poojitha** [cmdr2/stable-diffusion-ui#39]
Even if I run a prompt like a flower or water same error message is seen in the console

**Comment by cmdr2** [comment]
Hi @poojitha if you're using Windows, can you please try v2 (beta)? It doesn't filter for NSFW right now, and requires no dependencies (no docker or WSL required). Installation instructions: https://github.com/cmdr2/stable-diffusion-ui/tree/v2#installation

PS: There's a new Discord server for support and development discussions: https://discord.com/invite/u9yhsFmEkB . Please join in for faster discussion and feedback on v2. Thanks

**Comment by cmdr2** [comment]
Closing this, since v2 (released publicly) fixes this. Please give it a try if you get a chance at https://github.com/cmdr2/stable-diffusion-ui . Thanks!
