### ISSUE TITLE
Program starts perfectly once after install, fails on restarts

### ISSUE THREAD

**Issue by verkeorg** [cmdr2/stable-diffusion-ui#393]
Install works well and Stable Diffusion launches normally after the install. However, if I shut it down and try to boot it up again, it fails. It does bring up the UI, but says that "Stable Diffusion has stopped". I've tried to troubleshoot, but I'm afraid the command prompt messages are a bit above my understanding. I've attached the whole log to this message to better help possible troubleshooting.

Thanks for any tips and help in advance!

[loadlog.txt](https://github.com/cmdr2/stable-diffusion-ui/files/9868939/loadlog.txt)

**Comment by JeLuF** [comment]
Can you please open a `cmd` window and try these commands:
* `dir C:\Users\Verke\.cache\huggingface\transformers\c506559a5367a918bab46c39c79af91ab88846b49c8abd9d09e699ae067505c6.6365d436cc844f2f2b4885629b559d8ff0938ac484c01a6796538b2665de96c7`
    The file size in the result should be **1'710'671'599** bytes. If it is smaller than this, please delete all files in `C:\Users\Verke\.cache\huggingface\transformers\` and restart Stable Diffusion UI.
* `certutil -hashfile C:\Users\Verke\.cache\huggingface\transformers\c506559a5367a918bab46c39c79af91ab88846b49c8abd9d09e699ae067505c6.6365d436cc844f2f2b4885629b559d8ff0938ac484c01a6796538b2665de96c7`
    This command takes a moment to complete. The SHA1 should be: `717a26a684cf95496ef9e876c9fe86ce159168be`. If the command returns a different result, please delete all files n `C:\Users\Verke\.cache\huggingface\transformers\` and restart Stable Diffusion UI.

**Comment by verkeorg** [comment]
The file was indeed much smaller than that. This fixed the issue.

Many thanks, it lives again!
