### ISSUE TITLE
mouseover 'copy to clipboard icon' for prompt and settings

### ISSUE THREAD

**Issue by darren4321** [cmdr2/stable-diffusion-ui#409]
mouseover 'copy to clipboard icon' for prompt and settings, please.
Am having to use F12 and copying the complete prompt and settings from developer console (to paste to metadata fields in the downloaded image)

**Comment by JeLuF** [comment]
I think this is a feature not all of our users will be looking for, so I created a plugin providing this functionality.
https://github.com/cmdr2/stable-diffusion-ui/wiki/UI-Plugins#information-plugins

There is one plugin creating a JSON string, while the other one creates a table similar to the files in the autosave folder.
