### ISSUE TITLE
Variation of Image but in style of another image

### ISSUE THREAD

**Issue by Karric** [cmdr2/stable-diffusion-ui#41]
I have not yet loaded this tool (waiting for mac version). Based on the UI screenshot I see that it's possible to specify an artist as a style influence, but what about providing an image as the style influence?

Ideally this would be possible for both prompt mode and variation (of provided image) mode.

**Comment by cmdr2** [comment]
Hi, there is an "Initial Image" option (just below the prompt textbox), where you can provide it a guiding image, and specify how much weightage to give it between the image and the prompt. I think that's what you're describing?

**Comment by Karric** [comment]
@cmdr2 I'm not sure; I want this image to influence style/appearance but not content (vice versa would be useful too actually)

Example:
Clay Bust + Bunny ==> Clay Bunny
Bunny + Clay Bust ==> Bust covered in bunny fur with bunny eyes

The point is that some styles/artists don't have enough images to already be 'known' by these models via keyword.

**Comment by cmdr2** [comment]
Hi @Karric , I'm not sure if Stable Diffusion supports what you're describing. At the moment, this project is just a pretty UI and installer around the Stable Diffusion codebase, so it only supports giving an initial image and a prompt weight. And that affects the content.

Have you tried the prompts like your described? `Bust covered in bunny fur with bunny eyes`?

**Comment by Karric** [comment]
@cmdr2 I have not tried that (sounds unsetttling). Once I have this up and running I'll play around and see if I can accomplish my goal.

Thanks!

**Comment by cmdr2** [comment]
Closing this for now, since it's beyond the scope of this project. Please reopen if you feel this needs more attention. Thanks!
