### ISSUE TITLE
Error installing the packages necessary for Stable Diffusion

### ISSUE THREAD

**Issue by 245463540** [cmdr2/stable-diffusion-ui#415]
raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

failed

CondaEnvException: Pip failed

"Error installing the packages necessary for Stable Diffusion. Sorry about that, please try to:"

**Comment by JeLuF** [comment]
Are you using any security tools, web proxies, firewalls or VPNs, that might restrict the Internet access of the installer?

**Comment by 245463540** [comment]
> 引发读取超时错误（self._pool，无，“读取超时”。 pip._vendor：读取超时错误： HTTPS 连接池（主机 ='files.pythonhosted.org'，端口=443）： 读取超时。
> 
> 失败
> 
> CondaEnvException： Pip 失败
> 
> “安装稳定扩散所需的软件包时出错。很抱歉，请尝试：”



> 您是否使用任何可能限制安装程序访问互联网的安全工具，Web代理，防火墙或VPN？

I used a VPN

**Comment by 245463540** [comment]
Hotfixed broken JSON file from OpenAI

"Downloading Stable Diffusion.."

Cloning into 'stable-diffusion'...
fatal: unable to access 'https://github.com/basujindal/stable-diffusion.git/': Failed to connect to github.com port 443 after 21055 ms: Timed out
"Error downloading Stable Diffusion. Sorry about that, please try to:"

**Comment by JeLuF** [comment]
Something in your network setup prevents you from accessing some websites. This is an issue in the network setup and can't be fixed by Stable Diffusion UI easily.

**Comment by cmdr2** [comment]
@245463540 It looks like your VPN or Proxy is blocking access to github. At the moment, we can't do much about that, sorry. :/
