### ISSUE TITLE
fatal: unable to access 

### ISSUE THREAD

**Issue by 245463540** [cmdr2/stable-diffusion-ui#416]
Hotfixed broken JSON file from OpenAI

"Downloading Stable Diffusion.."

Cloning into 'stable-diffusion'...
fatal: unable to access 'https://github.com/basujindal/stable-diffusion.git/': OpenSSL SSL_read: Connection was reset, errno 10054
"Error downloading Stable Diffusion. Sorry about that, please try to:"

**Comment by cmdr2** [comment]
Hi @245463540 Like we commented on your other ticket https://github.com/cmdr2/stable-diffusion-ui/issues/415 , it looks like a VPN or Proxy is blocking access to github. There isn't much we can do about that, sorry
