### ISSUE TITLE
CondaValueError: prefix already exists

### ISSUE THREAD

**Issue by happynotwait** [cmdr2/stable-diffusion-ui#419]
CondaValueError: prefix already exists: H:\stable-diffusion-ui\stable-diffusion\env
![1](https://user-images.githubusercontent.com/116944774/198821464-6f3689a8-ffaa-4b10-b837-3ff924a959eb.png)
How can I solve it

**Comment by cmdr2** [comment]
Please delete the `H:\stable-diffusion-ui\stable-diffusion\env` folder and run the installer again.

**Comment by happynotwait** [comment]
thank you very much
