### ISSUE TITLE
File names don't have prompt in them. 

### ISSUE THREAD

**Issue by caranicas** [cmdr2/stable-diffusion-ui#43]
uuid file names make experimenting cumbersome. it means you need to do a lot of manual note taking and organization to keep things straight. Baking the prompt and relevant values into the file name would allow this organization to happen after the fact and a lot more rapidly. Leading to easier sharing and experimentation.

**Comment by cmdr2** [comment]
Thanks for the PR, closing this since I've merged your PR into the codebase!
