### ISSUE TITLE
Web UI input validation in numerical fields

### ISSUE THREAD

**Issue by JeLuF** [cmdr2/stable-diffusion-ui#441]
**Describe the bug**
Numerical input fields in the Web UI accept non-numerical input

**To Reproduce**
Type `hello` into the number of steps field in the image settings.

**Expected behavior**
Numerical fields should only allow numerical input.

**Screenshots**
![image](https://user-images.githubusercontent.com/5852422/199973412-a3ad4a4e-d902-49aa-be09-2c48ed3a9126.png)

**Comment by TLausZ** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number

the `type="number"` is missing in the input tag.

**Comment by cmdr2** [comment]
Fixed in 749c72e6a6734bb87458c547b9eaefb8413c4458 , released to beta. Will be released to main soon.

**Comment by cmdr2** [comment]
type='number' was rendering strangely on Chrome
