### ISSUE TITLE
Beta: "CUDA out of memory" on SDUI startup

### ISSUE THREAD

**Issue by JeLuF** [cmdr2/stable-diffusion-ui#443]
**Describe the bug**
https://discord.com/channels/1014774730907209781/1030335381754888262/1038162915280306178
When starting the SDUI Beta 4.3.9 on a 4 GB GTX 970, the system reported CUDA out of memory while loading `vae-ft-mse-840000-ema-pruned.vae.pt`

**Additional context**
Switching to `main` fixed the issue.

**Comment by JeLuF** [comment]
Another one: https://discord.com/channels/1014774730907209781/1021695193499582494/1038725621439795280
GTX1650

**Comment by cmdr2** [comment]
Fixed, the beta no longer loads the VAE by default on startup (unless the user chooses a VAE)
