### ISSUE TITLE
 "Error: The downloaded ESRGAN x4plus_anime model file was invalid! Bytes downloaded: 0"

### ISSUE THREAD

**Issue by lilizhong0817** [cmdr2/stable-diffusion-ui#447]
"Error: The downloaded ESRGAN x4plus_anime model file was invalid! Bytes downloaded: 0"

**Comment by JeLuF** [comment]
Did you try to restart the installer? It will try to download the ESRGAN model again. If this doesn't help, please copy the entire context of this error message into this ticket.

**Comment by lilizhong0817** [comment]
I have tried to restart the installer,but  it still shows error.

**Comment by cmdr2** [comment]
Hi, you can download that file manually from https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.2.4/RealESRGAN_x4plus_anime_6B.pth and place that inside the `stable-diffusion-ui/stable-diffusion` folder.
