### ISSUE TITLE
WARNING: No compatible GPU found. Using the CPU, but this will be very slow!

### ISSUE THREAD

**Issue by AIMI-SAYO** [cmdr2/stable-diffusion-ui#448]
**Describe the bug**
PyTorch detected my GPU (CUDA) but not SDUI

**To Reproduce**
just run the script

**Expected behavior**

**Screenshots**
![2022-11-06 13_52_38-NVIDIA GeForce Overlay](https://user-images.githubusercontent.com/46325569/200166614-97b76ff4-d21e-49e2-8fca-dcc2af130456.png)

**Desktop (please complete the following information):**
 - OS: Window 10 Pro (19044.2130)
 - Browser: OperaGX (91.0.4516.106)
 - Version: v2.3.5

**Comment by JeLuF** [comment]
https://discord.com/channels/1014774730907209781/1036099667517255701/1038825072779079751
Problem seems to be solved, right?

**Comment by AIMI-SAYO** [comment]
Re-Installing the whole script fixed the problem, but for someone who has limited internet bandwidth data it could be a problem since models cost +4GB, that's why I needed a fix other than re-installing, thank you
