### ISSUE TITLE
Site is not loading

### ISSUE THREAD

**Issue by omt66** [cmdr2/stable-diffusion-ui#449]
**Describe the bug**
Web site at localhost:9000 is not working in my Windows computer w/NVIDIA RTX 3060
It seems to be installing everything right without any issues but the site is not loading
The message on the browser is "This page isn't working localhost sent an invalid response ERR_INVALID_HTTP_RESPONSE"

**To Reproduce**
1. Go to 'C:\stable-diffusion-ui' directory
2. Double click on 'Start Stable Diffusion UI.cmd'
3. Let it run
4. It opens the browser window at http://localhost:9000/ and error message shows up

**Expected behavior**
Running application in the web page

**Screenshots**
![image](https://user-images.githubusercontent.com/155706/200203161-dbba11e4-3c6e-4995-babc-d0cf0e3d62ee.png)

![image](https://user-images.githubusercontent.com/155706/200203251-37a7d609-6c84-425d-9399-a5154eef9e01.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome

**Comment by cmdr2** [comment]
Hi, have you tried refreshing the browser page? Also, please ensure that you've gave the correct permissions to the firewall when it popped up.

It is working for most users, so we'd be happy to continue helping you out on the #support channel on Discord (https://discord.com/invite/u9yhsFmEkB). Please feel free to reopen if this continues being a problem. Thanks!
