### ISSUE TITLE
Access Denied 

### ISSUE THREAD

**Issue by skemur** [cmdr2/stable-diffusion-ui#450]
**Describe the bug**
Each time I try to run the installer for the first time i keep getting the access denied in cmd. i'll also get a notification from my pc that it cant run this app.

**To Reproduce**
1. download files, unzip, and started up 'Start Stable Diffusion UI'

**Expected behavior**
will have some text that is usual until i get access denied. have tried running and admin but still didn't work

**Screenshots**
attached

**Desktop (please complete the following information):**
Edition	Windows 10 Home
Version	21H1
Installed on	‎10/‎3/‎2021
OS build	19043.2130
Experience	Windows Feature Experience Pack 120.2212.4180.0
Device name	DESKTOP-758Q36S
Processor	Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz   2.59 GHz
Installed RAM	16.0 GB
Product ID	00325-96025-75360-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

![stable ui bug](https://user-images.githubusercontent.com/117614126/200213946-a79d22cc-2221-4fa4-beb5-ade2878d736e.PNG)

**Comment by EmmettMarkonikoff** [comment]
I have the same problem when trying to install. In addition to the identical issue seen above, I also get a flag from my Avast anti-virus saying the following:

<img width="450" alt="2022-11-07" src="https://user-images.githubusercontent.com/117558953/200269537-6e006855-a51c-4a58-9fc5-8c5c79f6c855.png">

**Comment by UntoldTactics** [comment]
Same as above, also had a flag on AVG antivirus. Also tried things listed in the issue regarding macromamba

**Comment by cmdr2** [comment]
For the original issue by @skemur - I've pushed a fix to the installer. Can you please try it again (after deleting the old installation)? https://github.com/cmdr2/stable-diffusion-ui/releases/download/v2.3.5/stable-diffusion-ui-windows.zip

The error for @UntoldTactics and @EmmettMarkonikoff are different from the original post. These two are involving the antivirus incorrectly flagging this file. We don't set the file as read-only, it was probably done by the anti-virus.

Please feel free to reopen if this issue continues, thanks!
