### ISSUE TITLE
CUDA error: no kernel image is available for execution on the device CUDA 

### ISSUE THREAD

**Issue by JMcPeak3373** [cmdr2/stable-diffusion-ui#456]
CUDA error: no kernel image is available for execution on the device CUDA 
Ran STABLE DIFFUSION with only base settings and I encountered this error, "Error: CUDA error: no kernel image is available for execution on the device CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1."

**To Reproduce**
Installed STABLE DIFFUSION and it ran just fine. shut it down then restarted it and even with only the base settings (nothing extra checked) the software failed with this error

**Expected behavior**
should have generated an image of some type

**Screenshots**

**Desktop (please complete the following information):**
 - OS: LINUX MINT 20.3 UNA, UBUNTU 20.4 FOCAL
 - Browser: FIREFOX 
 - Version: 106.0.4 (64-bit)

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by cmdr2** [comment]
Hi @JMcPeak3373 Please try the steps in the troubleshooting guide for this error: https://github.com/cmdr2/stable-diffusion-ui/wiki/Troubleshooting#runtimeerror-cuda-out-of-memory . Thanks!

**Comment by MrStirner** [comment]
D:\Git\cmd\git.exe
git version 2.38.1.windows.1
D:\github\stable-diffusion-ui\installer_files\env\Library\bin\conda.bat
D:\github\stable-diffusion-ui\installer_files\env\Scripts\conda.exe
conda 22.9.0

"Stable Diffusion UI - v2"

"Stable Diffusion UI's git repository was already installed. Updating from beta.."
HEAD is now at 0027622 Make on_sd_start.sh executable
Switched to a new branch 'beta'
branch 'beta' set up to track 'origin/beta'.
Already up to date.
463 File copiati
        1 file copiati.
        1 file copiati.
        1 file copiati.
        1 file copiati.
        1 file copiati.
        1 file copiati.
Sottodirectory o file tmp già esistente.

Hotfixed broken JSON file from OpenAI
"Stable Diffusion's git repository was already installed. Updating.."
HEAD is now at 7f32368 Use a specific version of opencv-python
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

HEAD is now at 7f32368 Use a specific version of opencv-python
"Packages necessary for Stable Diffusion were already installed"
"Packages necessary for GFPGAN (Face Correction) were already installed"
"Packages necessary for ESRGAN (Resolution Upscaling) were already installed"
"Packages necessary for Stable Diffusion UI were already installed"
"Data files (weights) necessary for Stable Diffusion were already downloaded. Using the HuggingFace 4 GB Model."
"Data files (weights) necessary for GFPGAN (Face Correction) were already downloaded"
"Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus were already downloaded"
"Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus_anime were already downloaded"
"Data files (weights) necessary for the default VAE (sd-vae-ft-mse-original) were already downloaded"

"Stable Diffusion is ready!"

PYTHONPATH=D:\github\stable-diffusion-ui\stable-diffusion;D:\github\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages
D:\github\stable-diffusion-ui\stable-diffusion\env\python.exe
D:\github\stable-diffusion-ui\installer_files\env\python.exe
C:\Users\EMANUELE\AppData\Local\Microsoft\WindowsApps\python.exe
Python 3.8.5
started in  D:\github\stable-diffusion-ui\stable-diffusion
D:\github\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\torch\cuda\__init__.py:122: UserWarning:
    Found GPU0 NVIDIA GeForce GTX 680 which is of cuda capability 3.0.
    PyTorch no longer supports this GPU because it is too old.
    The minimum cuda capability supported by this library is 3.7.

  warnings.warn(old_gpu_warn % (d, name, major, minor, min_arch // 10, min_arch % 10))
requesting for render_devices auto
devices_to_start {'cuda:0'}
devices_to_stop set()
Start new Rendering Thread on device cuda:0
Setting cuda:0 as active
loading D:\github\stable-diffusion-ui\models\stable-diffusion\sd-v1-4.ckpt to device cuda:0 using precision autocast
Loading model from D:\github\stable-diffusion-ui\models\stable-diffusion\sd-v1-4.ckpt
active devices {'cuda:0': {'name': 'NVIDIA GeForce GTX 680', 'mem_free': 3.575794894, 'mem_total': 4.294967296}}
INFO:     Started server process [7836]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
INFO:     127.0.0.1:51955 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:51955 - "GET /css/fonts.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:51957 - "GET /css/themes.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:51957 - "GET /css/auto-save.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:51955 - "GET /css/main.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:51957 - "GET /css/fontawesome-all.min.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:51957 - "GET /css/drawingboard.min.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:51955 - "GET /js/jquery-3.6.1.min.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:51962 - "GET /js/drawingboard.min.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:51963 - "GET /js/marked.min.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:51962 - "GET /js/utils.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:51962 - "GET /js/parameters.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:51962 - "GET /js/plugins.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:51962 - "GET /js/inpainting-editor.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:51962 - "GET /js/auto-save.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:51962 - "GET /js/main.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:51962 - "GET /js/themes.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:51962 - "GET /js/dnd.js HTTP/1.1" 200 OK
Scan D:\github\stable-diffusion-ui\models\stable-diffusion\sd-v1-4.ckpt: 1 scanned, 0 issue, 0 infected.
Scan D:\github\stable-diffusion-ui\models\vae\vae-ft-mse-840000-ema-pruned.ckpt: 1 scanned, 0 issue, 0 infected.
INFO:     127.0.0.1:51962 - "GET /get/models HTTP/1.1" 200 OK
INFO:     127.0.0.1:51962 - "GET /get/app_config HTTP/1.1" 200 OK
INFO:     127.0.0.1:51962 - "GET /get/modifiers HTTP/1.1" 200 OK
INFO:     127.0.0.1:51962 - "GET /get/ui_plugins HTTP/1.1" 200 OK
INFO:     127.0.0.1:51962 - "GET /get/devices HTTP/1.1" 200 OK
INFO:     127.0.0.1:51962 - "GET /Modifiers-dnd.plugin.js?t=1669656384799 HTTP/1.1" 200 OK
INFO:     127.0.0.1:51964 - "GET /Modifiers-wheel.plugin.js?t=1669656384800 HTTP/1.1" 200 OK
INFO:     127.0.0.1:51965 - "GET /release-notes.plugin.js?t=1669656384800 HTTP/1.1" 200 OK
INFO:     127.0.0.1:51965 - "GET /js/marked.min.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:51965 - "GET /get/app_config HTTP/1.1" 200 OK
Global Step: 470000
UNet: Running in eps-prediction mode
CondStage: Running in eps-prediction mode
FirstStage: Running in eps-prediction mode
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
loaded model
 model file: D:\github\stable-diffusion-ui\models\stable-diffusion\sd-v1-4.ckpt
 model.device: cpu
 modelCS.device: cuda:0
 modelFS.device: cpu
 using precision: autocast
INFO:     127.0.0.1:52085 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:52085 - "GET /css/fonts.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:52087 - "GET /css/themes.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:52095 - "GET /css/main.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:52098 - "GET /css/fontawesome-all.min.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:52096 - "GET /css/auto-save.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:52085 - "GET /css/drawingboard.min.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:52087 - "GET /js/marked.min.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52096 - "GET /js/jquery-3.6.1.min.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52097 - "GET /js/drawingboard.min.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52097 - "GET /js/utils.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52087 - "GET /js/plugins.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52095 - "GET /js/auto-save.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52098 - "GET /js/inpainting-editor.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52096 - "GET /js/parameters.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52097 - "GET /js/main.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52087 - "GET /js/themes.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52098 - "GET /js/dnd.js HTTP/1.1" 200 OK
Scan D:\github\stable-diffusion-ui\models\stable-diffusion\sd-v1-4.ckpt: 1 scanned, 0 issue, 0 infected.
INFO:     127.0.0.1:52115 - "GET /css/fontawesome-all.min.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:52115 - "GET /css/drawingboard.min.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:52115 - "GET /css/auto-save.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:52115 - "GET /css/themes.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:52115 - "GET /css/main.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:52115 - "GET /css/fonts.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:52115 - "GET / HTTP/1.1" 200 OK
Scan D:\github\stable-diffusion-ui\models\vae\vae-ft-mse-840000-ema-pruned.ckpt: 1 scanned, 0 issue, 0 infected.
INFO:     127.0.0.1:52098 - "GET /get/models HTTP/1.1" 200 OK
INFO:     127.0.0.1:52098 - "GET /get/app_config HTTP/1.1" 200 OK
INFO:     127.0.0.1:52098 - "GET /get/modifiers HTTP/1.1" 200 OK
INFO:     127.0.0.1:52098 - "GET /get/ui_plugins HTTP/1.1" 200 OK
INFO:     127.0.0.1:52098 - "GET /get/devices HTTP/1.1" 200 OK
INFO:     127.0.0.1:52117 - "GET /release-notes.plugin.js?t=1669656677821 HTTP/1.1" 200 OK
INFO:     127.0.0.1:52098 - "GET /Modifiers-dnd.plugin.js?t=1669656677819 HTTP/1.1" 200 OK
INFO:     127.0.0.1:52115 - "GET /Modifiers-wheel.plugin.js?t=1669656677820 HTTP/1.1" 200 OK
INFO:     127.0.0.1:52115 - "GET /js/marked.min.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52115 - "GET /get/app_config HTTP/1.1" 200 OK
INFO:     127.0.0.1:52115 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:52115 - "GET /css/fonts.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:52117 - "GET /css/themes.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:52098 - "GET /css/main.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:52098 - "GET /css/auto-save.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:52115 - "GET /css/fontawesome-all.min.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:52115 - "GET /css/drawingboard.min.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:52115 - "GET /js/jquery-3.6.1.min.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52117 - "GET /js/drawingboard.min.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52115 - "GET /js/marked.min.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52115 - "GET /js/utils.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52115 - "GET /js/parameters.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52115 - "GET /js/plugins.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52117 - "GET /js/inpainting-editor.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52117 - "GET /js/auto-save.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52115 - "GET /js/main.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52117 - "GET /js/themes.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52115 - "GET /js/dnd.js HTTP/1.1" 200 OK
Scan D:\github\stable-diffusion-ui\models\stable-diffusion\sd-v1-4.ckpt: 1 scanned, 0 issue, 0 infected.
Scan D:\github\stable-diffusion-ui\models\vae\vae-ft-mse-840000-ema-pruned.ckpt: 1 scanned, 0 issue, 0 infected.
INFO:     127.0.0.1:52115 - "GET /get/models HTTP/1.1" 200 OK
INFO:     127.0.0.1:52115 - "GET /get/app_config HTTP/1.1" 200 OK
INFO:     127.0.0.1:52115 - "GET /get/modifiers HTTP/1.1" 200 OK
INFO:     127.0.0.1:52115 - "GET /get/ui_plugins HTTP/1.1" 200 OK
INFO:     127.0.0.1:52115 - "GET /get/devices HTTP/1.1" 200 OK
INFO:     127.0.0.1:52115 - "GET /Modifiers-dnd.plugin.js?t=1669656681982 HTTP/1.1" 200 OK
INFO:     127.0.0.1:52117 - "GET /Modifiers-wheel.plugin.js?t=1669656681983 HTTP/1.1" 200 OK
INFO:     127.0.0.1:52098 - "GET /release-notes.plugin.js?t=1669656681983 HTTP/1.1" 200 OK
INFO:     127.0.0.1:52098 - "GET /js/marked.min.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52098 - "GET /get/app_config HTTP/1.1" 200 OK
INFO:     127.0.0.1:52098 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:52098 - "GET /css/fonts.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:52119 - "GET /css/main.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:52118 - "GET /css/themes.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:52120 - "GET /css/auto-save.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:52119 - "GET /css/fontawesome-all.min.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:52120 - "GET /js/jquery-3.6.1.min.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52118 - "GET /css/drawingboard.min.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:52118 - "GET /js/drawingboard.min.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52098 - "GET /js/marked.min.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52098 - "GET /js/parameters.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52118 - "GET /js/utils.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52098 - "GET /js/plugins.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52119 - "GET /js/auto-save.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52118 - "GET /js/inpainting-editor.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52119 - "GET /js/main.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52098 - "GET /js/themes.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52120 - "GET /js/dnd.js HTTP/1.1" 200 OK
Scan D:\github\stable-diffusion-ui\models\stable-diffusion\sd-v1-4.ckpt: 1 scanned, 0 issue, 0 infected.
Scan D:\github\stable-diffusion-ui\models\vae\vae-ft-mse-840000-ema-pruned.ckpt: 1 scanned, 0 issue, 0 infected.
INFO:     127.0.0.1:52098 - "GET /get/models HTTP/1.1" 200 OK
INFO:     127.0.0.1:52098 - "GET /get/app_config HTTP/1.1" 200 OK
INFO:     127.0.0.1:52098 - "GET /get/modifiers HTTP/1.1" 200 OK
INFO:     127.0.0.1:52098 - "GET /get/ui_plugins HTTP/1.1" 200 OK
INFO:     127.0.0.1:52098 - "GET /get/devices HTTP/1.1" 200 OK
INFO:     127.0.0.1:52120 - "GET /Modifiers-wheel.plugin.js?t=1669656711252 HTTP/1.1" 200 OK
INFO:     127.0.0.1:52098 - "GET /Modifiers-dnd.plugin.js?t=1669656711252 HTTP/1.1" 200 OK
INFO:     127.0.0.1:52119 - "GET /release-notes.plugin.js?t=1669656711252 HTTP/1.1" 200 OK
INFO:     127.0.0.1:52119 - "GET /js/marked.min.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52119 - "GET /get/app_config HTTP/1.1" 200 OK
{"render_devices": "auto", "update_branch": "beta", "ui": {"open_browser_on_start": true}, "model": {"stable-diffusion": "sd-v1-4"}, "net": {"listen_port": 9000, "listen_to_network": true}}
INFO:     127.0.0.1:52119 - "POST /render HTTP/1.1" 200 OK
Session 1669656710814 starting task 2184731301392 on NVIDIA GeForce GTX 680
Unloading models...
loading D:\github\stable-diffusion-ui\models\stable-diffusion\sd-v1-4.ckpt to device cuda:0 using precision full
Loading model from D:\github\stable-diffusion-ui\models\stable-diffusion\sd-v1-4.ckpt
Global Step: 470000
UNet: Running in eps-prediction mode
{"render_devices": "auto", "update_branch": "main", "ui": {"open_browser_on_start": true}, "model": {"stable-diffusion": "sd-v1-4"}, "net": {"listen_port": 9000, "listen_to_network": true}, "test_sd2": false}
requesting for render_devices auto
devices_to_start set()
devices_to_stop set()
active devices {'cuda:0': {'name': 'NVIDIA GeForce GTX 680', 'mem_free': 3.575794894, 'mem_total': 4.294967296}}
INFO:     127.0.0.1:52119 - "POST /app_config HTTP/1.1" 200 OK
CondStage: Running in eps-prediction mode
FirstStage: Running in eps-prediction mode
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
loaded model
 model file: D:\github\stable-diffusion-ui\models\stable-diffusion\sd-v1-4.ckpt
 model.device: cpu
 modelCS.device: cuda:0
 modelFS.device: cpu
 using precision: full

    session_id: 1669656710814
    prompt: a photograph of an astronaut riding a horse
    negative_prompt:
    seed: 5735527
    num_inference_steps: 50
    sampler: euler_a
    guidance_scale: 7.5
    w: 512
    h: 512
    precision: autocast
    save_to_disk_path: D:\github\stable-diffusion-ui\profile\Stable Diffusion UI
    turbo: True
    use_full_precision: True
    use_face_correction: None
    use_upscale: None
    use_stable_diffusion_model: D:\github\stable-diffusion-ui\models\stable-diffusion\sd-v1-4
    use_vae_model: None
    show_only_filtered_image: True
    output_format: jpeg

    stream_progress_updates: True
    stream_image_progress: True
    device cuda:0 as NVIDIA GeForce GTX 680


    Using precision: full
Global seed set to 5735527
data:   0%|                                                                                      | 0/1 [00:10<?, ?it/s]
Sampling:   0%|                                                                                  | 0/1 [00:10<?, ?it/s]
Traceback (most recent call last):
  File "D:\github\stable-diffusion-ui\ui\sd_internal\runtime.py", line 397, in mk_img
    yield from do_mk_img(req)
  File "D:\github\stable-diffusion-ui\ui\sd_internal\runtime.py", line 582, in do_mk_img
    uc = thread_data.modelCS.get_learned_conditioning(batch_size * [req.negative_prompt])
  File "D:\github\stable-diffusion-ui\stable-diffusion\optimizedSD\ddpm.py", line 296, in get_learned_conditioning
    c = self.cond_stage_model.encode(c)
  File "D:\github\stable-diffusion-ui\stable-diffusion\ldm\modules\encoders\modules.py", line 162, in encode
    return self(text)
  File "D:\github\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\github\stable-diffusion-ui\stable-diffusion\ldm\modules\encoders\modules.py", line 156, in forward
    outputs = self.transformer(input_ids=tokens)
  File "D:\github\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\github\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\transformers\models\clip\modeling_clip.py", line 722, in forward
    return self.text_model(
  File "D:\github\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\github\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\transformers\models\clip\modeling_clip.py", line 632, in forward
    hidden_states = self.embeddings(input_ids=input_ids, position_ids=position_ids)
  File "D:\github\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\github\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\transformers\models\clip\modeling_clip.py", line 165, in forward
    inputs_embeds = self.token_embedding(input_ids)
  File "D:\github\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\github\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\torch\nn\modules\sparse.py", line 158, in forward
    return F.embedding(
  File "D:\github\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\torch\nn\functional.py", line 2183, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

Session 1669656710814 task 2184731301392 completed by NVIDIA GeForce GTX 680.
{"render_devices": "auto", "update_branch": "main", "ui": {"open_browser_on_start": true}, "model": {"stable-diffusion": "sd-v1-4"}, "net": {"listen_port": 9000, "listen_to_network": true}, "test_sd2": false}
requesting for render_devices auto
devices_to_start set()
devices_to_stop set()
active devices {'cuda:0': {'name': 'NVIDIA GeForce GTX 680', 'mem_free': 3.573697742, 'mem_total': 4.294967296}}
INFO:     127.0.0.1:52191 - "POST /app_config HTTP/1.1" 200 OK
{"render_devices": "auto", "update_branch": "main", "ui": {"open_browser_on_start": true}, "model": {"stable-diffusion": "sd-v1-4"}, "net": {"listen_port": 9000, "listen_to_network": true}, "test_sd2": false}
INFO:     127.0.0.1:52191 - "POST /render HTTP/1.1" 200 OK
Session 1669656710814 starting task 2192359071120 on NVIDIA GeForce GTX 680
Unloading models...
loading D:\github\stable-diffusion-ui\models\stable-diffusion\sd-v1-4.ckpt to device cuda:0 using precision autocast
Loading model from D:\github\stable-diffusion-ui\models\stable-diffusion\sd-v1-4.ckpt
Global Step: 470000
UNet: Running in eps-prediction mode
CondStage: Running in eps-prediction mode
FirstStage: Running in eps-prediction mode
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
loaded model
 model file: D:\github\stable-diffusion-ui\models\stable-diffusion\sd-v1-4.ckpt
 model.device: cpu
 modelCS.device: cuda:0
 modelFS.device: cpu
 using precision: autocast

    session_id: 1669656710814
    prompt: a photograph of an astronaut riding a horse
    negative_prompt:
    seed: 3847944
    num_inference_steps: 50
    sampler: euler_a
    guidance_scale: 7.5
    w: 512
    h: 512
    precision: autocast
    save_to_disk_path: D:\github\stable-diffusion-ui\profile\Stable Diffusion UI
    turbo: True
    use_full_precision: False
    use_face_correction: None
    use_upscale: None
    use_stable_diffusion_model: D:\github\stable-diffusion-ui\models\stable-diffusion\sd-v1-4
    use_vae_model: None
    show_only_filtered_image: True
    output_format: jpeg

    stream_progress_updates: True
    stream_image_progress: True
    device cuda:0 as NVIDIA GeForce GTX 680


    Using precision: autocast
Global seed set to 3847944
data:   0%|                                                                                      | 0/1 [00:02<?, ?it/s]
Sampling:   0%|                                                                                  | 0/1 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "D:\github\stable-diffusion-ui\ui\sd_internal\runtime.py", line 397, in mk_img
    yield from do_mk_img(req)
  File "D:\github\stable-diffusion-ui\ui\sd_internal\runtime.py", line 582, in do_mk_img
    uc = thread_data.modelCS.get_learned_conditioning(batch_size * [req.negative_prompt])
  File "D:\github\stable-diffusion-ui\stable-diffusion\optimizedSD\ddpm.py", line 296, in get_learned_conditioning
    c = self.cond_stage_model.encode(c)
  File "D:\github\stable-diffusion-ui\stable-diffusion\ldm\modules\encoders\modules.py", line 162, in encode
    return self(text)
  File "D:\github\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\github\stable-diffusion-ui\stable-diffusion\ldm\modules\encoders\modules.py", line 156, in forward
    outputs = self.transformer(input_ids=tokens)
  File "D:\github\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\github\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\transformers\models\clip\modeling_clip.py", line 722, in forward
    return self.text_model(
  File "D:\github\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\github\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\transformers\models\clip\modeling_clip.py", line 632, in forward
    hidden_states = self.embeddings(input_ids=input_ids, position_ids=position_ids)
  File "D:\github\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\github\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\transformers\models\clip\modeling_clip.py", line 165, in forward
    inputs_embeds = self.token_embedding(input_ids)
  File "D:\github\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\github\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\torch\nn\modules\sparse.py", line 158, in forward
    return F.embedding(
  File "D:\github\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\torch\nn\functional.py", line 2183, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

Session 1669656710814 task 2192359071120 cancelled!

**Comment by MrStirner** [comment]
------  reported same error when try make image 

[...] return F.embedding(
  File "D:\github\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\torch\nn\functional.py", line 2183, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by JMcPeak3373** [comment]
I found out that it has to do with updates to STABLE DIFFUSION. The newer versions cannot use the older NVENC GPU on the older cards. Try switching to CPU rendering in the settings and see if it works, that's what fixed it for me.

**Comment by MrStirner** [comment]
Yes effectively i have a gtx680 4gb , with cpu it works , thanks (y)
