### ISSUE TITLE
ERROR: micromamba download failed

### ISSUE THREAD

**Issue by jsnferns** [cmdr2/stable-diffusion-ui#470]
Downloading micromamba from https://micro.mamba.pm/api/micromamba/linux-64/latest to /home/jsn/Documents/stable-diffusion-ui-linux/stable-diffusion-ui/installer_files/mamba/micromamba
scripts/bootstrap.sh: line 54: curl: command not found

bzip2: Compressed file ends unexpectedly;
	perhaps it is corrupted?  *Possible* reason follows.
bzip2: Inappropriate ioctl for device
	Input file = (stdin), output file = (stdout)

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.

tar: Child returned status 2
tar: Error is not recoverable: exiting now

EE micromamba download failed
EE If the lines above contain 'bzip2: Cannot exec', your system doesn't have bzip2 installed
EE If there are network errors, please check your internet setup

EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
ERROR: micromamba download failed
Ubuntu Linux

**Comment by cmdr2** [comment]
Hi, please install `curl`, the error message says `scripts/bootstrap.sh: line 54: curl: command not found`

`sudo apt install curl`

Thanks
