### ISSUE TITLE
Error installing the packages necessary for Stable Diffusion

### ISSUE THREAD

**Issue by BiseEise** [cmdr2/stable-diffusion-ui#472]
Verifying transaction: failed

CondaVerificationError: The package for pytorch located at C:\stable deffusion\stable-diffusion-ui-windows\stable-diffusion-ui\installer_files\env\pkgs\pytorch-1.11.0-py3.8_cuda11.3_cudnn8_0
appears to be corrupted. The path 'Lib/site-packages/caffe2/python/serialized_test/data/operator_test/collect_and_distribute_fpn_rpn_proposals_op_test.test_collect_and_dist.zip'
specified in the package manifest cannot be found.

CondaVerificationError: The package for pytorch located at C:\stable deffusion\stable-diffusion-ui-windows\stable-diffusion-ui\installer_files\env\pkgs\pytorch-1.11.0-py3.8_cuda11.3_cudnn8_0
appears to be corrupted. The path 'Lib/site-packages/caffe2/python/serialized_test/data/operator_test/cosine_embedding_criterion_op_test.test_cosine_embedding_criterion.zip'
specified in the package manifest cannot be found.

CondaVerificationError: The package for pytorch located at C:\stable deffusion\stable-diffusion-ui-windows\stable-diffusion-ui\installer_files\env\pkgs\pytorch-1.11.0-py3.8_cuda11.3_cudnn8_0
appears to be corrupted. The path 'Lib/site-packages/caffe2/python/serialized_test/data/operator_test/ctc_beam_search_decoder_op_test.test_ctc_beam_search_decoder.zip'
specified in the package manifest cannot be found.

CondaVerificationError: The package for pytorch located at C:\stable deffusion\stable-diffusion-ui-windows\stable-diffusion-ui\installer_files\env\pkgs\pytorch-1.11.0-py3.8_cuda11.3_cudnn8_0
appears to be corrupted. The path 'Lib/site-packages/caffe2/python/serialized_test/data/operator_test/learning_rate_adaption_op_test.test_learning_rate_adaption_op_normalization.zip'
specified in the package manifest cannot be found.

CondaVerificationError: The package for pytorch located at C:\stable deffusion\stable-diffusion-ui-windows\stable-diffusion-ui\installer_files\env\pkgs\pytorch-1.11.0-py3.8_cuda11.3_cudnn8_0
appears to be corrupted. The path 'Lib/site-packages/caffe2/python/serialized_test/data/operator_test/margin_ranking_criterion_op_test.test_margin_ranking_criterion.zip'
specified in the package manifest cannot be found.

CondaVerificationError: The package for pytorch located at C:\stable deffusion\stable-diffusion-ui-windows\stable-diffusion-ui\installer_files\env\pkgs\pytorch-1.11.0-py3.8_cuda11.3_cudnn8_0
appears to be corrupted. The path 'Lib/site-packages/caffe2/python/serialized_test/data/operator_test/piecewise_linear_transform_test.test_multi_predictions_params_from_arg.zip'
specified in the package manifest cannot be found.

CondaVerificationError: The package for pytorch located at C:\stable deffusion\stable-diffusion-ui-windows\stable-diffusion-ui\installer_files\env\pkgs\pytorch-1.11.0-py3.8_cuda11.3_cudnn8_0
appears to be corrupted. The path 'Lib/site-packages/caffe2/python/serialized_test/data/operator_test/sinusoid_position_encoding_op_test.test_sinusoid_embedding.zip'
specified in the package manifest cannot be found.

CondaVerificationError: The package for pytorch located at C:\stable deffusion\stable-diffusion-ui-windows\stable-diffusion-ui\installer_files\env\pkgs\pytorch-1.11.0-py3.8_cuda11.3_cudnn8_0
appears to be corrupted. The path 'Lib/site-packages/torch/include/ATen/ops/_fake_quantize_learnable_per_channel_affine_backward_compositeimplicitautograd_dispatch.h'
specified in the package manifest cannot be found.

CondaVerificationError: The package for pytorch located at C:\stable deffusion\stable-diffusion-ui-windows\stable-diffusion-ui\installer_files\env\pkgs\pytorch-1.11.0-py3.8_cuda11.3_cudnn8_0
appears to be corrupted. The path 'Lib/site-packages/torch/include/ATen/ops/_fake_quantize_learnable_per_tensor_affine_backward_compositeimplicitautograd_dispatch.h'
specified in the package manifest cannot be found.

CondaVerificationError: The package for pytorch located at C:\stable deffusion\stable-diffusion-ui-windows\stable-diffusion-ui\installer_files\env\pkgs\pytorch-1.11.0-py3.8_cuda11.3_cudnn8_0
appears to be corrupted. The path 'Lib/site-packages/torch/include/ATen/ops/fake_quantize_per_channel_affine_cachemask_backward_compositeimplicitautograd_dispatch.h'
specified in the package manifest cannot be found.

CondaVerificationError: The package for pytorch located at C:\stable deffusion\stable-diffusion-ui-windows\stable-diffusion-ui\installer_files\env\pkgs\pytorch-1.11.0-py3.8_cuda11.3_cudnn8_0
appears to be corrupted. The path 'Lib/site-packages/torch/include/ATen/ops/fake_quantize_per_tensor_affine_cachemask_backward_compositeimplicitautograd_dispatch.h'
specified in the package manifest cannot be found.

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/noarch::pycparser-2.21-pyhd3eb1b0_0, defaults/win-64::brotlipy-0.7.0-py38h2bbff1b_1003
  path: 'lib/site-packages/pycparser/__pycache__/__init__.cpython-38.pyc'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/noarch::pycparser-2.21-pyhd3eb1b0_0, defaults/win-64::brotlipy-0.7.0-py38h2bbff1b_1003
  path: 'lib/site-packages/pycparser/__pycache__/ast_transforms.cpython-38.pyc'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/noarch::pycparser-2.21-pyhd3eb1b0_0, defaults/win-64::brotlipy-0.7.0-py38h2bbff1b_1003
  path: 'lib/site-packages/pycparser/__pycache__/c_ast.cpython-38.pyc'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/noarch::pycparser-2.21-pyhd3eb1b0_0, defaults/win-64::brotlipy-0.7.0-py38h2bbff1b_1003
  path: 'lib/site-packages/pycparser/__pycache__/c_lexer.cpython-38.pyc'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/noarch::pycparser-2.21-pyhd3eb1b0_0, defaults/win-64::brotlipy-0.7.0-py38h2bbff1b_1003
  path: 'lib/site-packages/pycparser/__pycache__/c_parser.cpython-38.pyc'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/noarch::pycparser-2.21-pyhd3eb1b0_0, defaults/win-64::brotlipy-0.7.0-py38h2bbff1b_1003
  path: 'lib/site-packages/pycparser/__pycache__/lextab.cpython-38.pyc'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/noarch::pycparser-2.21-pyhd3eb1b0_0, defaults/win-64::brotlipy-0.7.0-py38h2bbff1b_1003
  path: 'lib/site-packages/pycparser/ply/__pycache__/__init__.cpython-38.pyc'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/noarch::pycparser-2.21-pyhd3eb1b0_0, defaults/win-64::brotlipy-0.7.0-py38h2bbff1b_1003
  path: 'lib/site-packages/pycparser/ply/__pycache__/lex.cpython-38.pyc'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/noarch::pycparser-2.21-pyhd3eb1b0_0, defaults/win-64::brotlipy-0.7.0-py38h2bbff1b_1003
  path: 'lib/site-packages/pycparser/ply/__pycache__/yacc.cpython-38.pyc'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/noarch::pycparser-2.21-pyhd3eb1b0_0, defaults/win-64::brotlipy-0.7.0-py38h2bbff1b_1003
  path: 'lib/site-packages/pycparser/__pycache__/plyparser.cpython-38.pyc'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/noarch::pycparser-2.21-pyhd3eb1b0_0, defaults/win-64::brotlipy-0.7.0-py38h2bbff1b_1003
  path: 'lib/site-packages/pycparser/__pycache__/yacctab.cpython-38.pyc'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/noarch::wheel-0.37.1-pyhd3eb1b0_0, defaults/win-64::win_inet_pton-1.1.0-py38haa95532_0
  path: 'lib/site-packages/wheel/__pycache__/__init__.cpython-38.pyc'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/noarch::wheel-0.37.1-pyhd3eb1b0_0, defaults/win-64::win_inet_pton-1.1.0-py38haa95532_0
  path: 'lib/site-packages/wheel/__pycache__/bdist_wheel.cpython-38.pyc'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/noarch::wheel-0.37.1-pyhd3eb1b0_0, defaults/win-64::win_inet_pton-1.1.0-py38haa95532_0
  path: 'lib/site-packages/wheel/cli/__pycache__/__init__.cpython-38.pyc'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/noarch::wheel-0.37.1-pyhd3eb1b0_0, defaults/win-64::win_inet_pton-1.1.0-py38haa95532_0
  path: 'lib/site-packages/wheel/__pycache__/macosx_libfile.cpython-38.pyc'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/noarch::wheel-0.37.1-pyhd3eb1b0_0, defaults/win-64::win_inet_pton-1.1.0-py38haa95532_0
  path: 'lib/site-packages/wheel/__pycache__/metadata.cpython-38.pyc'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/noarch::wheel-0.37.1-pyhd3eb1b0_0, defaults/win-64::win_inet_pton-1.1.0-py38haa95532_0
  path: 'lib/site-packages/wheel/__pycache__/pkginfo.cpython-38.pyc'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/noarch::wheel-0.37.1-pyhd3eb1b0_0, defaults/win-64::win_inet_pton-1.1.0-py38haa95532_0
  path: 'lib/site-packages/wheel/__pycache__/util.cpython-38.pyc'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/noarch::wheel-0.37.1-pyhd3eb1b0_0, defaults/win-64::win_inet_pton-1.1.0-py38haa95532_0
  path: 'lib/site-packages/wheel/vendored/__pycache__/__init__.cpython-38.pyc'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/noarch::wheel-0.37.1-pyhd3eb1b0_0, defaults/win-64::win_inet_pton-1.1.0-py38haa95532_0
  path: 'lib/site-packages/wheel/vendored/packaging/__pycache__/__init__.cpython-38.pyc'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/noarch::wheel-0.37.1-pyhd3eb1b0_0, defaults/win-64::win_inet_pton-1.1.0-py38haa95532_0
  path: 'lib/site-packages/wheel/vendored/packaging/__pycache__/_typing.cpython-38.pyc'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/noarch::wheel-0.37.1-pyhd3eb1b0_0, defaults/win-64::win_inet_pton-1.1.0-py38haa95532_0
  path: 'lib/site-packages/wheel/vendored/packaging/__pycache__/tags.cpython-38.pyc'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/noarch::wheel-0.37.1-pyhd3eb1b0_0, defaults/win-64::win_inet_pton-1.1.0-py38haa95532_0
  path: 'lib/site-packages/wheel/__pycache__/wheelfile.cpython-38.pyc'

How can I solve it please help?

**Comment by cmdr2** [comment]
Hi, please try the troubleshooting guide written for the Clobber Errors first: https://github.com/cmdr2/stable-diffusion-ui/wiki/Troubleshooting#no-ldm-found-or-antlr4-or-any-other-missing-module-or-clobbererror-this-transaction-has-incompatible-packages-due-to-a-shared-path

Please feel free to reopen or ask on the Discord server if this problem continues to happen, thanks!
