### ISSUE TITLE
Error installing the packages necessary for Stable Diffusion. but i have everything downloaded. 

### ISSUE THREAD

**Issue by ironsoldier2018** [cmdr2/stable-diffusion-ui#487]
i if try a few time to install the stable diffusion on my windows 11 but it keeps giving me the Error installing the packages necessary for Stable Diffusion. code wat do i need to do?

**Comment by JeLuF** [comment]
Can you please share the entire error message with us?
In the installer window, type `Ctrl-A`, then hit `Enter`. Paste the text into a notepad window, save it as a text file, and attach it to this ticket.

**Comment by ironsoldier2018** [comment]
[error message.txt](https://github.com/cmdr2/stable-diffusion-ui/files/10030136/error.message.txt)

**Comment by cmdr2** [comment]
Hi @ironsoldier2018 Please try the steps described for the Clobber Errors: https://github.com/cmdr2/stable-diffusion-ui/wiki/Troubleshooting#clobbererror-this-transaction-has-incompatible-packages-due-to-a-shared-path

Please feel free to reopen if that doesn't fix the problem, thanks!
