### ISSUE TITLE
Flatpak for Linux users

### ISSUE THREAD

**Issue by 12people** [cmdr2/stable-diffusion-ui#498]
**Is your feature request related to a problem? Please describe.**
The current Linux installation is fast, but still:
- is not very friendly for non-technical users who don't know how to use the Terminal
- is not usable on immutable distributions, such as Steam OS, Endless OS, or Fedora Silverblue

**Describe the solution you'd like**
It'd be great to have a [Flatpak](https://docs.flatpak.org/en/latest/) release on [Flathub](https://flathub.org/).

**Describe alternatives you've considered**
There are two competing package formats: AppImage and Snap. AppImage requires developers to integrate a security sandbox themselves, whereas Flatpak integrates this sandbox by default. Snap is a partly proprietary technology (the server is proprietary and centralized). Also, since Snap is not preinstalled on any popular immutable distribution (perhaps on any immutable distro, to my knowledge), releasing a Snap would not solve the issue for users of those distros.

**Comment by cmdr2** [comment]
Thanks! That's a great suggestion, and one that I'm pretty interested in.

Do you have any interest in taking a stab at this? Thanks!

**Comment by 12people** [comment]
Not right now — I'm drowning in work and projects as is, unfortunately. :/

**Comment by 12people** [comment]
I'm also realizing a bit late: Flatpak is used for GUI apps only and thus would not work for a browser UI. The whole thing would have to be wrapped in Electron or similar, which would add a whole another layer of complexity on implementing this.

Sounds like this would be harder than I originally thought. I would still leave this issue up in case someone here would like to take it in the future.

**Comment by 12people** [comment]
I found a GUI app that would be more suitable for a Flatpak: https://github.com/FahimF/sd-gui .

I will suggest making a Flatpak there instead.
