### ISSUE TITLE
Support for AMD GPU's

### ISSUE THREAD

**Issue by iofhua** [cmdr2/stable-diffusion-ui#499]
First I want to say **THANK YOU!** for making this simple installer for stable diffusion. I've been using it a lot over the past couple weeks and I appreciate all the work you put into it.

I run it on a Ryzen 5 3400G and I use the integrated Vega 11 graphics. When I look at the options in the stable diffusion UI it is stuck in CPU rendering mode. While the integrated graphics aren't all that great, it can take me over 2 hours to generate an image using only the CPU so I set it up to generate images overnight. I wish I could try it out with the GPU to see if it's any faster.

I looked up some guides to do that, something to do with pytorch, but it all looks like greek to me.

No rush. I just wanted you to know it's a feature I would like to have.

**Comment by emircanerkul** [comment]
@iofhua https://github.com/cmdr2/stable-diffusion-ui/issues/115

**Comment by cmdr2** [comment]
Tracking this in https://github.com/cmdr2/stable-diffusion-ui/issues/115

Current status: AMD now works out-of-the-box on Linux, but not yet on Windows
