### ISSUE TITLE
Compose file '/docker-compose' invalid because 'devices' was unexpected

### ISSUE THREAD

**Issue by alexanderdutton** [cmdr2/stable-diffusion-ui#5]
I'm fumbling through my WSL2/docker setup.
 
 I think I've got everything right with the GPU, as it detects, but when I get to docker-compose up, it is throwing this:

> ERROR: The Compose file './docker-compose.yml' is invalid because:
> services.stability-ai.deploy.resources.reservations value Additional properties are not allowed ('devices' was unexpected)

Thanks for your work and help!

**Comment by HVRyan** [comment]
> I'm fumbling through my WSL2/docker setup.
> 
> I think I've got everything right with the GPU, as it detects, but when I get to docker-compose up, it is throwing this:
> 
> > ERROR: The Compose file './docker-compose.yml' is invalid because:
> > services.stability-ai.deploy.resources.reservations value Additional properties are not allowed ('devices' was unexpected)
> 
> Thanks for your work and help!

Check the version:


docker-compose --version

I had to move up past 1.28

```~$ docker-compose --version
Docker Compose version v2.6.0```

**Comment by alexanderdutton** [comment]
Thanks for this, HVRyan .. I think the issue might have been that I had a copy of docker compose as well as docker-compose, and while I was updating the one, I was running the other.

I'd mixed my system up by incorrectly installing Desktop Docker first, and didn't do a good enough job of cleaning up -- in case that helps anyone else.

**Comment by cmdr2** [comment]
Thanks @alexanderdutton and @HVRyan . I've clarified this on the README, and warned people not to install Desktop Docker for Windows. I've also added a troubleshooting section, and included this error and solution.

@alexanderdutton  Hope your setup is working now!

**Comment by alexanderdutton** [comment]
So many astronauts on horses!

Thanks, @cmdr2 !

**Comment by cmdr2** [comment]
:)
