### ISSUE TITLE
Upscaling resolution

### ISSUE THREAD

**Issue by cmdr2** [cmdr2/stable-diffusion-ui#50]
RealESRGAN seems like a decent start

**Comment by Karric** [comment]
This project seems to use SD in a clever way to do upscaling, might be less work: https://github.com/jquesnelle/txt2imghd

**Comment by MrManny** [comment]
Just to let the fine folks know, this has landed in the `beta` branch.
See the beta announcement on Discord: https://discord.com/channels/1014774730907209781/1017700054007558226/1017830307304575056

**Comment by cmdr2** [comment]
Done
