### ISSUE TITLE
Error generating image on fresh install.

### ISSUE THREAD

**Issue by jdfinch** [cmdr2/stable-diffusion-ui#532]
[stable-diffusion-error.txt](https://github.com/cmdr2/stable-diffusion-ui/files/10072119/stable-diffusion-error.txt)

![Screenshot from 2022-11-22 19-40-22](https://user-images.githubusercontent.com/42592902/203448712-352bd957-2427-4041-8931-95d8138d1299.png)

The error happened today on an old install that used to work. I did a clean reinstall and still got the error.

**Comment by JeLuF** [comment]
Can you retry with a guidance scale bigger than one?

**Comment by jdfinch** [comment]
Ok yes, increasing the guidance worked. The error only happens on guidance scale =1.0 exactly.
