### ISSUE TITLE
Error: No execution permission for on_sd_start.sh

### ISSUE THREAD

**Issue by HPPinata** [cmdr2/stable-diffusion-ui#547]
**Describe the bug**
Fresh installation stops after cloning "sd-ui-files" and complains about on_sd_start.sh permissions

**To Reproduce**
1. Clean out old install (or use different directory)
2. Download & unpack linux.zip
3. Execute start.sh
5. ls -la stable-diffusion-ui/scripts/

**Expected behavior**
Scripts that get executed should have correct permissions.
Installation works fine after setting ``chmod 775 on_sd_start.sh``

**CLI**
```
Transaction finished
/home/momi/stable-diffusion-ui/installer_files/env/bin/git
git version 2.38.1
/home/momi/stable-diffusion-ui/installer_files/env/bin/conda
conda 22.9.0

Stable Diffusion UI

Downloading Stable Diffusion UI..

Using the main channel

Klone nach 'sd-ui-files'...
remote: Enumerating objects: 10224, done.
remote: Counting objects: 100% (38/38), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 10224 (delta 17), reused 26 (delta 17), pack-reused 10186
Empfange Objekte: 100% (10224/10224), 54.29 MiB | 3.74 MiB/s, fertig.
Löse Unterschiede auf: 100% (6372/6372), fertig.
scripts/on_env_start.sh: Zeile 43: ./scripts/on_sd_start.sh: Keine Berechtigung
Press any key to continue
```
```
ls -la stable-diffusion-ui/scripts/
insgesamt 32
drwxrwxr-x 1 momi users   142 25. Nov 12:47 .
drwxrwxr-x 1 momi users   252 25. Nov 12:47 ..
-rwxrwxr-x 1 momi users  3326 25. Nov 12:47 bootstrap.sh
-rw-rw-r-- 1 momi users   824 22. Nov 06:15 functions.sh
-rw-rw-r-- 1 momi users    18 25. Nov 12:47 install_status.txt
-rwxrwxr-x 1 momi users  1165 22. Nov 06:15 on_env_start.sh
-rw-r--r-- 1 momi users 13489 25. Nov 12:47 on_sd_start.sh
```

**Desktop (please complete the following information):**
 - OS: openSUSE: Leap 15.4, Tumbleweed; Fedora: 36, 37
 - Browser: /
 - Version: v2.4.13

**Comment by eresposito** [comment]
tried pulling that part of the if/then and manually applying those changes. Other items break.  I'm not good enough at debugging that file.

**Comment by eresposito** [comment]
remove stable diff ui
redownload
chmod =777 on_sd_start.sh
apt-get install libsm6 libxext6 libxrender-dev
run ./start.sh

**Comment by HPPinata** [comment]
> apt-get install libsm6 libxext6 libxrender-dev

This is a separate issue. The environment needs a few undeclared dependencies that probably are on most desktop systems by default.
On openSUSE it's just ``libgthread-2_0-0``
On Fedora the packages are ``xorg-x11-drivers`` and ``libSM`` thought here it's probably just a subset of those. I just haven't tested further which if the ``xorg-x11-drivers`` dependencies are the necessary ones.

This has been the state of things for several versions and at least when those dependencies are present it's actually enough to just:
1. unpack the .zip
2. execute start.sh
3. chmod 775 the on_sd_start.sh script
4. execute start.sh again

**Comment by eresposito** [comment]
> This has been the state of things for several versions and at least when those dependencies are present it's actually enough to just:
> 
>     1. unpack the .zip
>     2. execute start.sh
>     3. chmod 775 the on_sd_start.sh script
>     4. execute start.sh again

A couple days ago, I don't recall needing to chmod the file. In any case, this does fix the on_sd_start error with me.  I may have inadvertently completed this with a previous SD non ui install.

OS: Ubuntu 22.04.1 LTS

**Comment by HPPinata** [comment]
> A couple days ago, I don't recall needing to chmod the file. In any case, this does fix the on_sd_start error with me. I may have inadvertently completed this with a previous SD UI install.
> 
> OS: Ubuntu 22.04.1 LTS

I should have been more accurate: the dependency situation has been like this for several versions (and probably won't be fixed because it's different on all the distributions). The chmod thing is new but can be fixed easily by the maintainers (just set the permissions for the file in the repository, like for the other scripts), that's why I opened the issue.

**Comment by cucumberian** [comment]
`scripts/on_env_start.sh: line 43: ./scripts/on_sd_start.sh: Permission denied`
or line 43 in file scripts/on_env_start.sh can be changes on:
```bash ./scripts/on_sd_start.sh```

**Comment by HPPinata** [comment]
should work fine with 00276228cf05de8899424cbe2d91212737db77c4
