### ISSUE TITLE
RFC: "shunt" more system ram to SD when using CPU

### ISSUE THREAD

**Issue by eresposito** [cmdr2/stable-diffusion-ui#554]
**Is your feature request related to a problem? Please describe.**
No issue

**Describe the solution you'd like**
When CPU rendering, is there a way to use more system ram for larger (1024) images. I have no issue waiting for CPU images

**Additional context**
Maybe this is for stable diffusion itself

**Comment by JeLuF** [comment]
The software uses all the available RAM. There is no memory limit configured. Close all other running programs, or make more swap space available.
