### ISSUE TITLE
Add lets encrypt certbot ssl functionality

### ISSUE THREAD

**Issue by securehosting1** [cmdr2/stable-diffusion-ui#559]
**Want to provide images for friends family etc on a ssl domain**
Add SSL to domain set to stable0diffusion-ui 
example: http://super-cool-ai-images.domain.com:9000

**Solution**
https://super-cool-ai-images.domain.com

**Any alternatives?**
Someone said you can setup SSL through Cloudflare but did not manage to do so yet due to a lack of understandable instructions when searching google.
**Additional context**
Would be really cool to have SSL easily setup for the UI of this software, which would help this project get noticed even more.

**Comment by securehosting1** [comment]
> I think this is beyond the capabilities of this project. There are many different home network topologies to consider, and all the solutions I found require a cloud-side component to be running all the time.
> 
> There are projects offering tools to expose local web services to the internet, e.g. https://github.com/localtunnel/localtunnel (open source) or https://ngrok.com/ (commercial, offering a free tier).
> 
> When using such a service, make sure that you enable password protection since SDUI will allow anyone with access to it to fill up your disk space.

Hello, thanks for replying, i am running on a kvm vps server on a website, but want to make it secure etc, i think the other version stable-diffusion-webui may offer SSL functionality so not only the rich people who can pay someone to set up this amazing software on websites.

**Comment by JeLuF** [comment]
For a server installation, I'd recommend to configure a reverse proxy to handle the TLS and certificate update parts, e.g. haproxy, nginx or traefik, and to also implement user authentication using these tools.

**Comment by HPPinata** [comment]
Caddy is extremely easy to set up. A basic https reverse proxy ``/etc/caddy/Caddyfile`` looks like this (and most of it is optional):
```
{
    email    your@mail.net
    #key_type p384 #optional
    #acme_ca  https://acme-staging-v02.api.letsencrypt.org/directory #for testing
    #local_certs #locally signed (for testing or use without a CA)
}

#You can specify a domain or subdomain and certificates will be created automatically.
#With local certs you can even use an IP address (replace domain below with IP).
#Both support limiting the proxy to a port eg. your.domain.net:4444
your.domain.net {
    reverse_proxy localhost:9000
}
```

This is without annotations:
```
{
    email    your@mail.net
}

your.domain.net {
    reverse_proxy localhost:9000
}
```

**Comment by securehosting1** [comment]
I will try again later today using nginx proxy manager. Thanks.

**Comment by securehosting1** [comment]
Solved:

https://online-business-seo-forum.seotraining1.com/discussion/133/create-your-own-ai-images-self-hosted-easy-tutorial-home-or-server-desktop-install-linux/p1?new=1

**Comment by JeLuF** [comment]
Please keep in mind that anyone with access to your SDUI installation can fill your disk and write to any folder that the user running SDUI has access to. It is thus highly recommended to configure password authentication on the reverse proxy.

**Comment by securehosting1** [comment]
> Please keep in mind that anyone with access to your SDUI installation can fill your disk and write to any folder that the user running SDUI has access to. It is thus highly recommended to configure password authentication on the reverse proxy.

Thank you, what would be the easiest way to do that?

**Comment by pjbrunet** [comment]
> > Please keep in mind that anyone with access to your SDUI installation can fill your disk and write to any folder that the user running SDUI has access to. It is thus highly recommended to configure password authentication on the reverse proxy.
> 
> Thank you, what would be the easiest way to do that?

In Nginx, you can do this in the location block...

```
auth_basic            "Restricted Area";
auth_basic_user_file  passfile;
```

To generate the passfile, try this in Bash...
`printf "johnsmith:$(openssl passwd -1 c0mplexpassw0rd)\n" > /etc/nginx/passfile`

That said, I can't get the "ResearchForumOnline" config to work. I get a 502 error. I don't have the "proxy_params" file, etc.

**Comment by pjbrunet** [comment]
Update after two days of trying everything: I made the mistake of doing the proxy_pass to https://localhost instead of http!

The next problem is, Easy Diffusion doesn't use relative pathnames. I want to use a subdirectory for added security. Hopefully Nginx has a solution for that, fingers crossed.
