### ISSUE TITLE
AMD Support ?

### ISSUE THREAD

**Issue by Gadgetroch** [cmdr2/stable-diffusion-ui#579]
Hi,

I'm running on debian bookworm, and i have an RX 6700 XT.

How can i use it with stable-diffusion-ui ?

Thank's

**Comment by manotroll** [comment]
waiting for opencl support via gpu amd
even with the r9 5900X it takes 3 minutes to make an image like this, you can't play

**Comment by Gadgetroch** [comment]
Hi,

I speak about graphic card, not processor

**Comment by CristianPi** [comment]
it worked installing PyTorch  rocm 5.1.1 on the stable diffusion branch (linux) so it should be easy to add support for this

**Comment by GaiusIuliusCaesar** [comment]
Not working on my RX 6500XT either... this is very disappointing as the CPU takes a million years to make an image.

**Comment by jamiecropley** [comment]
Any updates on this? I have two rx 480's in my machine

**Comment by cmdr2** [comment]
Tracking this in https://github.com/cmdr2/stable-diffusion-ui/issues/115

Current status: AMD now works out-of-the-box on Linux, but not yet on Windows
