### ISSUE TITLE
Linux fail to start uvicorn

### ISSUE THREAD

**Issue by Janova89** [cmdr2/stable-diffusion-ui#58]
I think i found a error in on_sd_start.sh that makes fail the uvicorn init.
Tried on my debian 11 Server, installation goes good til the script is called, on line 78 is called the uvicorn server start it raise a trace back because no module fastapi is found. 
The path from the traceback error results to be:

"$INSTALL_DIR/stable-diffusion-ui/stable-diffusion/../ui"

In fact on line 16 the script move inside stable-diffusion, then on line 76 is defined a directory variable:

export SD_UI_PATH=`pwd`/../ui

but it would save:

"$CURRENT_DIR_PATH/../ui"

instead of the intended:

"$CURRENT_DIR_PATH/ui"

that is where server.py is saved.

A simple solution should be add a cd command before exporting the variable:

cd ..

export SD_UI_PATH=`pwd`/ui

I tried to fix locally but on_sd_start.sh is pulled from repository at init, and launching it alone make other things fail. I hope to be helpfull, congrats for the beautiful work.

**Comment by cmdr2** [comment]
Hi @Janova89 Thanks for investigating this! I've adapted your suggestion and pushed an update with https://github.com/cmdr2/stable-diffusion-ui/commit/7d69f4d3edbba97658a3ced760733b0d17e50f44

Please let me know if this continues to fail for you. Thanks
