### ISSUE TITLE
Jpg Quality Extremely Low

### ISSUE THREAD

**Issue by Aaron-G-42** [cmdr2/stable-diffusion-ui#585]
Currently the jpg quality is extremely low, as evidenced by saving the same image as PNG and comparing to the JPG output.

I request either saving as maximum JPG quality which will still be much smaller than PNG or exposing JPG quality setting to the UI.

Thanks for the great tool!

![example](https://user-images.githubusercontent.com/103456098/205071219-4513464e-2a20-4da6-a9e2-08a454c767b7.png)

**Comment by JeLuF** [comment]
You can now change the JPG quality:
![image](https://user-images.githubusercontent.com/5852422/236524403-3f03cb95-a78a-4ca4-a3cd-b677f1874689.png)
