### ISSUE TITLE
Feature request two-parter: Novel/experimental DPM/Karras samplers? Also, OpenJourney model support?

### ISSUE THREAD

**Issue by AdvaitaSprite** [cmdr2/stable-diffusion-ui#587]
### Main request - New Samplers: ### 

I've been experimenting with a variety of different UIs, online & locally installed (though I'm a big fan of this one for many reasons), & I've been discovering that some of the newer samplers which aren't available on stable-diffusion-ui are really, really powerful (especially for intricate, fine details).

So two part question, depending on which solution is more do-able, or perhaps you can implement both:

1. Would it be possible for you to please add some of the new samplers? There's a pretty expansive list of them following line 20 of this sampler file from AUTO1111's webui if that helps (https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/modules/sd_samplers.py), but the main ones I've been testing and really would love to see supported in the near future are [and I guess you can replace the spaces with underscores as needed for file/directory names]:

-DPM++2s a
-DPM++2M
-DPM 2 Karras
-DPM 2 a Karras
-DPM++2s a Karras
-DPM++2M Karras

The ones I've most extensively tried so far are DPM++2s a, DPM++2M, and especially with their respective Karras versions, I've been pretty blown away. However, the sites (e.g. dreamlike.art) where I've been using them are far from ideal for my purposes. I would rather have them accessible on your UI so I can have a local install, no credit limit for generations, the option to queue many items for generation at once.

2. If not (or if it will take a long time to get them added to updates on the back end), is there a simple, reproducible step by step method for adding (not "custom" per se-- not whole new samplers you made yourself-- but "custom" in the sense that they'd be added exclusively to your personal installation) samplers at will? If it would just take a small download &/or adding something to a list in a sampler-related Python code then that would be very worth my while, but at least as things work currently, I have a feeling that because the UI updates automatically from github, anything I'd add the files of my personal installation would be undone upon updating [I was trying to follow directions I found online to add Memory Efficient Attention with xformers library and it seemed like when it auto-updated on launch everything reverted so if you have a solution for that, that would be amazing too; they're reporting 50%-100% increase in generation speed, but that's all at the brink of my technical knowledge].

### ~~Secondary Request/Question: OpenJourney Support~~ ###

P.S. while I'm here, OpenJourney (a StableDiffusion 1.5 implementation trained on Midjourney 4 images) is absolutely blowing me away. It's tremendous; it really does provide some of the benefits of Midjourney 4 (in terms of artistic and stylistic richness, vivid color, consistent textures and edges) to StableDiffusion, ~~so enabling the use of the model (if it doesn't already work; I'm still trying to find it in downloadable .ckpt file format instead of just as a dropdown menu option on a website), or adding a link to a download of it on the github page, or adding it as an optional/default feature upon installation would be arguably even more awesome and game-changing than the new samplers... I'm still trying to find out whether OpenJourney is based off of the 2.0 Clip encoder or the old 1.5 one, or whether there's anything else to it (a new .yaml config file perhaps?), or if it's literally just a training checkpoint I could already put in the "models/stable-diffusion" folder and start using if I could find it (but I only see plus sides to integrating it as a feature, unless it's so unwieldy in terms of storage that it absolutely shouldn't be lumped in by default).~~ Together, DPM++/Karras samplers and OpenJourney would seriously open up a whole world of creative options in stable-diffusion-ui. It's very limiting trying to use them on a site like dreamlike.art and then hitting the credit limit for the hour just as I'm starting to get into a flow, and having to queue them one batch at a time is just a huge time sink, so access through this UI would be a massive boon.

**Acknowledgements**

I was thrilled to see how fast you all have been upgrading the queue, adding new features, support for 2.0 (though my GPU is woefully short of being able to utilize it), etc., and I think expanding the sampler options to keep up with the times (which are evolving oh so rapidly these days, especially in this field) and to render other alternative UIs unnecessary (so I & other users don't need one UI installed for this feature, another for another feature, memberships on different sites for speed, or for access to different samplers) would be a huge level up! Keep up the amazing work.

Thanks for your time and effort, to everyone who is working on the project.

Edit: I do want to just mention-- I eventually found a .ckpt file for OpenJourney [only 2gb too, so not bad at all], and it has worked quite well, though doesn't seem as refined as the results I was getting on PromptHero using OpenJourney for whatever reason [I'd presume some optimization on their back-end]. So support doesn't seem to be an issue! Working with the Elden Ring and James Webb Space Telescope models people have released has also been amazing. Anyway, I retract the second part of this request, but the Karras and DPM++ sampler request remains. Thanks again!

**Comment by cmdr2** [comment]
These samplers have been added in recent versions
