### ISSUE TITLE
Can't install on a fresh Ubuntu 22.04 vm

### ISSUE THREAD

**Issue by tamasberesoebb** [cmdr2/stable-diffusion-ui#594]
**Describe the bug**
downloaded installer
extracted
ran ./start.sh
fails

**To Reproduce**
1. downloaded installer
2. extracted
3. ran ./start.sh
4. fails

**Expected behavior**
I've managed to install it a couple of months ago without issues

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 Server. Freshly installed in a VM. 64GB Ram, Teslpa P4 GPU, 8 vCPU Cores
 - Browser: -
 - Version: 2.4.13

**Additional context**
See log file
root@stablediffusion:~# cd stable-diffusion-ui/
root@stablediffusion:~/stable-diffusion-ui# ./start.sh 
Downloading micromamba from https://micro.mamba.pm/api/micromamba/linux-64/latest to /root/stable-diffusion-ui/installer_files/mamba/micromamba
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  3979    0  3979    0     0   3034      0 --:--:--  0:00:01 --:--:--  7741
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0bin/micromamba
100 5547k  100 5547k    0     0  1156k      0  0:00:04  0:00:04 --:--:-- 1803k
Micromamba version:
1.1.0

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

Empty environment created at prefix: /root/stable-diffusion-ui/installer_files/env
Packages to install: conda

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

conda-forge/noarch                                  10.5MB @   2.9MB/s  4.2s
conda-forge/linux-64                                28.1MB @   4.5MB/s  8.0s

Transaction

  Prefix: /root/stable-diffusion-ui/installer_files/env

  Updating specs:

   - conda

  Package                      Version  Build               Channel                   Size
────────────────────────────────────────────────────────────────────────────────────────────
  Install:
────────────────────────────────────────────────────────────────────────────────────────────

  + _libgcc_mutex                  0.1  conda_forge         conda-forge/linux-64       3kB
  + _openmp_mutex                  4.5  2_gnu               conda-forge/linux-64      24kB
  + brotlipy                     0.7.0  py311hd4cff14_1005  conda-forge/linux-64     354kB
  + bzip2                        1.0.8  h7f98852_4          conda-forge/linux-64     496kB
  + ca-certificates          2022.9.24  ha878542_0          conda-forge/linux-64     154kB
  + certifi                  2022.9.24  pyhd8ed1ab_0        conda-forge/noarch       159kB
  + cffi                        1.15.1  py311h409f033_2     conda-forge/linux-64     292kB
  + charset-normalizer           2.1.1  pyhd8ed1ab_0        conda-forge/noarch        36kB
  + conda                       22.9.0  py311h38be061_2     conda-forge/linux-64       1MB
  + conda-package-handling       2.0.2  pyh38be061_0        conda-forge/noarch       253kB
  + conda-package-streaming      0.7.0  pyhd8ed1ab_1        conda-forge/noarch        17kB
  + cryptography                38.0.4  py311h42a1071_0     conda-forge/linux-64       1MB
  + idna                           3.4  pyhd8ed1ab_0        conda-forge/noarch        57kB
  + ld_impl_linux-64              2.39  hcc3a1bd_1          conda-forge/linux-64     691kB
  + libffi                       3.4.2  h7f98852_5          conda-forge/linux-64      58kB
  + libgcc-ng                   12.2.0  h65d4601_19         conda-forge/linux-64     954kB
  + libgomp                     12.2.0  h65d4601_19         conda-forge/linux-64     466kB
  + libnsl                       2.0.0  h7f98852_0          conda-forge/linux-64      31kB
  + libsqlite                   3.40.0  h753d276_0          conda-forge/linux-64     810kB
  + libstdcxx-ng                12.2.0  h46fd767_19         conda-forge/linux-64       4MB
  + libuuid                     2.32.1  h7f98852_1000       conda-forge/linux-64      28kB
  + libzlib                     1.2.13  h166bdaf_4          conda-forge/linux-64      66kB
  + ncurses                        6.3  h27087fc_1          conda-forge/linux-64       1MB
  + openssl                      3.0.7  h166bdaf_0          conda-forge/linux-64       3MB
  + pip                         22.3.1  pyhd8ed1ab_0        conda-forge/noarch         2MB
  + pycosat                      0.6.4  py311hd4cff14_1     conda-forge/linux-64     114kB
  + pycparser                     2.21  pyhd8ed1ab_0        conda-forge/noarch       103kB
  + pyopenssl                   22.1.0  pyhd8ed1ab_0        conda-forge/noarch       125kB
  + pysocks                      1.7.1  pyha2e5f31_6        conda-forge/noarch        19kB
  + python                      3.11.0  ha86cf86_0_cpython  conda-forge/linux-64      38MB
  + python_abi                    3.11  3_cp311             conda-forge/linux-64       6kB
  + readline                     8.1.2  h0f457ee_0          conda-forge/linux-64     298kB
  + requests                    2.28.1  pyhd8ed1ab_1        conda-forge/noarch        55kB
  + ruamel_yaml                0.15.80  py311hd4cff14_1008  conda-forge/linux-64     325kB
  + setuptools                  65.5.1  pyhd8ed1ab_0        conda-forge/noarch       748kB
  + tk                          8.6.12  h27826a3_0          conda-forge/linux-64       3MB
  + toolz                       0.12.0  pyhd8ed1ab_0        conda-forge/noarch        49kB
  + tzdata                       2022g  h191b570_0          conda-forge/noarch       108kB
  + urllib3                    1.26.13  pyhd8ed1ab_0        conda-forge/noarch       111kB
  + wheel                       0.38.4  pyhd8ed1ab_0        conda-forge/noarch        33kB
  + xz                           5.2.6  h166bdaf_0          conda-forge/linux-64     418kB
  + yaml                         0.2.5  h7f98852_2          conda-forge/linux-64      89kB
  + zstandard                   0.19.0  py311hbe0fcd7_1     conda-forge/linux-64     394kB
  + zstd                         1.5.2  h6239696_4          conda-forge/linux-64     459kB

  Summary:

  Install: 44 packages

  Total download: 62MB

────────────────────────────────────────────────────────────────────────────────────────────

Transaction starting
_libgcc_mutex                                        2.6kB @  23.7kB/s  0.1s
python_abi                                           5.7kB @  46.5kB/s  0.1s
ca-certificates                                    153.9kB @ 906.4kB/s  0.2s
libzlib                                             65.5kB @ 346.7kB/s  0.1s
yaml                                                89.1kB @ 413.9kB/s  0.0s
ld_impl_linux-64                                   691.4kB @   2.5MB/s  0.3s
ncurses                                              1.0MB @   3.8MB/s  0.2s
charset-normalizer                                  36.5kB @ 121.2kB/s  0.0s
zstd                                               459.1kB @   1.5MB/s  0.1s
toolz                                               49.1kB @ 146.8kB/s  0.0s
cffi                                               292.1kB @ 784.6kB/s  0.1s
brotlipy                                           353.6kB @ 887.3kB/s  0.1s
urllib3                                            110.7kB @ 265.1kB/s  0.0s
conda                                                1.3MB @   2.4MB/s  0.2s
libstdcxx-ng                                         4.5MB @   8.1MB/s  0.6s
pip                                                  1.6MB @   2.7MB/s  0.3s
libffi                                              58.3kB @  99.9kB/s  0.0s
libgcc-ng                                          953.8kB @   1.5MB/s  0.2s
idna                                                56.7kB @  84.3kB/s  0.1s
setuptools                                         748.3kB @   1.1MB/s  0.1s
pycosat                                            114.1kB @ 158.9kB/s  0.0s
pyopenssl                                          125.0kB @ 168.8kB/s  0.0s
libuuid                                             28.3kB @  36.6kB/s  0.0s
requests                                            54.6kB @  70.3kB/s  0.1s
libnsl                                              31.2kB @  38.0kB/s  0.1s
tzdata                                             108.1kB @ 130.7kB/s  0.1s
pysocks                                             19.0kB @  22.3kB/s  0.0s
conda-package-handling                             253.2kB @ 278.9kB/s  0.1s
openssl                                              3.0MB @   3.1MB/s  0.4s
bzip2                                              495.7kB @ 497.2kB/s  0.1s
cryptography                                         1.5MB @   1.4MB/s  0.2s
certifi                                            158.7kB @ 149.1kB/s  0.1s
tk                                                   3.5MB @   3.2MB/s  0.5s
libsqlite                                          810.5kB @ 755.9kB/s  0.1s
conda-package-streaming                             17.5kB @  16.2kB/s  0.0s
wheel                                               32.5kB @  29.0kB/s  0.0s
pycparser                                          102.7kB @  91.1kB/s  0.1s
xz                                                 418.4kB @ 369.6kB/s  0.1s
libgomp                                            466.2kB @ 409.8kB/s  0.1s
_openmp_mutex                                       23.6kB @  20.6kB/s  0.0s
readline                                           298.1kB @ 253.6kB/s  0.0s
ruamel_yaml                                        325.0kB @ 272.6kB/s  0.1s
zstandard                                          393.8kB @ 328.2kB/s  0.1s
python                                              37.6MB @  15.7MB/s  2.2s
Linking python_abi-3.11-3_cp311
Linking _libgcc_mutex-0.1-conda_forge
Linking libstdcxx-ng-12.2.0-h46fd767_19
Linking ld_impl_linux-64-2.39-hcc3a1bd_1
Linking ca-certificates-2022.9.24-ha878542_0
Linking libgomp-12.2.0-h65d4601_19
Linking _openmp_mutex-4.5-2_gnu
Linking libgcc-ng-12.2.0-h65d4601_19
Linking libuuid-2.32.1-h7f98852_1000
Linking bzip2-1.0.8-h7f98852_4
Linking ncurses-6.3-h27087fc_1
Linking openssl-3.0.7-h166bdaf_0
Linking xz-5.2.6-h166bdaf_0
Linking libzlib-1.2.13-h166bdaf_4
Linking libnsl-2.0.0-h7f98852_0
Linking libffi-3.4.2-h7f98852_5
Linking yaml-0.2.5-h7f98852_2
Linking readline-8.1.2-h0f457ee_0
Linking libsqlite-3.40.0-h753d276_0
Linking zstd-1.5.2-h6239696_4
Linking tk-8.6.12-h27826a3_0
Linking tzdata-2022g-h191b570_0
Linking python-3.11.0-ha86cf86_0_cpython
Linking wheel-0.38.4-pyhd8ed1ab_0
Linking setuptools-65.5.1-pyhd8ed1ab_0
Linking pip-22.3.1-pyhd8ed1ab_0
Linking pycparser-2.21-pyhd8ed1ab_0
Linking charset-normalizer-2.1.1-pyhd8ed1ab_0
Linking pysocks-1.7.1-pyha2e5f31_6
Linking idna-3.4-pyhd8ed1ab_0
Linking certifi-2022.9.24-pyhd8ed1ab_0
Linking toolz-0.12.0-pyhd8ed1ab_0
Linking ruamel_yaml-0.15.80-py311hd4cff14_1008
Linking pycosat-0.6.4-py311hd4cff14_1
Linking cffi-1.15.1-py311h409f033_2
Linking cryptography-38.0.4-py311h42a1071_0
Linking zstandard-0.19.0-py311hbe0fcd7_1
Linking brotlipy-0.7.0-py311hd4cff14_1005
Linking pyopenssl-22.1.0-pyhd8ed1ab_0
Linking conda-package-streaming-0.7.0-pyhd8ed1ab_1
Linking urllib3-1.26.13-pyhd8ed1ab_0
Linking conda-package-handling-2.0.2-pyh38be061_0
Linking requests-2.28.1-pyhd8ed1ab_1
Linking conda-22.9.0-py311h38be061_2
Transaction finished
/usr/bin/git
git version 2.34.1
/root/stable-diffusion-ui/installer_files/env/bin/conda
conda 22.9.0

Stable Diffusion UI

Downloading Stable Diffusion UI..

Using the main channel

Cloning into 'sd-ui-files'...
remote: Enumerating objects: 10822, done.
remote: Counting objects: 100% (556/556), done.
remote: Compressing objects: 100% (200/200), done.
remote: Total 10822 (delta 393), reused 480 (delta 349), pack-reused 10266
Receiving objects: 100% (10822/10822), 54.45 MiB | 7.95 MiB/s, done.
Resolving deltas: 100% (6808/6808), done.

Hotfixed broken JSON file from OpenAI

Downloading Stable Diffusion..

Cloning into 'stable-diffusion'...
remote: Enumerating objects: 857, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 857 (delta 5), reused 7 (delta 2), pack-reused 841
Receiving objects: 100% (857/857), 97.50 MiB | 14.00 MiB/s, done.
Resolving deltas: 100% (378/378), done.
HEAD is now at 7f32368 Use a specific version of opencv-python

Downloading packages necessary for Stable Diffusion..

***** This will take some time (depending on the speed of the Internet connection) and may appear to be stuck, but please be patient ***** ..

Collecting package metadata (repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/root/stable-diffusion-ui/installer_files/env/lib/python3.11/site-packages/urllib3/response.py", line 761, in _update_chunk_length
        self.chunk_left = int(line, 16)
                          ^^^^^^^^^^^^^
    ValueError: invalid literal for int() with base 16: b''
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/root/stable-diffusion-ui/installer_files/env/lib/python3.11/site-packages/urllib3/response.py", line 444, in _error_catcher
        yield
      File "/root/stable-diffusion-ui/installer_files/env/lib/python3.11/site-packages/urllib3/response.py", line 828, in read_chunked
        self._update_chunk_length()
      File "/root/stable-diffusion-ui/installer_files/env/lib/python3.11/site-packages/urllib3/response.py", line 765, in _update_chunk_length
        raise InvalidChunkLength(self, line)
    urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/root/stable-diffusion-ui/installer_files/env/lib/python3.11/site-packages/requests/models.py", line 816, in generate
        yield from self.raw.stream(chunk_size, decode_content=True)
      File "/root/stable-diffusion-ui/installer_files/env/lib/python3.11/site-packages/urllib3/response.py", line 624, in stream
        for line in self.read_chunked(amt, decode_content=decode_content):
      File "/root/stable-diffusion-ui/installer_files/env/lib/python3.11/site-packages/urllib3/response.py", line 816, in read_chunked
        with self._error_catcher():
      File "/root/stable-diffusion-ui/installer_files/env/lib/python3.11/contextlib.py", line 155, in __exit__
        self.gen.throw(typ, value, traceback)
      File "/root/stable-diffusion-ui/installer_files/env/lib/python3.11/site-packages/urllib3/response.py", line 461, in _error_catcher
        raise ProtocolError("Connection broken: %r" % e, e)
    urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/root/stable-diffusion-ui/installer_files/env/lib/python3.11/site-packages/conda/exceptions.py", line 1129, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/root/stable-diffusion-ui/installer_files/env/lib/python3.11/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/stable-diffusion-ui/installer_files/env/lib/python3.11/site-packages/conda/notices/core.py", line 72, in wrapper
        return_value = func(*args, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^
      File "/root/stable-diffusion-ui/installer_files/env/lib/python3.11/site-packages/conda_env/cli/main_create.py", line 156, in execute
        result[installer_type] = installer.install(prefix, pkg_specs, args, env)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/stable-diffusion-ui/installer_files/env/lib/python3.11/site-packages/conda_env/installers/conda.py", line 50, in install
        unlink_link_transaction = solver.solve_for_transaction(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/stable-diffusion-ui/installer_files/env/lib/python3.11/site-packages/conda/core/solve.py", line 156, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/stable-diffusion-ui/installer_files/env/lib/python3.11/site-packages/conda/core/solve.py", line 199, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/stable-diffusion-ui/installer_files/env/lib/python3.11/site-packages/conda/core/solve.py", line 304, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/stable-diffusion-ui/installer_files/env/lib/python3.11/site-packages/conda/common/io.py", line 86, in decorated
        return f(*args, **kwds)
               ^^^^^^^^^^^^^^^^
      File "/root/stable-diffusion-ui/installer_files/env/lib/python3.11/site-packages/conda/core/solve.py", line 467, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/stable-diffusion-ui/installer_files/env/lib/python3.11/site-packages/conda/core/solve.py", line 1061, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/stable-diffusion-ui/installer_files/env/lib/python3.11/site-packages/conda/core/index.py", line 301, in get_reduced_index
        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/stable-diffusion-ui/installer_files/env/lib/python3.11/site-packages/conda/core/subdir_data.py", line 137, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/stable-diffusion-ui/installer_files/env/lib/python3.11/concurrent/futures/_base.py", line 619, in result_iterator
        yield _result_or_cancel(fs.pop())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/stable-diffusion-ui/installer_files/env/lib/python3.11/concurrent/futures/_base.py", line 317, in _result_or_cancel
        return fut.result(timeout)
               ^^^^^^^^^^^^^^^^^^^
      File "/root/stable-diffusion-ui/installer_files/env/lib/python3.11/concurrent/futures/_base.py", line 456, in result
        return self.__get_result()
               ^^^^^^^^^^^^^^^^^^^
      File "/root/stable-diffusion-ui/installer_files/env/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
        raise self._exception
      File "/root/stable-diffusion-ui/installer_files/env/lib/python3.11/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/stable-diffusion-ui/installer_files/env/lib/python3.11/site-packages/conda/core/subdir_data.py", line 129, in <lambda>
        subdir_query = lambda url: tuple(SubdirData(Channel(url), repodata_fn=repodata_fn).query(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/stable-diffusion-ui/installer_files/env/lib/python3.11/site-packages/conda/core/subdir_data.py", line 142, in query
        self.load()
      File "/root/stable-diffusion-ui/installer_files/env/lib/python3.11/site-packages/conda/core/subdir_data.py", line 207, in load
        _internal_state = self._load()
                          ^^^^^^^^^^^^
      File "/root/stable-diffusion-ui/installer_files/env/lib/python3.11/site-packages/conda/core/subdir_data.py", line 277, in _load
        raw_repodata_str = fetch_repodata_remote_request(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/stable-diffusion-ui/installer_files/env/lib/python3.11/site-packages/conda/core/subdir_data.py", line 527, in fetch_repodata_remote_request
        resp = session.get(join_url(url, filename), headers=headers, proxies=session.proxies,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/stable-diffusion-ui/installer_files/env/lib/python3.11/site-packages/requests/sessions.py", line 600, in get
        return self.request("GET", url, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/stable-diffusion-ui/installer_files/env/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
        resp = self.send(prep, **send_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/stable-diffusion-ui/installer_files/env/lib/python3.11/site-packages/requests/sessions.py", line 745, in send
        r.content
      File "/root/stable-diffusion-ui/installer_files/env/lib/python3.11/site-packages/requests/models.py", line 899, in content
        self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/stable-diffusion-ui/installer_files/env/lib/python3.11/site-packages/requests/models.py", line 818, in generate
        raise ChunkedEncodingError(e)
    requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

`$ /root/stable-diffusion-ui/installer_files/env/bin/conda-env create --prefix env --force -f environment.yaml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/root/stable-diffusion-ui/installer_files/env/bin/conda
             CONDA_PREFIX=/root/stable-diffusion-ui/installer_files/env
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/root/stable-diffusion-ui/installer_files/env/bin/python
               CONDA_ROOT=/root/stable-diffusion-ui/installer_files/env
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                     PATH=/root/stable-diffusion-ui/installer_files/env/bin:/root/stable-
                          diffusion-ui/installer_files/env/condabin:/root/stable-diffusion-ui/in
                          staller_files/env/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bi
                          n:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
         PYTHONNOUSERSITE=1
               PYTHONPATH=/root/stable-diffusion-ui/stable-diffusion:/root/stable-diffusion-
                          ui/stable-diffusion/env/lib/site-packages
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /root/stable-diffusion-ui/installer_files/env
            shell level : 1
       user config file : /root/.condarc
 populated config files : 
          conda version : 22.9.0
    conda-build version : not installed
         python version : 3.11.0.final.0
       virtual packages : __cuda=11.4=0
                          __linux=5.15.0=0
                          __glibc=2.35=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /root/stable-diffusion-ui/installer_files/env  (writable)
      conda av data dir : /root/stable-diffusion-ui/installer_files/env/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /root/stable-diffusion-ui/installer_files/env/pkgs
                          /root/.conda/pkgs
       envs directories : /root/stable-diffusion-ui/installer_files/env/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/22.9.0 requests/2.28.1 CPython/3.11.0 Linux/5.15.0-56-generic ubuntu/22.04.1 glibc/2.35
                UID:GID : 0:0
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: y
Upload successful.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true

EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

ERROR: 'conda env create' failed

Error downloading Stable Diffusion UI. Sorry about that, please try to:
 1. Run this installer again.
 2. If that doesn't fix it, please try the common troubleshooting steps at https://github.com/cmdr2/stable-diffusion-ui/wiki/Troubleshooting
 3. If those steps don't help, please copy *all* the error messages in this window, and ask the community at https://discord.com/invite/u9yhsFmEkB
 4. If that doesn't solve the problem, please file an issue at https://github.com/cmdr2/stable-diffusion-ui/issues

Thanks!

**Comment by JeLuF** [comment]
This looks like a conda bug, and there's not much we can do about that.

A general remark: Please don't run the installer or the stable diffusion UI server as root.

**Comment by tamasberesoebb** [comment]
I've solved this by downloading conda and replacing the included binary in the installer folder
curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
I've replaced this file:
/stable-diffusion-ui/installer_files/mamba/micromamba
Now it works.
