### ISSUE TITLE
Server-side settings for the save folder

### ISSUE THREAD

**Issue by JeLuF** [cmdr2/stable-diffusion-ui#597]
**Is your feature request related to a problem? Please describe.**
On a multi-user-server, it's problematic that the remote users can define a save folder. They can write to any folder on the server that server.py has access to

**Describe the solution you'd like**
config.bat setting that overwrites the user provided save path. If set, the option in the UI is disabled.

**Additional context**
https://discord.com/channels/1014774730907209781/1014774732018683928/1048353853466222602

> Aytee — today,  22:43 
> Just wanted to briefly bump my minor suggestion that I posted before the holiday weekend but got buried since then:
> With my access from multiple devices, I'd love for the ability to set the Auto-Save Images setting/location from the server-side, rather than it being a per-browser setting. It's sometimes hard for me to remember the full file path I use when I'm on my phone or using another computer.
> Even if I could just hard-code the Auto-Save location in one of the launcher batch file or something (like the IP/port settings), that would be super super helpful for me personally.
> I guess there must be a default location path set somewhere, since it always seems to default to "%userprofile%\Stable Diffusion UI", although I can't seem to find it. 
> But the other half of my problem is if I forget to turn on the actual Auto-save toggle too, I queue up a huge batch without it, and then I have to go individually save the images after-the-fact. This is especially annoying if I queued it on a mobile device.

**Comment by xeruf** [comment]
I think it should generally be possible to pre-set options in a file, as I use multiple devices and want roughly the same settings on each.
And maybe rather than disabling the option, users could set a subpath for themselves.

**Comment by xeruf** [comment]
And while we are at it, please default to XDG paths and don't clutter my home directory :)
