### ISSUE TITLE
Suspect that a conda file reference is breaking

### ISSUE THREAD

**Issue by LinkinL0gs** [cmdr2/stable-diffusion-ui#598]
**Describe the bug**
I have been using this wonderful project for a good while now not having any issues whatsoever until a couple weeks ago it simply wouldn't start at all.  I keep always getting: 

```
A subdirectory or file tmp already exists.
The system cannot find the path specified.
Access is denied.
The system cannot find the file G:\Stable.
```
Which is odd since that's not the actual folder where it's kept, it's actually in "G:\Stable Diffusion\stable-diffusion-ui-win64\stable-diffusion-ui"
I did some digging and found a note inside conda_hook.bat, and MAYBE this is related?
```
@REM The file name is conda_hook.bat rather than conda-hook.bat because conda will see
@REM the latter as a 'conda hook' command.
```
I suspect there might be a bug somewhere in the windows 64 toolchain.

**To Reproduce**
Run the Start Stable Diffusion UI.cmd on my computer

**Expected behavior**
Not this, everything was going good til recently

**Screenshots**
![image](https://user-images.githubusercontent.com/97209669/205404176-6bbc1625-5957-43cf-b67d-603e2d0c2412.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit, Ryzen 2700, RTX2080
 - Browser: Can't get that far anymore
 - Version: 

**Additional context**

**Comment by LinkinL0gs** [comment]
Was able to resolve this by simply moving the project folder to the root directory of the drive such that the beginning of any folder references is:
G:\stable-diffusion-ui-win64

**Comment by JeLuF** [comment]
The problem was actually the space character in the path name. Conda can't handle that properly.

**Comment by LinkinL0gs** [comment]
@JeLuF 
Right, that's what I began to suspect after re-reading my comment thread and lead me to try moving the project's folder to the root directory of the drive.  That being said, Did you perhaps mean to say that the _current_ version of conda can't handle spaces in paths?  As this project was working out of that original path no problems for a good long while, or is conda a recent addition? > "G:\Stable Diffusion\stable-diffusion-ui-win64\stable-diffusion-ui"

Eitherway the proper remediation in my opinion would be to check for paths which violate these rules of conda's and provide a more clear and concise message to the end user than simply:

> Access is denied.
>The system cannot find the file G:\Stable

Perhaps an alert like: "Spaces are no longer allowed in the folder names where you are keeping this project, you will need to correct that by either renaming the folder or moving to a folder closer to the root of your drive."  I'm sure that'd be a much better pill to swallow for people.  I say that because I'm certain that this will be even a larger problem for people who keep the project in their "C:\Users\[%USERNAME%]\My Documents\Downloads" folder.  I Hope this helps the project someway as I'd hate to see less windows adoption of it when it's such a wonderful addition to an already vibrant community of Stable-Diffusion users.

**Comment by cmdr2** [comment]
Recent versions of the Windows installer warn the user about spaces. Thanks
