### ISSUE TITLE
Add image resolution to the queue info along other params.

### ISSUE THREAD

**Issue by Seedmanc** [cmdr2/stable-diffusion-ui#603]
**Is your feature request related to a problem? Please describe.**
When loading a large amount of tasks into queue it's easy to forget which options were used if they're not displayed there. I believe the resolution is just as important as the params already listed there, such as the sampler, steps and so on.

**Describe the solution you'd like**
Just add the image sizes like the rest of the info, e.g. **Resolution**: 1024x768

**Describe alternatives you've considered**
I suppose it can be solved using a custom plugin as well. I know there's the button "use these settings" that can be used to view the resolution, but it overwrites current settings, which might be undesirable.

**Comment by JeLuF** [comment]
![image](https://user-images.githubusercontent.com/5852422/236523225-8ec28a02-c98c-41ee-b888-8a6f96bf399a.png)
Image dimensions are now part of the queue info
