### ISSUE TITLE
Can I make NSFW now?

### ISSUE THREAD

**Issue by Archon332** [cmdr2/stable-diffusion-ui#628]
Hello everyone.

Looked at other old NSFW discussions and seen that there is no NSFW block, but also no NSFW on\off button in the settings.
And I tried to make some NSFW picture some times. The first one happened like there is no NSFW filter, but after there was always convenient censoring like lather even when I put it into negative promts and some NSFW tags in prompt. These were disgusting.

So my questions are: does NSFW filter exists now? And if it is, would we disable it in future, or even now by some manipulasions?

In not-NSWF cases this UI works perfect. Glad my friend advised me this. And thanks to creator of this masterpiece and everyone associated with it.

**Comment by TechieCrow** [comment]
Check out [Civitai](https://civitai.com/?types=Checkpoint) for NSFW models to use, I have had success with some of them.

Personally my favourite model is [Hentai-Diffusion](https://github.com/Delcos/Hentai-Diffusion), it's able to generate both NSFW and SFW images very well.

**Comment by Archon332** [comment]
Tried to use Hentai-Diffusion. I like it. Thank you.
