### ISSUE TITLE
Sampler option disappears after opening img2img

### ISSUE THREAD

**Issue by ahroyce** [cmdr2/stable-diffusion-ui#655]
**Describe the bug**
I am using SD 2.4.19 UI and want to use an initial image. after I select the image i noted that the sampler drop down box disappears.

**To Reproduce**
1. Go to 'Browse'
2. Click on 'any image'
3. Scroll down to 'Sampler'
4. the sampler box is gone

**Expected behavior**
I am expecting the sampler box so I can change the sampler being used

**Screenshots**

**Desktop (please complete the following information):**
 - OS: W11
 - Browser: Chrome
 - Version: 108.0.5359.99 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by AssassinJN** [comment]
This is an expected result. ddim is the only sampler supposed to be used for img2img and as such the dropdown is removed.
