### ISSUE TITLE
Grid layout for history results

### ISSUE THREAD

**Issue by ProgrammingLife** [cmdr2/stable-diffusion-ui#660]
**Is your feature request related to a problem? Please describe.**
When I look at the history I wish to see differences more clearly, nearly followed one by one in grid order, let's say in 4 columns instead of one result per one row as it is now.
I wish to have an abillity to compare results one to another when they are placed in more compact mode like it would be in grid layout.

**Describe the solution you'd like**
Grid layout for history results.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by JeLuF** [comment]
There is already a grid layout in place. Your images are probably so large that only one image fits per line. You can use Ctrl-Mousewheel to scale your page and get an overview of the images:
![image](https://user-images.githubusercontent.com/5852422/207870559-380485f5-75e3-40f4-b0ae-880a1967c82f.png)

This will unfortunately also scale all the other elements of the user interface.
