### ISSUE TITLE
add extension 

### ISSUE THREAD

**Issue by alphaleadership** [cmdr2/stable-diffusion-ui#666]
**Is your feature request related to a problem? Please describe.**
can you add a support of https://github.com/AUTOMATIC1111/stable-diffusion-webui extension 

**Describe the solution you'd like**
to use that extension in your code 

**Describe alternatives you've considered**

**Additional context**

**Comment by cmdr2** [comment]
Sorry, but these are two separate UIs, not extensions. If I'm missing any information, please feel free to post and reopen.
