### ISSUE TITLE
Use CPU (not GPU)

### ISSUE THREAD

**Issue by Douglassmn** [cmdr2/stable-diffusion-ui#667]
I cant disable this option. It´s stuck.

**Comment by aivct** [comment]
Wait, by any chance are you also on an intel GPU? Speaking for myself, I think I just realized that's the problem for me.

**Comment by JeLuF** [comment]
> I cant disable this option. It´s stuck.

Which GPU are you using? Only NVidia GPU with 4GB video RAM or more are supported.

**Comment by cmdr2** [comment]
Closing as this is the intended behavior (if no compatible GPU is found). Please feel free to reopen if you have a GPU with greater than 3gb of VRAM. Thanks!

But yes, we can show a helpful message in the UI, if the button has been disabled for this reason.

**Comment by Cyberbutt** [comment]
> > I cant disable this option. It´s stuck.
> 
> Which GPU are you using? Only NVidia GPU with 4GB video RAM or more are supported.

I have NVidia GPU GTX 1080ti 11GB video RAM and it is not supported. Same problem. I cant disable this option. It´s stuck.
