### ISSUE TITLE
Ballpark Download Size

### ISSUE THREAD

**Issue by stylemessiah** [cmdr2/stable-diffusion-ui#677]
A ballpark download size would be at very least be helpful.....so people could decide the potential impact

Did not even try because of this single issue

**Comment by JeLuF** [comment]
As stated in the requirements, the installation needs about 25 GB of disk space. Some of this is compressed, so you can assume that the download size will be about 15 GB.

**Comment by stylemessiah** [comment]
> As stated in the requirements, the installation needs about 25 GB of disk space. Some of this is compressed, so you can assume that the download size will be about 15 GB.

Perhaps you could add this to the README?
