### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by jrodriguez-h** [cmdr2/stable-diffusion-ui#681]
**Describe the bug**
An error that does not allow to download the program

![error](https://user-images.githubusercontent.com/70878299/208602309-9111c10d-ae92-4acf-bad2-2bd9856fdc7d.jpg)

**Comment by JeLuF** [comment]
Are you using any anti-malware, anti-virus, VPN or proxy software?

**Comment by jeanroh89** [comment]
no
