### ISSUE TITLE
Add button to discard or hide individual images

### ISSUE THREAD

**Issue by NiklasRosenstein** [cmdr2/stable-diffusion-ui#682]
**Is your feature request related to a problem? Please describe.**

When you generate a lot of images, it would help a lot if you can filter out undesired results as you spot them. 

**Describe the solution you'd like**

I would like to see a "Discard" button on every image, which will remove or hide it from the results. The button should be usable while new images are still being generated for the same query.

**Comment by sandiMexicola** [comment]
I like this idea.

**Comment by korziner** [comment]
Will remove or hide it from the results? I suggest to remove also from storage, when auto-save configured.
