### ISSUE TITLE
Firefox 102 esr won't start rendering due to failed call of performance.measure

### ISSUE THREAD

**Issue by FAlterSoft** [cmdr2/stable-diffusion-ui#696]
Using the UI on Debian bookworm's  default browser (Firefox 102 esr), the Image generation won't start. Instead, there is a javascript error on performance.measure instruction in engine.js.

**To Reproduce**
1. Open the UI in Firefox
2. Click on 'Make Image'
3. nothing happens
4. Press F12 to open developer tools and go to console
5. See error

**Expected behavior**
The HTTP POST /render should be done.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian bookworm
 - Browser: Firefox 102 esr

**Additional context**
I am not a javascript developer. But it seems this particular call of [performance.measure](https://developer.mozilla.org/en-US/docs/Web/API/Performance/measure) is supported from Firefox 103 (if I got the documentation right) so the problem might be that the default browser of Debian bookworm is "just too old", but keep in mind bookworm is testing and uses Firefox 102 esr which is the latest esr version right now. So the argument of debian always being behind isn't valid in this case.
For me I temporarily removed the whole performance measuring code around the code line mentioned in the error message. I can't fix the problem since I haven't tried to learn javascript yet, but I can remove that code and I'm not really interested in that performance measurement being done there. AKA I commented this out:

File stable-diffusion-ui/ui/media/js/engine.js
Lines 843 to 845

        async post(timeout=-1) {
            performance.mark('make-render-request')
            //if (performance.getEntriesByName('click-makeImage', 'mark').length > 0) {
            //    console.log('delay between clicking and making the server request:', performance.measure('diff', 'click-makeImage', 'make-render-request').duration + ' ms')
            //}
            let jsonResponse = await super.post('/render', timeout)
            if (typeof jsonResponse?.task !== 'number') {

There is probably a fix that will still keep that time measurements intact...

**Comment by cloudscalebytes** [comment]
@FAlterSoft That fixed the issue for me, thanks.
