### ISSUE TITLE
Beta 2.5.1 bug: img2img above 512x512 results in tensor error

### ISSUE THREAD

**Issue by VooDyn** [cmdr2/stable-diffusion-ui#699]
Any img2img attempt with the resolution set higher than 512x512 results in the following error in the UI:

`Error: The size of tensor a (96) must match the size of tensor b (64) at non-singleton dimension 3`

The first value is linked to the resolution entered in the UI.

It happens with all models I have installed, pre- and post 2.0 models.

Log included in the attachments.

[sdlog.txt](https://github.com/cmdr2/stable-diffusion-ui/files/10300297/sdlog.txt)

**Comment by jsuelwald** [comment]
@VooDyn This got fixed now in Beta
