### ISSUE TITLE
No module 'xformers'. Proceeding without it.

### ISSUE THREAD

**Issue by ke1ne** [cmdr2/stable-diffusion-ui#700]
Getting the "No module 'xformers'. Proceeding without it." message on latest Easy Diffusion v2.5.1 (beta)
Did no manual changes in code, etc.
Should I install xformers manually in some way?
P.S. Thank you so much for your project!

1. Run the script as usual via the Start Stable Diffusion UI.cmd
2. Waiting for browser start
3. Getting this message: No module 'xformers'. Proceeding without it
4. UI works, pics generated, etc.

**Expected behavior**
Working xformers?

**Screenshots**
<img width="865" alt="2022-12-25-21-05-47-AVE4sqyx3p" src="https://user-images.githubusercontent.com/8934421/209479578-b43273c1-881b-4410-8d18-bb8eed1ddb71.png">

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome 108
 - Version: Easy Diffusion v2.5.1 (beta)

**Comment by JeLuF** [comment]
This is expected behaviour. The message comes from a library we are using that does support xformers if present, but can also work without it if xformers are not installed. We intend to include xformers in the future, but there are some issues that we need to solve for this to work.

**Comment by ke1ne** [comment]
@JeLuF Oh, I see, thanks! Are any guidelines to install xformers for your gui available?

**Comment by BenjaminX** [comment]
@JeLuF   any updates about xformers library improve procesing time?

**Comment by JeLuF** [comment]
> @JeLuF any updates about xformers library improve procesing time?

xformers improve performance, but at the same time, they break hypernetworks and the samplers become non-deterministic.
