### ISSUE TITLE
WebP image output format

### ISSUE THREAD

**Issue by Fish0s** [cmdr2/stable-diffusion-ui#704]
Can you please add an option to output the images as WebP? This format is so much more efficient and the library for this already exists in Stable Diffusion. Even if it's just though a hidden option available by editing the html file and uncommentating something it would be a great help and would save me lots of disk space without compromising on quality :)

**Comment by JeLuF** [comment]
WebP output format has been added.
![image](https://user-images.githubusercontent.com/5852422/236519918-af86f4b0-b161-43c8-a1f5-f640fec08067.png)
