### ISSUE TITLE
Clicking Stop button doesn't stop the task right away

### ISSUE THREAD

**Issue by iegoshin** [cmdr2/stable-diffusion-ui#731]
**Describe the bug**
When you click 'Stop' button, it doesn't stop right away, instead it tries to finish the current task. I am using CPU mode (AMD card on Ubuntu)

**To Reproduce**
Steps to reproduce the behaviour:
1. Start generating some image
2. You can hear processor fan is spinning up right away
3. Click 'Stop' button
4. It takes about a minute to stop fan from spinning

**Expected behaviour**
I would expect to task stopped right away

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Firefox
 - Version: 108.0.1 (64-bit)

**Comment by JeLuF** [comment]
Can't reproduce. For me, it only completes the current iteration, not the entire image. 
Can you please share the logs of the server?

**Comment by iegoshin** [comment]
Doesn't happen for me any more. I think it happened when I stopped / started the server, didn't refresh the page and added a new generation. Perhaps web socket closed and didn't re-open or something.
