### ISSUE TITLE
Error while trying merging 2 models

### ISSUE THREAD

**Issue by ololiyuki** [cmdr2/stable-diffusion-ui#735]
[Error_Trying_Merge_Models.txt](https://github.com/cmdr2/stable-diffusion-ui/files/10324883/Error_Trying_Merge_Models.txt)

Hello folks!

Trying the feature for merging models as described in "What's new section" of Easy Diffusion, 
I always get the error "positional argument follows keyword argument", as attached in this message.

Any help would be priceless...

Thanks a lot... 

Vincent

**Comment by JeLuF** [comment]
Try to ommit the `ratio=` and `use_fp16=` prefixes:
```py
m0 = 'D:/stable-diffusion-ui/models/stable-diffusion/peterpolach.ckpt'
m1 = 'D:/stable-diffusion-ui/models/stable-diffusion/Double_Exposure_v2.ckpt'
out = 'D:/stable-diffusion-ui/models/stable-diffusion/mergedpolachdouble.ckpt'
merge_models(m0, m1, 0.3, out, True)
```
I moved the pathes to variables for readability, you can pass them directly if you want.

**Comment by ololiyuki** [comment]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\sdkit\train\merge_models.py", line 15, in merge_models
    save_tensor_file(merged, out_path)
  File "D:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\sdkit\utils\file_utils.py", line 16, in save_tensor_file
    return torch.save(data, path, map_location="cpu")
TypeError: save() got an unexpected keyword argument 'map_location'


Get this errors now....

**Comment by JeLuF** [comment]
There is a pull request to fix this bug.  `map_location="cpu"` is wrong here. It needs to be merged to fix this.

Does `merge_models('D:/stable-diffusion-ui/models/stable-diffusion/peterpolach.ckpt', 'D:/stable-diffusion-ui/models/stable-diffusion/Double_Exposure_v2.ckpt', 0.5, 'D:/stable-diffusion-ui/models/stable-diffusion/mergedpolachdouble.safetensors', True)` work?

**Comment by ololiyuki** [comment]
Hi JeLuf...

Well... with '.safetensors' extension, it works like a charm...!

Thanks

**Comment by JeLuF** [comment]
You should use safetensors anyway :-) In contrast to ckpt, it can not contain executable code.
