### ISSUE TITLE
No option for full precision mode on beta channel? Also, "CUDA: 0"

### ISSUE THREAD

**Issue by AdvaitaSprite** [cmdr2/stable-diffusion-ui#740]
I wondered at first if maybe full precision would just be built into the balanced/fast/slow render speed/VRAM usage setting, but even on the highest setting it is still half-precision. I'm loving the beta channel right now because it has what are IMO the best samplers, and the speeds it hits with the "fast" mode selected are unlike anything I've seen before-- so thank you for adding those, & kudos on achieving such speeds without sacrificing quality; it's all very impressive). But it makes it very hard to know which channel to use when one of them has all of that but no full precision mode and the other has none of that, but full precision mode. 

So yeah; I'm not sure whether it's a bug or a mistake or if it's just taking time to code for compatibility between the "half/full precision" toggle and the new "balanced/fast/slow" option. But I didn't see anyone else acknowledging it in issues, & it's definitely been an issue for me, so I wanted to bring it to your attention in case it was an oversight. I am having some other issues on and off, but I think it's necessary to make a separate issue for them if they persist. 
       
One other issue! [Writing the below conclusion reminded me]. From the time I started using this UI 

Thanks! And thanks again for implementing the additional samplers in the beta channel; I don't know if it was in response to my post about them or not but it's awesome that you all got to that quickly! I've already gotten some fantastic results with DPM ++2M in particular, but also the Stability AI solver. I'd rank them up there with DPM 2, DPM 2a, and perhaps DDIM or Heun. Still need to experiment more with Fast, Adaptive, SDE, & 2s ancestral before I can judge against them.  
      
Anyway, I wasn't sure whether to post this as a bug report or a feature request, because I don't know why the full precision option disappears in beta, but I would greatly appreciate the option. Just got a new GPU and I'm very excited about what it can do. OH, PS: that actually reminds me of another issue I keep meaning to ask about. From the first version I ever used, on this UI, under settings where it shows the GPU information, it has always said "CUDA: 0." Before I was using an Nvidia GTX 1050ti (which had something like 700 or 800 CUDA cores. Now I'm using an RTX 3080, with more like 8,000 CUDA cores! But for some reason, with both GPUs, it has always said "CUDA: 0." Is it supposed to read how many cores it's utilizing? Or is it just a binary indicator where 0 = yes and 1 = no or something? It just always read as something showing up wrong to me, but maybe that's what it is.
      
Cheers! Happy New Year.

**Desktop:**
 - OS: Windows 10 Home
 - Browser: Firefox
 - Version: 2.5.4 beta or 2.4.23 is what shows up in the non-beta channel, but it's been crashing so one more reason I haven't been using it

**Comment by JeLuF** [comment]
"CUDA:0" is your first GPU, not the number of CUDA cores it's using. If you'd install both GPUs into your computer, you'd have "CUDA:0" and "CUDA:1". Some accelerator cards like the Tesla M10 will show up as 4 GPUs on a single card, so you'll see CUDA:0 to CUDA:3 on such a system.

The Full Precision option has been removed since there's no advantage in using FP when HP is available. Cards like the 1050 require FP. There is a list of cards for which we enforce FP mode, but for all others, we use HP because it saves a lot of GPU memory.

**Comment by cookingjoe** [comment]
Thanks for the explanation. Is there a way I can manually enable full precision? My card keeps on getting me black images. It was solved when I had the full precision option on using the previous version. Thanks!

**Comment by Kittera** [comment]
I too would like to know if there's a way so I can test something. There's a weird bit in a spreadsheet comparing ML GPUs, which seems to claim that my stepdad's Tesla P100 has dedicated fp16 hardware where my Tesla P40 does not; The p100 is optimized for training, allegedly, and fp16; The p40, for inference, and fp32.

This data comes from TechPowerUp, but it claims my P40's fp16 performance should be 0.183 tflop/s, where my fp32 should be 11.76 tflop/s. It claims his P100's fp16 to be 19.5 tflop/s, and his fp32 should be 9.576 tflop/s. 

So far, I must confess we've been getting similar times, his slightly faster than mine, on same prompts/config drag races we've done.

**Comment by JeLuF** [comment]
On Windows, you can edit `scripts\config.bat` and add a line
```
@set FORCE_FULL_PRECISION=T
```

On Linux, edit `scripts/config.sh` and add a line
```
export FORCE_FULL_PRECISION=T
```
