### ISSUE TITLE
Is there any way to get Highres Fix working in this?

### ISSUE THREAD

**Issue by Bestulo** [cmdr2/stable-diffusion-ui#749]
I'm getting duplicates in my high res 1024x1024 pictures. If I go for 512x512, I get one person with a normal body. If I go for anything higher, I get more than one body, sometimes one person with two torsoes, if taller (768x1280), and most of the time i get two people if it's big but square (1024x1024). I even got two people, and one of them has two torsoes.

I read on reddit that if you apply high res fix you can fix this but i don't know if this ui has this feature. they say it's on a1111's ui but i don't know how to use that one.

**Comment by sandiMexicola** [comment]
Yes, stable-diffusion-ui has this option.  If you hover your mouse over the completed image, you should see a list of options, one of which is something like "upscale"... which does a 4x upscale.  
Or, at least, that is how it works in Windows.  🙂

**Comment by Bestulo** [comment]
Oh, I didn't know they're the same thing! I now see that "highres fix" is just generating at lower size and then upscaling. Thanks :)
