### ISSUE TITLE
Compatibility with AMD Radeon RX 6800M

### ISSUE THREAD

**Issue by Netlex** [cmdr2/stable-diffusion-ui#750]
**Describe the bug**
It does not support AMD series graphics cards, specifically the AMD Radeon RX 6800M model.

**Expected behavior**
Is it possible to enable AMD Radeon RX 6800M graphics card support?

**Desktop (please complete the following information):**
 - OS: Win 11 Pro
 - Browser: Google Chrome
 - Version: latest

**Comment by k2042** [comment]
Yep, especially since there are ways and tutorials how to make it work on AMD GPUs, surely there is already a solution that can just be intergated into this glorious tool?

**Comment by DrRazzz** [comment]
A similar problem with AMD Radeon RX 6800M. I will be grateful to the author if he solves it.

**Comment by cmdr2** [comment]
Tracking this in https://github.com/cmdr2/stable-diffusion-ui/issues/115

Current status: AMD now works out-of-the-box on Linux, but not yet on Windows
