### ISSUE TITLE
Freeze/Hang at "hypernetwork functionality added to cross attention" during install

### ISSUE THREAD

**Issue by PrudentPotato** [cmdr2/stable-diffusion-ui#751]
**Describe the bug**
Install hangs at
"hypernetwork functionality added to cross attention"

Tried multiple times. Hangs at same spot.

**To Reproduce**
_Click to install: Start Stable Diffusion UI.cmd_

**Screenshots**
![2023-01-07 (1)](https://user-images.githubusercontent.com/21150390/211132763-7f83e97d-4837-4d65-a5b7-8d2ef1f0fd86.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64-bit
 - Python: 3.9.12
 - GPU: ASUS VS239 on Radeon RX 580 Series

**Additional context**
Installing on a secondary SSD... Does it have to be C: ?

The instructions are so straight forward... After failing to install AMD gpu instructions multiple times, I tried this one-clicker 😄 

**Thank you for providing this! I would pay for it if it worked for my PC. Can't afford the number of SAAS generations I need.**

I'm curious - is it really freezing at this action, or is it the action proceeding it that it's really freezing on? I'm a newb.

Thanks for your help.

**Comment by PrudentPotato** [comment]
Just tried it on another AMD PC... Interestingly it hung at the same spot.

**I just tried to re-install on the previous PC and it opened a browser windows. Moving further along.** I'll continue to track my progress here in case it helps.

**Comment by PrudentPotato** [comment]
It works!

![a_photograph_of_an_astronaut_riding_a_horse_Seed-3584595_Steps-25_Guidance-7 5](https://user-images.githubusercontent.com/21150390/211133518-bd764598-7740-4580-afdd-42896f95becc.jpeg)

So maybe the bug isn't that it hangs. It just didn't open the browser window automatically.

I'm curious if I had just entered the web address, http://localhost:9000/ if it would have worked.

Great! Thank you! Now to get an NVIDIA GPU 😮‍💨

**Comment by sandiMexicola** [comment]
cool!  😎👍

**Comment by zorrhyena011101** [comment]
I re-install it and even that I can't use it. Keeps freezing at hypernetwork funcionality  added to cross attention, I have Debian 11 and AMD Ryzen 7 5700G

**Comment by JeLuF** [comment]
> I re-install it and even that I can't use it. Keeps freezing at hypernetwork funcionality added to cross attention, I have Debian 11 and AMD Ryzen 7 5700G

Are you using Firefox ESR? If yes, please try to restart the application. If that doesn't fix it, which browser and version are you using?
