### ISSUE TITLE
Green/black image output with NVIDIA T550 Laptop GPU 

### ISSUE THREAD

**Issue by LeChasseur** [cmdr2/stable-diffusion-ui#755]
**Describe the bug**
Using the GPU (NVIDIA T550 Laptop GPU ) produces black images after rendering (green during rendering in preview mode). Seems to be a prblem that exists elswhere too (https://github.com/CompVis/stable-diffusion/issues/69, https://huggingface.co/stabilityai/stable-diffusion-2-1/discussions/9). 

"Use full precision" in v. 2.4.23 produced images as a work around but is not available for beta 2.5.4. Using CPU works but is slow.

During start there is an indication that there is no xformers module:
................................................
PYTHONPATH=/home/yyyy/Downloads/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages
/home/yyyy/Downloads/stable-diffusion-ui/stable-diffusion/env/bin/python
Python 3.8.5
No module 'xformers'. Proceeding without t.`
...............................................

Tried to install xformers which failed:
.............................................
 Collecting xformers
  Using cached xformers-0.0.13.tar.gz (292 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-xidy_vni/xformers_11a78bba741f42e08f453dc18859f257/setup.py", line 239, in <module>
          ext_modules=get_extensions(),
        File "/tmp/pip-install-xidy_vni/xformers_11a78bba741f42e08f453dc18859f257/setup.py", line 157, in get_extensions
          raise RuntimeError(
      RuntimeError: CUTLASS submodule not found. Did you forget to run `git submodule update --init --recursive` ?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed_

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
.........................................

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.1
 - Browser: Chromium Version 108.0.5359.124 , Firefox 
 - Version: Easy Diffusion v2.5.4 (beta), same for 2-4-23

**Comment by JeLuF** [comment]
Can you please open the "Settings" tab, scroll to the bottom of the page, and copy the full name of the graphics card as reported here:
![image](https://user-images.githubusercontent.com/5852422/211224029-d5eabff3-2616-4632-8eec-3778a8114057.png)
There is a list of GPUs for which we enforce full precision and we need to add that card to this list to fix the bug.

Installing xformers might break your installation if not done correctly and is currently not supported. We'll probably install it in one of the next releases, we're currently testing it.

**Comment by LeChasseur** [comment]
Thanks for looking into this issue!
![Bildschirmfoto vom 2023-01-12 12-08-09](https://user-images.githubusercontent.com/1921914/212051946-77d5c1ef-4f5f-4557-ace1-edc6bb3fb3b7.png)
Unfortunately, there is not much information. I looked in the datasheet of the computer and found the following:
Discrete: NVIDIA® T550, 4GB VRAM
Processor Integrated: Intel Iris Xe2
I hope this helps. Maybe the device is still too new.
Thanks for all your work!

**Comment by LeChasseur** [comment]
Works for me, many thanks.
