### ISSUE TITLE
Link Diverted!   

### ISSUE THREAD

**Issue by Kenno9000** [cmdr2/stable-diffusion-ui#756]
The link on: 
https://stable-diffusion-ui.github.io/ 

points to:
https://github.com/CompVis/stable-diffusion

This, and some other "thing" in the start-up/update script must as well.  My much loved SD-UI turned into "Easy Diffusion" without notice.  I'm pretty sure you wouldn't do that! All the best.  ken.

**Comment by JeLuF** [comment]
The link is correct. Stable Diffusion UI is based on Stable Diffusion by CompVis. Stable Diffusion UI is a distribution of Stable Diffusion, just like Ubuntu is a distribution of Linux. 

"Easy Diffusion" is the name used in the Beta version at the moment. The name change is currently being tested. There are many good reasons for such a change. Main advantage of the new name is in my eyes that confusion with other projects can be avoided. Stable Diffusion UI is not the official UI for Stable Diffusion, it's not the only one, and other interfaces have very similar names.
