### ISSUE TITLE
Option to change the visual size of the generated images in the browser

### ISSUE THREAD

**Issue by mortiferus93** [cmdr2/stable-diffusion-ui#760]
Since the latest update new generated images are displayed in a streched way, so I can only see one image at a time. Bevor I could see 6 (3x2) images at once.

Suggestion:
Adding a size slider for the display of the generated images just like the one for the thumpnail size in the Image Modifier menu

**Comment by uswin** [comment]
yes, this issue just occur today, yesterday night this issue not appear yet, but now the generated image is just waaay to big. please kindly revert back to previous size, or make a slider for thumbnail size for generated image. thanks you so much

**Comment by JeLuF** [comment]
Do you have upscaling enabled, or is there also an issue without upscaling?

**Comment by mortiferus93** [comment]
The problem only occures with enabled upscaling

**Comment by uswin** [comment]
today the issue seem to be fixed. i use upscaling 4x, so all is good now

**Comment by mortiferus93** [comment]
disabling the beta "solved" the problem for me

**Comment by JeLuF** [comment]
As uswin mentioned, there was a fix for this a few hours ago. Not exactly reverting to the old behaviour, but I think it's a usable compromise.
