### ISSUE TITLE
GPU cuda:0 with less than 3 GB of VRAM is not compatible with Stable Diffusion

### ISSUE THREAD

**Issue by Deltact** [cmdr2/stable-diffusion-ui#761]
This error pops up forever, it's not much of an issue it's just annoying, a switch to disable warnings in the settings would be nice.
I use the CPU to render my images and it works fine.

Further updates to add, update the readme file memory requirements from 8GB to 12GB minimum (with 4GB Pagefile minimum), this works on a Windows 10 Pro x64 System, Version 22H2 with OS Build 19045.2364

I don't know whether Linux can run SD with simply 8GB due to it's reduced usage of RAM but SD expands to about 15GB at launch, with a 4 GB pagefile, it's fast enough for a SATA 3 HDD to prevent the RAM from overflowing whilst also allowing SD to run.
RAM Usage hovers around 4-6 GB with SD on idle/rendering, it doesn't change much.

16GB for best results, 12GB minimum with a 4GB pagefile to get it started.

**Comment by JeLuF** [comment]
The 3GB warning should only be printed once since two days. Do you still get this message multiple times with a freshly started `Start Stable Diffusion UI.cmd`? If yes, what is the version number shown in the web page?

**Comment by JeLuF** [comment]
I only fixed it in the beta version. I wasn't aware that the same bug already existed back in 2.4.
