### ISSUE TITLE
micromamba.exe is not a valid application

### ISSUE THREAD

**Issue by DeMoN100** [cmdr2/stable-diffusion-ui#770]
I ran the installation and this error popped up but then continued to install some of the files but a few others were coming up as access is denied so it did not fully install.

![ai error](https://user-images.githubusercontent.com/8564572/212501972-1e52ea22-151e-40ab-8d69-9b427eba9827.jpg)
_OS_: Windows 7 Professional SP1

**Comment by JeLuF** [comment]
Windows 7 is EOSL and not supported.

**Comment by DeMoN100** [comment]
I see hopefully that will change in the future.
Also it would be nice if you added the discussons tab to this repo. I would like to ask some questions & find out information. But I don't use discord & i'm not going to make a discord account just to find out what I want to know an alternative is essential.
