### ISSUE TITLE
ERROR : "CUDA out of memory" when turbo mode activated with GPU 3Go

### ISSUE THREAD

**Issue by vincent38wargnier** [cmdr2/stable-diffusion-ui#773]
**Describe the bug**
Hi, I'm getting the following issue when the turbo mode is activated :
![image](https://user-images.githubusercontent.com/33725800/212556426-3840324e-8c31-463e-9ade-58f6531a66eb.png)

![image](https://user-images.githubusercontent.com/33725800/212556411-84afa116-775d-4ab9-8ff4-c6a936c34cf2.png)

**To Reproduce**
1. Try to run the default prompt with the default settings

**Expected behavior**
Should generate the image

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 20H2

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**
![image](https://user-images.githubusercontent.com/33725800/212556647-9e75bf37-6a8e-42e7-a161-7b3bb89042f7.png)

**Comment by JeLuF** [comment]
With only 3GB of VRAM, you need to disable turbo mode in the settings, and disable face correction and upscalers.

**Comment by vincent38wargnier** [comment]
Yeah, I thought it was a bug due to the way it popped to me sorry.
