### ISSUE TITLE
Wont recognize custom models

### ISSUE THREAD

**Issue by EvilleEverett** [cmdr2/stable-diffusion-ui#787]
I love this GUI, thank you so much for your work. I(ve downloaded a few CKPT files and Ive put them in the model folder that says "Put custom models here" ...then I refresh, restart, etc but the only model option in the drop down menu is still sd-v1-4. I tried everything I could think of but Im not super tech-y. Im sure theres got to be a simple fix.... Help?

**Comment by JeLuF** [comment]
Which folder exactly did you place the models in?
It should be sufficient to reload the web page, a restart of the backend application is not required.

On my system, it looks like this:
![image](https://user-images.githubusercontent.com/5852422/213547018-27349ee3-da12-4811-bac0-6ab9291de1dd.png)
Do you spot any differences?

**Comment by EvilleEverett** [comment]
Ok I found on the command screen, it's seeing the model I added but it's still not showing in GUI. Can you tell from this screenshotSent from my T-Mobile 5G Device
-------- Original message --------From: JeLuF ***@***.***> Date: 1/19/23  1:59 PM  (GMT-06:00) To: cmdr2/stable-diffusion-ui ***@***.***> Cc: EvilleEverett ***@***.***>, Author ***@***.***> Subject: Re: [cmdr2/stable-diffusion-ui] Wont recognize custom models (Issue #787) 
Which folder exactly did you place the models in?
It should be sufficient to reload the web page, a restart of the backend application is not required.
On my system, it looks like this:

Do you spot any differences?

**Comment by JeLuF** [comment]
The screen shot didn't make it. Can you try to send the screenshot via the web page instead via mail?

**Comment by EvilleEverett** [comment]
![326421156_703280207950886_1461760199425803854_n](https://user-images.githubusercontent.com/123034254/213810129-fa734964-be57-45c0-aceb-7ae0d759f282.jpg)
You can see where it saw 2 CKPT files (none infected) but Im guessing it has something to do with the Cache allocation being smaller than the reserve request? When it comes to this stuff , python-cache-cuda? Im totally lost. Im more an artist than tech specialist. I love Easy Diffusion and hope to keep using it and sharing it with others :)

**Comment by JeLuF** [comment]
You can use `Windows-Key + Shift + S`  in Windows to create screenshots, and then you can paste them directly into e.g. github.

Can you open this in your browser: http://localhost:9000/get/models and copy me the entire text that you get back?

**Comment by EvilleEverett** [comment]
> You can use `Windows-Key + Shift + S` in Windows to create screenshots, and then you can paste them directly into e.g. github.
> 
> Can you open this in your browser: http://localhost:9000/get/models and copy me the entire text that you get back?

{"active":{"stable-diffusion":"sd-v1-4","vae":"","hypernetwork":""},"options":{"stable-diffusion":["sd-v1-4"],"vae":["vae-ft-mse-840000-ema-pruned"],"hypernetwork":[]}}

**Comment by EvilleEverett** [comment]
BTW I REALLY appreciate your attention on this. Ive been trying to figure this out for a couple of months on my own before I posted here. I tried asking other places with no response. I tried help guides and tried figuring it out on my own to no avail. Youre a saint. Thank you.

**Comment by JeLuF** [comment]
Can you please open your Windows Explorer, navigate to `C:\stablediff\stable-diffusion-ui\models\stable-diffusion` and make a screenshot of that?

**Comment by EvilleEverett** [comment]
![image](https://user-images.githubusercontent.com/123034254/213886408-0dfcff4e-29cb-4641-9caf-e0ba0c7e8592.png)

**Comment by EvilleEverett** [comment]
I think maybe I found the issue... This must be a different place.... 
![image](https://user-images.githubusercontent.com/123034254/213886575-52a67f32-8ea2-4234-a861-9381e13be6b1.png)

**Comment by JeLuF** [comment]
You named the model like the built-in model, so you will only see the name once in the drop down. Rename `sd-v1-4.ckpt`  and it should show up.

**Comment by EvilleEverett** [comment]
> You named the model like the built-in model, so you will only see the name once in the drop down. Rename `sd-v1-4.ckpt` and it should show up.

Im not sure how or why but I had two istalls in my PC, separate program folders. I had been loading the files into the one that that was not activated by the start button. I moved my CKPT file to the SD folder of the one that runs with the start button and it worked perfectly. I had no idea I had 2 copies of Easy Diffusion in my PC. I had a feeling it was a PICNIC error. (Problem In Chair,Not In Computer). Thank you again, I would not have discovered this without your email this morning!
