### ISSUE TITLE
Is it any way to load sd models from custom directory?

### ISSUE THREAD

**Issue by ke1ne** [cmdr2/stable-diffusion-ui#796]
Hi, guys, I would like to load (at least) "main" ckpt/safetensors models from another directory, outside of the UI's files. Is it possible? Or just I missed it?
Thank you!

**Comment by paolodalprato** [comment]
I agree with this request

**Comment by JeLuF** [comment]
You can use the windows `mklink` tool to create links to individual files or entire folders.

**Comment by ke1ne** [comment]
> You can use the windows `mklink` tool to create links to individual files or entire folders.

Indeed. Thank you!
