### ISSUE TITLE
Incorrectly interpreted prompt weight inside brackets

### ISSUE THREAD

**Issue by Bielecki** [cmdr2/stable-diffusion-ui#799]
**Describe the bug**
When you type token with weight in brackets it captures bracket along with weight:
```
09:33:23.447 WARNING cuda:0 Warning: '0.6),' is not a value, are you missing a space?   prompt_parser.py:55
09:33:23.499 WARNING cuda:0 Warning: '0.2),' is not a value, are you missing a space?   prompt_parser.py:55
```
I am not sure tho if it just ignores the token, ignores the weight or is it just a warning and everything works fine.

**To Reproduce**
1. Start generating image with prompt like `(sunny:0.6), landscape`
2. Open console window and the warning will be there

**Expected behavior**
It should separate numbers and dot from another punctuation marks, or just print a warning that you should use brackets OR weight (if I understood Writing Prompts wiki correctly).

**Comment by JeLuF** [comment]
That's not how `:` works in Stable Diffusion UI. You can't limit its effect to only the part in brackets. I updated the wiki page:

* Instead of using brackets, you can also provide the importance ("weight") as numbers: `girl on a swing:1.2 green grass:1.0 pink trousers:0.8`

    The first weight impacts the entire beginning of the prompt. In the above example, `girl on a swing` has a weight of 1.2, `green grass` has a  weight of 1.0 and `pink trousers` has a weight of 0.8.

    The weight acts a separator, so you don't need a comma behind it. There *must* be a space character after the weight. If you use a comma or a bracket, you will get a warning like `WARNING cuda:0 Warning: '2.0,' is not a value, are you missing a space?`

There is a new parser in a test phase that will be more powerful and that will also understand things like `(sunny:0.6)`, but that will take some more time.

**Comment by rmaiabr** [comment]
> That's not how `:` works in Stable Diffusion UI. You can't limit its effect to only the part in brackets. I updated the wiki page:
> 
> * Instead of using brackets, you can also provide the importance ("weight") as numbers: `girl on a swing:1.2 green grass:1.0 pink trousers:0.8`
>   The first weight impacts the entire beginning of the prompt. In the above example, `girl on a swing` has a weight of 1.2, `green grass` has a  weight of 1.0 and `pink trousers` has a weight of 0.8.
>   The weight acts a separator, so you don't need a comma behind it. There _must_ be a space character after the weight. If you use a comma or a bracket, you will get a warning like `WARNING cuda:0 Warning: '2.0,' is not a value, are you missing a space?`
> 
> There is a new parser in a test phase that will be more powerful and that will also understand things like `(sunny:0.6)`, but that will take some more time.

Thank you to your answer. It help me a lot and solved me a question

**Comment by spiralofhope** [comment]
Could you confirm if this is closed because

- there is a new parser which allows a comma now, 
- or closed/invalid because it's currently working as intended and the documentation describes the correct usage?

**Comment by JeLuF** [comment]
It's closed because it's currently working as intended and the documentation describes the correct usage.
