### ISSUE TITLE
Work with AMD CPUs

### ISSUE THREAD

**Issue by denversasha** [cmdr2/stable-diffusion-ui#804]
Im using an AMD CPU. When I run this installer it does not recognize my GPU and renders solely with CPU.

**Comment by Icomefrompast** [comment]
I have the same problem, if you find the solution, tell me here.
Thanks.
I will do the same.

**Comment by Icomefrompast** [comment]
![imagen](https://user-images.githubusercontent.com/123849074/215300927-71480b88-3264-4983-a495-d3fcea25a5f0.png)

**Comment by havokas90** [comment]
same

**Comment by risharde** [comment]
Same here, won't ever switch to Nvidia either - totally need AMD GPU working - I'm digging in but I doubt I can be much use integrating this - it's rocket science for me, hoping one of you with the talent will get this in!

**Comment by 0142929** [comment]
we really hope that there will be support for amd radeon cards.
my rx 6650 feel very lonely, and the processor does it under heavy load very slowly...
thanks.

**Comment by cmdr2** [comment]
Tracking this in https://github.com/cmdr2/stable-diffusion-ui/issues/115

Current status: AMD now works out-of-the-box on Linux, but not yet on Windows
