### ISSUE TITLE
How much space it all takes would be nice to know beforehand

### ISSUE THREAD

**Issue by apollolux** [cmdr2/stable-diffusion-ui#805]
**Is your feature request related to a problem? Please describe.**
Some advance notice of how much space the final Stable Diffusion + UI setup takes on the given drive would be nice to know before hand.

**Describe the solution you'd like**
A simple minimum storage requirements and preferred storage requirements like every other proper installer shows beforehand. Other minimum specs besides GPU would be helpful, like RAM or CPU for CPU-only mode.

**Describe alternatives you've considered**
There are none.

**Additional context**
I thought the base install would take ten gigs, maybe twelve and change at the most, before adding third-party models and datasets. Imagine my surprise to see the grand total be more than twenty gigs. None of this is advertised here nor does it even say go to the base Stable Diffusion site to find out these numbers.

Edit: Apparently, the readme has this info, but the website at this time currently does not.

**Comment by sandoba** [comment]
The main page at https://github.com/cmdr2/stable-diffusion-ui already lists the following under "System Requirements": "**Minimum 8 GB of RAM and 25GB of disk space.**". Realistically including external models and custom models 50+ GB should be available.

**Comment by apollolux** [comment]
@sandoba While you are correct that the readme on the github project displays this info, the main website does not. In fairness, I probably should have specified the website instead of the readme.

**Comment by cmdr2** [comment]
Has been updated in the website as well - https://stable-diffusion-ui.github.io/docs/installation/

Thanks
