### ISSUE TITLE
Error: CUDA out of memory. without Turbo mode

### ISSUE THREAD

**Issue by Bogieloo** [cmdr2/stable-diffusion-ui#806]
**Describe the bug**
The software works as intended but every 2~3 prompts i get the error

Error: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 4.00 GiB total capacity; 3.35 GiB already allocated; 0 bytes free; 3.40 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

in which I DO have turbo mode off by default, it triggers randomly and the software stops working after it, could be related to changing a certain setting but undoing doesn't fix

**To Reproduce**
1. do normal prompts

**Expected behavior**
Process the prompt into an image

![image](https://user-images.githubusercontent.com/99389439/215330826-59d0f94a-b2f2-4b0a-8c28-3539bd350780.png)

**Desktop (please complete the following information):**
 - OS: **Windows 11 Version 22H2** (Host & User)
 - Browser: Brave
 - Version: **Brave 1.47.186 Chromium: 109.0.5414.119 (Official Build) (64-bit)** (Host & User)

**Additional context**
Changing the settings every way possible doesn't fix anything, Specsheet:

CPU: Intel i5-12450H (Host & User)
GPU: 1650 (Host) 3070 (User)
Ram: 16GB (Host & User)
Disk: 1Tb M.2 SSD (Host & User)

**Comment by Bogieloo** [comment]
Update: it may refunction after waiting for a long time

**Comment by Bogieloo** [comment]
Update: it appears to occur very more frequently when having an initial image

**Comment by Anthonyg5005** [comment]
I'd recommend using your 3070 instead of the 1650, the model you're using seems to require more VRAM than what's on the card

**Comment by Bogieloo** [comment]
> I'd recommend using your 3070 instead of the 1650, the model you're using seems to require more VRAM than what's on the card

I didn't know different models had different requirements, Tysm!
