### ISSUE TITLE
Clarification re Windows portable installation

### ISSUE THREAD

**Issue by apollolux** [cmdr2/stable-diffusion-ui#810]
**Is your feature request related to a problem? Please describe.**
The instructions for Windows basically say extract the zip to a location (preferably a drive root) and run the cmd file. On first run, it will download all the required files and such and by default launch the UI in the default browser at the end. A dialog asking about network permissions for Python will likely appear on this first run. Later executions of the cmd file will check for updates and then launch the UI. Uninstalling is said to be simply removing the stable-diffusion-ui directory.

If everything is self-contained, can SD-UI be moved to an external drive (an SD/MicroSD or USB drive of appropriate size) after everything is set up and run from there on later executions as if it was any other "portable" self-contained Windows program, assuming its Python is given permission to run on the network?

**Describe the solution you'd like**
Clarification on whether SD-UI can be run "portably" after initial setup, and possibly language added to the readme/docs and website to that effect.

**Describe alternatives you've considered**
Not sure if there are Windows alternatives for running Stable Diffusion with a UI "portably."

**Additional context**
While I understand that I could have SD-UI running on one computer and make it available to the home network, there are times I'd rather not do that and instead have a computer that has better specs but not the same user permissions run it off an external drive.

**Comment by JeLuF** [comment]
We think that the installation is portable, as long as the drive that you use uses NTFS as file system type. We didn't do intensive testing though.

**Comment by apollolux** [comment]
Only NTFS? No ExFAT? I'm down for running the experiment myself, I just want to confirm if an existing drive that's ExFAT formatted that I know supports large files could work in place of NTFS or if particularities of NTFS formatting disqualify even ExFAT from this experiment and I'd have to prepare another external drive for it that's specifically NTFS formatted.

**Comment by JeLuF** [comment]
ExFAT doesn't support symlinks, which conda uses.
