### ISSUE TITLE
Segfault when loading some models

### ISSUE THREAD

**Issue by Technologicat** [cmdr2/stable-diffusion-ui#812]
**Describe the bug**

The Easy Diffusion (2.5.12 beta) server crashes with a segmentation fault when loading some models (`.safetensors` or `.ckpt`), whereas other models work just fine.

**To Reproduce**
1. Install some more models into `stable-diffusion-ui/models/stable-diffusion/`.
   - Known **crashing** models:
     - SD 2.1 (`v2-1_768-ema-pruned`), uses v-prediction mode. From [here](https://huggingface.co/stabilityai/stable-diffusion-2-1).
     - The character art model Art & Eros, based on SD 1.5, uses eps-prediction mode. Beside character art, this model is also capable of producing NSFW results, so no link here.
   - Known **NOT crashing**  models:
     - SD 1.4 (default)
     - SD 1.5 (`v1-5-pruned-emaonly`), from [here](https://huggingface.co/runwayml/stable-diffusion-v1-5).
     - The anime model Anything v3.0 (`Anything-V3.0-pruned`), based on SD 1.5 according to [its CivitAI summary](https://civitai.com/models/66/anything-v3).
3. Start Easy Diffusion (`bash start.sh`)
4. In the UI, click on `Image Settings`
5. Click on the `Model` dropdown, and choose a model that is known to crash.
6. Click on the `Make image(s)` button. Easy Diffusion starts loading the model onto the GPU.
7. The Easy Diffusion server crashes. A segfault error message appears in the terminal (the process ID will vary):

```
./scripts/on_sd_start.sh: line 297:  9214 Segmentation fault      (core dumped) uvicorn main:server_api --app-dir "$SD_UI_PATH" --port ${SD_UI_BIND_PORT:-9000} --host ${SD_UI_BIND_IP:-0.0.0.0} --log-level error
```

**Expected behavior**
Any model should load without crashing the program. :)

**Desktop** (actually laptop):
 - OS: Linux Mint 21 Cinnamon (based on Ubuntu 22.04 Jammy Jellyfish)
 - Version:
   - Easy Diffusion 2.5.12 beta (latest as of 31 January 2023)
   - NVIDIA driver 525.78.01 (classical proprietary driver)
   - Linux kernel 5.15.0-58-generic
 - GPU: NVIDIA Corporation GA104 [Geforce RTX 3070 Ti Laptop GPU] (with 8 GB VRAM)
   - `nvidia-smi` reports CUDA 12.0

**Additional context**
I have checked the other bug reports here, and while some crashes have been reported, this one seems new.

This crash only occurs with some GPUs. When tested on another laptop with an NVIDIA Corporation TU106GLM [Quadro RTX Mobile / Max-Q] (with 6 GB VRAM) - with the same versions of Easy Diffusion, OS, NVIDIA driver and Linux kernel - the same models load correctly. For that machine, `nvidia-smi` also reports CUDA 12.0.

All the model files are virus-free according to both CivitAI (where applicable) and Easy Diffusion itself.

I traced where the crash occurs in the Python code by adding some `log.info` calls:

- Starting at `load_model` in `stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages/sdkit/models/model_loader/__init__.py`, it calls:
- `load_model` in `stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages/sdkit/models/model_loader/stable_diffusion/__init__.py`, which crashes on the line:
- `_, _ = model.load_state_dict(sd, strict=False)`
- where `load_state_dict` is defined at
`stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages/torch/nn/modules/module.py:1440`.

The MRO of `LatentDiffusion` looked rather long and there are many `load_state_dict` methods defined in various packages installed in the venv, so I traced this via `inspect.getsourcefile` and `inspect.getsourcelines` on the actual `model` instance.

The crash occurs when loading the actual latent diffusion model; it doesn't matter which VAE model is chosen.

If `Auto-Save Settings` is enabled in the UI, then once the error has occurred, Easy Diffusion will crash every time it is started, because it tries to load the crashing model. To recover from this and make Easy Diffusion usable again, there are two options:

 - Option **a**: Rename or move the crashing model file so that Easy Diffusion won't find it, and will default back to SD 1.4.
 - Option **b**: Start Easy Diffusion, and quickly before the crash occurs, pick some other model, and click on the `Make image(s)` button. This will autosave the settings. The next time Easy Diffusion starts, it will load the model picked here.

**Comment by Technologicat** [comment]
Tracing this a bit further:

- The crash occurs inside the `load` helper function (defined inside the mentioned `load_state_dict`), in the private method `_load_state_dict`.
- The private method loops over `local_state`, and crashes on the line `param.copy_(input_param)`, when processing the `param` for the key `"model.diffusion_model.time_embed.2.weight"`. The offending key is the same for both of the crashing models, so whatever is causing this, it seems unrelated to the inference mode.

I suppose the next step is to track down what type `param` is, and dig deeper...

Also, forgot to mention originally, but to check data integrity, I also `sha1sum -b`'d the checkpoints on both machines, and the checksums match - so both machines are loading the exact same data, with the exact same code.

**Comment by Technologicat** [comment]
Just one more addition:

 - The `param` in question is `Parameter` from `stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages/torch/nn/parameter.py`.
 - The `copy_` method is inherited from `Tensor` defined in `stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages/torch/_tensor.py`, which in turn inherits it from `torch._C._TensorBase` (or some layer below that).

So it seems that to trace this further, we'd have to dig into the C layer of PyTorch. For me, that's a bit too much effort.

The thought comes to mind, the RTX 3070 Ti mobile is a newer GPU than the Quadro RTX Mobile. So maybe it needs a newer version of PyTorch?

The venv has PyTorch 1.11.0 (according to `pip list` in the developer console), while the latest stable is 1.13.1.

Is it safe to upgrade, or will doing so bork the venv?

(Asking since I'm not a PyTorch user, so I have no idea of possible API changes.)

**Comment by Technologicat** [comment]
For the record, I tested the crashing models (including the official SD 2.1) also on AUTOMATIC1111's UI, and they work just fine there.

As of early February 2023, AUTOMATIC1111's UI uses torch 1.13.1+cu117 and torchvision 0.14.1+cu117, which are both newer than those in the Easy Diffusion beta: torch 1.11.0 and torchvision 0.12.0. So this indeed seems a PyTorch and/or CUDA version compatibility issue with the RTX 3070 Ti mobile GPU, not a bug in Easy Diffusion itself.

@cmdr2, please advise: shall I close this, and open another issue requesting to upgrade the torch and torchvision versions used by Easy Diffusion, for compatibility with the 30xx series GPUs?

**Comment by cmdr2** [comment]
I apologize for missing this issue. Torch versions can be updated without an issue, the newer installations install 1.13.1 on Windows and Mac, and Torch 2 on Linux.

**Comment by Technologicat** [comment]
Ok. Thank you!
