### ISSUE TITLE
"Stop use these settings''

### ISSUE THREAD

**Issue by Archon332** [cmdr2/stable-diffusion-ui#815]
When I copied prompt for my comrades, before prompt was inscription "Stop use these settings". What is it complaining about?

Sample: "Waiting  Stop Use these settingshighly detailed, digital painting, HDRI, masterpiece, smooth, sharp focus, illustration, golden ratio, (1girl, 1boy, Kurosawa Dia \(love live! sunshine)\, long hair, black hair, green eyes, hairclips, blunt bangs. etc)"

**Comment by Michyrr** [comment]
"Use these settings" and "Stop" are buttons that the UI uses. You just copied them accidentally when you copied the prompt.

**Comment by xeruf** [comment]
close please :)

**Comment by Archon332** [comment]
Done!
