### ISSUE TITLE
Installing Stable Diffusion on Linux Mint Error

### ISSUE THREAD

**Issue by SharkyGoChompChomp21** [cmdr2/stable-diffusion-ui#82]
I tried Installing Stable Diffusion V2 on Linux Mint again & again and here's what Error I got. I'm a BIG Noob so explain like I'm Five!

__________________________________________________________________________________________________________

Stable Diffusion UI

Stable Diffusion UI's git repository was already installed. Updating..
HEAD is now at 051ef56 Merge pull request #79 from iJacqu3s/patch-1
Already up to date.
Stable Diffusion's git repository was already installed. Updating..
HEAD is now at c56b493 Merge pull request #117 from neonsecret/basujindal_attn
Already up to date.

Downloading packages necessary for Stable Diffusion..

***** This will take some time (depending on the speed of the Internet connection) and may appear to be stuck, but please be patient ***** ..

WARNING: A space was detected in your requested environment path
'/home/sharky/Desktop/Stable Diffusion/stable-diffusion-ui/stable-diffusion/env'
Spaces in paths can sometimes be problematic.
Collecting package metadata (repodata.json): done
Solving environment: done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(730): An error occurred while installing package 'defaults::cudatoolkit-11.3.1-h2bc3f7f_2'.
Rolling back transaction: done

LinkError: post-link script failed for package defaults::cudatoolkit-11.3.1-h2bc3f7f_2
location of failed script: /home/sharky/Desktop/Stable Diffusion/stable-diffusion-ui/stable-diffusion/env/bin/.cudatoolkit-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: 
stderr: Traceback (most recent call last):
  File "/home/sharky/Desktop/Stable Diffusion/stable-diffusion-ui/installer/bin/conda", line 12, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'
Traceback (most recent call last):
  File "/home/sharky/Desktop/Stable Diffusion/stable-diffusion-ui/installer/bin/conda", line 12, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'
/home/sharky/Desktop/Stable Diffusion/stable-diffusion-ui/stable-diffusion/env/bin/.cudatoolkit-post-link.sh: line 3: $PREFIX/.messages.txt: ambiguous redirect

return code: 1

()

Error installing the packages necessary for Stable Diffusion. Please try re-running this installer. If it doesn't work, please copy the messages in this window, and ask the community at https://discord.com/invite/u9yhsFmEkB or file an issue at https://github.com/cmdr2/stable-diffusion-ui/issues

________________________________________________________________________________________________________

Hope this helps someone!

**Comment by SharkyGoChompChomp21** [comment]
I decided to rename my folder where I house the stable-diffusion-ui from "Stable Diffusion" to "StableDiffusion", Simply removing that space decluttered a lot of the terminal junk text when I try to run Stable Diffusion.

I still get an error though, but it feels like progress since it's a different error

From my understanding the terminal is trying to find conda but sees it has no directory, (Which I thought it would make it on it's own). Could this be the error?

Here's the Error I got

____________________________________________________________________________________________________

Stable Diffusion UI

Stable Diffusion UI's git repository was already installed. Updating..
HEAD is now at 051ef56 Merge pull request #79 from iJacqu3s/patch-1
git: 'remote-https' is not a git command. See 'git --help'.
Stable Diffusion's git repository was already installed. Updating..
HEAD is now at c56b493 Merge pull request #117 from neonsecret/basujindal_attn
git: 'remote-https' is not a git command. See 'git --help'.


Downloading packages necessary for Stable Diffusion..


***** This will take some time (depending on the speed of the Internet connection) and may appear to be stuck, but please be patient ***** ..

installer/etc/profile.d/conda.sh: line 34: /home/sharky/Desktop/Stable Diffusion/stable-diffusion-ui/installer/bin/conda: No such file or directory


Error installing the packages necessary for Stable Diffusion. Please try re-running this installer. If it doesn't work, please copy the messages in this window, and ask the community at https://discord.com/invite/u9yhsFmEkB or file an issue at https://github.com/cmdr2/stable-diffusion-ui/issues

___________________________________________________________________________________________________________________________

I really feel like I'm getting much closer to solving this issue

**Comment by is0lated** [comment]
I had the same issue. I deleted everything and started again in a folder without a space in its name. I think if you change the name of the folder after getting part way through the install, the old folder name is stored in a couple of places.

Basically, delete everything and start again making sure there's no spaces in the path and everything should work. Or at least it did for me.

**Comment by SharkyGoChompChomp21** [comment]
Okay I'm gonna try Deleting the entire folder and start again
Thank you
I will tell you what happens next

**Comment by SharkyGoChompChomp21** [comment]
I GOT IT TO WORK!!! well I installed it. I typed in a text for stable diffusion to generate and it crashed my computer this is what I mean by it worked.
What fixed the problem was reinstalling stable diffusion again after deleting it.
I renamed my old folder where I had extracted stable diffusion.  (From "Stable Diffusion" to "StableDiffusion) (Adding a space in the name of the folder where the file is extracted to just messes up the whole install).

Here's exactly what I did for anyone having the same issue. I'm using linux mint

1) I went to https://github.com/cmdr2/stable-diffusion-ui#installation
2) Scrolled down to the installation section
3) Clicked on the highlighted "for linux" text 
4) It downloaded a file named stable-diffusion-ui-linux
5) I Opened it
6) I Dragged the folder named "stable-diffusion-ui" (From the File I downloaded) into another folder I made on my desktop named StableDiffusion
7) Don't put a space in the folder's name. (My Mistake was naming this folder on my desktop "Stable Diffusion" with a space instead of "StableDiffusion" with no space. Otherwise it confuses the terminal when you install it.)
8) At this step I should have named the folder correctly (With No Spaces!), and the folder should contain "stable-diffusion-ui" inside it (The one from the downloaded file after I open said downloaded file)
9) I right clicked on the folder named "stable-diffusion-ui" and hovered over to "open in terminal" and clicked it. Note I did not hover over to the "open with" option since that's not where the terminal option is located, my stupid ass did that as you can see from my earlier posts.
10) It should open the terminal with "[color=#0080FF]~/Desktop/StableDiffusion/stable-diffusion-ui[/color]$" in blue color. That's the only difference from when I otherwise open the terminal normally.
11) After it's open I typed into the terminal "./start.sh" and pressed enter.
12) Wait, it will show nothing happing for the 1st 5-10 seconds and then the text starts running (The super hacker geeky text that no Noob understands)(You know, terminal does all that terminal installation text shit).
13) Keeping waiting as the text keeps running (This is how it's installing) till it finishes installing.
14) Once it's done, the terminal opened another tab in my browser with Stable Diffusion UI v2.07 (beta). It brought me to the main page where you can put text in and start generating images

15) I typed something into it to generate but My Computer Crashed (Probably because Stable Diffusion is beefy and my laptop can't handle it). 
I'm gonna try it again and see If I can get it to work (Gonna put in a more simple prompt) and tell you what happens


I hope this helps

**Comment by SharkyGoChompChomp21** [comment]
This is what Happend

______________________________________________________________________________________________________________________________________________________________________________

Stable Diffusion is ready!

started in  /home/sharky/Desktop/StableDiffusion/stable-diffusion-ui/stable-diffusion
INFO:     Started server process [4311]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
Opening in existing browser session.
INFO:     127.0.0.1:50926 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:50926 - "GET /media/kofi.png HTTP/1.1" 200 OK
INFO:     127.0.0.1:50926 - "GET /modifiers.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:50926 - "GET /output_dir HTTP/1.1" 200 OK
INFO:     127.0.0.1:50926 - "GET /favicon.ico HTTP/1.1" 404 Not Found
Loading model from sd-v1-4.ckpt
Global Step: 470000
UNet: Running in eps-prediction mode

**Comment by cmdr2** [comment]
Thanks for your patience @SharkyGoChompChomp21 !

Did it generate images after your restarted your PC? Thanks

**Comment by is0lated** [comment]
I had some trouble getting it to work with my laptop's pretty limited RAM. You'll probably want at least 16GB of ram and even then be sure not to have too many things open in the background. I managed to get it to work once I set up some swap space, but it definitely slowed things down quite a bit.

**Comment by SharkyGoChompChomp21** [comment]
@cmdr2 
Nope, (It said "stable diffusion has stopped" in red, never saw it say "Stable Diffusion is Ready" in Green) I had to manual press the power button since my computer is stuck. I have a big feeling it's because of the Ram since I'm probably gonna need a Beefy Computer and not a Lenovo Ideapad Laptop.
I believe I have 8 gigs of ram and not the 16GB needed. I'm gonna try it on a more beefy computer Once I get one with 16GB Ram but would recommend it having more? Is 16GB how much it takes up with no breathing room or is that howmuch system needs to be conformable in running it?

**Comment by is0lated** [comment]
@SharkyGoChompChomp21
During start up, it seems to jump up to around 12GB - 13GB of memory used at startup (including the chromium browser it opens), but then drops down a bit. Currently, while running it on my laptop CPU I'm using about 10GB with a couple of other browser tabs open. So, once you get it running you can do other stuff in the background pretty comfortably with 16GB of total RAM.

**Comment by cmdr2** [comment]
Hi @SharkyGoChompChomp21  16 GB will work quite comfortably. 8 GB is probably too tight and hasn't worked in my experience.

Unfortunately there isn't much I can do if it's running out of RAM, we'll have to wait for the Stable Diffusion team to make a less memory-intensive version (it's on their roadmap). You can try some of the online hosted versions of Stable Diffusion, or the Google Colabs that people have set up. Closing this, thanks! :)
