### ISSUE TITLE
so i checked the version's and  how can i update my version to 1.5 or the newer 2.1 i heard there is a support for Stable diffusion 2.1 i don't know where it is in my files

### ISSUE THREAD

**Issue by Protovax** [cmdr2/stable-diffusion-ui#833]
just looking for a an  "update"

**Comment by JeLuF** [comment]
The default model installed with EasyDiffusion is the version 1.4 model. For the later versions, there's lots of different variants to choose from and we don't want to install tens of gigabytes of models by default. The 2.1 models can be found at:

* https://huggingface.co/stabilityai/stable-diffusion-2-1-base - Trained on 512x512 sized images
* https://huggingface.co/stabilityai/stable-diffusion-2-1 - Trained on 768x768 sized images, giving better results at larger image sizes

**Comment by Protovax** [comment]
Thank you

**Comment by Protovax** [comment]
hey man about that when i downloaded the version and deleted the previous 1.4 one . the 1.4 one keeps appearing back and it's causing problems

**Comment by cmdr2** [comment]
@Protovax Right now, you can't delete the 1.4 model. You can continue to use the other models that you've downloaded into `models/stable-diffusion`.

Can you please tell us what problem keeping the 1.4 model is causing?

**Comment by JeLuF** [comment]
You can now delete the 1.4 model if you have any other model in the `models/stable-diffusion` folder.
