### ISSUE TITLE
Adding tags switches to tag filtered view, frustrating users, disrupting workflow

### ISSUE THREAD

**Issue by udgigor** [cmdr2/stable-diffusion-ui#836]
**Describe the bug**
When adding a tag to let say 10 items some 30 rows down in the image library the entire app switches to a view that only filters for the tag, when returning to the library there is no way to know what items were recently tagged, and duplication of this selection/tag process occurs among same-y looking images. If just one item needs to be tagged, again the UI switches to the tag filtered view, and the user has to go back reload their library again and re-orient themselves in the library.

**To Reproduce**
1. Go to 'basic gallery', scroll down some rows to get lost in your work as one does
2. Select a row or 4 of images
3. Open tag gizmo area
4. enter tag, hit return, press
5. now you're in the tag filtered zone
6. click the home button
7. wait for your library to reload
8. now you're back at the top of your library some possibly thousands of images away from where you started, by the time you reach the images you just tagged your brain is over loaded with images and can't remember what images you tagged.

**Expected behavior**
When tagging images a little tag icon should appear on their control bar to let the user know a tag was set for this image and then allow them to continue working in the same UI view they were in without any switching/reloading things, if they want to filter for tagged images they can select an image, pop open the info, click on a tag word and filter from that point.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome/Edge ? Not sure that's relevant, but....
 - Version: Agent 0.2.4  breadmachine 0.0.18

**Additional context**

**Comment by JeLuF** [comment]
> 1. Go to 'basic gallery', scroll down some rows to get lost in your work as one does

I think your report is about a different software. This software doesn't have a 'basic gallery' area.

**Comment by udgigor** [comment]
Yep, don't know how I ended up here from someone else's discord, sorry about that
