### ISSUE TITLE
Erro installing in Ubuntu linux under Mac environment via Virtual box

### ISSUE THREAD

**Issue by jimqartworks** [cmdr2/stable-diffusion-ui#84]
InvalidArchiveError("Error with archive /home/jimq/stable-diffusion-ui/installer/pkgs/cudatoolkit-11.3.1-h2bc3f7f_2/.cph_tmphordd_nn/pkg-cudatoolkit-11.3.1-h2bc3f7f_2.tar.zst.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nFailed to create dir 'bin'")

Error installing the packages necessary for Stable Diffusion. Please try re-running this installer. If it doesn't work, please copy the messages in this window, and ask the community at https://discord.com/invite/u9yhsFmEkB or file an issue at https://github.com/cmdr2/stable-diffusion-ui/issues

Thank you

**Comment by cmdr2** [comment]
Hi, I believe this was fixed? https://github.com/cmdr2/stable-diffusion-ui/issues/102
