### ISSUE TITLE
Save some disk space, do not automatically download the default model if others are present

### ISSUE THREAD

**Issue by light-min** [cmdr2/stable-diffusion-ui#848]
**Is your feature request related to a problem? Please describe.**
I don't use the default model, so I deleted it. I thought that, since I had 5 other .ckpt and .safetensors in the folder, the default one would not be downloaded. When I fired up the script again, it started downloading sd-v1-4.ckpt

**Describe the solution you'd like**
I think that the script should download the default model only if others are not present, or at the user's request

**Comment by am576** [comment]
> **Describe the solution you'd like** I think that the script should download the default model only if others are not present, or at the user's request

Agree. This shouldn't be mandatory, it should give the user an option

**Comment by JeLuF** [comment]
Recently added changes allow you to delete the default model, as long as you have any other model in the `models\stable-diffusion`  folder.

**Comment by JeLuF** [comment]
Can you please provide logs showing the download? And please also show that you actually have a supported model in the models\stable-diffusion directory.

**Comment by Ciel-MC** [comment]
> Can you please provide logs showing the download? And please also show that you actually have a supported model in the models\stable-diffusion directory.

```
18:36:51.058 INFO MainThread started in /home/ciel/Downloads/easy-diffusion/stable-diffusion                                server.py:31
18:36:51.061 INFO MainThread started at 12/08/23 18:36:51                                                                   server.py:32
stable-diffusion model(s) found.
> download gfpgan 1.4
18:36:52.681 INFO MainThread Downloading https://github.com/TencentARC/GFPGAN/releases/download/v1.3.4/GFPGANv1.4.pth   http_utils.py:30
to /home/ciel/Downloads/easy-diffusion/models/gfpgan/GFPGANv1.4.pth                                                                     
Downloading:   0%|                                                                                    | 320k/332M [00:00<08:43, 665kB/s]```
And I am sure that the model works, because I just bypassed it by touching an empty file, and it did move on to download the rest of the models as well, but I just let them finish because it's relatively small, after I got into the UI, I can generate images fine, so the model works, but it is insistent on downloading all models

**Comment by JeLuF** [comment]
The GFPGAN model is not a stable diffusion model, but a face correction model.
