### ISSUE TITLE
Torch not found during install on Windows

### ISSUE THREAD

**Issue by TTSKarlsson** [cmdr2/stable-diffusion-ui#849]
**Describe the bug**
Error when `Start Stable Diffusion UI.cmd` tries to install `torch`

**To Reproduce**
Run `Start Stable Diffusion UI.cmd` in Windows 11 `cmd.exe` prompt.

**Expected behavior**
Should probably not error.

**Screenshots**
![20230209_200702_1355x388](https://user-images.githubusercontent.com/9962943/217913296-2012ed3d-ef09-46ca-b97f-3bf001045598.png)

![20230209_200815_852x60](https://user-images.githubusercontent.com/9962943/217913399-20760685-85a6-4cf6-b6fb-ca58f8733184.png)

**Desktop (please complete the following information):**
 - OS: Window 11
 - Browser: Irrelevant
 - Version: v2.5.15 (? There;s no version info on the downloaded zip nor in the folder) 

**Additional context**
I get same error messages when I rerun `Start Stable Diffusion UI.cmd`
I've removed and reinstalled, same problem.
Error FAQ says to check python version, and that it should be 3.8.5. I only have 3.8.5 installed, but `Start Stable Diffusion UI.cmd` installs a venv with 3.11.0 as shown in the screenshots.

**Comment by JeLuF** [comment]
There was a problem with the installer causing this problem. The new version should fix it. Please delete `C:\stable-diffusion-ui`, download https://github.com/cmdr2/stable-diffusion-ui/releases/download/v2.5.15/stable-diffusion-ui-windows.zip and follow the installation instructions as before.

**Comment by TTSKarlsson** [comment]
Thank you, that fixed it. I had to run the installer 3 times in a row for it to finish.
