### ISSUE TITLE
Stable Diffusion UI - v2

### ISSUE THREAD

**Issue by Janarbek1985** [cmdr2/stable-diffusion-ui#860]
"!!!! WARNING !!!!"

"Your 'stable-diffusion-ui' folder is at D:\stable-diffusion-ui-windows\stable-diffusion-ui"

"The 'stable-diffusion-ui' folder needs to be at the top of your drive, for e.g. 'C:\stable-diffusion-ui' or 'D:\stable-diffusion-ui' etc."
"Not placing this folder at the top of a drive can cause errors on some computers."

"Recommended: Please close this window and move the 'stable-diffusion-ui' folder to the top of a drive. For e.g. 'C:\stable-diffusion-ui'. Then run the installer again."

"Not Recommended: If you're sure that you want to install at the current location, please press any key to continue."

Press any key to continue . . .

"Downloading Stable Diffusion UI.."

"Using the main channel"

Cloning into 'sd-ui-files'...
remote: Enumerating objects: 13346, done.
remote: Counting objects: 100% (555/555), done.
remote: Compressing objects: 100% (255/255), done.
remote: Total 13346 (delta 396), reused 431 (delta 294), pack-reused 12791
Receiving objects: 100% (13346/13346), 55.39 MiB | 3.48 MiB/s, done.
Resolving deltas: 100% (8750/8750), done.
491 File(s) copied
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.

Hotfixed broken JSON file from OpenAI
module torch not found
"Installing torch and torchvision.."
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch
"Error installing torch. Sorry about that, please try to:"
"  1. Run this installer again."
"  2. If that doesn't fix it, please try the common troubleshooting steps at https://github.com/cmdr2/stable-diffusion-ui/wiki/Troubleshooting"
"  3. If those steps don't help, please copy *all* the error messages in this window, and ask the community at https://discord.com/invite/u9yhsFmEkB"
"  4. If that doesn't solve the problem, please file an issue at https://github.com/cmdr2/stable-diffusion-ui/issues"
"Thanks!"
Press any key to continue . . .

**Comment by JeLuF** [comment]
Your 'stable-diffusion-ui' folder is at D:\stable-diffusion-ui-windows\stable-diffusion-ui

The 'stable-diffusion-ui' folder needs to be at the top of your drive, i.e. 'D:\stable-diffusion-ui' 
Not placing this folder at the top of a drive can cause errors on some computers. Reason for this is that there's a limit on Windows for the length of filenames and the installation folder has about 25 characters max length otherwise the installation will fail because the filenames will get too long and `D:\stable-diffusion-ui-windows\stable-diffusion-ui` has way more than 25 characters.

**Comment by Janarbek1985** [comment]
To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "C:\STABLE\stable-diffusion-webui-master\launch.py", line 361, in <module>
    start()
  File "C:\STABLE\stable-diffusion-webui-master\launch.py", line 356, in start
    webui.webui()
  File "C:\STABLE\stable-diffusion-webui-master\webui.py", line 232, in webui
    app.add_middleware(GZipMiddleware, minimum_size=1000)
  File "C:\STABLE\stable-diffusion-webui-master\venv\lib\site-packages\starlette\applications.py", line 135, in add_middleware
    raise RuntimeError("Cannot add middleware after an application has started")
RuntimeError: Cannot add middleware after an application has started

**Comment by JeLuF** [comment]
That error is not from this software, but from a different project: https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/launch.py#L361

**Comment by Janarbek1985** [comment]
and what do you advise to do?

**Comment by JeLuF** [comment]
> and what do you advise to do?

I would recommend that you ask on the issue tracker of that project.
