### ISSUE TITLE
"Error: The downloaded ESRGAN x4plus_anime model file was invalid! Bytes downloaded: "

### ISSUE THREAD

**Issue by dennisling2345** [cmdr2/stable-diffusion-ui#861]
**Describe the bug**
"Error: The downloaded ESRGAN x4plus_anime model file was invalid! Bytes downloaded: "

"Error downloading the data files (weights) for ESRGAN (Resolution Upscaling) x4plus_anime. Sorry about that, please try to:"

**Comment by JeLuF** [comment]
Try restarting the installer. This usually gets fixed on second try.

**Comment by dennisling2345** [comment]
> Try restarting the installer. This usually gets fixed on second try.

I have tried 4 times and stuck in this every time.

**Comment by wiggum23** [comment]
Same problem here, tried reinstalling, did not work.

**Comment by Sprk-nl** [comment]
Same problem here. Although, I think I made an error and started the script from the explorer.
Opening a terminal, and execute "Start Stable Diffusion UI.cmd" worked fine the 2nd time.

**Comment by JeLuF** [comment]
> > Try restarting the installer. This usually gets fixed on second try.
> 
> I have tried 4 times and stuck in this every time.

Can you please share the full log output?

**Comment by wiggum23** [comment]
I finally was successful after the 8 or 9th try.

**Comment by Devoron** [comment]
I have same trouble. 

"error downloading the data files (weights) for esrgan (resolution upscaling) x4plus_anime"

**Comment by Devoron** [comment]
**Solution:** You can download the file from https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.2.4/RealESRGAN_x4plus_anime_6B.pth and save it into the models\esrgan folder in the installation directory, then rerun the installer

**Comment by JeLuF** [comment]
This has been fixed via PR #904
