### ISSUE TITLE
Command-line usage?

### ISSUE THREAD

**Issue by xeruf** [cmdr2/stable-diffusion-ui#906]
**Is your feature request related to a problem? Please describe.**
This tool is awesome, as it simplifies installation on any system.
But I would like to be able to use the basic features like txt2img from the CLI as well, without installing it separately.

**Describe the solution you'd like**
Include txt2img in the package, maybe under `scripts/`, so I can use it on demand.

**Describe alternatives you've considered**
installing everything twice :/

**Additional context**
I mainly use Arch

**Comment by JeLuF** [comment]
You don't need to install everything twice. You can use the `developer_console.sh` script to use the EasyDiffusion environment with everything preinstalled. The engine we use is called [sdkit](https://github.com/easydiffusion/sdkit) and you can use the examples and scripts from that project in the EasyDiffusion environment.

**Comment by xeruf** [comment]
That's good to know, still maybe you can include a script like txt2img?

**Comment by cmdr2** [comment]
You can run this:
1. Open the developer console (`./developer_console.sh`)
2. Run `python your_file.py`

Where your_file.py is a modified version of https://github.com/easydiffusion/sdkit/blob/main/examples/001-generate-model_file_on_disk.py

Beyond that, sorry, no plans to support CLI-based image generation in Easy Diffusion.
Where your_file.py`
