### ISSUE TITLE
question: is there a way to toggle NSFW filter?

### ISSUE THREAD

**Issue by hananelroe** [cmdr2/stable-diffusion-ui#91]

**Comment by cmdr2** [comment]
Hi, it is currently not turned on, so NSFW is not blocked. There were some issues with the new code, so I'm working on making it optional again. For now, it will not block NSFW images.

**Comment by hananelroe** [comment]
ok, thanks.
btw,  for creating this interface, it's amazing!

**Comment by cmdr2** [comment]
You're welcome :)
