### ISSUE TITLE
"ERROR: torch install failed", during install on Ubuntu

### ISSUE THREAD

**Issue by EijiK33** [cmdr2/stable-diffusion-ui#919]
**Describe the bug**
When I tried installing stable-diffusion-ui on Ubuntu, the error message appeared.
`ERROR: torch install failed`

Could someone help me?
Or is there anything I can do to fix this?

Thanks!

**To Reproduce**
1. Go to the "stable-diffusion-ui" directory
2. Run ./start.sh
3. See this error.

**Expected behavior**
To complete installation and start stable-diffusion-ui

**Screenshots**
![Screenshot from 2023-02-21 09-39-10](https://user-images.githubusercontent.com/125864827/220222776-10bdd20e-0fc7-41d1-9c7a-044d42f2250a.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.2 LTS
 - Browser: Firefox Browser 110.0 (64-bit)
 - Version: v2.5.15

**Additional context**

**Comment by JeLuF** [comment]
Your system ran out of memory. Your physical RAM size plus your swap size should be at least 12GB, better 16GB. Depending on the general workload of your system it can be even more than that.

**Comment by EijiK33** [comment]
@JeLuF Thank you for your explanation. I understand.
