### ISSUE TITLE
Force full precision

### ISSUE THREAD

**Issue by Title666645** [cmdr2/stable-diffusion-ui#922]
**Describe the bug**
Generates only gray images, full precision should fix it but i can't force it manually (I have a rx 5700 xt, so its not on the full precision list)

**To Reproduce**
1. Go to 'Web page'
2. Click on 'Make Image'
3. Scroll to Image
4. See a gray image

**Expected behavior**
A normal, generated image

**Screenshots**
![image](https://user-images.githubusercontent.com/67227071/220410325-8d970fcd-df76-4f9a-a554-798de90becac.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.10
 - Browser: Firefox
 - Version: 2.5.15

**Additional context**
There also is an error in CLI:
`IOpen(HIP): Warning [SQLiteBase] Missing system database file: gfx1030_18.kdb Performance may degrade. Please follow instructions to install: https://github.com/ROCmSoftwarePlatform/MIOpen#installing-miopen-kernels-package`
I tried installing miopen-hip and later just miopen-hip-gfx1030-36kbk but the error stays

**Comment by JeLuF** [comment]
In `scripts/config.sh`, add the line:
```
export FORCE_FULL_PRECISION=T
```

**Comment by dansity** [comment]
I have the similar issue on RTX2060, for me the output is black.
I have added the export FORCE_FULL_PRECISION=T line to config.sh as @JeLuF suggested but it is completely ignored during loading:

```
10:13:34.594 INFO MainThread started in D:\stable-diffusion-ui\stable-diffusion                             server.py:19
10:13:34.601 INFO MainThread started at 02/22/23 10:13:34                                                   server.py:20
10:13:35.146 INFO MainThread Scanned 3 models. Nothing infected                                    model_manager.py:215
10:13:35.434 INFO MainThread Start new Rendering Thread on device: cuda:0                        task_manager.py:393
10:13:59.595 INFO cuda:0 Setting cuda:0 as active, with precision: half                            device_manager.py:118
10:13:59.599 INFO cuda:0 loading stable-diffusion model from                                              __init__.py:22
```

**Comment by Title666645** [comment]
I added the line, and it works! Thanks!
There is still the miopenkernels issue, but I'm probably going to post that on ROCm.

Output:
`cuda:0 Setting cuda:0 as active, with precision: full`

**Comment by JeLuF** [comment]
> I have the similar issue on RTX2060, for me the output is black. I have added the export FORCE_FULL_PRECISION=T line to config.sh as @JeLuF suggested but it is completely ignored during loading:
> 
> ```
> 10:13:34.594 INFO MainThread started in D:\stable-diffusion-ui\stable-diffusion                             server.py:19
> 10:13:34.601 INFO MainThread started at 02/22/23 10:13:34                                                   server.py:20
> 10:13:35.146 INFO MainThread Scanned 3 models. Nothing infected                                    model_manager.py:215
> 10:13:35.434 INFO MainThread Start new Rendering Thread on device: cuda:0                        task_manager.py:393
> 10:13:59.595 INFO cuda:0 Setting cuda:0 as active, with precision: half                            device_manager.py:118
> 10:13:59.599 INFO cuda:0 loading stable-diffusion model from                                              __init__.py:22
> ```

You're using Windows. My previous instructions were for Linux. On Windows, you need to edit `scripts\config.bat` and add a line
```
@set FORCE_FULL_PRECISION=T
```
