### ISSUE TITLE
Make automatic update an option

### ISSUE THREAD

**Issue by worthlesscog** [cmdr2/stable-diffusion-ui#96]
I think currently when you run the start script, it automatically pulls. That feels like a risky proposition as in the event of a bad commit, you run the risk of mangling everyones install with a bad update and saddling yourself with a pile of "mine no longer works!" mails.

If it's an option like a switch on the start script, it also gives folks the choice of not updating if they have a working setup that they're happy with and don't want the changes.

**Comment by cmdr2** [comment]
Hi, it sure is, and I'm choosing a middle ground of keep the auto-updates but having people pull from a stable `main` branch, or optionally from a `beta` branch.

This project is very young (less than 2 weeks old), and lots of basic bugs are fixed everyday, and I don't have the resources to provide support (GitHub and Discord chat) for older versions. If auto-updates are disabled, there'll be lots of people running older versions (I'm one of those people who never updates, if I have an option). I simply can't provide support for that right now.

So the middle path is a main release channel, and a beta channel for enthusiasts. That is rolling out today. Thanks for the suggestion, it definitely makes sense what you're saying :)
