### ISSUE TITLE
After reboot the "Start Stable Diffusion UI.cmd" became blank

### ISSUE THREAD

**Issue by iegoshin** [cmdr2/stable-diffusion-ui#969]
**Describe the bug**
Second time in two days, Easy Diffusion UI doesn't start for me. I checked the command file and it's blank again. It happened for me yesterday. I had to reinstall the program from scratch yesterday. Not sure what is going on. Can it clear the .cmd file by itself? E.g. if the terminal is closed?

**To Reproduce**
Create a shortcut to the .cmd file
Add it to startup apps so Easy Diffusion started automatically
Work in CPU mode until it becomes unresponsive
Close the terminal window
Restart windows
File "Start Stable Diffusion UI.cmd" is blank

**Expected behavior**
Any way to fix it, e.g. run some "fixme.cmd" without having to re-download and re-install 20 gigs of data.

**Desktop (please complete the following information):**
 - Windows 10 home

**Comment by JeLuF** [comment]
There is a backup copy of the `Start Stable Diffusion UI.cmd` file in `sd-ui-files\scripts\Start Stable Diffusion UI.cmd`. You can copy it back into place if this happens.

I wasn't able to reproduce the issue. Can you share the logfile of the successful script execution?

**Comment by iegoshin** [comment]
> There is a backup copy of the `Start Stable Diffusion UI.cmd` file in `sd-ui-files\scripts\Start Stable Diffusion UI.cmd`. You can copy it back into place if this happens.
> 
> I wasn't able to reproduce the issue. Can you share the logfile of the successful script execution?

Sorry, I reinstalled it already...
