### ISSUE TITLE
Bug report: multiple "|" inside different brackets is not splitting right

### ISSUE THREAD

**Issue by iegoshin** [cmdr2/stable-diffusion-ui#970]
**Describe the bug**
If you want to test bracketed combinations of terms, it splits as if there was no brackets at all

**To Reproduce**
Try running this prompt: 
(1man|1girl) wearing (victorian|medieval|antique) clothes

**Expected behavior**

I would expect it to produce the following queries:
(1man) wearing (victorian) clothes
(1man) wearing (medieval) clothes
(1man) wearing (antique) clothes
(1girl) wearing (victorian) clothes
(1girl) wearing (medieval) clothes
(1girl) wearing (antique) clothes

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser:
 - Version:

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by S0ulMeister** [comment]
Use Brackets.
[1man|1girl] wearing [victorian|medieval|antique]

**Comment by iegoshin** [comment]
> Use Brackets. [1man|1girl] wearing [victorian|medieval|antique]

Hmm... Don't square brackets reduce the weight of the terms?

**Comment by S0ulMeister** [comment]
> > Use Brackets. [1man|1girl] wearing [victorian|medieval|antique]
> 
> 
> 
> Hmm... Don't square brackets reduce the weight of the terms?

Information on Prompt editing is available here:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Features
At least in the documentation, they use brackets. I'm having a similar issue too however.

**Comment by iegoshin** [comment]
> > > Use Brackets. [1man|1girl] wearing [victorian|medieval|antique]
> > 
> > 
> > Hmm... Don't square brackets reduce the weight of the terms?
> 
> Information on Prompt editing is available here: https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Features At least in the documentation, they use brackets. I'm having a similar issue too however.

Are you sure stable-diffusion-ui is using the same prompt parser as automatic1111? Weight support was working for automatic1111 for a long time and easy diffusion added it just recently. Though it doesn't quite work for me with multiple words in brackets, e.g. (medieval castle:1.5)

**Comment by Holden933** [comment]
Use curly brackets and commas instead.

It's mentioned briefly on: https://github.com/cmdr2/stable-diffusion-ui/wiki/Writing-prompts

{1man,1girl} wearing {victorian,medieval,antique} clothes

That will create 6 pictures...

1man wearing victorian clothes
1man wearing medieval clothes
1man wearing antique clothes
1girl wearing victorian clothes
1girl wearing medieval clothes
1girl wearing antique clothes

All the pictures will have the same seed number, even if the "Random" slider is ON.

But if you add the plugin "Seed Randomizer by Patrice" and set it to "Extreme", then you'll get a different seed number for each picture.

**Comment by S0ulMeister** [comment]
> > > > Use Brackets. [1man|1girl] wearing [victorian|medieval|antique]
> > > 
> > > 
> > > Hmm... Don't square brackets reduce the weight of the terms?
> > 
> > 
> > Information on Prompt editing is available here: https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Features At least in the documentation, they use brackets. I'm having a similar issue too however.
> 
> Are you sure stable-diffusion-ui is using the same prompt parser as automatic1111? Weight support was working for automatic1111 for a long time and easy diffusion added it just recently. Though it doesn't quite work for me with multiple words in brackets, e.g. (medieval castle:1.5)

Oh I see. What I was implying was that bracketing is used for "flickering" the prompt between each step. I see now you wanted completely separate images. I use automatic1111 and ultimately I use a setting outside of the prompt window. I use the "script" settings at the very bottom on "X/Y/Z" plot. You'll be able to get separate image generations that way, and you can even specify to use random seeds too.
