### ISSUE TITLE
'conda' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by TomPython** [cmdr2/stable-diffusion-ui#978]
Error when installing the Easy Diffusion 2.5

Cloning into 'sd-ui-files'...
remote: Enumerating objects: 14209, done.
remote: Counting objects: 100% (165/165), done.
remote: Compressing objects: 100% (92/92), done.
remote: Total 14209 (delta 97), reused 117 (delta 70), pack-reused 14044
Receiving objects: 100% (14209/14209), 55.58 MiB | 42.00 KiB/s, done.

Resolving deltas: 100% (9422/9422), done.
Updating files: 100% (547/547), done.
493 File(s) copied
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
'conda' is not recognized as an internal or external command,
operable program or batch file.

"Error activating conda for Easy Diffusion. Sorry about that, please try to:"
"  1. Run this installer again."
"  2. If that doesn't fix it, please try the common troubleshooting steps at https://github.com/cmdr2/stable-diffusion-ui/wiki/Troubleshooting"
"  3. If those steps don't help, please copy *all* the error messages in this window, and ask the community at https://discord.com/invite/u9yhsFmEkB"
"  4. If that doesn't solve the problem, please file an issue at https://github.com/cmdr2/stable-diffusion-ui/issues"
"Thanks!"

**Desktop (please complete the following information):**
 - OS: Win 10

**Comment by JeLuF** [comment]
Please share the full log. You can copy it using these 6 clicks:
![image](https://user-images.githubusercontent.com/5852422/224472795-4752044a-30e0-462c-ba5f-ed76e8bc6f6a.png)

**Comment by Weaklyispro** [comment]
I am also having the same issue my log is  also
 Install dir: D:\stable-diffusion-ui\
C:\Program Files\Git\cmd\git.exe
git version 2.39.2.windows.1
INFO: Could not find files for the given pattern(s).
'conda' is not recognized as an internal or external command,
operable program or batch file.

"Easy Diffusion - v2"

"Easy Diffusion's git repository was already installed. Updating from main.."
HEAD is now at 4e35580 Update README.md
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
493 File(s) copied
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
A subdirectory or file tmp already exists.
'conda' is not recognized as an internal or external command,
operable program or batch file.

"Error activating conda for Easy Diffusion. Sorry about that, please try to:"
"  1. Run this installer again."
"  2. If that doesn't fix it, please try the common troubleshooting steps at https://github.com/cmdr2/stable-diffusion-ui/wiki/Troubleshooting"
"  3. If those steps don't help, please copy *all* the error messages in this window, and ask the community at https://discord.com/invite/u9yhsFmEkB"
"  4. If that doesn't solve the problem, please file an issue at https://github.com/cmdr2/stable-diffusion-ui/issues"
"Thanks!"

Press any key to continue . . .
Press any key to continue . . .
Press any key to continue . . .

**Comment by TomPython** [comment]
Hi There,

I think I have figured it out by totally removing the old python
environment and reinstalling it through your instructions.
Many thanks for your help!

Regards,
Tom

JeLuF ***@***.***> 于2023年3月11日周六 21:03写道：
