### ISSUE TITLE
doesn't work at all on win 10

### ISSUE THREAD

**Issue by krom2077** [cmdr2/stable-diffusion-ui#98]
hello

last release doesn't work at all, if I double click on `Start Stable Diffusion UI.cmd` the terminal opens for a fraction of a second then nothing. if I run `installer\scripts\activate.bat` from cmd.exe without administrator privileges I get` \Common was unexpected` and a list of folders in my c:\ drive, same if I run cmd.exe as an administrator with the difference that the message before the list of folders on my hard drive is `\Nmap" was unexpected.
`

stable-diffusion-ui folder is in C:\ and or in D:\

**Comment by keymaster777** [comment]
Im on Windows 10 and an trying the install now. I can verify I got past that point in the install without any problems.

**Comment by cmdr2** [comment]
@krom2077 Did you download the github repository or did you download from the installation instructions? https://github.com/cmdr2/stable-diffusion-ui#installation

Also, can you press Win+R and type "cmd" and run, and then run `cd C:\stable-diffusion-ui` (assuming that's where it is), and then run `"Start Stable Diffusion UI.cmd"` ? Can you please paste the output of the error here? Thanks

**Comment by meanin2** [comment]
> @krom2077 Did you download the github repository or did you download from the installation instructions? https://github.com/cmdr2/stable-diffusion-ui#installation
> 
> Also, can you press Win+R and type "cmd" and run, and then run `cd C:\stable-diffusion-ui` (assuming that's where it is), and then run `"Start Stable Diffusion UI.cmd"` ? Can you please paste the output of the error here? Thanks

C:\stable-diffusion-ui-main\scripts>"Start Stable Diffusion UI.cmd"

C:\stable-diffusion-ui-main\scripts>installer\Scripts\activate.bat
The system cannot find the path specified.

**Comment by meanin2** [comment]
> > @krom2077 Did you download the github repository or did you download from the installation instructions? https://github.com/cmdr2/stable-diffusion-ui#installation
> > Also, can you press Win+R and type "cmd" and run, and then run `cd C:\stable-diffusion-ui` (assuming that's where it is), and then run `"Start Stable Diffusion UI.cmd"` ? Can you please paste the output of the error here? Thanks
> 
> C:\stable-diffusion-ui-main\scripts>"Start Stable Diffusion UI.cmd"
> 
> C:\stable-diffusion-ui-main\scripts>installer\Scripts\activate.bat The system cannot find the path specified.
> 
> My folder is called stable-diffusion-ui-main and the start command file is in scripts folder. I don't see the activate.bat anywhere.

I downloaded from the repo instead of from the windows link. Looks like that was probably the issue.

**Comment by cmdr2** [comment]
Thanks, yes please use the installation docs, not the github repo. I'm closing this issue for now, please re-open if the issue still continues. https://github.com/cmdr2/stable-diffusion-ui/blob/main/README.md#installation

**Comment by G3Kappa** [comment]
Hey, I'm having the same issue. It seems that the /scripts folder is not bundles with the installation. Can you please repro?

**Comment by cmdr2** [comment]
@G3Kappa Please don't download the git repo. You need to download from https://github.com/cmdr2/stable-diffusion-ui/blob/main/README.md#installation . I just checked the windows release (provided in that link), and it contains the scripts folder.

Thanks
