### ISSUE TITLE
Global list of tasks on the server

### ISSUE THREAD

**Issue by iegoshin** [cmdr2/stable-diffusion-ui#985]
**Is your feature request related to a problem? Please describe.**
If your SD server is shared with other people, some of them might start a HUGE batch and reload/close browser page. After that they lost access and ability to cancel it. Other people don't know what's in the queue now, how long it'll run for (ETA) and when their tasks will start.

**Describe the solution you'd like**
1. Some Admin UI with global list of tasks, even without much details, but with ETA - estimated time arrival
2. Ability to cancel any task, even if you didn't start it
3. For each queued task display the time remaining to start, refreshed once a several minutes at least. If it doesn't change for a long time then you can tell that something is wrong either with the server or with your browser.

**Comment by JeLuF** [comment]
The batches are managed on the client side. In the worst case, 2 render jobs are on the server's queue: The currently rendering one and the next one. If the browser page is reloaded, only those two jobs need to complete.
