### ISSUE TITLE
Beta version and XFormers Linux Mint 21

### ISSUE THREAD

**Issue by agentsimon** [cmdr2/stable-diffusion-ui#988]
**Describe the bug**
XFormers not loading
No module 'xformers'. Proceeding without it.

**Expected behavior**
Beta version should run the Xformers
**Screenshots**
![start_up](https://user-images.githubusercontent.com/31639346/224234272-cfca0d08-ac47-45f2-b595-839638a91ada.png)

![nvidia](https://user-images.githubusercontent.com/31639346/224234314-4d418af0-6bdd-4b47-8b9b-11093bfd0902.png)
![os](https://user-images.githubusercontent.com/31639346/224234320-a2edd760-7f76-4cdd-87e5-0eb9c8cc8a90.png)

**Comment by agentsimon** [comment]
Here is my Xformers check
![xformers_check](https://user-images.githubusercontent.com/31639346/224270459-91bba1b1-a90a-487b-bb38-c5e570de5c25.png)

**Comment by agentsimon** [comment]
I ran it using ./developer_console.sh installed Xformers and triton using pip (pip install xformers pip install triton)
The xformers loaded. Nice

**Comment by JeLuF** [comment]
xformers has some side effects (non-deterministic results) and breaks some functionality (Hypernetworks, IIRC). That's why we don't install it. `No module 'xformers'. Proceeding without it` isn't an error message.

**Comment by agentsimon** [comment]
Ahh ok, thanks for the heads up
