### ISSUE TITLE
Cannot get rid of default SD model

### ISSUE THREAD

**Issue by iegoshin** [cmdr2/stable-diffusion-ui#989]
**Describe the bug**
If you don't use default model and try to delete it, next time you start the app it'll download it again. Why do I have to keep it around? I have a better use for 4gb, e.g. download some other model.

**Expected behavior**
Don't download standard model if there are at least one other model there.

**Comment by JeLuF** [comment]
We're working on this.

**Comment by iegoshin** [comment]
> We're working on this.

Thank you!
