### ISSUE TITLE
'OSError: [Errno 22] Invalid argument' Avoid reserved characters in Windows file names

### ISSUE THREAD

**Issue by nightkall** [cmdr2/stable-diffusion-ui#99]
When using the option '**Automatically save to**' with [Windows **reserved file name characters**](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions) in a prompt (double quote in my case: "), **it doesn't save the .png and .txt file** and throws this error:

`OSError: [Errno 22] Invalid argument: 'C:\\R\\cmdr2\\1f6d5759\\"Javier_Bardem"_Gta_vice_city_gta_5_cover_art_bord_25617819.png'
`

```
The following reserved characters:

< (less than)
> (greater than)
: (colon)
" (double quote)
/ (forward slash)
\ (backslash)
| (vertical bar or pipe)
? (question mark)
* (asterisk)
```
[https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions)

**Comment by cmdr2** [comment]
Thanks! Will fix this :)

**Comment by JeLuF** [comment]
This has been fixed.
https://github.com/cmdr2/stable-diffusion-ui/blob/9d201f82f16e496b6079604455ada1c6fed83cb3/ui/sd_internal/runtime.py#L42
