### ISSUE TITLE
Make delays when overheated

### ISSUE THREAD

**Issue by iegoshin** [cmdr2/stable-diffusion-ui#993]
**Is your feature request related to a problem? Please describe.**
If SD is running non stop for a long time, CPU, SSD or video card can easily get overheated.

**Describe the solution you'd like**
It would be nice to make breaks in such cases. It's better to wait a minute or two than to burn some hardware down.

**Comment by iegoshin** [comment]
> Normally hardware doesn't overheat. Plenty of people play games constantly which use cpu and gpu.
> 
> SSDs/storage is not written all the time also.
> 
> also waiting a minute or two doesn't do much. To cool down (if someone would really implement something like this) it would take much lnger to cool down the whole system.

Yeah, i guess it would be more an issue in the CPU mode...

**Comment by RenaKunisaki** [comment]
Maybe a better idea is to have a script running which pauses the process when temperature is too high.

Even better is to fix your system's cooling so it doesn't overheat...
