### ISSUE TITLE
Feature request: download support Aria2

### ISSUE THREAD

**Issue by ivysrono** [cmdr2/stable-diffusion-ui#996]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Down files from download.pytorch.org and so on may be too slow to work.

**Describe alternatives you've considered**
Add configs support Aria2.

**Additional context**

**Comment by cmdr2** [comment]
We've changed our model downloading code to allow resuming incomplete downloads, for connections that are slow or intermittent. No plans to use aria2 right now though.
